Repository hmcts/rpx-xui-webapp, pull requests merged in 2019-05, with the labels that each got.

#28 Features/add more testing to pipeline
  package.json
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/config/support/common.conf.js
  test/e2e/config/support/jenkins.conf.js
  test/e2e/config/support/local.conf.js
  test/e2e/features/app/dummy.feature
  test/e2e/features/step_definitions/steps/dummy.steps.js
  yarn.lock
Labels: ns:xui-webapp-pr-28

#33 Nojia/terraform set asp name
  infrastructure/main.tf
  src/cases/containers/case-create/case-create.component.spec.ts
Labels: ns:xui-webapp-pr-33

#36 xui clientid added
  Jenkinsfile_parameterized
  api/config/application.config.ts
  api/config/environments/aat.config.ts
  api/config/environments/local.config.ts
  charts/xui-webapp/values.template.yaml
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: ns:xui-webapp-pr-36

#34 moving urls to config.json file EUI-148
  src/app/models/configuration.model.ts
  src/app/providers/providers.module.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/auth/auth.service.ts
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/config/configuration.services.spec.ts
  src/app/services/config/configuration.services.ts
  src/assets/config/config.json
  src/assets/images/test.jpg
  src/cases/containers/case-create/case-create.component.spec.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: ns:xui-webapp-pr-34

#37 refactor_automation
  rpx-xui-webapp.iml
  test/e2e/config/protractor.conf.js
  test/e2e/features/pageObjects/dummyObjects.steps.js
Labels: ns:xui-webapp-pr-37

#38 Eui 169
  package.json
  src/app/app.module.ts
  src/app/containers/app/app.component.ts
  src/app/services/logger/console-logger.service.spec.ts
  src/app/services/logger/console-logger.service.ts
  src/app/services/logger/logger.module.ts
  src/app/services/logger/logger.service.ts
  yarn.lock
Labels: ns:xui-webapp-pr-38

#40 add coverage reports to build
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  angular.json
  package-lock.json
  package.json
  src/karma.conf.js
  yarn.lock
Labels: ns:xui-webapp-pr-40
