Repository hmcts/rpx-xui-webapp, pull requests merged in 2019-08, with the labels that each got.

#110 Created search results for Case list filter
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/case-search/case-search.component.ts
Labels: ns:xui-webapp-pr-110

#111 EUI-450 Url routing plus EUI-479 tabs issue
  src/app/app.routes.ts
  src/app/containers/app/app.component.scss
Labels: ns:xui-webapp-pr-111

#105 EXUI-408 Manage case phase-banner
  src/app/components/header/header.component.html
  src/app/components/index.ts
  src/app/components/phase-banner/phase-banner.component.html
  src/app/components/phase-banner/phase-banner.component.ts
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-search/case-search.component.ts
  src/cases/containers/case-search/case.search.component.spec.ts
  src/cases/services/search-filter.service.spec.ts
  src/cases/store/reducers/search-filter.reducer.spec.ts
Labels: ns:xui-webapp-pr-105

#116 Feature/eui 447
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-search/case-search.component.html
Labels: ns:xui-webapp-pr-116

#118 Feature/eui 660 web config plus case-list result defect fixes
  angular.json
  src/cases/containers/case-filter/case-filter.component.spec.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.ts
  src/cases/containers/case-search/case.search.component.spec.ts
  src/cases/services/search-filter.service.spec.ts
  src/cases/services/search-filter.service.ts
  src/cases/store/actions/case-list.action.ts
  src/cases/store/actions/case-search.action.ts
  src/cases/store/effects/case-list.effects.ts
  src/cases/store/effects/index.ts
  src/cases/store/effects/search-filter.effects.ts
  src/cases/store/reducers/case-list.reducer.spec.ts
  src/cases/store/reducers/case-list.reducer.ts
  src/cases/store/reducers/index.ts
  src/cases/store/reducers/search-filter.reducer.ts
  src/cases/store/selectors/case-list.selectors.ts
  src/cases/store/selectors/index.ts
  src/web.config
Labels: ns:xui-webapp-pr-118

#119 updated response headers
  src/web.config
Labels: ns:xui-webapp-pr-119

#117 Feature/eui 477 postcode button aa
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/config/configuration.services.spec.ts
  src/cases/containers/case-create/case-create.component.spec.ts
  src/cases/containers/case-details/case-details.compoent.spec.ts
  src/cases/containers/case-filter/case-filter.component.spec.ts
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-search/case-search.component.spec.ts
  src/style/app.scss
Labels: ns:xui-webapp-pr-117

#120 removed watch and bowserheadless
  package.json
Labels: ns:xui-webapp-pr-120

#121 new csp header added
  src/cases/containers/case-list/case-list.component.spec.ts
  src/web.config
Labels: ns:xui-webapp-pr-121

#125 Removed web.config deployment in the build
  angular.json
Labels: ns:xui-webapp-pr-125

#115 EUI-443 removed margin
  src/style/app.scss
Labels: ns:xui-webapp-pr-115

#126 PR - Case search filter show/hide filter implementation
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/case-search/case-search.component.ts
  src/cases/store/actions/case-search.action.ts
  src/cases/store/effects/search-filter.effects.ts
  src/cases/store/reducers/search-filter.reducer.ts
  src/cases/store/selectors/search.filter.selectors.ts
Labels: ns:xui-webapp-pr-126

#127 Feature/eui 66 case progression
  src/app/app.routes.ts
  src/cases/case-feature.routes.ts
  src/cases/store/selectors/case-details.selectors.ts
Labels: ns:xui-webapp-pr-127

#129 EUI-705 grey bar
  src/style/app.scss
Labels: ns:xui-webapp-pr-129
