Repository hmcts/rpx-xui-webapp, pull requests merged in 2019-12, with the labels that each got.

#305 increased upload limit to Infinity
  api/documents/DMStore.ts
Labels: ns:xui-webapp-pr-305

#306 increased upload limit to 100MB for upload path only, rejection can b…
  api/documents/DMStore.ts
Labels: ns:xui-webapp-pr-306

#308 added root web.config with all the usual params + upload limit increa…
  web.config
Labels: ns:xui-webapp-pr-308

#309 Update jurisdictions to include SSCS 4 docker
  api/amendedJurisdictions/index.ts
Labels: ns:xui-webapp-pr-309

#307 AWAITING CAB: Stop a User accessing ManageCases if they do not have a caseworker role.
  api/auth/index.spec.ts
  api/auth/index.ts
  api/auth/manageCasesUserRoleAuth.spec.ts
  api/auth/manageCasesUserRoleAuth.ts
  api/config/environments/aat.config.ts
  api/config/environments/demo.config.ts
  api/config/environments/ithc.config.ts
  api/config/environments/local.config.ts
  api/config/environments/perftest.config.ts
  api/config/environments/preview.config.ts
  api/config/environments/prod.config.ts
  api/lib/objectUtilities.spec.ts
  api/lib/objectUtilities.ts
Labels: ns:xui-webapp-pr-307

#311 Feature/eui 1234 get help page
  package.json
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/get-help/get-help.component.html
  src/app/components/get-help/get-help.component.spec.ts
  src/app/components/get-help/get-help.component.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/index.ts
  src/app/shared/shared.module.ts
  yarn.lock
Labels: ns:xui-webapp-pr-311

#312 EUI-519 un-commented polyfills
  package.json
  src/polyfills.ts
  yarn.lock
Labels: ns:xui-webapp-pr-312

#313 Feature/eui 1234 get help page
  src/app/app.constants.ts
Labels: ns:xui-webapp-pr-313

#289 EUI-1111: MC Functional tests refactor and enable tests in pipeline
  .vscode/launch.json
  .vscode/settings.json
  Jenkinsfile_nightly
  dummy.pdf
  package-lock.json
  package.json
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/documents/dummy.pdf
  test/e2e/features/app/FRCreateCase.feature
  test/e2e/features/app/FRCreateCase_CaseWorker.feature
  test/e2e/features/app/FRCreateCase_solicitor.feature
  test/e2e/features/app/divorceCreateCase.feature
  test/e2e/features/app/divorcesCreateCase.feature
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/probateCreateCase.feature
  test/e2e/features/app/searchCase.feature
  test/e2e/features/pageObjects/CaseListPage.js
  test/e2e/features/pageObjects/Divorcecase.js
  test/e2e/features/pageObjects/FRCase.js
  test/e2e/features/pageObjects/ProbateCase.js
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/pageObjects/createCaseStartPage.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/pageObjects/probatePage.js
  test/e2e/features/pageObjects/searchPage.js
  test/e2e/features/step_definitions/caseList.steps.js
  test/e2e/features/step_definitions/caseManager.steps.js
  test/e2e/features/step_definitions/createCase.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/searchCase.steps.js
  test/e2e/support/customWaits.js
  test/e2e/support/world.js
Labels: ns:xui-webapp-pr-289

#317 adding publiclaw and ia
  api/amendedJurisdictions/index.ts
Labels: ns:xui-webapp-pr-317
