Repository hmcts/rpx-xui-webapp, pull requests merged in 2019-06, with the labels that each got.

#30 enable signout via ngrx action
  api/application.ts
  debug.log
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/providers/providers.module.ts
  src/app/services/auth/auth.guard.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effect.spec.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app-config.reducer.ts
  src/cases/containers/case-create/case-create.component.spec.ts
Labels: ns:xui-webapp-pr-30

#42 Revert "enable signout via ngrx action"
  api/application.ts
  debug.log
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/providers/providers.module.ts
  src/app/services/auth/auth.guard.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effect.spec.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app-config.reducer.ts
  src/cases/containers/case-create/case-create.component.spec.ts
Labels: ns:xui-webapp-pr-42

#43 Chore/revert back to jui idam client
  src/assets/config/config.json
Labels: ns:xui-webapp-pr-43

#39 Present Search Results - eui 89
  .angulardoc.json
  .gitignore
  .vscode/launch.json
  README.md
  api/application.ts
  api/lib/proxy.ts
  package-lock.json
  package.json
  proxy.config.json
  src/app/components/exui-mian-wrapper/exui-page-wrapper.component.html
  src/app/components/exui-mian-wrapper/exui-page-wrapper.component.scss
  src/app/components/exui-mian-wrapper/exui-page-wrapper.component.ts
  src/app/containers/app/app.component.html
  src/assets/config/config.json
  src/assets/fonts/FontAwesome.otf
  src/assets/fonts/bold-a2452cb66f-v1.woff2
  src/assets/fonts/fontawesome-webfont.eot
  src/assets/fonts/fontawesome-webfont.svg
  src/assets/fonts/fontawesome-webfont.ttf
  src/assets/fonts/fontawesome-webfont.woff
  src/assets/fonts/fontawesome-webfont.woff2
  src/assets/fonts/light-f38ad40456-v1.woff2
  src/assets/health.json
  src/assets/img/accordion-minus.png
  src/assets/img/accordion-plus.png
  src/assets/img/apple-touch-icon-120x120.png
  src/assets/img/apple-touch-icon-152x152.png
  src/assets/img/apple-touch-icon-60x60.png
  src/assets/img/apple-touch-icon-76x76.png
  src/assets/img/dropdown-arrow.PNG
  src/assets/img/editor.png
  src/assets/img/editorBanner.png
  src/assets/img/favicon.ico
  src/assets/img/gov.uk_logotype_crown.svg
  src/assets/img/gov.uk_logotype_crown_invert_trans.png
  src/assets/img/icon-search-white.png
  src/assets/img/viewer.png
  src/assets/img/viewerBanner.png
  src/assets/img/warning.png
  src/assets/img/x.PNG
  src/cases/cases.module.ts
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/case-search/case-search.component.ts
  src/cases/containers/case-search/case.search.component.spec.ts
  src/cases/store/helpers/entity.ts
  src/cases/store/index.ts
  src/cases/store/reducers/index.ts
  src/cases/store/reducers/search-filter.reducer.spec.ts
  src/cases/store/reducers/search-filter.reducer.ts
  src/cases/store/selectors/index.ts
  src/cases/store/selectors/search.filter.selectors.ts
  src/style/_buttons.scss
  src/style/_forms.scss
  src/style/_markdown.scss
  src/style/_notifications.scss
  src/style/_print.scss
  src/style/app.scss
  src/style/vendor/prism.scss
  src/styles.scss
  yarn.lock
Labels: ns:xui-webapp-pr-39

#45 Feature/eui 42 logout 2
  debug.log
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/providers/providers.module.ts
  src/app/services/auth/auth.guard.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effect.spec.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app-config.reducer.ts
  src/cases/containers/case-create/case-create.component.spec.ts
Labels: ns:xui-webapp-pr-45

#51 update idam client
  api/config/application.config.ts
  api/config/environments/aat.config.ts
  api/config/environments/local.config.ts
  src/assets/config/config.json
Labels: ns:xui-webapp-pr-51

#49 update jenkins file
  Jenkinsfile_CNP
Labels: ns:xui-webapp-pr-49

#53 added data declarations
  infrastructure/main.tf
Labels: ns:xui-webapp-pr-53

#55 tf updates
  infrastructure/main.tf
  infrastructure/output.tf
Labels: ns:xui-webapp-pr-55

#66 Bug/add missing preview config for prs
  api/config/environments/preview.config.ts
  api/config/index.ts
Labels: ns:xui-webapp-pr-66

#65 remove superfluous colon in redirect
  src/app/services/auth/auth.service.ts
Labels: ns:xui-webapp-pr-65

#54 Bug/fz cancel btm fix eui 210
  src/app/containers/exiu-ccd-connector-wrapper/exui-ccd-connector.component.spec.ts
  src/cases/containers/case-create/case-create.component.html
  src/cases/containers/case-create/case-create.component.ts
  src/cases/store/actions/create-case.action.spec.ts
  src/cases/store/actions/create-case.action.ts
  src/cases/store/effects/case-create.effects.spec.ts
  src/cases/store/effects/case-create.effects.ts
  src/cases/store/reducers/create-case.reducer.spec.ts
  src/cases/store/reducers/create-case.reducer.ts
Labels: ns:xui-webapp-pr-54

#47 Updated the feature files
  test/e2e/features/app/createCase.feature
  test/e2e/features/app/dummy.feature
  test/e2e/features/app/searchCase.feature
Labels: ns:xui-webapp-pr-47

#50 Feature/eui 193
  package-lock.json
  src/app/app.module.ts
  src/app/components/exui-logger/exui-logger.component.spec.ts
  src/app/components/exui-logger/exui-logger.component.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/services/logger/console-logger.service.spec.ts
  src/app/services/logger/console-logger.service.ts
  src/app/shared/shared.module.ts
  src/app/store/actions/logger-state.actions.ts
  src/app/store/effects/logger.effects.ts
  src/app/store/reducers/index.ts
  src/app/store/reducers/logger.reducer.spec.ts
  src/app/store/reducers/logger.reducer.ts
  src/app/store/selectors/logger.selector.spec.ts
  src/app/store/selectors/logger.selector.ts
  src/cases/containers/case-filter/case-filter.component.spec.ts
  src/cases/containers/case-search/case.search.component.spec.ts
Labels: ns:xui-webapp-pr-50

#35 Apply contained CCD component's tagname to container's data-selector
  package.json
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.ts
  src/app/containers/exiu-ccd-connector-wrapper/exui-ccd-connector.component.ts
Labels: ns:xui-webapp-pr-35

#69 few changes to package and conf
  package.json
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:xui-webapp-pr-69

#68 health end point
  api/application.ts
  api/config/environments/prod.config.ts
  package-lock.json
  package.json
  proxy.config.json
  yarn.lock
Labels: ns:xui-webapp-pr-68

#76 Chore/fix preview env
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  README.md
  api/services/idam.ts
  charts/xui-webapp/values.template.yaml
Labels: ns:xui-webapp-pr-76

#80 Another test of auto pr
  README.md
  package.json
  whitelist.sh
Labels: ns:xui-webapp-pr-80

#78 Build test 17/6/19
  README.md
Labels: ns:xui-webapp-pr-78

#73 Add footer to application
  src/app/app.constants.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.ts
  src/app/components/index.ts
  src/app/containers/app/app.component.html
  src/app/containers/footer/footer.component.html
  src/app/containers/footer/footer.component.scss
  src/app/containers/footer/footer.component.spec.ts
  src/app/containers/footer/footer.component.ts
  src/app/containers/footer/footer.model.ts
  src/app/containers/index.ts
  src/assets/images/govuk-crest-2x.png
  src/assets/images/govuk-crest.png
Labels: ns:xui-webapp-pr-73

#81 Eui 57
  README.md
  package.json
  test/e2e/config/conf.js
  test/e2e/features/app/createCase.feature
  test/e2e/features/app/searchCase.feature
  test/e2e/features/pageObjects/appealCreatedPage.js
  test/e2e/features/pageObjects/basePage.js
  test/e2e/features/pageObjects/caseCreatedPage.js
  test/e2e/features/pageObjects/caseListPage.js
  test/e2e/features/pageObjects/createCaseStartPage.js
  test/e2e/features/pageObjects/createCaseWizardPage.js
  test/e2e/features/pageObjects/dummyObjects.steps.js
  test/e2e/features/pageObjects/searchCasePage.js
  test/e2e/features/pageObjects/webdriver-components/button.js
  test/e2e/features/pageObjects/webdriver-components/dropdown.js
  test/e2e/features/pageObjects/webdriver-components/radioField.js
  test/e2e/features/pageObjects/webdriver-components/textField.js
  test/e2e/features/step_definitions/createCase.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/searchCase.steps.js
  test/e2e/features/step_definitions/steps/dummy.steps.js
  test/e2e/utils/TestData.js
  test/e2e/utils/errors/custom-error.js
  test/e2e/utils/euiDataGenerationUtils.js
Labels: ns:xui-webapp-pr-81

#85 Feature/fz view case eui 59
  src/cases/containers/case-details/case-details.component.html
  src/cases/containers/case-details/case-details.component.ts
Labels: ns:xui-webapp-pr-85

#87 Feature/eui 89 fresh
  src/app/containers/exiu-ccd-connector-wrapper/exui-ccd-connector.component.ts
  src/assets/config/config.json
  src/cases/cases.module.ts
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/case-search/case-search.component.scss
  src/cases/containers/case-search/case-search.component.ts
  src/cases/containers/case-search/case.search.component.spec.ts
  src/cases/mock/search-filter.mock.ts
  src/cases/services/index.ts
  src/cases/services/search-filter.service.spec.ts
  src/cases/services/search-filter.service.ts
  src/cases/store/actions/case-search.action.spec.ts
  src/cases/store/actions/case-search.action.ts
  src/cases/store/effects/index.ts
  src/cases/store/effects/search-filter.effects.spec.ts
  src/cases/store/effects/search-filter.effects.ts
  src/cases/store/reducers/search-filter.reducer.spec.ts
  src/cases/store/reducers/search-filter.reducer.ts
  src/cases/store/selectors/search.filter.selectors.spec.ts
  src/cases/store/selectors/search.filter.selectors.ts
  src/karma.conf.js
Labels: ns:xui-webapp-pr-87

#89 EUI-212 fixed bug
  src/app/app.module.ts
  src/styles.scss
Labels: ns:xui-webapp-pr-89

#88 Feature/eui 51
  package-lock.json
  package.json
  src/app/containers/app/app.component.scss
  src/cases/cases.module.ts
  src/cases/containers/case-list/case-list-filter.component.scss
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/store/actions/case-list.action.ts
  src/cases/store/actions/index.ts
  src/cases/store/reducers/case-list.reducer.spec.ts
  src/cases/store/reducers/case-list.reducer.ts
  src/cases/store/reducers/index.ts
  src/cases/store/selectors/search.filter.selectors.ts
  yarn.lock
Labels: ns:xui-webapp-pr-88
