Repository hmcts/rpx-xui-webapp, pull requests merged in 2019-10, with the labels that each got.

#176 enabled sonar coverage - DO NOT MERGE
  sonar-project.properties
Labels: ns:xui-webapp-pr-176

#181 Bug/eui 831 v2 redirect
  src/app/app.routes.ts
  src/cases/store/effects/case-create.effects.ts
Labels: ns:xui-webapp-pr-181

#180 Feature/eui 702 print urls
  api/application.ts
  api/documents/DMStore.spec.ts
  api/lib/interceptors.spec.ts
  api/lib/middleware/serviceToken.spec.ts
  api/print/index.spec.ts
  api/print/index.ts
  api/print/printService.spec.ts
  api/print/printService.ts
  api/print/routes.ts
  package-lock.json
  package.json
  proxy.config.json
  src/assets/config/config.json
  yarn.lock
Labels: ns:xui-webapp-pr-180

#179 adding feedback link
  src/app/components/phase-banner/phase-banner.component.html
Labels: ns:xui-webapp-pr-179

#183 EUI-888 and EUI-883
  src/app/components/accessibility/accessibility.component.spec.ts
  src/app/components/privacy-policy/privacy-policy.component.spec.ts
  src/cases/components/case-alert/alert.component.spec.ts
Labels: ns:xui-webapp-pr-183

#196 update sonar source
  sonar-project.properties
Labels: ns:xui-webapp-pr-196

#197 EUI-903 done error handling
  api/documents/DMStore.ts
  api/documents/index.ts
Labels: ns:xui-webapp-pr-197

#201 adding unit test, also moving constructors into ngOnInit to enable un…
  src/app/shared/services/exui-title.service.spec.ts
  src/app/shared/services/exui-title.service.ts
Labels: ns:xui-webapp-pr-201

#205 enable prod deploymeny for MC
  Jenkinsfile_CNP
Labels: ns:xui-webapp-pr-205

#193 Feature/eui 889 case home unit test & alert component unit test fix
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/components/case-alert/alert.component.ts
  src/cases/containers/case-home/case-home.component.spec.ts
Labels: ns:xui-webapp-pr-193

#204 Feature/eui 879 route effect testing
  src/app/store/effects/router.effect.spec.ts
Labels: ns:xui-webapp-pr-204

#206 unit test for all cases actions
  src/cases/store/actions/case-list.action.spec.ts
  src/cases/store/actions/case-search.action.spec.ts
  src/cases/store/actions/create-case.action.spec.ts
Labels: ns:xui-webapp-pr-206

#207 fixed issue with nyc/mocha reporting inconsistent coverage results
  api/.nycrc.json
  api/documents/document.interface.spec.ts
  api/package.json
  api/test/mocha.opts
Labels: ns:xui-webapp-pr-207

#209 adding router action unit test
  src/app/store/actions/router.action.spec.ts
Labels: ns:xui-webapp-pr-209

#210 enable sonar for MC
  sonar-project.properties
Labels: ns:xui-webapp-pr-210

#198 fixed document/print authentication
  api/application.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/responseRequest.ts
  api/routes.ts
Labels: ns:xui-webapp-pr-198

#215 fixing the failed test on auth service
  src/app/services/auth/auth.service.spec.ts
Labels: ns:xui-webapp-pr-215

#218 EUI-923 Amended jurisdiction response
  api/amendedJurisdictions/index.spec.ts
  api/amendedJurisdictions/index.ts
  api/application.ts
Labels: ns:xui-webapp-pr-218

#217 enable-sonar
  sonar-project.properties
Labels: ns:xui-webapp-pr-217

#226 Bugfix/eui 957 reordering middleware
  api/application.ts
  api/lib/middleware/auth.spec.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/serviceToken.spec.ts
  api/lib/middleware/serviceToken.ts
Labels: ns:xui-webapp-pr-226

#227 update new key vault variable for idam
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  charts/xui-webapp/values.yaml
  infrastructure/main.tf
Labels: ns:xui-webapp-pr-227

#229 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:xui-webapp-pr-229

#261 output env variables and check secrets
  Dockerfile
  api/application.ts
  api/server.ts
  charts/xui-webapp/values.aat.template.yaml
  charts/xui-webapp/values.preview.template.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:xui-webapp-pr-261
