Repository hmcts/rpx-xui-webapp, pull requests merged in 2019-09, with the labels that each got.

#128 PR case list toggle button implemented
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/case-search/case-search.component.ts
  src/cases/store/actions/case-list.action.ts
  src/cases/store/effects/case-list.effects.ts
  src/cases/store/reducers/case-list.reducer.ts
  src/cases/store/selectors/case-list.selectors.ts
Labels: ns:xui-webapp-pr-128

#130 Feature/eui 527
  api/application.ts
  package.json
  src/app/app.module.ts
  src/app/components/exui-logger/exui-logger.component.spec.ts
  src/app/components/exui-logger/exui-logger.component.ts
  src/app/containers/app/app.component.html
  src/app/services/errorHandler/defaultErrorHandler.spec.ts
  src/app/services/errorHandler/defaultErrorHandler.ts
  src/app/services/logger/CryptoWrapper.spec.ts
  src/app/services/logger/appInsightsWrapper.ts
  src/app/services/logger/console-logger.service.spec.ts
  src/app/services/logger/console-logger.service.ts
  src/app/services/logger/cryptoWrapper.ts
  src/app/services/logger/jwtDecodeWrapper.ts
  src/app/services/logger/logger.service.spec.ts
  src/app/services/logger/logger.service.ts
  src/app/services/logger/monitoring.service.spec.ts
  src/app/services/logger/monitoring.service.ts
  src/app/shared/shared.module.ts
  src/app/store/effects/logger.effects.ts
  src/app/store/reducers/index.ts
  src/app/store/reducers/logger.reducer.spec.ts
  src/app/store/reducers/logger.reducer.ts
  src/app/store/selectors/logger.selector.spec.ts
  src/app/store/selectors/logger.selector.ts
  yarn.lock
Labels: ns:xui-webapp-pr-130

#131 CaseDetails Component exclude
  src/cases/containers/case-details/case-details.compoent.spec.ts
Labels: ns:xui-webapp-pr-131

#133 Features eui 732
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.ts
Labels: ns:xui-webapp-pr-133

#136 Fix the .
  api/server.ts
Labels: ns:xui-webapp-pr-136

#137 make node to https
  infrastructure/main.tf
Labels: ns:xui-webapp-pr-137

#132 Feature/eui 444 login filter
  src/cases/containers/case-list/case-list.component.ts
Labels: ns:xui-webapp-pr-132

#159 EUI-758 fix for ithc
  api/config/environments/ithc.config.ts
Labels: ns:xui-webapp-pr-159

#161 Feature/eui 771 success case creation
  src/cases/store/effects/case-create.effects.spec.ts
  src/cases/store/effects/case-create.effects.ts
Labels: ns:xui-webapp-pr-161

#163 Feature/eui 660 security headers
  angular.json
  api/healthCheck/index.spec.ts
  api/package.json
  src/web.config
Labels: ns:xui-webapp-pr-163

#164 change s2s protocol to http
  api/config/environments/aat.config.ts
  api/config/environments/ithc.config.ts
  api/config/environments/local.config.ts
  api/config/environments/preview.config.ts
  api/config/environments/prod.config.ts
Labels: ns:xui-webapp-pr-164

#166 Feature/eui 537 accesibility aa
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.ts
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/cookie-policy/cookie-policy.component.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
  src/app/components/index.ts
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/privacy-policy/privacy-policy.component.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/components/terms-and-conditions/terms-and-conditions.component.ts
Labels: ns:xui-webapp-pr-166

#169 Logging the create case
  src/cases/store/effects/case-create.effects.spec.ts
  src/cases/store/effects/case-create.effects.ts
Labels: ns:xui-webapp-pr-169

#170 Open files inline
  api/documents/DMStore.ts
  api/documents/index.spec.ts
  api/documents/index.ts
Labels: ns:xui-webapp-pr-170

#174 Feature/eui 632 node coverage
  api/documents/index.spec.ts
  api/healthCheck/index.spec.ts
  api/healthCheck/index.ts
  api/lib/errorStack.spec.ts
  api/lib/errorStack.ts
  api/lib/http/index.spec.ts
  api/lib/index.ts
  api/lib/interceptors.spec.ts
  api/lib/log4jui.spec.ts
  api/lib/log4jui.ts
  api/lib/middleware/serviceToken.spec.ts
  api/lib/middleware/serviceToken.ts
  api/lib/proxy.spec.ts
  api/lib/proxy.ts
  api/lib/util.spec.ts
  api/lib/util.ts
  api/postCodeLookup/index.spec.ts
  api/postCodeLookup/index.ts
  api/services/idam.ts
  api/services/serviceAuth.spec.ts
  api/services/serviceAuth.ts
Labels: ns:xui-webapp-pr-174

#172 Bugfix/eui 835 csp blocking app insights
  src/web.config
Labels: ns:xui-webapp-pr-172

#177 Bug/eui 706 refresh create
  src/cases/case-feature.routes.ts
  src/cases/cases.module.ts
  src/cases/containers/case-create-submit/case-create-submit.component.html
  src/cases/containers/case-create-submit/case-create-submit.component.ts
  src/cases/containers/index.ts
  src/cases/resolvers/create-case-event-trigger.resolver.spec.ts
  src/cases/resolvers/create-case-event-trigger.resolver.ts
  src/cases/store/effects/case-create.effects.ts
Labels: ns:xui-webapp-pr-177

#162 title update on manage case
  src/app/shared/services/exui-title.service.spec.ts
  src/app/shared/services/exui-title.service.ts
  src/app/shared/shared.module.ts
  src/cases/case-feature.routes.ts
  src/cases/containers/case-create/case-create.component.ts
  src/cases/containers/case-details-home/case-details-home.html
  src/cases/containers/case-details-home/case-details-home.ts
  src/cases/containers/case-filter/case-filter.component.ts
  src/cases/containers/case-home/case-home.component.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.ts
  src/cases/containers/index.ts
  src/index.html
Labels: ns:xui-webapp-pr-162
