Repository hmcts/rpx-xui-webapp, pull requests merged in 2020-03, with the labels that each got.

#407 clean up unecessary config code
  .gitignore
  Jenkinsfile_CNP
  api/.env.defaults
  api/application.ts
  api/configuration/index.ts
  api/configuration/references.ts
  api/documents/DMStore.ts
  api/lib/appInsights.ts
  api/lib/tunnel.ts
  api/local.ts
  api/package.json
  api/server.ts
  api/services/idam.ts
  api/services/serviceAuth.ts
  api/webpack-node.config.js
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/requirements.yaml
  charts/xui-webapp/values.aat.template.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  src/app/guards/acceptTerms.guard.spec.ts
  src/app/guards/acceptTerms.guard.ts
  src/app/services/terms-and-conditions/terms-and-conditions.service.ts
  web.config
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-407

#410 added url env variables within terraform/ase envs
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:xui, rel:xui-webapp-pr-410

#424 using legacy terms and conditions and feature toggling it with APP_INITIALIZER
  src/app/app-initilizer.ts
  src/app/app.routes.ts
  src/app/containers/footer/footer.component.spec.ts
  src/app/containers/footer/footer.component.ts
  src/app/containers/index.ts
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.ts
  src/app/guards/acceptTerms.guard.spec.ts
  src/app/guards/acceptTerms.guard.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
Labels: ns:xui, rel:xui-webapp-pr-424

#426 Feature/redis into master
  api/application.ts
  api/configuration/references.ts
  api/lib/sessionStore.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/requirements.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-426

#431 Feature/redis password in url 2
  Jenkinsfile_CNP
  api/application.ts
  api/configuration/references.ts
  api/lib/sessionStore.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  infrastructure/main.tf
Labels: ns:xui, rel:xui-webapp-pr-431

#442 Feature/merge master into develop
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  README.md
  api/application.ts
  api/configuration/references.ts
  api/configurationUI/index.ts
  api/lib/sessionStore.ts
  api/local.ts
  api/openRoutes.ts
  api/package.json
  api/server.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/requirements.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  proxy.config.json
  src/app/services/auth/auth.guard.spec.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/auth/auth.service.ts
  src/app/shared/services/environment.service.spec.ts
  src/app/shared/services/environment.service.ts
  src/models/environmentConfig.model.ts
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-442

#447 Removing secrets logging.
  api/local.ts
  api/server.ts
  api/services/idam.ts
  api/services/serviceAuth.ts
Labels: ns:xui, rel:xui-webapp-pr-447

#448 Feature/eui 1713 add config check
  api/configuration/appConfig.ts
  api/configuration/appConfigCheckRouter.ts
  api/configuration/constants.ts
  api/configuration/health.ts
  api/configuration/index.ts
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/local.ts
  api/openRoutes.ts
  api/server.ts
  config/custom-environment-variables.json
  src/app/shared/services/environment.service.ts
Labels: ns:xui, rel:xui-webapp-pr-448

#435 Feature/eui 1685 global tokens
  api/amendedJurisdictions/index.spec.ts
  api/documents/DMStore.spec.ts
  api/documents/DMStore.ts
  api/documents/index.ts
  api/emAnno/emAnnoService.spec.ts
  api/emAnno/emAnnoService.ts
  api/emAnno/index.ts
  api/lib/middleware/auth.ts
  api/lib/models/index.ts
  api/lib/proxy.ts
  api/postCodeLookup/index.ts
  api/print/index.ts
  api/print/printService.spec.ts
  api/print/printService.ts
  api/termsAndConditions/index.ts
  api/userTermsAndConditions/index.ts
Labels: ns:xui, rel:xui-webapp-pr-435

#450 Feature/merge master into develop 31 03 2020
  README.md
  api/amendedJurisdictions/index.spec.ts
  api/documents/DMStore.spec.ts
  api/documents/DMStore.ts
  api/documents/index.ts
  api/emAnno/emAnnoService.spec.ts
  api/emAnno/emAnnoService.ts
  api/emAnno/index.ts
  api/lib/middleware/auth.ts
  api/lib/models/index.ts
  api/lib/proxy.ts
  api/postCodeLookup/index.ts
  api/print/index.ts
  api/print/printService.spec.ts
  api/print/printService.ts
  api/termsAndConditions/index.ts
  api/userTermsAndConditions/index.ts
Labels: ns:xui, rel:xui-webapp-pr-450

#452 Develop merge tandc 31 03 2020
  README.md
  api/configuration/appConfig.ts
  api/configuration/appConfigCheckRouter.ts
  api/configuration/constants.ts
  api/configuration/health.ts
  api/configuration/index.ts
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/local.ts
  api/openRoutes.ts
  api/server.ts
  api/services/idam.ts
  api/services/serviceAuth.ts
  config/custom-environment-variables.json
  src/app/app-initilizer.ts
  src/app/app.routes.ts
  src/app/containers/footer/footer.component.spec.ts
  src/app/containers/footer/footer.component.ts
  src/app/containers/index.ts
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.ts
  src/app/guards/acceptTerms.guard.spec.ts
  src/app/guards/acceptTerms.guard.ts
  src/app/shared/services/environment.service.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
Labels: ns:xui, rel:xui-webapp-pr-452

#446 Develop to master
  README.md
  api/configuration/appConfig.ts
  api/configuration/appConfigCheckRouter.ts
  api/configuration/constants.ts
  api/configuration/health.ts
  api/configuration/index.ts
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/local.ts
  api/openRoutes.ts
  api/server.ts
  api/services/idam.ts
  api/services/serviceAuth.ts
  config/custom-environment-variables.json
  src/app/app-initilizer.ts
  src/app/app.routes.ts
  src/app/containers/footer/footer.component.spec.ts
  src/app/containers/footer/footer.component.ts
  src/app/containers/index.ts
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.ts
  src/app/guards/acceptTerms.guard.spec.ts
  src/app/guards/acceptTerms.guard.ts
  src/app/shared/services/environment.service.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
Labels: ns:xui, rel:xui-webapp-pr-446
