Repository hmcts/rpx-xui-webapp, pull requests merged in 2020-04, with the labels that each got.

#406 Fix for redirect bug after another user login
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/services/search-filter.service.ts
Labels: ns:xui, rel:xui-webapp-pr-406

#400 update FPLA contact details - to be released after 03 March
  src/app/app.constants.ts
Labels: ns:xui, rel:xui-webapp-pr-400

#455 Feature/health endpoint
  api/application.ts
  api/configuration/index.ts
  api/health/index.ts
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-455

#454 added sourcemap support for production mode
  api/server.ts
  api/webpack-node.config.js
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-454

#457 fix the race condition between app-initilizer and state for the first…
  src/app/guards/acceptTerms.guard.spec.ts
  src/app/guards/acceptTerms.guard.ts
Labels: ns:xui, rel:xui-webapp-pr-457

#460 update redis base chart to use bitnami
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/requirements.yaml
Labels: ns:xui, rel:xui-webapp-pr-460

#459 Markrup fix for legacy T&Cs
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
Labels: ns:xui, rel:xui-webapp-pr-459

#453 Feature/eui 1699 timeout increase aa
  api/application.ts
Labels: ns:xui, rel:xui-webapp-pr-453

#468 Hotfix/eui 1808 redis health endpoint
  api/health/index.ts
  api/health/redis.health.ts
  api/lib/sessionStore.ts
Labels: ns:xui, rel:xui-webapp-pr-468

#469 Update to Accessibility copy.
  src/app/components/accessibility/accessibility.component.html
Labels: ns:xui, rel:xui-webapp-pr-469

#474 Feature/eui 1774 get help gen page
  package.json
  src/app/app.constants.ts
  src/app/components/get-help/get-help.component.html
  src/app/components/get-help/get-help.component.spec.ts
  src/app/components/get-help/get-help.component.ts
Labels: ns:xui, rel:xui-webapp-pr-474

#422 Feature/eui 1650 tnc content
  package.json
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.spec.ts
  src/app/containers/terms-and-conditions/terms-and-conditions.component.ts
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-422
