Repository hmcts/rpx-xui-webapp, pull requests merged in 2020-06, with the labels that each got.

#510 Update privacy policy with latest version
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/privacy-policy/privacy-policy.component.ts
Labels: ns:xui, rel:xui-webapp-pr-510

#521 Release/eui 1988 mv upgrade 2
  api/amendedJurisdictions/index.spec.ts
  api/amendedJurisdictions/index.ts
  api/application.ts
  api/health/index.ts
  api/lib/error.handler.ts
  api/lib/interceptors.ts
  api/lib/middleware/auth.ts
  api/lib/processError.handler.ts
  api/lib/proxy.spec.ts
  api/lib/proxy.ts
  api/payments/index.spec.ts
  api/payments/index.ts
  api/payments/paymentsService.ts
  api/postCodeLookup/index.spec.ts
  api/postCodeLookup/index.ts
  api/redaction/markup.spec.ts
  api/redaction/markup.ts
  api/redaction/redaction.spec.ts
  api/redaction/redaction.ts
  api/services/serviceAuth.ts
  api/termsAndConditions/index.ts
  api/termsAndConditions/routes.ts
  api/termsAndConditions/termAndConditionsUtil.spec.ts
  api/termsAndConditions/termsAndConditionsUtil.ts
  api/userTermsAndConditions/index.ts
  api/userTermsAndConditions/routes.ts
  api/userTermsAndConditions/userTermsAndConditionsUtil.spec.ts
  api/userTermsAndConditions/userTermsAndConditionsUtil.ts
Labels: ns:xui, rel:xui-webapp-pr-521

#525 EUI-2060 made error handling dynamic and added tests
  api/lib/error.handler.spec.ts
  api/lib/error.handler.ts
Labels: ns:xui, rel:xui-webapp-pr-525

#526 Merge pull request #490 from hmcts/bugfix/EUI-1886-ccd-multiple-calls
  .vscode/launch.json
  api/package.json
  src/cases/cases.module.ts
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-list/case-list.component.ts
Labels: ns:xui, rel:xui-webapp-pr-526

#527 Remove log token eui-2066
  api/lib/error.handler.spec.ts
  api/lib/error.handler.ts
Labels: ns:xui, rel:xui-webapp-pr-527

#537 Crossbrowser_tests_MC
  Jenkinsfile_nightly
  package.json
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/probateCreateCase.feature
  test/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-537

#533 Feature/eui 1938 checkbox permission aa
  api/configuration/references.ts
  api/user/index.spec.ts
  api/user/index.ts
  package.json
  src/app/containers/app/app.component.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.scss
  src/cases/containers/case-list/case-list.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-533

#544 hotfix for new preview env
  charts/xui-webapp/values.preview.template.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-544

#545 updated ccdui-toolkit to 2.64.5-case-sharing-prerelease
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-545

#546 Add stalebot to MC
  .github/stale.yml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-546

#547 Feature/eui 1948 caseshare by type aa
  Jenkinsfile_parameterized
  api/.env.defaults
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  package.json
  src/app/app.module.ts
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/store/selectors/share-case.selectors.spec.ts
  src/main.ts
  src/models/environmentConfig.model.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-547

#529 Candidate fix for WAF rules false positives by changing the format of…
  api/auth/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-529

#552 added OIDC feature flag
  api/application.ts
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/lib/middleware/proxy.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-552
