Repository hmcts/rpx-xui-webapp, pull requests merged in 2020-05, with the labels that each got.

#480 Added Contact text missed in EUI-1590
  src/app/components/get-help/get-help.component.html
Labels: ns:xui, rel:xui-webapp-pr-480

#423 making the case search toggle same like case list
  src/cases/containers/case-search/case-search.component.html
Labels: ns:xui, rel:xui-webapp-pr-423

#418 update get help content
  src/app/app.constants.ts
Labels: ns:xui, rel:xui-webapp-pr-418

#481 remove unecessary network call
  src/app/guards/acceptTerms.guard.spec.ts
  src/app/guards/acceptTerms.guard.ts
Labels: ns:xui, rel:xui-webapp-pr-481

#421 EUI-1646 mutation tests using stryker
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  stryker.ng.conf.js
  stryker.node.conf.js
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-421

#482 fix the app initializer
  src/app/app-initilizer.ts
Labels: ns:xui, rel:xui-webapp-pr-482

#359 EUI-1472-ZAP-setting
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  security.sh
Labels: ns:xui, rel:xui-webapp-pr-359

#465 Feature/eui 1570 proxy middleware
  api/application.ts
  api/documents/DMStore.spec.ts
  api/documents/DMStore.ts
  api/documents/document.interface.spec.ts
  api/documents/document.interface.ts
  api/documents/index.spec.ts
  api/documents/index.ts
  api/documents/routes.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/proxy.ts
  api/lib/middleware/serviceToken.ts
  api/lib/proxy.ts
  api/print/index.spec.ts
  api/print/index.ts
  api/print/printService.spec.ts
  api/print/printService.ts
  api/print/routes.ts
  charts/xui-webapp/Chart.yaml
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-465

#483 Release/eui 1875 aa
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  api/application.ts
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/documents/DMStore.spec.ts
  api/documents/DMStore.ts
  api/documents/document.interface.spec.ts
  api/documents/document.interface.ts
  api/documents/index.spec.ts
  api/documents/index.ts
  api/documents/routes.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/proxy.ts
  api/lib/middleware/serviceToken.ts
  api/lib/proxy.ts
  api/payments/index.spec.ts
  api/payments/index.ts
  api/payments/paymentsService.spec.ts
  api/payments/paymentsService.ts
  api/payments/paymentsUtil.spec.ts
  api/payments/paymentsUtil.ts
  api/payments/routes.ts
  api/print/index.spec.ts
  api/print/index.ts
  api/print/printService.spec.ts
  api/print/printService.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
  package.json
  proxy.config.json
  security.sh
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/components/accessibility/accessibility.component.html
  src/app/components/get-help/get-help.component.html
  src/app/components/get-help/get-help.component.spec.ts
  src/app/components/get-help/get-help.component.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/cases/containers/case-search/case-search.component.html
  stryker.ng.conf.js
  stryker.node.conf.js
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-483

#470 Hotfix/eui 1805 payments tab aa
  api/application.ts
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/payments/index.spec.ts
  api/payments/index.ts
  api/payments/paymentsService.spec.ts
  api/payments/paymentsService.ts
  api/payments/paymentsUtil.spec.ts
  api/payments/paymentsUtil.ts
  api/payments/routes.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
  proxy.config.json
  src/app/app.module.ts
Labels: ns:xui, rel:xui-webapp-pr-470

#489 Hotfix/eui 1898 payment history aa
  api/application.ts
Labels: ns:xui, rel:xui-webapp-pr-489

#495 Upgraded common lib version
  package.json
  src/app/app.module.ts
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-495

#498 Tests/eui 1787 functional tests
  package.json
  test/e2e/config/fullfunctional.conf.js
  test/e2e/features/app/FRCreateCase_CaseWorker.feature
  test/e2e/features/app/FRCreateCase_solicitor.feature
  test/e2e/features/app/divorceCreateCase.feature
  test/e2e/features/app/immigrationAsylumCreateCase.feature
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/probateCreateCase.feature
  test/e2e/features/app/publicLawCreateCase.feature
  test/e2e/features/pageObjects/IACase.js
  test/e2e/features/pageObjects/PublicLawCase.js
  test/e2e/features/step_definitions/caseManager.steps.js
Labels: ns:xui, rel:xui-webapp-pr-498

#501 remove tf config files
  Jenkinsfile_CNP
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:xui, rel:xui-webapp-pr-501

#506 feature toggled T&C's route with dummy return data, early returns as …
  Jenkinsfile_CNP
  api/health/redis.health.ts
  api/lib/error.handler.ts
  api/local.ts
  api/server.ts
  api/termsAndConditions/index.ts
  api/termsAndConditions/resources/terms.html
  api/userTermsAndConditions/index.ts
Labels: ns:xui, rel:xui-webapp-pr-506

#512 removed all references to T&C's routes as we believe the imports may …
  Jenkinsfile_CNP
  api/amendedJurisdictions/index.spec.ts
  api/amendedJurisdictions/index.ts
  api/application.ts
  api/health/index.ts
  api/termsAndConditions/index.ts
  api/termsAndConditions/resources/terms.html
  api/termsAndConditions/routes.ts
  api/termsAndConditions/termAndConditionsUtil.spec.ts
  api/termsAndConditions/termsAndConditionsUtil.ts
  api/userTermsAndConditions/index.ts
  api/userTermsAndConditions/routes.ts
  api/userTermsAndConditions/userTermsAndConditionsUtil.spec.ts
  api/userTermsAndConditions/userTermsAndConditionsUtil.ts
Labels: ns:xui, rel:xui-webapp-pr-512

#515 enabled correct logging of errors
  api/lib/error.handler.ts
Labels: ns:xui, rel:xui-webapp-pr-515

#519 error handling within interceptors.ts
  api/application.ts
  api/lib/error.handler.ts
  api/lib/interceptors.ts
  api/lib/middleware/auth.ts
  api/lib/proxy.spec.ts
  api/lib/proxy.ts
  api/services/serviceAuth.ts
Labels: ns:xui, rel:xui-webapp-pr-519

#520 fixed annotations error handling
  api/emAnno/emAnnoService.ts
  api/emAnno/index.spec.ts
  api/emAnno/index.ts
Labels: ns:xui, rel:xui-webapp-pr-520
