Repository hmcts/rpx-xui-webapp, pull requests merged in 2020-09, with the labels that each got.

#627 Tests/pa11y tests chrome version fix
  infrastructure/state.tf
  package.json
  test/e2e/features/app/fplCreateCase.feature
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-627

#630 Feature/eui 2564 ld implementation aa
  Jenkinsfile_parameterized
  api/.env.defaults
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/app.module.ts
  src/main.ts
  src/models/environmentConfig.model.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-630

#634 EUI-2575: Update Internal Search API URL
  api/searchCases/index.ts
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-634

#635 Bug/eui 1844 utc local date aa
  infrastructure/state.tf
  package.json
  test/e2e/features/app/fplCreateCase.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-635

#638 Feature/eui 2086 respondent journey
  api/caseshare/index.ts
  api/caseshare/routes.ts
  api/organisations/index.ts
  package.json
  src/app/app.module.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/cases/converters/case-converter.ts
  src/cases/store/actions/organisations-list.action.spec.ts
  src/cases/store/effects/index.ts
  src/cases/store/reducers/index.ts
  test/e2e/features/step_definitions/loginLogout.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-638

#643 Feature/noc/eui 2449 container aa
  src/app/app.routes.ts
  src/noc/containers/index.ts
  src/noc/containers/noc-home/noc-home.component.html
  src/noc/containers/noc-home/noc-home.component.scss
  src/noc/containers/noc-home/noc-home.component.ts
  src/noc/noc.module.spec.ts
  src/noc/noc.module.ts
  src/noc/noc.routes.ts
  src/noc/store/actions/index.ts
  src/noc/store/effects/index.ts
  src/noc/store/index.ts
  src/noc/store/reducers/index.ts
  src/noc/store/selectors/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-643

#646 EUI-2625-accessibility-policy
  package.json
  src/app/components/accessibility/accessibility.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-646

#648 Feature/noc/eui 2458 navigation aa
  src/noc/constants/navigationVisibilityStates.ts
  src/noc/containers/index.ts
  src/noc/containers/noc-home/noc-home.component.html
  src/noc/containers/noc-home/noc-home.component.ts
  src/noc/containers/noc-navigation/noc-navigation.component.html
  src/noc/containers/noc-navigation/noc-navigation.component.spec.ts
  src/noc/containers/noc-navigation/noc-navigation.component.ts
  src/noc/store/actions/noc-navigation.action.spec.ts
  src/noc/store/actions/noc-navigation.action.ts
  src/noc/store/reducers/index.ts
  src/noc/store/reducers/noc-navigation.reducer.spec.ts
  src/noc/store/reducers/noc-navigation.reducer.ts
  src/noc/store/selectors/index.ts
  src/noc/store/selectors/noc-navigation.selectors.spec.ts
  src/noc/store/selectors/noc-navigation.selectors.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-648

#650 EUI-2657: Reinstate EUI-2575
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-650

#642 upgraded to latest node lib - csrf feature
  Jenkinsfile_nightly
  api/auth/index.ts
  api/test/pact/pact-tests/oidc.spec.ts
  audit.json
  package.json
  security.sh
  yarn.lock
Labels: ns:xui, prd:xui, qa/automation, rel:xui-webapp-pr-642
