Repository hmcts/rpx-xui-webapp, pull requests merged in 2020-12, with the labels that each got.

#761 EUI-2951: Task assignment error
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-home/task-home.component.ts
  src/work-allocation/resolvers/task.resolver.spec.ts
  src/work-allocation/services/work-allocation-task.service.spec.ts
  src/work-allocation/services/work-allocation-task.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-761

#767 EUI-2735: My and Available tasks
  package.json
  src/app/app-utils.ts
  src/app/components/index.ts
  src/work-allocation/components/task-field-wrapper/task-field-wrapper.component.scss
  src/work-allocation/components/task-field/task-field.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.html
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/index.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation/containers/task-assignment/task-assignment-container.component.scss
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-home/task-home.component.html
  src/work-allocation/containers/task-home/task-home.component.scss
  src/work-allocation/containers/task-home/task-home.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.html
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-manager/task-manager.component.html
  src/work-allocation/containers/work-allocation-home/work-allocation-home.component.html
  src/work-allocation/containers/work-allocation-home/work-allocation-home.component.ts
  src/work-allocation/work-allocation-feature.routes.ts
  src/work-allocation/work-allocation.module.ts
  test/accessibility/tests/workAllocation.test.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-767

#768 Feature/eui 2980 task deep link
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-home/task-home.component.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-768

#772 EUI-2735: My and Available tasks (PACT integration)
  angular.json
  api/test/pact/constants/work-allocation/actions.spec.ts
  api/test/pact/constants/work-allocation/behaviours.spec.ts
  api/test/pact/constants/work-allocation/caseworkers.spec.ts
  api/test/pact/constants/work-allocation/locations.spec.ts
  api/test/pact/constants/work-allocation/services.spec.ts
  api/test/pact/constants/work-allocation/tasks.spec.ts
  api/test/pact/pact-tests/work-allocation-get-task.spec.ts
  api/test/pact/pact-tests/work-allocation-post-cancel.spec.ts
  api/test/pact/pact-tests/work-allocation-post-claim.spec.ts
  api/test/pact/pact-tests/work-allocation-post-unclaim.spec.ts
  api/test/pact/pact-tests/work-allocation.caseworker-get-all.spec.ts
  api/test/pact/pact-tests/work-allocation.caseworker-get-by-id.spec.ts
  api/test/pact/pact-tests/work-allocation.caseworker-get-by-location-and-service.spec.ts
  api/test/pact/pact-tests/work-allocation.caseworker-get-by-location.spec.ts
  api/test/pact/pact-tests/work-allocation.caseworker-get-by-service.spec.ts
  api/test/pact/pact-tests/work-allocation.location-get-all.spec.ts
  api/test/pact/pact-tests/work-allocation.location-get-by-id.spec.ts
  api/test/pact/pact-tests/work-allocation.task-assign.spec.ts
  api/test/pact/pact-tests/work-allocation.task-complete.spec.ts
  api/test/pact/pact-tests/work-allocation.task-get-by-id.spec.ts
  api/test/pact/pact-tests/work-allocation.task-post-action.spec.ts
  api/test/pact/pact-tests/work-allocation.task-post-assign-bad-task.spec.ts
  api/test/pact/pact-tests/work-allocation.task-post-assign.spec.ts
  api/test/pact/pact-tests/work-allocation.task-search.spec.ts
  src/work-allocation/components/index.ts
  src/work-allocation/components/task-field-wrapper/task-field-wrapper.component.html
  src/work-allocation/components/task-field-wrapper/task-field-wrapper.component.scss
  src/work-allocation/components/task-field-wrapper/task-field-wrapper.component.ts
  src/work-allocation/components/task-field/task-field.component.html
  src/work-allocation/components/task-field/task-field.component.spec.ts
  src/work-allocation/components/task-field/task-field.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-manager/task-manager.component.html
  src/work-allocation/containers/task-manager/task-manager.component.scss
  src/work-allocation/containers/task-manager/task-manager.component.ts
  src/work-allocation/models/dtos/search-task-request.ts
  src/work-allocation/services/work-allocation-task.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-772

#773 Feature/eui 2897 wa inline messaging
  src/work-allocation/components/index.ts
  src/work-allocation/components/info-message/info-message.component.html
  src/work-allocation/components/info-message/info-message.component.spec.ts
  src/work-allocation/components/info-message/info-message.component.ts
  src/work-allocation/containers/task-home/task-home.component.html
  src/work-allocation/containers/task-home/task-home.component.ts
  src/work-allocation/enums/index.ts
  src/work-allocation/enums/info-message-type.ts
  src/work-allocation/enums/info-message.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-773

#774 Hotfix/e UI 2995 performance and ie11 fix
  api/amendedJurisdictions/index.spec.ts
  api/amendedJurisdictions/index.ts
  api/application.ts
  api/caseshare/routes.ts
  api/emAnno/index.spec.ts
  api/emAnno/index.ts
  api/emAnno/models.ts
  api/emAnno/routes.ts
  api/lib/middleware/proxy.ts
  api/payments/index.spec.ts
  api/payments/index.ts
  api/payments/paymentsService.spec.ts
  api/payments/paymentsService.ts
  api/payments/paymentsUtil.spec.ts
  api/payments/paymentsUtil.ts
  api/payments/routes.ts
  api/postCodeLookup/index.spec.ts
  api/postCodeLookup/index.ts
  api/proxy.config.ts
  api/redaction/markup.spec.ts
  api/redaction/markup.ts
  api/redaction/markupRoutes.ts
  api/redaction/redaction.spec.ts
  api/redaction/redaction.ts
  api/redaction/redactionModels.ts
  api/redaction/redactionRoutes.ts
  api/routes.ts
  api/searchCases/index.spec.ts
  api/searchCases/index.ts
  api/test/pact/pact-tests/work-allocation-post-cancel.spec.ts
  api/test/pact/pact-tests/work-allocation-post-claim.spec.ts
  api/test/pact/pact-tests/work-allocation-post-task.spec.ts
  api/test/pact/pact-tests/work-allocation-post-unclaim.spec.ts
  api/test/pact/pact-tests/work-allocation.task-assign.spec.ts
  api/user/routes.ts
  api/workAllocation/index.spec.ts
  api/workAllocation/index.ts
  api/workAllocation/interfaces/task.ts
  api/workAllocation/interfaces/taskSearchParameter.ts
  api/workAllocation/routes.spec.ts
  api/workAllocation/routes.ts
  api/workAllocation/taskService.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  package.json
  src/work-allocation/services/case-worker-data.service.spec.ts
  src/work-allocation/services/work-allocation-task.service.spec.ts
  src/work-allocation/services/work-allocation-task.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-774

#775 EUI-2735: Unit tests
  src/work-allocation/components/task-assignment/task-assignment.component.spec.ts
  src/work-allocation/components/task-assignment/task-assignment.component.ts
  src/work-allocation/components/task-field/task-field.component.spec.ts
  src/work-allocation/components/work-allocation.components.module.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.html
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-home/task-home.component.spec.ts
  src/work-allocation/containers/task-home/task-home.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.html
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/task-list/task-list.component.scss
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.ts
  src/work-allocation/guards/index.ts
  src/work-allocation/guards/work-allocation-feature-toggle.guard.ts
  src/work-allocation/models/dtos/index.ts
  src/work-allocation/models/dtos/search-task-request.ts
  src/work-allocation/models/dtos/task-search-parameter.spec.ts
  src/work-allocation/models/dtos/task-search-parameter.ts
  src/work-allocation/models/dtos/task.spec.ts
  src/work-allocation/models/dtos/task.ts
  src/work-allocation/models/index.ts
  src/work-allocation/models/json-config.spec.ts
  src/work-allocation/models/tasks/index.ts
  src/work-allocation/pipes/caseworker-display-name.pipe.ts
  src/work-allocation/resolvers/index.ts
  src/work-allocation/resolvers/task.resolver.ts
  src/work-allocation/services/case-worker-data.service.spec.ts
  src/work-allocation/services/case-worker-data.service.ts
  src/work-allocation/services/caseworker-data.service.spec.ts
  src/work-allocation/services/caseworker-data.service.ts
  src/work-allocation/services/index.ts
  src/work-allocation/services/location-data.service.spec.ts
  src/work-allocation/services/location-data.service.ts
  src/work-allocation/services/work-allocation-task.service.spec.ts
  src/work-allocation/services/work-allocation-task.service.ts
  src/work-allocation/tests/utils.spec.ts
  src/work-allocation/work-allocation-feature.routes.ts
  src/work-allocation/work-allocation.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-775

#782 Update ccd-case-ui-toolkit for ET perf issue
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-782

#784 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-784

#785 Feature/performance tabs
  package.json
  src/style/_material.scss
  src/style/app.scss
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-785

#783 Feature/e UI 2897 assign claim task
  README.md
  api/test/pact/constants/work-allocation/actions.spec.ts
  api/test/pact/constants/work-allocation/behaviours.spec.ts
  api/test/pact/constants/work-allocation/tasks.spec.ts
  api/workAllocation/index.ts
  src/app/app.routes.ts
  src/app/components/index.ts
  src/app/components/not-authorised/not-authorised.component.html
  src/app/components/not-authorised/not-authorised.component.ts
  src/work-allocation/components/work-allocation.components.module.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/task-home/task-home.component.html
  src/work-allocation/containers/task-home/task-home.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-manager/task-manager.component.html
  src/work-allocation/enums/index.ts
  src/work-allocation/enums/task-action-ids.ts
  src/work-allocation/models/comms/infomation-message.model.ts
  src/work-allocation/services/info-message-comms.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-783

#780 allow static caching of assets
  api/lib/middleware/removeCacheHeaders.ts
  api/server.ts
  package.json
  src/app/app-initilizer.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-780

#794 E UI 2897 unit tests
  package.json
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/services/info-message-comms.service.spec.ts
  src/work-allocation/services/info-message-comms.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-794

#795 EUI-2897 Refresh Task and 400 Messages shown at the same time as per design. Messages removed when user clicks on diff sub nav item.
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/task-home/task-home.component.html
  src/work-allocation/containers/task-home/task-home.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/services/info-message-comms.service.spec.ts
  src/work-allocation/services/info-message-comms.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-795

#798 hot fix to retain Tab name
  package.json
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/ngIntegration/tests/headerTabs.test.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-798
