Repository hmcts/rpx-xui-webapp, pull requests merged in 2020-01, with the labels that each got.

#316 Feature/eui 226 ccd routes upgrade
  package.json
  src/cases/containers/case-create-submit/case-create-submit.component.ts
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.scss
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/case-search/case-search.component.spec.ts
  src/cases/containers/case-search/case-search.component.ts
  src/cases/services/search-filter.service.spec.ts
  src/cases/services/search-filter.service.ts
  yarn.lock
Labels: ns:xui-webapp-pr-316

#323 Update linting rules
  tslint.json
Labels: ns:xui-webapp-pr-323

#333 EUI-1350 ITHC merge
  package.json
  src/app/app.routes.ts
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.ts
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-333

#335 fix for error not showing
  src/cases/containers/case-home/case-home.component.spec.ts
  src/cases/containers/case-home/case-home.component.ts
Labels: ns:xui, rel:xui-webapp-pr-335

#338 Bug/eui 1342 create case cancel link
  src/cases/store/effects/case-create.effects.spec.ts
  src/cases/store/effects/case-create.effects.ts
Labels: ns:xui, rel:xui-webapp-pr-338

#340 Csp fix image eui 1304
  src/web.config
Labels: ns:xui, rel:xui-webapp-pr-340

#342 Rebase terms and conditions
  Dockerfile
  api/application.ts
  api/config/environments/local.config.ts
  api/config/environments/preview.config.ts
  api/interface/userAcceptTandCResponse.ts
  api/lib/util.spec.ts
  api/lib/util.ts
  api/package.json
  api/termsAndConditions/index.ts
  api/termsAndConditions/routes.ts
  api/termsAndConditions/termAndConditionsUtil.spec.ts
  api/termsAndConditions/termsAndConditionsUtil.ts
  api/userTermsAndConditions/index.ts
  api/userTermsAndConditions/routes.ts
  api/userTermsAndConditions/userTermsAndConditionsUtil.spec.ts
  api/userTermsAndConditions/userTermsAndConditionsUtil.ts
  package.json
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/components/hmcts-primary-navigation/hmcts-primary-navigation.component.html
  src/app/components/hmcts-primary-navigation/hmcts-primary-navigation.component.ts
  src/app/components/index.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/components/terms-and-conditions/terms-and-conditions.component.ts
  src/app/containers/accept-tc.wrapper/accept-tc-wrapper.component.html
  src/app/containers/accept-tc.wrapper/accept-tc-wrapper.component.spec.ts
  src/app/containers/accept-tc.wrapper/accept-tc-wrapper.component.ts
  src/app/containers/index.ts
  src/app/containers/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.spec.ts
  src/app/containers/terms-and-conditions/terms-and-conditions.component.ts
  src/app/guards/acceptTerms.guard.spec.ts
  src/app/guards/acceptTerms.guard.ts
  src/app/guards/allowAcceptTerms.guard.spec.ts
  src/app/guards/allowAcceptTerms.guard.ts
  src/app/models/TermsAndCondition.ts
  src/app/services/acceptTerms/acceptTerms.service.spec.ts
  src/app/services/acceptTerms/acceptTerms.service.ts
  src/app/services/terms-and-conditions/terms-and-conditions.service.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/acceptTC.effects.spec.ts
  src/app/store/effects/acceptTC.effects.ts
  src/app/store/effects/app.effects.ts
  src/app/store/effects/index.ts
  src/app/store/reducers/app-config.reducer.spec.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
  src/index.html
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-342

#349 Feature/openid connect demo
  api/auth/index.ts
  package-lock.json
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-349

#351 Bug/eui 1409 toolkit upgrade continue button aa
  angular.json
  package.json
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.html
  src/app/services/ccd-config/ccd-case.config.ts
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-351

#355 EUI-1349 changes for demo
  api/application.ts
  package-lock.json
  proxy.config.json
  src/assets/config/config.json
  src/cases/case-feature.routes.ts
  src/cases/cases.module.ts
  src/cases/resolvers/activity.resolver.spec.ts
  src/cases/resolvers/activity.resolver.ts
  yarn.lock
Labels: ns:xui, rel:xui-webapp-pr-355
