Repository hmcts/rpx-xui-webapp, pull requests merged in 2020-08, with the labels that each got.

#610 share-case-update-configs
  api/configuration/appConfig.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-610

#607 hotfix chart version and tf cleanup
  Jenkinsfile_CNP
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-607

#621 Bugs/share case
  api/caseshare/real-api.ts
  package.json
  src/cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/cases/containers/case-share-complete/case-share-complete.component.ts
  src/cases/containers/case-share/case-share.component.html
  src/cases/containers/case-share/case-share.component.spec.ts
  src/cases/containers/case-share/case-share.component.ts
  src/cases/converters/case-converters.spec.ts
  src/cases/store/actions/share-case.action.ts
  src/cases/store/reducers/share-case.reducer.spec.ts
  src/cases/store/reducers/share-case.reducer.ts
  test/accessibility/config/config.js
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/tests/index.js
  test/nodeMock/reqResMapping.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-621

#622 Nightly build fix
  Jenkinsfile_nightly
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-622
