Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-11, with the labels that each got.

#1397 Feature/e UI 4609 get all work
  api/lib/proxy.ts
  api/proxy.config.ts
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/searchCases/index.ts
  api/tslint.json
  api/workAllocation2/index.spec.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/case.ts
  api/workAllocation2/interfaces/roleCaseData.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/app/app-utils.ts
  src/app/app.constants.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.html
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation-2/containers/work-case-list/work-case-list.component.html
  src/work-allocation-2/containers/work-case-list/work-case-list.component.ts
  src/work-allocation-2/models/cases/case.model.ts
  src/work-allocation-2/services/work-allocation-case.service.ts
  src/work-allocation-2/tests/utils.spec.ts
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1397

#1421 bug fix for displaying person details
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1421

#1422 Remove pagination footer from my cases
  src/work-allocation-2/containers/work-case-list/work-case-list.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1422

#1423 all-locations filter apply on cases instead of Role Assignments
  api/workAllocation2/index.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1423

#1420 WA FT test fix Nightly
  test/e2e/features/step_definitions/workallocation/workallocation.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1420

#1429 Bug/remove location hard coded
  api/roleAccess/dtos/to-role-assignment-dto.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1429

#1430 fix the current user from session
  api/roleAccess/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1430

#1427 add some logging
  api/workAllocation2/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1427

#1431 Role Assignment
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1431

#1432 upgrade CCD-UI-toolkit 4.7.0-rc.7
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1432

#1434 userId should be taken from the session/passport
  api/workAllocation2/index.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1434

#1418 EUI-4679 Global search date of death validation unhappy path
  package.json
  src/search/containers/search-form/search-form.component.html
  src/search/containers/search-form/search-form.component.scss
  src/search/containers/search-form/search-form.component.spec.ts
  src/search/containers/search-form/search-form.component.ts
  src/search/enums/index.ts
  src/search/enums/search-form-control.enum.ts
  src/search/enums/search-form-error-message.enum.ts
  src/search/enums/search-form-error-type.enum.ts
  src/search/models/index.ts
  src/search/models/search-validation-error.model.ts
  src/search/utils/index.ts
  src/search/utils/search-validators.spec.ts
  src/search/utils/search-validators.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1418

#1419 EUI-4626: Implement session storage of Global Search state
  src/search/containers/search-form/search-form.component.spec.ts
  src/search/containers/search-form/search-form.component.ts
  src/search/containers/search-results/search-results.component.spec.ts
  src/search/containers/search-results/search-results.component.ts
  src/search/enums/index.ts
  src/search/enums/search-state-persistence-key.enum.ts
  src/search/models/index.ts
  src/search/models/search-parameters.model.ts
  src/search/models/search-request-criteria.model.ts
  src/search/search-routing.module.ts
  src/search/services/search.service.spec.ts
  src/search/services/search.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1419

#1436 feature/EUI-4680-hearings-status
  api/hearings/models/hearingStatusMappings.ts
  api/hearings/models/hearings.enum.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearings-badge.pipe.spec.ts
  src/hearings/pipes/hearings-badge.pipe.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1436

#1439 Bug/safety check find logic
  .gitignore
  Jenkinsfile_CNP
  api/test/pact/pact-tests/wa/searchTasks.spec.ts
  api/workAllocation/index.ts
  api/workAllocation2/util.ts
  package.json
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/models/nav-item.model.ts
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-search/case-search.component.html
  src/work-allocation/guards/senior-tribunal-caseworker-guard.spec.ts
  src/work-allocation/guards/tribunal-caseworker-guard.ts
  test/e2e/features/app/timestamp.feature
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/timestamp.steps.js
  test/e2e/features/step_definitions/workallocation/workallocation.steps.js
  test/e2e/support/hooks.js
  test/ngIntegration/tests/features/navigationHeader.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1439

#1441 Fix caseworker parameter issue
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  test/integration/tests/utils/wa/taskRequestBody.ts
  test/integration/tests/workAllocation.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1441

#1445 WA test fix to handle both OIDC true and false cases to get user id
  test/e2e/features/pageObjects/hearingRecordingsCase.js
  test/e2e/features/step_definitions/navigationHeader.steps.js
  test/integration/tests/workAllocation.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1445

#1425 Feature/e UI 4639 jurisdiction config
  api/configuration/references.ts
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/models/allocate-role-state-data.interface.ts
  api/routes.ts
  api/waSupportedJurisdictions/index.spec.ts
  api/waSupportedJurisdictions/index.ts
  api/workAllocation2/index.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  config/custom-environment-variables.json
  config/default.json
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation-2/components/work-allocation.components.module.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.html
  src/work-allocation-2/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.html
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/task-home/task-home.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation-2/services/index.ts
  src/work-allocation-2/services/wa-supported-jurisdiction.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1425

#1443 fix case allocator role
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1443

#1448 E UI 4681 change display of hearing link
  src/cases/components/case-hearings-list/case-hearings-list.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1448

#1168 MC-Release-23.1
  config/default.json
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/cases/case-feature.routes.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/cases/containers/index.ts
  test/e2e/features/pageObjects/CaseListPage.js
  test/e2e/features/pageObjects/createCaseStartPage.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/step_definitions/caseManager.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/navigationHeader.steps.js
  test/e2e/features/step_definitions/workallocation/workallocation.steps.js
  test/e2e/support/customWaits.js
  test/e2e/support/hooks.js
  test/integration/tests/mocha.json
  test/integration/tests/utils/helper.ts
  test/integration/tests/workAllocation.spec.ts
  yarn.lock
Labels: DO NOT MERGE, ns:xui, prd:xui, rel:xui-webapp-pr-1168

#1440 exclusions integration work
  api/auth/interfaces/UserInfo.ts
  api/roleAccess/exclusionService.spec.ts
  api/roleAccess/exclusionService.ts
  api/roleAccess/index.ts
  api/roleAccess/models/caseRoleRequestPayload.ts
  api/roleAccess/models/release2ContentType.ts
  api/roleAccess/routes.ts
  api/user/index.ts
  api/user/interfaces/roleAssignment.ts
  api/user/utils.spec.ts
  api/user/utils.ts
  api/workAllocation2/util.ts
  src/role-access/components/exclusions-table/exclusions-table.component.html
  src/role-access/components/exclusions-table/exclusions-table.component.spec.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.ts
  test/ngIntegration/tests/features/workallocation2/rolesAccess/exclusions.feature
  test/ngIntegration/tests/features/workallocation2/rolesAccess/rolesAndAccessTabPage.feature
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1440

#1446 EUI-4692-mock-hearing-stage
  api/hearings/data/hearings.mock.data.ts
  api/hearings/data/reference.mock.data.ts
  api/hearings/hearing.mock.ts
  api/hearings/index.ts
  api/hearings/models/refData.model.ts
  api/hearings/routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1446

#1460 Feature/e UI 4690 location api
  api/locations/data/location.mock.data.ts
  api/locations/data/locationType.enum.ts
  api/locations/data/serviceCourtType.mapping.ts
  api/locations/index.ts
  api/locations/location.mock.ts
  api/locations/models/location.model.ts
  api/locations/routes.ts
  api/routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1460

#1456 roleType Filter to avoid duplicates
  api/workAllocation/caseWorkerService.ts
  api/workAllocation/util.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1456

#1451 Feature/e UI 4495 forget specific person conditionally
  package.json
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.spec.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/components/index.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1451

#1467 fix for the loading caseworkers from role-access tab
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/role-access/role-access.module.ts
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1467

#1464 Bugfix/show roles and access tab for caseworker ia
  src/app/app-utils.spec.ts
  src/app/app.constants.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1464

#1453 E UI 4628 order of display
  api/hearings/data/hearings.mock.data.ts
  api/hearings/models/caseHearing.model.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/models/caseHearing.model.ts
  src/hearings/models/caseHearingView.model.ts
  src/hearings/store/effects/hearings.effects.spec.ts
  src/hearings/store/reducers/hearings.reducer.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1453

#1468 Mc CVE temp
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1468

#1472 remove location column from case role table
  src/role-access/components/case-roles-table/case-roles-table.component.html
  src/role-access/components/case-roles-table/case-roles-table.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1472

#1473 caseworker-ia-admofficer default route
  src/app/components/routing/application-routing.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1473

#1474 E UI 4751 hearings
  api/locations/location.mock.ts
  package.json
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1474

#1477 non case-allocator is not allowed to delete exclusion
  src/cases/components/roles-and-access/roles-and-access.component.html
  src/role-access/components/exclusions-table/exclusions-table.component.html
  src/role-access/components/exclusions-table/exclusions-table.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1477

#1470 EUI-4461: Pagination for Global Search
  package.json
  src/search/containers/search-form/search-form.component.ts
  src/search/containers/search-results/search-results.component.html
  src/search/containers/search-results/search-results.component.spec.ts
  src/search/containers/search-results/search-results.component.ts
  src/search/models/index.ts
  src/search/models/search-result.model.ts
  src/search/services/search.service.spec.ts
  src/search/services/search.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1470

#1478 getLocations using new filter
  api/workAllocation2/interfaces/location.ts
  api/workAllocation2/locationController.spec.ts
  api/workAllocation2/locationController.ts
  src/work-allocation-2/services/location-data.service.spec.ts
  src/work-allocation-2/services/location-data.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1478

#1394 retrieving role types
  api/roleAccess/models/roleType.ts
  api/roleAccess/roleAssignmentService.ts
  api/workAllocation2/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1394

#1403 Feature/e UI 4615 task integration
  api/workAllocation2/index.spec.ts
  api/workAllocation2/index.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/taskService.mock.ts
  api/workAllocation2/taskService.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/role-access/utils/role-access-utils.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.html
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.ts
  src/work-allocation-2/resolvers/task.resolver.spec.ts
  src/work-allocation-2/resolvers/task.resolver.ts
  src/work-allocation-2/services/work-allocation-task.service.ts
  src/work-allocation/resolvers/task.resolver.ts
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1403

#1481 Feature/enext 4688
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.html
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.scss
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.spec.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.ts
  src/hearings/containers/index.ts
  src/hearings/containers/request-hearing/request-hearing.component.html
  src/hearings/containers/request-hearing/request-hearing.component.scss
  src/hearings/containers/request-hearing/request-hearing.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/containers/request-hearing/welsh-hearing/welsh-hearing.component.html
  src/hearings/containers/request-hearing/welsh-hearing/welsh-hearing.component.scss
  src/hearings/containers/request-hearing/welsh-hearing/welsh-hearing.component.spec.ts
  src/hearings/containers/request-hearing/welsh-hearing/welsh-hearing.component.ts
  src/hearings/hearings.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1481

#1449 first commit
  api/workAllocation2/index.spec.ts
  api/workAllocation2/index.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  package.json
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.scss
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.spec.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/services/location-data.service.spec.ts
  src/work-allocation-2/services/task-data.service.spec.ts
  src/work-allocation-2/services/task-types.service.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1449

#1487 CVE fix temp
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1487

#1488 EUI-4450: Load existing search parameters into form
  src/search/containers/search-form/search-form.component.spec.ts
  src/search/containers/search-form/search-form.component.ts
  src/search/models/search-request-criteria.model.ts
  src/search/models/search-request-party.model.ts
  src/search/services/search.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1488

#1480 EUI-4449 Global Search other unhappy paths
  src/search/containers/no-results/no-results.component.html
  src/search/containers/no-results/no-results.component.spec.ts
  src/search/containers/no-results/no-results.component.ts
  src/search/containers/search-results/search-results.component.spec.ts
  src/search/containers/search-results/search-results.component.ts
  src/search/enums/index.ts
  src/search/enums/no-results-message-id.enum.ts
  src/search/search-routing.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1480

#1483 E UI 4708 hearing venue service location
  api/locations/data/location.mock.data.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  package.json
  src/cases/case-feature.module.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/containers/index.ts
  src/hearings/containers/request-hearing/location-search-container/location-search-container.component.html
  src/hearings/containers/request-hearing/location-search-container/location-search-container.component.spec.ts
  src/hearings/containers/request-hearing/location-search-container/location-search-container.component.ts
  src/hearings/containers/request-hearing/request-hearing.component.html
  src/hearings/containers/request-hearing/request-hearing.component.scss
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/hearings.module.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/location.model.ts
  src/hearings/store/selectors/hearings.selectors.spec.ts
  src/style/app.scss
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1483

#1491 Booking wrapper
  src/app/app.routes.ts
  src/booking/booking.module.spec.ts
  src/booking/booking.module.ts
  src/booking/booking.routes.ts
  src/booking/constants/pageVisibilityStates.ts
  src/booking/containers/booking-check/booking-check.component.html
  src/booking/containers/booking-check/booking-check.component.scss
  src/booking/containers/booking-check/booking-check.component.spec.ts
  src/booking/containers/booking-check/booking-check.component.ts
  src/booking/containers/booking-date/booking-date.component.html
  src/booking/containers/booking-date/booking-date.component.scss
  src/booking/containers/booking-date/booking-date.component.spec.ts
  src/booking/containers/booking-date/booking-date.component.ts
  src/booking/containers/booking-home/booking-home.component.html
  src/booking/containers/booking-home/booking-home.component.scss
  src/booking/containers/booking-home/booking-home.component.spec.ts
  src/booking/containers/booking-home/booking-home.component.ts
  src/booking/containers/booking-location/booking-location.component.html
  src/booking/containers/booking-location/booking-location.component.scss
  src/booking/containers/booking-location/booking-location.component.spec.ts
  src/booking/containers/booking-location/booking-location.component.ts
  src/booking/containers/booking-wrapper/booking-wrapper.component.html
  src/booking/containers/booking-wrapper/booking-wrapper.component.scss
  src/booking/containers/booking-wrapper/booking-wrapper.component.spec.ts
  src/booking/containers/booking-wrapper/booking-wrapper.component.ts
  src/booking/containers/index.ts
  src/booking/models/booking-navigation-event.enum.ts
  src/booking/models/booking-navigation.interface.ts
  src/booking/models/booking-state.enum.ts
  src/booking/models/index.ts
  src/booking/models/new-booking.interface.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1491

#1494 EUI-4652 (EUI-4404): Fix rendering of read-only Collection field in editable Complex field
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1494

#1500 Feature/e UI 4753 service hearing value
  api/hearings/data/reference.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/hearing.mock.ts
  api/hearings/index.ts
  api/hearings/models/defaultHearingWindow.model.ts
  api/hearings/models/hearings.enum.ts
  api/hearings/models/judiciary.model.ts
  api/hearings/models/panelPreference.model.ts
  api/hearings/models/partyFlags.model.ts
  api/hearings/models/partyUnavilability.model.ts
  api/hearings/models/screenNavigation.model.ts
  api/hearings/models/serviceHearingValues.model.ts
  api/hearings/models/vocabulary.model.ts
  api/hearings/routes.ts
  api/locations/index.ts
  api/locations/location.mock.ts
  api/locations/routes.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/containers/request-hearing/request-hearing.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/models/defaultHearingWindow.model.ts
  src/hearings/models/hearingValuesStateData.ts
  src/hearings/models/judiciary.model.ts
  src/hearings/models/partyFlags.model.ts
  src/hearings/models/partyUnavilability.model.ts
  src/hearings/models/screenNavigation.model.ts
  src/hearings/models/serviceHearingValues.model.ts
  src/hearings/models/vocabulary.model.ts
  src/hearings/services/hearings.service.ts
  src/hearings/store/actions/hearing-values.action.spec.ts
  src/hearings/store/actions/hearing-values.action.ts
  src/hearings/store/actions/index.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/effects/hearing-values.effects.ts
  src/hearings/store/effects/index.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
  src/hearings/store/reducers/hearing-values.reducer.ts
  src/hearings/store/reducers/index.ts
  src/hearings/store/selectors/hearing-values.selectors.spec.ts
  src/hearings/store/selectors/hearing-values.selectors.ts
  src/hearings/store/selectors/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1500

#1479 EUI-4350 Booking UI- Work access screen- display story
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/judicialBooking/data/booking.mock.data.ts
  api/judicialBooking/index.spec.ts
  api/judicialBooking/index.ts
  api/judicialBooking/models/booking.model.ts
  api/proxy.config.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  proxy.config.json
  src/booking/booking.module.ts
  src/booking/containers/booking-home/booking-home.component.html
  src/booking/containers/booking-home/booking-home.component.scss
  src/booking/containers/booking-home/booking-home.component.spec.ts
  src/booking/containers/booking-home/booking-home.component.ts
  src/booking/models/booking.interface.ts
  src/booking/models/index.ts
  src/booking/services/booking.service.spec.ts
  src/booking/services/booking.service.ts
  src/booking/services/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1479

#1498 Feature/EUI 4360 book time location page
  package.json
  src/booking/booking.module.ts
  src/booking/containers/booking-date/booking-date.component.html
  src/booking/containers/booking-date/booking-date.component.scss
  src/booking/containers/booking-date/booking-date.component.spec.ts
  src/booking/containers/booking-date/booking-date.component.ts
  src/booking/models/booking-date.enum.ts
  src/booking/models/index.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1498

#1496 Feature/e UI 4778 all work task integration
  api/workAllocation2/index.ts
  src/app/resolvers/case-tasks-resolver.service.spec.ts
  src/app/resolvers/case-tasks-resolver.service.ts
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/tasks-container/tasks-container.component.html
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/models/tasks/index.ts
  src/work-allocation-2/services/work-allocation-case.service.ts
  test/e2e/support/hooks.js
  test/ngIntegration/tests/stepDefinitions/nodeMock.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1496

#1502 Feature/e UI 4826 location api cr
  api/locations/data/serviceCourtType.mapping.ts
  api/locations/index.ts
  api/locations/location.mock.ts
  api/locations/models/location.model.ts
  package.json
  src/hearings/containers/request-hearing/location-search-container/location-search-container.component.html
  src/hearings/containers/request-hearing/location-search-container/location-search-container.component.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1502

#1492 Bugfix/e UI 4560 case details active tab
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/work-allocation-2/containers/task-assignment-choose-role/task-assignment-choose-role.component.spec.ts
  src/work-allocation-2/containers/task-assignment-choose-role/task-assignment-choose-role.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1492

#1476 Feature/e UI 3750 display role type for assign and reassign
  api/workAllocation2/constants/task-roles.mock.data.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/TaskRole.ts
  api/workAllocation2/routes.ts
  src/app/resolvers/case-tasks-resolver.service.spec.ts
  src/app/resolvers/case-tasks-resolver.service.ts
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/tasks-container/tasks-container.component.html
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/role-access/components/choose-radio-option/choose-radio-option.component.html
  src/role-access/components/choose-radio-option/choose-radio-option.component.ts
  src/role-access/models/options-model.ts
  src/role-access/role-access.module.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/index.ts
  src/work-allocation-2/containers/my-cases/my-cases.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment-choose-role/task-assignment-choose-role.component.html
  src/work-allocation-2/containers/task-assignment-choose-role/task-assignment-choose-role.component.scss
  src/work-allocation-2/containers/task-assignment-choose-role/task-assignment-choose-role.component.spec.ts
  src/work-allocation-2/containers/task-assignment-choose-role/task-assignment-choose-role.component.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/models/tasks/TaskRole.ts
  src/work-allocation-2/models/tasks/index.ts
  src/work-allocation-2/resolvers/index.ts
  src/work-allocation-2/resolvers/task-role-resolver.service.spec.ts
  src/work-allocation-2/resolvers/task-role-resolver.service.ts
  src/work-allocation-2/resolvers/task.resolver.spec.ts
  src/work-allocation-2/services/work-allocation-case.service.ts
  src/work-allocation-2/services/work-allocation-task.service.ts
  src/work-allocation-2/work-allocation-feature.routes.ts
  src/work-allocation-2/work-allocation2.module.ts
  test/accessibility/tests/workAllocation/allWork.test.js
  test/accessibility/tests/workAllocation/rolesAndAccessWorkFlowPages.test.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1476

#1504 all-work remove location filter
  api/workAllocation2/index.ts
  api/workAllocation2/util.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.html
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1504

#1510 feature/EUI 4735
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.html
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.spec.ts
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.ts
  src/hearings/containers/index.ts
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.html
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.spec.ts
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.ts
  src/hearings/models/partyUnavilability.model.ts
  src/hearings/models/partyUnavilabilityRange.model.ts
  src/hearings/store/selectors/hearing-values.selectors.spec.ts
  src/hearings/store/selectors/hearing-values.selectors.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1510

#1495 feature/EUI-4698
  api/hearings/data/reference.mock.data.ts
  src/hearings/containers/index.ts
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.html
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.scss
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.spec.ts
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.ts
  src/hearings/containers/request-hearing/location-search-container/location-search-container.component.spec.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/models/refData.model.ts
  src/hearings/resolvers/priority/priority.resolve.ts
  src/hearings/resolvers/priority/priority.resolver.spec.ts
  src/hearings/services/hearings-ref-data.service.spec.ts
  src/hearings/services/hearings-ref-data.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1495

#1516 EUI-4373: 16-digit case reference input validation
  src/app/components/case-reference-search-box/case-reference-search-box.component.html
  src/app/components/case-reference-search-box/case-reference-search-box.component.scss
  src/app/components/case-reference-search-box/case-reference-search-box.component.spec.ts
  src/app/components/case-reference-search-box/case-reference-search-box.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.scss
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/components/hmcts-primary-navigation/hmcts-primary-navigation.component.html
  src/app/components/hmcts-primary-navigation/hmcts-primary-navigation.component.scss
  src/app/components/hmcts-primary-navigation/hmcts-primary-navigation.component.spec.ts
  src/app/components/hmcts-primary-navigation/hmcts-primary-navigation.component.ts
  src/app/components/index.ts
  src/app/containers/app-header/app-header.component.html
  src/app/containers/app-header/app-header.component.ts
  src/app/shared/shared.module.ts
  src/app/store/actions/app.actions.ts
  src/app/store/reducers/app-config.reducer.spec.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
  src/search/containers/no-results/no-results.component.html
  src/search/containers/no-results/no-results.component.spec.ts
  src/search/containers/no-results/no-results.component.ts
  src/search/containers/search-results/search-results.component.html
  src/search/containers/search-results/search-results.component.spec.ts
  src/search/containers/search-results/search-results.component.ts
  src/search/enums/index.ts
  src/search/enums/no-results-message-id.enum.ts
  src/search/enums/process-for-access-type.enum.ts
  src/search/search-routing.module.ts
  src/search/utils/search-validators.spec.ts
  src/search/utils/search-validators.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1516

#1515 Feature/e UI 4361 booking date entry validation
  src/booking/containers/booking-date/booking-date.component.html
  src/booking/containers/booking-date/booking-date.component.ts
  src/booking/containers/utils/date-validators.spec.ts
  src/booking/containers/utils/date-validators.ts
  src/booking/containers/utils/index.ts
  src/booking/models/booking-date-validation-error.ts
  src/booking/models/booking-date.enum.ts
  src/booking/models/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1515

#1513 feature/EUI-4735
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.html
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.scss
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.spec.ts
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.ts
  src/hearings/containers/index.ts
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.html
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.spec.ts
  src/hearings/containers/request-hearing/date-priority-hearing/date-priority-hearing.component.ts
  src/hearings/models/partyUnavilability.model.ts
  src/hearings/models/partyUnavilabilityRange.model.ts
  src/hearings/store/selectors/hearing-values.selectors.spec.ts
  src/hearings/store/selectors/hearing-values.selectors.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1513

#1508 bug/EUI-4627
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1508

#1517 Bug/e UI 4804 judicial user
  api/workAllocation2/index.spec.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/case.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/app/app-utils.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1517

#1518 Upgrade properties-volume
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1518

#1519 EUI-4549: Case Reference search box input validation
  src/app/components/case-reference-search-box/case-reference-search-box.component.ts
  src/search/utils/search-validators.spec.ts
  src/search/utils/search-validators.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1519
