Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-01, with the labels that each got.

#760 Release exui mc 4.0.6
  src/app/app.routes.ts
  src/app/containers/app-header/app-header.component.spec.ts
  src/app/containers/app-header/app-header.component.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/shared/services/exui-title.service.spec.ts
  src/app/shared/services/exui-title.service.ts
  src/app/shared/shared.module.ts
  src/cases/case-feature.routes.ts
  src/cases/containers/case-home/case-home.component.spec.ts
  src/cases/containers/case-home/case-home.component.ts
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.spec.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.html
  src/cases/store/selectors/share-case.selectors.spec.ts
  test/accessibility/tests/footerPages.js
  test/e2e/features/pageObjects/FPLcase.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-760

#808 hotfix/axios security
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-808

#748 XUI MC enable HPA
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/requirements.yaml
  charts/xui-webapp/values.yaml
Labels: dependencies, ns:xui, prd:xui, rel:xui-webapp-pr-748

#814 EUI-3031: Clear session storage on logout
  src/app/services/auth/auth.service.spec.ts
  src/app/services/auth/auth.service.ts
  src/app/services/index.ts
  src/app/services/session-storage/session-storage.service.ts
  src/work-allocation/components/available-tasks-filter/available-tasks-filter.component.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/services/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-814

#815 EUI-2954: Unassign, cancel, and mark task as done
  src/work-allocation/components/constants/index.ts
  src/work-allocation/components/constants/task-action.constants.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/index.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.html
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/enums/index.ts
  src/work-allocation/enums/info-message.ts
  src/work-allocation/enums/task-action-ids.ts
  src/work-allocation/enums/task-action-type.ts
  src/work-allocation/services/work-allocation-task.service.ts
  src/work-allocation/work-allocation-feature.routes.ts
  test/accessibility/tests/workAllocation.test.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-815

#818 update node chart version
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/requirements.yaml
  charts/xui-webapp/values.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-818

#820 E UI 2963
  .gitignore
  api/test/pact/constants/work-allocation/actions.spec.ts
  api/test/pact/constants/work-allocation/tasks.spec.ts
  api/workAllocation/constants/actions.ts
  api/workAllocation/index.ts
  src/cases/case-feature.routes.ts
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/components/case-alert/alert.component.ts
  src/cases/containers/case-details-home/case-details-home.component.html
  src/cases/containers/case-details-home/case-details-home.component.spec.ts
  src/cases/containers/case-details-home/case-details-home.component.ts
  src/cases/containers/case-details-home/case-details-home.ts
  src/cases/containers/case-details/case-details.component.spec.ts
  src/cases/containers/case-details/case-details.component.ts
  src/cases/containers/index.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/enums/task-action-ids.ts
  src/work-allocation/work-allocation.module.ts
  test/nodeMock/reqResMapping.js
  test/nodeMock/workAllocation/mockData.js
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-820

#828 Workallocation utils spec
  src/work-allocation/utils/index.ts
  src/work-allocation/utils/work-allocation-utils.spec.ts
  src/work-allocation/utils/work-allocation-utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-828

#738 Active menu highlighting
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/containers/app-header/app-header.component.html
  src/app/containers/app-header/app-header.component.spec.ts
  src/app/containers/app-header/app-header.component.ts
  src/cases/containers/case-list/case-list.component.ts
  test/accessibility/tests/caseList.test.js
  test/e2e/features/app/searchCase.feature
  test/nodeMock/reqResMapping.js
Labels: dependencies, ns:xui, prd:xui, rel:xui-webapp-pr-738

#839 E UI 3134 manage options
  src/app/app.constants.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/containers/app-header/app-header.component.spec.ts
  src/index.html
  src/noc/noc.routes.ts
  src/work-allocation/containers/task-list/task-list.component.scss
  src/work-allocation/work-allocation-feature.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-839

#845 Functionality for unassign message discrepancy
  src/work-allocation/components/constants/task-action.constants.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/enums/info-message.ts
  src/work-allocation/tests/utils.spec.ts
  src/work-allocation/work-allocation-feature.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-845

#832 consumer pact with rd-professional-api and modified workallocation
  Jenkinsfile_CNP
  api/test/pact/pact-tests/case-share/case-share-get-cases-from-case-assingnment.spec.ts
  api/test/pact/pact-tests/case-share/case-share-post-assign-cases-to-users.spec.ts
  api/test/pact/pact-tests/idam/idam.get-user-by-email.spec.ts
  api/test/pact/pact-tests/idam/idam.spec.ts
  api/test/pact/pact-tests/idam/oidc.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/getOrganisations.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/getUsers.spec.ts
  api/test/pact/pact-tests/test.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation-get-task.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation-post-cancel.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation-post-claim.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation-post-task.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation-post-unclaim.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.caseworker-get-all.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.caseworker-get-by-id.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.caseworker-get-by-location-and-service.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.caseworker-get-by-location.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.caseworker-get-by-service.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.caseworker-post-search.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.location-get-all.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.location-get-by-id.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.task-assign.spec.ts
  api/test/pact/pact-tests/workAllocation/work-allocation.task-complete.spec.ts
  api/test/pact/pactFixtures.ts
  api/test/pact/pactUtil.ts
  test/e2e/config/crossbrowser.conf.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-832

#844 E UI 2992 noc integration ishita
  src/noc/constants/nocErrorMap.enum.ts
  src/noc/containers/noc-affirmation/noc-affirmation.component.html
  src/noc/containers/noc-affirmation/noc-affirmation.component.scss
  src/noc/containers/noc-affirmation/noc-affirmation.component.ts
  src/noc/containers/noc-case-ref/noc-case-ref.component.html
  src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.html
  src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.spec.ts
  src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.ts
  src/noc/containers/noc-check-your-answers/noc-check-your-answers.component.html
  src/noc/containers/noc-home/noc-home.component.scss
  src/noc/containers/noc-home/noc-home.component.ts
  src/noc/containers/noc-q-and-a/noc-q-and-a.component.html
  src/noc/containers/noc-submit-success/noc-submit-success.component.html
  src/noc/models/noc-state-data.interface.ts
  src/noc/store/actions/noc.action.spec.ts
  src/noc/store/actions/noc.action.ts
  src/noc/store/reducers/noc.reducer.ts
  src/noc/store/selectors/noc.selectors.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-844

#849 tests on CCD api jurisdiction timeout, retry logic
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/support/world.js
  test/integration/tests/ccd_endpoints.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-849

#836 EUI 3061
  api/application.ts
  api/configuration/health.ts
  api/configuration/references.ts
  api/health/index.ts
  api/healthCheck/index.ts
  api/interfaces/environment.config.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.aat.template.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-836

#856 upgrade ccd-ui-toolkit
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/cases/containers/case-create-submit/case-create-submit.component.spec.ts
  test/e2e/features/app/searchCase.feature
  test/integration/tests/utils/request.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-856
