Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-06, with the labels that each got.

#1052 EUI-3756: Enable wildcard searching for HRS jurisdiction
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1052

#1055 EUI 3740 implementing generic filter
  api/auth/index.ts
  api/configuration/references.ts
  api/workAllocation2/caseWorkerService.ts
  api/workAllocation2/constants/locations.ts
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/task.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/taskService.mock.ts
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/app.module.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.html
  src/work-allocation-2/containers/task-home/task-home.component.html
  src/work-allocation-2/containers/task-home/task-home.component.scss
  src/work-allocation-2/containers/task-home/task-home.component.spec.ts
  src/work-allocation-2/containers/task-home/task-home.component.ts
  src/work-allocation-2/models/dtos/index.ts
  src/work-allocation-2/resolvers/location-resolver.service.ts
  src/work-allocation-2/resolvers/location.resolver.spec.ts
  src/work-allocation-2/services/caseworker-data.service.ts
  src/work-allocation-2/services/judicialworker-data.service.spec.ts
  src/work-allocation-2/services/judicialworker-data.service.ts
  src/work-allocation-2/services/location-data.service.ts
  src/work-allocation-2/work-allocation-feature.routes.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1055

#1099 Crossbrowser fix for MC
  package.json
  test/e2e/config/crossbrowser.conf.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1099

#1096 Feature/e UI 4031
  api/workAllocation/index.ts
  api/workAllocation/routes.ts
  src/app/app.constants.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.html
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/services/work-allocation-task.service.ts
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1096

#1073 upgrade @hmcts/rpx-xui-node-lib@2.25.3
  api/workAllocation/index.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1073

#1075 EUI-4074-removing-sorting
  src/work-allocation/components/constants/config.constants.ts
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/task-list/task-list.component.scss
  src/work-allocation/models/tasks/task-field-config.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1075

#1102 page_size is 25 now
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1102

#1105 fix CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1105

#1095 Feature/common lib changes ud rm
  package.json
  src/app/app-initilizer.spec.ts
  src/app/app-initilizer.ts
  src/app/app.module.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/shared/shared.module.ts
  src/noc/noc.module.ts
  src/work-allocation-2/containers/task-home/task-home.component.ts
  test/e2e/config/appTestConfig.js
  test/e2e/features/app/workAllocation.feature
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/workAllocation/taskListTable.js
  test/e2e/features/step_definitions/ldService.steps.js
  test/e2e/features/step_definitions/navigationHeader.steps.js
  test/e2e/support/customWaits.js
  test/e2e/utils/request.js
  test/ngIntegration/tests/features/launchDarklyService.feature
  test/ngIntegration/tests/features/workAllocation/taskActions.feature
  test/ngIntegration/tests/features/workAllocation/taskListAvailableTasks.feature
  test/ngIntegration/tests/features/workAllocation/taskListMyTasks.feature
  test/ngIntegration/tests/features/workAllocation/taskManager.feature
  test/ngIntegration/tests/features/workallocation2/taskActions.feature
  test/ngIntegration/tests/stepDefinitions/workallocation/wa.steps.js
  test/ngIntegration/tests/stepDefinitions/workallocation/waCommon.steps.js
  test/nodeMock/nodeApp/mockData.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1095

#1110 fix CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1110

#1104 ExpressionChanged fix console CaseHomeComponent error
  src/cases/containers/case-home/case-home.component.ts
Labels: dependencies, ns:xui, prd:xui, rel:xui-webapp-pr-1104

#1115 fix CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1115

#1065 EUI-4056-Find-case-missing
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1065

#980 EUI-3664 Fix WA Task Assignee disappearing on refresh
  src/work-allocation/components/task-assignment/task-assignment.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-980

#1107 adding role management Info for the currently logged in User
  api/auth/interfaces/UserInfo.ts
  api/user/index.spec.ts
  api/user/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1107

#1116 Feature/e UI 3975 wa pagination
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/index.spec.ts
  api/workAllocation2/index.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/taskService.mock.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  package.json
  src/app/app.constants.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.html
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.html
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.html
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.html
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/containers/task-list/task-list.component.ts
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.html
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation-2/models/dtos/index.ts
  src/work-allocation-2/services/work-allocation-task.service.ts
  test/nodeMock/workAllocation/reqResMapping.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1116

#1126 Find person Component for Judicial and Caseworker
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/interfaces/person.ts
  api/workAllocation2/personService.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  package.json
  src/work-allocation-2/components/find-person/find-person.component.html
  src/work-allocation-2/components/find-person/find-person.component.scss
  src/work-allocation-2/components/find-person/find-person.component.spec.ts
  src/work-allocation-2/components/find-person/find-person.component.ts
  src/work-allocation-2/components/index.ts
  src/work-allocation-2/components/work-allocation.components.module.ts
  src/work-allocation-2/containers/find-person-container/find-person-container.component.html
  src/work-allocation-2/containers/find-person-container/find-person-container.component.ts
  src/work-allocation-2/containers/index.ts
  src/work-allocation-2/models/dtos/index.ts
  src/work-allocation-2/services/find-person.service.spec.ts
  src/work-allocation-2/services/find-person.service.ts
  src/work-allocation-2/work-allocation-feature.routes.ts
  src/work-allocation-2/work-allocation2.module.ts
  src/work-allocation/components/work-allocation.components.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1126

#1129 Clean up of the testable components
  src/work-allocation-2/containers/find-person-container/find-person-container.component.html
  src/work-allocation-2/containers/find-person-container/find-person-container.component.ts
  src/work-allocation-2/containers/index.ts
  src/work-allocation-2/work-allocation-feature.routes.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1129

#1130 Temporarily add CVE known issues workaround
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1130

#1131 all work changes
  api/workAllocation2/index.ts
  api/workAllocation2/taskService.mock.ts
  src/app/app.routes.ts
  src/style/app.scss
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/containers/all-work-home/all-work-home.component.html
  src/work-allocation-2/containers/all-work-home/all-work-home.component.scss
  src/work-allocation-2/containers/all-work-home/all-work-home.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.html
  src/work-allocation-2/containers/all-work-task/all-work-task.component.scss
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/index.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/containers/task-home/task-home.component.ts
  src/work-allocation-2/work-allocation-feature.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1131

#1136 Feature/EUI-3569 reassign confirm
  api/lib/http/index.spec.ts
  api/lib/http/index.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/proxy.ts
  api/lib/middleware/removeCacheHeaders.ts
  api/workAllocation/index.ts
  api/workAllocation/interfaces/task.ts
  api/workAllocation/interfaces/taskSearchParameter.ts
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/taskService.mock.ts
  src/work-allocation-2/components/find-person/find-person.component.html
  src/work-allocation-2/components/find-person/find-person.component.spec.ts
  src/work-allocation-2/components/find-person/find-person.component.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/models/tasks/task-assignee.model.ts
  src/work-allocation-2/models/tasks/task-permission.model.ts
  src/work-allocation-2/tests/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1136

#1108 Feature/e UI 3842 cookie banner third parties aa
  package.json
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/services/logger/logger.service.spec.ts
  src/app/services/logger/logger.service.ts
  src/app/services/logger/monitoring.service.spec.ts
  src/app/services/logger/monitoring.service.ts
  src/cases/containers/case-home/case-home.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1108

#1144 E2e test fix/enhncement to improve robustness.
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/support/reportLogger.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1144

#1103 tests/Nightly build fixes
  Jenkinsfile_nightly
  api/auth/index.ts
  test/e2e/config/crossbrowser.conf.js
  test/integration/tests/config/config.ts
  test/integration/tests/nodeApp_endpoints.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1103

#1149 CVE test
  README.md
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1149
