Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-07, with the labels that each got.

#1125 EUI-3616 - Mock sorting
  api/workAllocation2/taskService.mock.ts
  src/work-allocation-2/containers/task-list/task-list.component.html
  src/work-allocation-2/containers/task-list/task-list.component.scss
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/containers/task-list/task-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1125

#944 Release/a11y fixes
  package.json
  sonar-project.properties
  src/app/app.module.ts
  src/app/components/accessibility/accessibility.component.html
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/get-help/get-help.component.html
  src/app/components/header/header.component.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/components/not-authorised/not-authorised.component.html
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/service-down/service-down.component.html
  src/app/components/signed-out/signed-out.component.html
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/accept-tc.wrapper/accept-tc-wrapper.component.html
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.spec.ts
  src/cases/containers/case-list/case-list.component.html
  test/accessibility/helpers/customeA11yValidations.js
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/tests/index.js
  test/e2e/features/pageObjects/caseEditPage.js
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/pageObjects/errorPage.js
  test/e2e/features/pageObjects/searchPage.js
  test/e2e/features/pageObjects/workAllocation/taskListTable.js
  test/e2e/features/step_definitions/testCaseType.steps.js
  test/e2e/support/customWaits.js
  test/e2e/support/reportLogger.js
  test/ngIntegration/config/protractor-cucumber.conf.js
  test/ngIntegration/tests/features/ccdFields.feature
  test/ngIntegration/tests/features/ccdToolkit_caseCreate.feature
  test/ngIntegration/tests/features/workAllocation/taskActions.feature
  test/ngIntegration/tests/features/workAllocation/taskListAvailableTasks.feature
  test/ngIntegration/tests/features/workallocation2/myWork_MyTasks.feature
  test/ngIntegration/tests/pageObjects/caselistPage.js
  test/ngIntegration/tests/pageObjects/ccdCaseEditPages.js
  test/ngIntegration/tests/stepDefinitions/caseEditpage.steps.js
  test/ngIntegration/tests/stepDefinitions/caseEventMock.steps.js
  test/ngIntegration/tests/stepDefinitions/caselistMock.steps.js
  test/ngIntegration/tests/stepDefinitions/workallocation/wa.steps.js
  test/ngIntegration/util/cucumberHooks.js
  test/nodeMock/ccd/ccdCaseConfig/CCDCaseField.js
  test/nodeMock/ccd/ccdCaseConfig/caseCreateConfigGenerator.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-944

#1152 WA pact tests updated to resolve data mismatch on provider side tests…
  api/test/pact/pact-tests/logs/oidc-integration.log
  api/test/pact/pact-tests/logs/work-allocation.log
  api/test/pact/pact-tests/settings/provider.mock.ts
  api/test/pact/pact-tests/utils/configOverride.ts
  api/test/pact/pact-tests/utils/matchers.ts
  api/test/pact/pact-tests/utils/moduleUtil.ts
  api/test/pact/pact-tests/wa/assignTask.spec.ts
  api/test/pact/pact-tests/wa/cancelTask.spec.ts
  api/test/pact/pact-tests/wa/claimTask.spec.ts
  api/test/pact/pact-tests/wa/completeTask.spec.ts
  api/test/pact/pact-tests/wa/getTaskById.spec.ts
  api/test/pact/pact-tests/wa/searchForCompletableTasks.spec.ts
  api/test/pact/pact-tests/wa/searchTasks.spec.ts
  api/test/pact/pact-tests/wa/unclaimTask.spec.ts
  api/test/pact/pactUtil.ts
  stryker.node.conf.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1152

#1155 Derived icon changes and reset sorting fix
  api/workAllocation2/constants/mock.data.ts
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/components/derived-icon-field/derived-icon-field.component.html
  src/work-allocation-2/components/derived-icon-field/derived-icon-field.component.spec.ts
  src/work-allocation-2/containers/task-list/task-list.component.html
  src/work-allocation-2/containers/task-list/task-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1155

#1159 Generically name task related models / enums for reusability. Fix tests and wa2->wa1 references
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/components/task-field/task-field.component.spec.ts
  src/work-allocation-2/components/task-field/task-field.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/containers/task-home/task-home.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/containers/task-list/task-list.component.ts
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation-2/enums/field-type.ts
  src/work-allocation-2/enums/index.ts
  src/work-allocation-2/enums/sort-order.ts
  src/work-allocation-2/enums/task-sort.ts
  src/work-allocation-2/models/common/field-config.model.ts
  src/work-allocation-2/models/common/index.ts
  src/work-allocation-2/models/common/sort-field.model.ts
  src/work-allocation-2/models/tasks/index.ts
  src/work-allocation-2/models/tasks/task-service-config.model.ts
  src/work-allocation-2/models/tasks/task-sort-field.model.ts
  src/work-allocation-2/tests/utils.spec.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1159

#1156 all work component with changes
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/taskService.mock.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/app/containers/app-header/app-header.component.spec.ts
  src/app/containers/app-header/app-header.component.ts
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/components/constants/list.constants.ts
  src/work-allocation-2/components/constants/pagination.constants.ts
  src/work-allocation-2/components/constants/sort.constants.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.html
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.scss
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation-2/containers/all-work-home/all-work-home.component.spec.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.html
  src/work-allocation-2/containers/all-work-task/all-work-task.component.scss
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.html
  src/work-allocation-2/containers/task-list/task-list.component.scss
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/containers/task-list/task-list.component.ts
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation-2/models/common/field-config.model.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/services/caseworker-data.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1156

#1162 case name hyperlink
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.scss
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1162

#1165 add exlusion component
  angular.json
  package.json
  src/cases/case-feature.routes.ts
  src/cases/cases.module.ts
  src/cases/components/describe-exclusion/describe-exclusion.component.html
  src/cases/components/describe-exclusion/describe-exclusion.component.scss
  src/cases/components/describe-exclusion/describe-exclusion.component.spec.ts
  src/cases/components/describe-exclusion/describe-exclusion.component.ts
  src/cases/components/index.ts
  src/cases/containers/case-details/case-details.component.html
  src/cases/containers/case-details/case-details.component.spec.ts
  src/cases/containers/case-details/case-details.component.ts
  src/cases/containers/index.ts
  src/cases/containers/role-container/allocate-role-container.component.html
  src/cases/containers/role-container/allocate-role-container.component.spec.ts
  src/cases/containers/role-container/allocate-role-container.component.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/models/common/route-data.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1165

#1091 22.2 + 22.3 Release
  angular.json
  package.json
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-search/case-search.component.html
  src/style/_material.scss
  src/style/app.scss
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/ngIntegration/tests/pageObjects/ccdCaseEditPages.js
  test/ngIntegration/tests/stepDefinitions/caseEventMock.steps.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1091

#1163 Adding in generic allocate-role component with container
  api/user/constants.ts
  api/user/index.spec.ts
  api/user/index.ts
  api/user/interfaces/roleAssignment.ts
  api/user/utils.spec.ts
  api/user/utils.ts
  src/app/app.constants.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
  src/cases/case-feature.routes.ts
  src/cases/components/allocate-role/allocate-role.component.html
  src/cases/components/allocate-role/allocate-role.component.spec.ts
  src/cases/components/allocate-role/allocate-role.component.ts
  src/cases/components/constants/allocation.constants.ts
  src/cases/components/constants/index.ts
  src/cases/components/index.ts
  src/cases/containers/allocate-role-container/allocate-role-container.component.html
  src/cases/containers/allocate-role-container/allocate-role-container.component.spec.ts
  src/cases/containers/allocate-role-container/allocate-role-container.component.ts
  src/cases/containers/index.ts
  src/cases/containers/role-container/allocate-role-container.component.spec.ts
  src/cases/containers/role-container/allocate-role-container.component.ts
  src/cases/enums/allocation-text.ts
  src/cases/enums/allocation-type.ts
  src/cases/enums/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1163

#1174 HOTFIX to downgrade the version of media viewer
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1174

#1175 feature/EUI-4296-role-access-infra
  src/app/app.routes.ts
  src/role-access/constants/exclusion-navigation-visibility-states.ts
  src/role-access/constants/exclusion-page-visibility-states.ts
  src/role-access/constants/index.ts
  src/role-access/containers/exclusion/check-answers/check-answers.component.html
  src/role-access/containers/exclusion/check-answers/check-answers.component.scss
  src/role-access/containers/exclusion/check-answers/check-answers.component.spec.ts
  src/role-access/containers/exclusion/check-answers/check-answers.component.ts
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.html
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.scss
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.spec.ts
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.ts
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.html
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.scss
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.spec.ts
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.ts
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.html
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.scss
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.spec.ts
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.ts
  src/role-access/containers/exclusion/exclusion-home/exclusion-home.component.html
  src/role-access/containers/exclusion/exclusion-home/exclusion-home.component.scss
  src/role-access/containers/exclusion/exclusion-home/exclusion-home.component.spec.ts
  src/role-access/containers/exclusion/exclusion-home/exclusion-home.component.ts
  src/role-access/containers/exclusion/exclusion-navigation/exclusion-navigation.component.html
  src/role-access/containers/exclusion/exclusion-navigation/exclusion-navigation.component.spec.ts
  src/role-access/containers/exclusion/exclusion-navigation/exclusion-navigation.component.ts
  src/role-access/containers/exclusion/find-person/find-person.component.html
  src/role-access/containers/exclusion/find-person/find-person.component.scss
  src/role-access/containers/exclusion/find-person/find-person.component.spec.ts
  src/role-access/containers/exclusion/find-person/find-person.component.ts
  src/role-access/containers/index.ts
  src/role-access/models/exclusion-navigation-event.enum.ts
  src/role-access/models/exclusion-navigation.interface.ts
  src/role-access/models/exclusion-state-data.interface.ts
  src/role-access/models/exclusion-state.enum.ts
  src/role-access/models/exclusion.enum.ts
  src/role-access/models/http-error.interface.ts
  src/role-access/models/index.ts
  src/role-access/models/person-model.ts
  src/role-access/role-access.module.ts
  src/role-access/role-access.routes.ts
  src/role-access/store/actions/exclusion.action.ts
  src/role-access/store/actions/index.ts
  src/role-access/store/effects/exclusion.effects.ts
  src/role-access/store/effects/index.ts
  src/role-access/store/index.ts
  src/role-access/store/reducers/exclusion.reducer.spec.ts
  src/role-access/store/reducers/exclusion.reducer.ts
  src/role-access/store/reducers/index.ts
  src/role-access/store/selectors/exclusion.selectors.ts
  src/role-access/store/selectors/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1175

#1170 Feature/e UI 3575 exclusions
  api/exclusions/exclusionService.ts
  api/exclusions/routes.ts
  api/user/routes.ts
  src/cases/case-feature.routes.ts
  src/cases/components/index.ts
  src/cases/components/role-exclusions/role-exclusion.component.scss
  src/cases/components/role-exclusions/role-exclusions.component.html
  src/cases/components/role-exclusions/role-exclusions.component.spec.ts
  src/cases/components/role-exclusions/role-exclusions.component.ts
  src/cases/containers/index.ts
  src/cases/containers/role-and-access/role-access.component.html
  src/cases/containers/role-and-access/role-access.component.ts
  src/cases/models/role-exclusions/role-exclusion.model.ts
  src/cases/services/index.ts
  src/cases/services/role-exclusions.service.spec.ts
  src/cases/services/role-exclusions.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1170

#1121 feature/EUI-4117-noc-guard
  src/app/app.constants.ts
  src/app/containers/app-header/app-header.component.ts
  src/app/models/TermsAndCondition.ts
  src/app/models/user-details.model.ts
  src/noc/guards/noc-guard.spec.ts
  src/noc/guards/noc-guard.ts
  src/noc/noc.module.ts
  src/noc/noc.routes.ts
  src/work-allocation/guards/senior-tribunal-caseworker-guard.spec.ts
  src/work-allocation/guards/work-allocation-feature-toggle.guard.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1121

#908 corrected typo of exiu-ccd-connector-wrapper
  src/app/containers/exui-ccd-connector-wrapper/exui-ccd-connector.component.spec.ts
  src/app/containers/exui-ccd-connector-wrapper/exui-ccd-connector.component.ts
  src/app/containers/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-908

#1014 Media viewer page refresh amends
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.spec.ts
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.ts
Labels: dependencies, ns:xui, prd:xui, rel:xui-webapp-pr-1014

#1141 Bugfix/e UI 4083 the footer on the page should be anchored to the bottom of the page
  src/index.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1141

#1049 Fixing vanishing info message issue
  src/work-allocation/containers/info-message-container/info-message-container.component.spec.ts
  src/work-allocation/containers/info-message-container/info-message-container.component.ts
  src/work-allocation/tests/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1049

#1122 work allocation, set correct search params for when assignee is set to unassigned
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1122

#1184 feature/EUI-4145-roles
  api/exclusions/exclusionService.ts
  api/server.ts
  api/user/routes.ts
  api/workAllocation2/index.ts
  api/workAllocation2/routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1184

#1171 EUI-4258 Adding complete IAC journey test
  test/e2e/features/app/iaCompleteCreateCaseJourney.feature
  test/e2e/features/pageObjects/common/ccdFields.js
  test/e2e/features/pageObjects/iacCase.js
  test/e2e/features/step_definitions/checkFunctionalities.steps.js
  test/integration/tests/workAllocation.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1171

#1180 Release/EX-UI_mc_release_bucket3
  src/app/app.constants.ts
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.spec.ts
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.ts
  src/app/containers/app-header/app-header.component.ts
  src/app/containers/exui-ccd-connector-wrapper/exui-ccd-connector.component.spec.ts
  src/app/containers/exui-ccd-connector-wrapper/exui-ccd-connector.component.ts
  src/app/containers/index.ts
  src/app/models/TermsAndCondition.ts
  src/app/models/user-details.model.ts
  src/index.html
  src/noc/guards/noc-guard.spec.ts
  src/noc/guards/noc-guard.ts
  src/noc/noc.module.ts
  src/noc/noc.routes.ts
  src/work-allocation/containers/info-message-container/info-message-container.component.spec.ts
  src/work-allocation/containers/info-message-container/info-message-container.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/guards/senior-tribunal-caseworker-guard.spec.ts
  src/work-allocation/guards/work-allocation-feature-toggle.guard.ts
  src/work-allocation/tests/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1180

#1185 Feature/e UI 3939 choose role
  src/role-access/components/allocate-role/allocate-role.component.html
  src/role-access/components/allocate-role/allocate-role.component.spec.ts
  src/role-access/components/allocate-role/allocate-role.component.ts
  src/role-access/components/choose-role/choose-role.component.html
  src/role-access/components/choose-role/choose-role.component.spec.ts
  src/role-access/components/choose-role/choose-role.component.ts
  src/role-access/components/exclusion/index.ts
  src/role-access/components/index.ts
  src/role-access/components/role-exclusions/role-exclusion.component.scss
  src/role-access/components/role-exclusions/role-exclusions.component.html
  src/role-access/components/role-exclusions/role-exclusions.component.spec.ts
  src/role-access/components/role-exclusions/role-exclusions.component.ts
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.html
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.spec.ts
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.ts
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.html
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.spec.ts
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.ts
  src/role-access/containers/role-and-access/role-access.component.ts
  src/role-access/models/enums/allocation-text.ts
  src/role-access/models/index.ts
  src/role-access/models/role.model.ts
  src/role-access/role-access.module.ts
  src/role-access/services/role-exclusions.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1185

#1190 adding CaseId to the state
  src/role-access/containers/exclusion/exclusion-navigation/exclusion-navigation.component.ts
  src/role-access/models/exclusion-state-data.interface.ts
  src/role-access/models/person-model.ts
  src/role-access/store/reducers/exclusion.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1190

#1188 describe exclusion NGRX changes
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.html
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.spec.ts
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.ts
  src/role-access/store/actions/exclusion.action.ts
  src/role-access/store/reducers/exclusion.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1188

#1009 Bug/e UI 3621 collection search filter 2 aa
  src/cases/services/search-filter.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1009

#1193 Fixing task list
  src/role-access/components/allocate-role/allocate-role.component.html
  src/role-access/components/allocate-role/allocate-role.component.spec.ts
  src/role-access/components/allocate-role/allocate-role.component.ts
  src/role-access/components/choose-radio-option/choose-radio-option.component.html
  src/role-access/components/choose-radio-option/choose-radio-option.component.spec.ts
  src/role-access/components/choose-radio-option/choose-radio-option.component.ts
  src/role-access/components/choose-role/choose-role.component.html
  src/role-access/components/choose-role/choose-role.component.spec.ts
  src/role-access/components/choose-role/choose-role.component.ts
  src/role-access/components/index.ts
  src/role-access/constants/allocation.constants.ts
  src/role-access/constants/index.ts
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.html
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.spec.ts
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.ts
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.html
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.spec.ts
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.ts
  src/role-access/models/enums/allocation-text.ts
  src/role-access/models/enums/allocation-type.ts
  src/role-access/models/enums/index.ts
  src/role-access/models/index.ts
  src/role-access/models/radio-option.model.ts
  src/work-allocation-2/components/index.ts
  src/work-allocation-2/components/task-field/task-field.component.html
  src/work-allocation-2/components/task-field/task-field.component.scss
  src/work-allocation-2/components/task-field/task-field.component.spec.ts
  src/work-allocation-2/components/task-field/task-field.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1193

#1191 Feature/EUI-3936 choose exclusion option
  package.json
  src/role-access/components/choose-radio-option/choose-radio-option.component.html
  src/role-access/components/choose-radio-option/choose-radio-option.component.spec.ts
  src/role-access/components/choose-radio-option/choose-radio-option.component.ts
  src/role-access/components/role-exclusions/role-exclusions.component.html
  src/role-access/constants/index.ts
  src/role-access/constants/role-access.constants.ts
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.html
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.spec.ts
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.ts
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.html
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.spec.ts
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.ts
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.html
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.ts
  src/role-access/containers/exclusion/exclusion-home/exclusion-home.component.ts
  src/role-access/containers/exclusion/exclusion-navigation/exclusion-navigation.component.ts
  src/role-access/models/options-model.ts
  src/role-access/store/actions/exclusion.action.ts
  src/role-access/store/reducers/exclusion.reducer.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1191

#1192 Exclusion Search Person
  src/role-access/containers/exclusion/exclusion-home/exclusion-home.component.html
  src/role-access/containers/exclusion/exclusion-home/exclusion-home.component.ts
  src/role-access/containers/exclusion/find-person/find-person.component.html
  src/role-access/containers/exclusion/find-person/find-person.component.spec.ts
  src/role-access/containers/exclusion/find-person/find-person.component.ts
  src/role-access/containers/exclusion/search-person/search-person.component.html
  src/role-access/containers/exclusion/search-person/search-person.component.scss
  src/role-access/containers/exclusion/search-person/search-person.component.spec.ts
  src/role-access/containers/exclusion/search-person/search-person.component.ts
  src/role-access/containers/index.ts
  src/role-access/models/exclusion-state-data.interface.ts
  src/role-access/role-access.module.ts
  src/role-access/store/actions/exclusion.action.ts
  src/role-access/store/reducers/exclusion.reducer.ts
  src/work-allocation-2/components/find-person/find-person.component.html
  src/work-allocation-2/components/find-person/find-person.component.spec.ts
  src/work-allocation-2/components/index.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/find-person.module.ts
  src/work-allocation-2/work-allocation2.module.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1192

#1189 EUI-3777 create prepended tabs on case view v2
  angular.json
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/cases/case-feature.routes.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  src/cases/containers/case-viewer-container/case-viewer-container.component.scss
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/cases/containers/index.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.html
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.scss
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/cases/containers/tasks-container/tasks-container.component.html
  src/cases/containers/tasks-container/tasks-container.component.scss
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1189

#1167 bug-EUI-4261-redirect-uri
  api/user/index.ts
  package.json
  test/integration/tests/nodeApp_endpoints.spec.ts
  test/integration/tests/utils/authUtil.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1167

#1201 Check your answers page
  api/exclusions/exclusionService.ts
  api/exclusions/routes.ts
  api/user/routes.ts
  src/cases/containers/tasks-container/tasks-container.component.html
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/role-access/components/answers/answers.component.html
  src/role-access/components/answers/answers.component.spec.ts
  src/role-access/components/answers/answers.component.ts
  src/role-access/components/index.ts
  src/role-access/containers/exclusion/check-answers/check-answers.component.html
  src/role-access/containers/exclusion/check-answers/check-answers.component.scss
  src/role-access/containers/exclusion/check-answers/check-answers.component.spec.ts
  src/role-access/containers/exclusion/check-answers/check-answers.component.ts
  src/role-access/containers/exclusion/exclusion-home/exclusion-home.component.ts
  src/role-access/models/answer.model.ts
  src/role-access/models/enums/answer-text.ts
  src/role-access/models/enums/exclusion-text.ts
  src/role-access/models/enums/index.ts
  src/role-access/models/exclusion-state-data.interface.ts
  src/role-access/models/index.ts
  src/role-access/models/person-model.ts
  src/role-access/models/role-access-http-error.interface.ts
  src/role-access/role-access.module.ts
  src/role-access/services/role-exclusions.service.ts
  src/role-access/store/actions/exclusion.action.ts
  src/role-access/store/effects/exclusion.effects.ts
  src/role-access/store/reducers/exclusion.reducer.ts
  src/work-allocation-2/containers/info-message-container/info-message-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1201

#1207 Feature/exlucsion integration 2
  api/user/index.ts
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/interfaces/person.ts
  api/workAllocation2/personService.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.html
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.scss
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.spec.ts
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.ts
  src/role-access/containers/add-exclusion/check-answers/check-answers.component.html
  src/role-access/containers/add-exclusion/check-answers/check-answers.component.spec.ts
  src/role-access/containers/add-exclusion/check-answers/check-answers.component.ts
  src/role-access/containers/add-exclusion/choose-exclusion/choose-exclusion.component.html
  src/role-access/containers/add-exclusion/choose-exclusion/choose-exclusion.component.spec.ts
  src/role-access/containers/add-exclusion/choose-exclusion/choose-exclusion.component.ts
  src/role-access/containers/add-exclusion/choose-person-role/choose-person-role.component.html
  src/role-access/containers/add-exclusion/choose-person-role/choose-person-role.component.spec.ts
  src/role-access/containers/add-exclusion/choose-person-role/choose-person-role.component.ts
  src/role-access/containers/add-exclusion/describe-exclusion/describe-exclusion.component.html
  src/role-access/containers/add-exclusion/describe-exclusion/describe-exclusion.component.spec.ts
  src/role-access/containers/add-exclusion/describe-exclusion/describe-exclusion.component.ts
  src/role-access/containers/add-exclusion/exclusion-navigation/exclusion-navigation.component.html
  src/role-access/containers/add-exclusion/exclusion-navigation/exclusion-navigation.component.spec.ts
  src/role-access/containers/add-exclusion/exclusion-navigation/exclusion-navigation.component.ts
  src/role-access/containers/add-exclusion/search-person/search-person.component.html
  src/role-access/containers/add-exclusion/search-person/search-person.component.spec.ts
  src/role-access/containers/add-exclusion/search-person/search-person.component.ts
  src/role-access/containers/exclusion/check-answers/check-answers.component.html
  src/role-access/containers/exclusion/choose-exclusion/choose-exclusion.component.scss
  src/role-access/containers/exclusion/choose-person-role/choose-person-role.component.scss
  src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.scss
  src/role-access/containers/exclusion/search-person/search-person.component.scss
  src/role-access/containers/index.ts
  src/role-access/models/exclusion.enum.ts
  src/role-access/role-access.routes.ts
  src/role-access/store/effects/exclusion.effects.ts
  src/work-allocation-2/components/find-person/find-person.component.html
  src/work-allocation-2/components/find-person/find-person.component.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/models/dtos/index.ts
  src/work-allocation-2/services/find-person.service.spec.ts
  src/work-allocation-2/services/find-person.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1207

#1212 Tech/e UI 4321 relocate find person component
  package.json
  src/role-access/containers/add-exclusion/search-person/search-person.component.html
  src/role-access/containers/add-exclusion/search-person/search-person.component.spec.ts
  src/role-access/containers/add-exclusion/search-person/search-person.component.ts
  src/role-access/role-access.module.ts
  src/work-allocation-2/components/find-person/find-person.component.html
  src/work-allocation-2/components/find-person/find-person.component.scss
  src/work-allocation-2/components/find-person/find-person.component.spec.ts
  src/work-allocation-2/components/find-person/find-person.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/find-person.module.ts
  src/work-allocation-2/services/find-person.service.spec.ts
  src/work-allocation-2/services/find-person.service.ts
  src/work-allocation-2/work-allocation2.module.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1212

#1187 release 22.4
  package.json
  src/cases/services/search-filter.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1187

#1177 EUI-3955: All work > Tasks tab > Assign task
  src/work-allocation-2/containers/all-work-home/all-work-home.component.html
  src/work-allocation-2/containers/all-work-home/all-work-home.component.scss
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/enums/assign-hint-text.ts
  src/work-allocation-2/enums/index.ts
  src/work-allocation-2/enums/info-message.ts
  src/work-allocation-2/work-allocation-feature.routes.ts
  test/e2e/features/pageObjects/workAllocation/taskCheckYourChangesPage.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1177

#1213 EUI-4170: Roles and access > Delete exclusion > "Check your answers" page
  src/role-access/components/answers/answers.component.html
  src/role-access/containers/delete-exclusion/delete-exclusion.component.html
  src/role-access/containers/delete-exclusion/delete-exclusion.component.spec.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.ts
  src/role-access/containers/index.ts
  src/role-access/models/answer.model.ts
  src/role-access/models/enums/answer-text.ts
  src/role-access/models/exclusion-navigation-event.enum.ts
  src/role-access/resolvers/role-exclusions.resolver.spec.ts
  src/role-access/resolvers/role-exclusions.resolver.ts
  src/role-access/role-access.routes.ts
  src/role-access/services/role-exclusions.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1213
