Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-10, with the labels that each got.

#1342 fix for the delete Exclusion
  api/roleAccess/exclusionService.spec.ts
  api/roleAccess/exclusionService.ts
  src/role-access/components/exclusions-table/exclusions-table.component.html
  src/role-access/components/exclusions-table/exclusions-table.component.spec.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.spec.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.ts
  src/role-access/models/role-exclusion.model.ts
  src/role-access/role-access.routes.ts
  src/role-access/services/role-exclusions.mock.service.ts
  test/accessibility/tests/workAllocation/rolesAndAccessWorkFlowPages.test.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1342

#1349 Common library version change
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1349

#1354 EUI-4452-unit-test-coverage
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/components/case-alert/alert.component.ts
  src/cases/containers/case-create/case-create.component.spec.ts
  src/cases/containers/case-create/case-create.component.ts
  src/cases/containers/case-details/case-details.component.spec.ts
  src/cases/containers/case-details/case-details.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1354

#1355 Feature/e UI 4553 exclusions
  api/roleAccess/exclusionService.spec.ts
  api/roleAccess/exclusionService.ts
  api/roleAccess/models/caseRoleRequestPayload.ts
  api/roleAccess/routes.ts
  api/user/interfaces/roleAssignment.ts
  api/user/utils.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/role-access/components/exclusions-table/exclusions-table.component.html
  src/role-access/components/exclusions-table/exclusions-table.component.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.spec.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.ts
  src/role-access/resolvers/role-exclusions.resolver.spec.ts
  src/role-access/resolvers/role-exclusions.resolver.ts
  src/role-access/role-access.routes.ts
  src/role-access/services/role-exclusions.service.spec.ts
  src/role-access/services/role-exclusions.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1355

#1357 Changes to find caseworker
  api/workAllocation2/personService.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1357

#1377 tidy up
  api/hearings/hearing.mock.ts
  api/hearings/index.ts
  src/hearings/pipes/hearings-badge.pipe.spec.ts
  src/hearings/pipes/hearings-badge.pipe.ts
  src/hearings/pipes/hearings.pipes.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1377

#1379 Feature/e UI 4581 4604 my cases legalops
  api/configuration/references.ts
  api/lib/middleware/proxy.ts
  api/lib/proxy.ts
  api/proxy.config.ts
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/exclusionService.spec.ts
  api/roleAccess/exclusionService.ts
  api/roleAccess/models/caseRoleRequestPayload.ts
  api/roleAccess/routes.ts
  api/searchCases/interfaces/ElasticSearchQuery.ts
  api/tslint.json
  api/user/interfaces/roleAssignment.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/caseSearchParameter.ts
  api/workAllocation2/interfaces/roleCaseData.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/app/resolvers/case-roles-resolver.service.spec.ts
  src/app/resolvers/case-roles-resolver.service.ts
  src/app/shared/shared.module.ts
  src/cases/case-feature.routes.ts
  src/cases/components/roles-and-access/roles-and-access.component.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.html
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/role-access/components/case-roles-table/case-roles-table.component.html
  src/role-access/components/case-roles-table/case-roles-table.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.spec.ts
  src/role-access/containers/remove-role/remove-role.component.spec.ts
  src/role-access/containers/remove-role/remove-role.component.ts
  src/role-access/models/case-role.interface.ts
  src/role-access/models/specific-role.model.ts
  src/role-access/role-access.routes.ts
  src/role-access/services/allocate-role.service.ts
  src/role-access/services/role-exclusions.service.ts
  src/role-access/utils/role-access-utils.ts
  src/work-allocation-2/containers/my-cases/my-cases.component.spec.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation-2/services/work-allocation-case.service.ts
  test/integration/tests/workallocation/release2Cases.spec.ts
  test/ngIntegration/tests/features/workallocation2/allWork/allWork_filters.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/Cases_pagination.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/allWorkCases.feature
  test/ngIntegration/tests/features/workallocation2/myCases/myCases.feature
  test/ngIntegration/tests/features/workallocation2/myCases/myCases_negativeCases.feature
  test/ngIntegration/tests/features/workallocation2/myCases/myCases_pagination.feature
  test/ngIntegration/tests/features/workallocation2/workFilter_unhappyPath.feature
  test/ngIntegration/tests/features/workallocation2/workFilters.feature
  test/nodeMock/workAllocation/reqResMapping.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1379

#1389 Eui 4453 display upcoming hearing section ray
  api/hearings/data/mock.data.ts
  api/hearings/hearing.mock.ts
  api/hearings/index.ts
  api/hearings/models/caseHearing.model.ts
  api/hearings/models/hearingStatusMapping.ts
  api/hearings/models/hearingStatusMappings.ts
  api/hearings/models/hearings.enum.ts
  src/app/components/get-help/get-help.component.spec.ts
  src/app/services/role-category-mapping/role-category-mapping.service.stub.ts
  src/app/store/reducers/index.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.stub.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/models/caseHearing.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearings-badge.pipe.spec.ts
  src/hearings/pipes/hearings-badge.pipe.ts
  src/hearings/store/effects/hearings.effects.spec.ts
  src/hearings/store/reducers/hearings.reducer.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1389
