Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-02, with the labels that each got.

#829 Add email and update postal in your rights
  src/app/components/privacy-policy/privacy-policy.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-829

#854 Ta 351 consumer rd professional
  api/test/pact/pact-tests/case-share/getCaseAssignments.spec.ts
  api/test/pact/pact-tests/case-share/postCaseAssignments.spec.ts
  api/test/pact/pact-tests/idam/getUserDetails.spec.ts
  api/test/pact/pact-tests/idam/getUserDetailsByEmail.spec.ts
  api/test/pact/pact-tests/idam/idam.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/getOrganisations.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/getUsers.spec.ts
  api/test/pact/pactFixtures.ts
  api/test/pact/publish/publish.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-854

#841 made changes as instructed to Google Analytics tagging
  api/application.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/environments/environment.ts
  src/index.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-841

#857 EUI 2992 noc integration ishita
  src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.spec.ts
  src/noc/containers/noc-check-your-answers/noc-check-your-answers.component.html
  src/noc/containers/noc-home/noc-home.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-857

#821 Fix caselist loading when not running on ES
  api/amendedJurisdictions/index.spec.ts
  api/amendedJurisdictions/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-821

#877 EUI 3344 noc column changes
  src/noc/containers/noc-check-your-answers/noc-check-your-answers.component.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-877

#878 Feature/e UI 3242 wa integration ck
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-878

#880 EUI-3381: Alerts look weird
  src/cases/components/case-alert/alert.component.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-880

#884 EUI-3387: Menu not showing on reload for Work Allocation
  src/app/containers/app/app.component.ts
  src/cases/containers/case-home/case-home.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-884

#885 Integration changes
  api/workAllocation/index.spec.ts
  api/workAllocation/index.ts
  api/workAllocation/interfaces/task.ts
  api/workAllocation/taskTestData.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  src/work-allocation/components/constants/config.constants.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/models/dtos/index.spec.ts
  src/work-allocation/models/dtos/index.ts
  src/work-allocation/models/tasks/task-field-config.model.ts
  src/work-allocation/services/caseworker-data.service.spec.ts
  src/work-allocation/services/caseworker-data.service.ts
  src/work-allocation/services/work-allocation-task.service.spec.ts
  src/work-allocation/services/work-allocation-task.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-885

#819 Changes for testing of conditional show performance
  .gitignore
  api/searchCases/index.ts
  package.json
  src/cases/components/case-alert/alert.component.scss
  src/cases/containers/case-create-submit/case-create-submit.component.spec.ts
  test/e2e/features/app/searchCase.feature
  test/e2e/features/pageObjects/Divorcecase.js
  test/ngIntegration/mockData/ccdCaseMock.js
  test/nodeMock/app.js
  test/nodeMock/ccd/ccdApi.js
  test/nodeMock/ccd/ccdCaseConfig/CCDCaseField.js
  test/nodeMock/ccd/ccdCaseConfig/caseCreateConfigGenerator.js
  test/nodeMock/ccd/ccdCaseConfig/caseDetailsConfigGenerator.js
  test/nodeMock/ccd/ccdCaseConfig/workBasketInputGenerator.js
  test/nodeMock/ccd/reqResMapping.js
  test/nodeMock/reqResMapping.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-819

#888 Feature/conditional show perf prerelease label fix
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-888

#894 EUI 3369 content change unshare case failed
  src/cases/containers/case-share-complete/case-share-complete.component.html
  src/cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/cases/containers/case-share-complete/case-share-complete.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-894

#900 Feature/e UI 3232 wa integration/revert and fix tabs
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-900

#892 EUI-3403: Optional top-level documents
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-892

#883 Ta 410 fix pact publish
  Jenkinsfile_CNP
  README.md
  api/.env.defaults
  api/configuration/references.ts
  api/test/pact/cer/ca-bundle.crt
  api/test/pact/pact-tests/case-share/getCaseAssignments.spec.ts
  api/test/pact/pact-tests/case-share/postCaseAssignments.spec.ts
  api/test/pact/pact-tests/idam/getUserDetails.spec.ts
  api/test/pact/pact-tests/idam/getUserDetailsByEmail.spec.ts
  api/test/pact/pact-tests/idam/oidc.spec.ts
  api/test/pact/pact-tests/logs/oidc-integration.log
  api/test/pact/pact-tests/logs/work-allocation.log
  api/test/pact/pact-tests/rdProfessionalApi/getOrganisations.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/getUsers.spec.ts
  api/test/pact/pact-tests/settings/provider.mock.ts
  api/test/pact/publish/publish.ts
  config/custom-environment-variables.json
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-883

#919 Editing all comments as per 903
  api/workAllocation/index.spec.ts
  api/workAllocation/index.ts
  api/workAllocation/locationService.ts
  api/workAllocation/taskTestData.spec.ts
  api/workAllocation/util.ts
  package.json
  src/app/guards/acceptTerms.guard.ts
  src/app/services/auth/auth.service.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  test/integration/tests/utils/request.ts
  test/ngIntegration/config/protractor-cucumber.conf.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-919

#924 400 error Handling
  src/work-allocation/utils/work-allocation-utils.spec.ts
  src/work-allocation/utils/work-allocation-utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-924
