Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-05, with the labels that each got.

#1011 Feature/e UI 3773 add em hrs api proxy
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/health/index.ts
  api/proxy.config.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  proxy.config.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1011

#1028 disabling the health check status for HRS
  api/health/index.ts
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1028

#1031 Update package.json with additional resolutions
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  package.json
  test/e2e/support/reports.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1031

#1036 yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1036

#1037 cve changes 2
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1037

#1033 added changes to reassign component
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/containers/task-home/task-home.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1033

#873 EUI-2802 share case remove user
  api/caseshare/dtos/case-user-dto.ts
  api/caseshare/dtos/user-dto.ts
  api/caseshare/index.ts
  api/caseshare/models/case-assignee-mapping.model.ts
  api/caseshare/models/case-share.model.ts
  api/caseshare/models/ccd-raw-case-user.model.ts
  api/caseshare/models/ccd-raw-user.model.ts
  api/caseshare/models/data-base.model.ts
  api/caseshare/models/organisation.model.ts
  api/caseshare/models/prd-raw-user.model.ts
  api/caseshare/models/unassigned-case.model.ts
  api/caseshare/models/user-details.model.ts
  api/caseshare/real-api.ts
  api/caseshare/routes.ts
  api/caseshare/stub-api.ts
  api/common/crudService.ts
  charts/xui-webapp/values.preview.template.yaml
  src/app/app.constants.ts
  src/cases/containers/case-share-complete/case-share-complete.component.html
  src/cases/containers/case-share-complete/case-share-complete.component.scss
  src/cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/cases/containers/case-share-complete/case-share-complete.component.ts
  src/cases/containers/case-share/case-share.component.ts
  test/e2e/features/pageObjects/caseEditPage.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-873

#1046 Feature/e UI 3792 implement manage link logic
  api/workAllocation2/caseWorkerService.ts
  api/workAllocation2/constants/actions.ts
  api/workAllocation2/constants/locations.ts
  api/workAllocation2/index.spec.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/task.ts
  api/workAllocation2/interfaces/taskSearchParameter.ts
  api/workAllocation2/locationController.spec.ts
  api/workAllocation2/locationController.ts
  api/workAllocation2/locationService.spec.ts
  api/workAllocation2/locationService.ts
  api/workAllocation2/routes.spec.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/taskService.spec.ts
  api/workAllocation2/taskService.ts
  api/workAllocation2/taskTestData.spec.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1046

#1061 Feature/activity tracker ud
  api/configuration/uiConfigRouter.ts
  api/user/index.spec.ts
  api/user/index.ts
  package.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/models/environmentConfig.model.ts
  test/e2e/features/pageObjects/caseEditPage.js
  test/integration/tests/nodeApp_endpoints.spec.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1061

#1059 Feature/EUI-3619 tasks and permission
  api/workAllocation2/caseWorkerService.ts
  api/workAllocation2/constants/actions.ts
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/index.spec.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/task.ts
  api/workAllocation2/interfaces/taskSearchParameter.ts
  api/workAllocation2/locationController.spec.ts
  api/workAllocation2/routes.spec.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/taskService.mock.ts
  api/workAllocation2/taskService.spec.ts
  api/workAllocation2/taskService.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.html
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.html
  src/work-allocation-2/containers/task-list/task-list.component.ts
  src/work-allocation-2/resolvers/task.resolver.spec.ts
  src/work-allocation-2/resolvers/task.resolver.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1059

#1054 feature/EUI-3916
  api/caseshare/real-api.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1054

#1039 Unassign screen WorkAllocation 2
  api/application.ts
  api/workAllocation2/taskService.mock.ts
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/components/task-field/task-field.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.html
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.spec.ts
  tslint.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1039

#1060 Feature/e UI 3805 task assignment confirm phillip whitaker
  package.json
  src/work-allocation-2/containers/index.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/work-allocation-feature.routes.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1060

#969 Default organisation selection
  api/organisations/index.ts
  api/routes.ts
  package.json
  src/cases/cases.module.ts
  src/cases/containers/case-list/case-list.component.ts
  src/cases/store/selectors/share-case.selectors.spec.ts
  src/organisation/models/index.ts
  src/organisation/models/organisation.interface.ts
  src/organisation/organisation.module.ts
  src/organisation/services/index.ts
  src/organisation/services/organisation.service.ts
  src/organisation/store/actions/index.ts
  src/organisation/store/actions/organisation.actions.spec.ts
  src/organisation/store/actions/organisation.actions.ts
  src/organisation/store/effects/index.ts
  src/organisation/store/effects/organisation.effects.spec.ts
  src/organisation/store/effects/organisation.effects.ts
  src/organisation/store/index.ts
  src/organisation/store/reducers/index.ts
  src/organisation/store/reducers/organisation.reducer.spec.ts
  src/organisation/store/reducers/organisation.reducer.ts
  src/organisation/store/selectors/index.ts
  src/organisation/store/selectors/organisation.selectors.spec.ts
  src/organisation/store/selectors/organisation.selectors.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-969

#1022 Feature/e UI 2029 wcag status messages phillip whitaker
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/case-search/case-search.component.ts
  test/e2e/features/pageObjects/caseEditPage.js
  test/e2e/features/step_definitions/testCaseType.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1022

#1066 Test fix: Increase wait time for page with retry
  test/e2e/features/pageObjects/searchPage.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1066

#1064 idam id different for oidc/oAuth2
  src/work-allocation/components/task-assignment/task-assignment.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1064

#1001 Update content on cookie policy page
  src/app/components/cookie-policy/cookie-policy-component.spec.ts
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/cookie-policy/cookie-policy.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1001

#1069 Reversion fix for Share Case checkbox not showing
  src/cases/containers/case-list/case-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1069

#1076 Adding datetime libraries to dev dependencies
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1076

#1062 Bugfix/e UI 2925 activity tracker proxy 3 ud
  api/activityTracker/index.ts
  api/auth/index.ts
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/lib/middleware/proxy.ts
  api/lib/models/index.ts
  api/proxy.config.ts
  api/user/index.spec.ts
  api/user/index.ts
  api/workAllocation/routes.spec.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  proxy.config.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/cases/case-feature.routes.ts
  src/cases/cases.module.ts
  src/cases/resolvers/activity.resolver.spec.ts
  src/cases/resolvers/activity.resolver.ts
  src/models/environmentConfig.model.ts
  test/integration/tests/nodeApp_endpoints.spec.ts
  test/ngIntegration/tests/stepDefinitions/caseEditpage.steps.js
  test/ngIntegration/tests/stepDefinitions/caselistPage.steps.js
  test/ngIntegration/tests/stepDefinitions/searchCase.steps.js
  test/nodeMock/ccd/ccdApi.js
  test/nodeMock/ccd/reqResMapping.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1062

#1079 fix CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1079

#1070 feature/wa-release1-pagination-mock-apis
  api/common/httpMock.ts
  api/common/interceptorsMock.ts
  api/common/mockService.ts
  api/workAllocation/caseWorkerService.ts
  api/workAllocation/constants/mock.data.ts
  api/workAllocation/index.spec.ts
  api/workAllocation/index.ts
  api/workAllocation/interfaces/task.ts
  api/workAllocation/interfaces/taskSearchParameter.ts
  api/workAllocation/routes.ts
  api/workAllocation/taskService.mock.ts
  api/workAllocation/taskService.spec.ts
  api/workAllocation/taskService.ts
  api/workAllocation/util.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/models/dtos/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1070

#1072 EUI-3564/Manage link logic fix
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1072

#1081 Media Viewer 2.7.0 package amends
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1081

#1077 Feature/e UI 4013 angular pagination 1 phillip whitaker
  package.json
  src/work-allocation/containers/available-tasks/available-tasks.component.html
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.html
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.html
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1077

#1086 EUI-4097 integrate with pagination api
  api/workAllocation/index.spec.ts
  api/workAllocation/index.ts
  api/workAllocation/util.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1086

#1092 added new summary
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1092

#1084 Revert "Media Viewer 2.7.0 package amends"
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1084
