Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-03, with the labels that each got.

#920 Feature/e UI 3456 route credential
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  api/application.ts
  api/auth/index.ts
  api/configuration/references.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  package.json
  test/integration/tests/prdApi.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-920

#911 EUI 3384 hyphens in case number
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/components/case-alert/alert.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-911

#913 Feature/e UI 3382 assign changes
  api/workAllocation/interfaces/task.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  src/work-allocation/components/task-assignment/task-assignment.component.html
  src/work-allocation/components/task-assignment/task-assignment.component.spec.ts
  src/work-allocation/components/task-assignment/task-assignment.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-913

#916 Feature/e UI 3242 wa integration location filter testing
  src/work-allocation/components/available-tasks-filter/available-tasks-filter.component.html
  src/work-allocation/components/available-tasks-filter/available-tasks-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-916

#930 Feature/e UI 3428 assign and go to case
  src/work-allocation/components/case-reference-field/case-reference-field.component.html
  src/work-allocation/components/case-reference-field/case-reference-field.component.spec.ts
  src/work-allocation/components/case-reference-field/case-reference-field.component.ts
  src/work-allocation/components/constants/config.constants.ts
  src/work-allocation/components/task-field/task-field.component.html
  src/work-allocation/components/task-field/task-field.component.spec.ts
  src/work-allocation/components/work-allocation.components.module.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.ts
  src/work-allocation/enums/task-field-type.ts
  src/work-allocation/models/tasks/task.model.ts
  src/work-allocation/tests/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-930

#937 Service Message Banner functionality
  package.json
  src/app/app.constants.ts
  src/app/containers/app-header/app-header.component.html
  src/app/containers/app-header/app-header.component.ts
  src/app/services/auth/auth.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-937

#934 Feature/e UI 3437 task list styling
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/task-list/task-list.component.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-934

#927 Feature/e UI 3223 integrate spinner aa
  package.json
  src/cases/cases.module.ts
  src/cases/containers/case-home/case-home.component.html
  src/cases/containers/case-home/case-home.component.ts
  test/e2e/features/app/workAllocation.feature
  test/e2e/features/pageObjects/CaseListPage.js
  test/e2e/features/step_definitions/caseList.steps.js
  test/e2e/support/hooks.js
  test/nodeMock/reqResMapping.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-927

#644 Feature/eui 2010 skip link
  sonar-project.properties
  src/app/app.module.ts
  src/app/components/accessibility/accessibility.component.html
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/get-help/get-help.component.html
  src/app/components/header/header.component.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/service-down/service-down.component.html
  src/app/components/signed-out/signed-out.component.html
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/accept-tc.wrapper/accept-tc-wrapper.component.html
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.spec.ts
  test/accessibility/helpers/customeA11yValidations.js
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/tests/index.js
  test/nodeMock/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-644

#649 Fix aria on filter button
  src/cases/containers/case-list/case-list.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-649

#940 hmcts/rpx-xui-node-lib@2.25.1
  package.json
  test/e2e/features/pageObjects/searchPage.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-940

#948 Bugfix/e UI 2925 activity tracker logging
  api/activityTracker/index.ts
  api/lib/middleware/proxy.ts
  api/proxy.config.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-948

#954 yarn.lock changes
  package.json
  test/e2e/features/pageObjects/searchPage.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-954

#953 Bug fix for Issue with caseworkers failing when logged in as case officer
  api/workAllocation/index.ts
  api/workAllocation/util.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-953

#955 EUI-3594: Hotfix for error message display
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-955

#968 Fix for goto case link
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/enums/task-action-ids.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-968

#970 Tests/updates for env and code changes
  test/e2e/features/pageObjects/caseEditPage.js
  test/integration/tests/utils/authUtil.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-970

#967 Bug/e UI 3611 caseworkers
  api/workAllocation/index.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/resolvers/task.resolver.spec.ts
  src/work-allocation/resolvers/task.resolver.ts
  src/work-allocation/services/caseworker-data.service.ts
  src/work-allocation/utils/work-allocation-utils.ts
  src/work-allocation/work-allocation-feature.routes.ts
  src/work-allocation/work-allocation.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-967

#960 code changes for zap security scan
  api/application.ts
  audit.json
  package.json
  src/app/app.module.ts
  src/web.config
  test/accessibility/helpers/pa11yUtil.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-960

#958 EUI-3396-3465
  api/auth/interfaces/UserInfo.ts
  api/configuration/references.ts
  api/searchCases/index.spec.ts
  api/searchCases/index.ts
  api/searchCases/interfaces/ElasticSearchQuery.ts
  config/default.json
  src/cases/resolvers/create-case-event-trigger.resolver.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-958
