Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-04, with the labels that each got.

#905 EUI-3452: Check your answers page show/hide issue
  package.json
  test/e2e/features/pageObjects/caseEditPage.js
  test/e2e/support/hooks.js
  test/ngIntegration/mockData/ccdCaseMock.js
  test/ngIntegration/tests/pageObjects/ccdCaseEditPages.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-905

#972 EUI-3587: Fix "Print URL" pipe for rewriting remote Print Service URLs
  package.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-972

#984 EUI-3674-mandatory-organisation
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-984

#989 Feature/e UI 3565 judicial user header
  package.json
  src/app/app.routes.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/components/index.ts
  src/app/components/routing/application-routing.component.html
  src/app/components/routing/application-routing.component.spec.ts
  src/app/components/routing/application-routing.component.ts
  src/app/containers/app-header/app-header.component.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/models/nav-item.model.ts
  src/work-allocation/work-allocation-feature.routes.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-989

#985 EUI-3708: Case submission regression
  package.json
  test/e2e/features/pageObjects/caseEditPage.js
  test/e2e/support/hooks.js
  test/ngIntegration/mockData/ccdCaseMock.js
  test/ngIntegration/tests/pageObjects/ccdCaseEditPages.js
  test/nodeMock/app.js
  test/nodeMock/ccd/ccdCaseConfig/caseDetailsConfigGenerator.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-985

#995 EUI-3797: Missing payments tab
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-995

#981 Unassign fix
  api/workAllocation/constants/locations.ts
  api/workAllocation/index.ts
  api/workAllocation/routes.ts
  api/workAllocation/util.ts
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/cases/containers/case-create-submit/case-create-submit.component.spec.ts
  src/work-allocation/components/constants/derived-icon.constants.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/guards/senior-tribunal-caseworker-guard.spec.ts
  src/work-allocation/guards/senior-tribunal-caseworker-guard.ts
  src/work-allocation/guards/tribunal-caseworker-guard.spec.ts
  src/work-allocation/guards/tribunal-caseworker-guard.ts
  src/work-allocation/services/work-allocation-task.service.ts
  src/work-allocation/work-allocation-feature.routes.ts
  src/work-allocation/work-allocation.module.ts
  test/accessibility/helpers/pa11yUtil.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/workAllocation/taskActionPage.js
  test/e2e/features/pageObjects/workAllocation/taskAssignmentPage.js
  test/e2e/features/pageObjects/workAllocation/taskListPage.js
  test/e2e/features/pageObjects/workAllocation/taskManagerPage.js
  test/e2e/features/pageObjects/workAllocation/taskMessageBanner.js
  test/e2e/features/step_definitions/navigationHeader.steps.js
  test/e2e/features/step_definitions/workallocation.steps.js
  test/integration/tests/mocha.json
  test/integration/tests/utils/authUtil.ts
  test/integration/tests/utils/request.ts
  test/integration/tests/workAllocation.spec.ts
  test/ngIntegration/tests/features/workAllocation/taskActions.feature
  test/ngIntegration/tests/features/workAllocation/taskListAvailableTasks.feature
  test/ngIntegration/tests/pageObjects/caselistPage.js
  test/ngIntegration/tests/stepDefinitions/wa.steps.js
  test/ngIntegration/util/browserUtil.js
  test/nodeMock/app.js
  test/nodeMock/ccd/ccdCaseConfig/caseCreateConfigGenerator.js
  test/nodeMock/nodeApp/mockData.js
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-981

#999 Security check issue: jose
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-999

#986 Build cleanup
  .dockerignore
  Jenkinsfile_CNP
  README.md
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-986

#1003 Disabling WA test because backend issues returning random 504
  test/integration/tests/mocha.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1003

#1005 MC disable auto scaling
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1005

#1006 Bug/e UI 3774 service singleton
  package.json
  sonar-project.properties
  src/app/app.module.ts
  src/app/shared/services/mc-launch-darkly-service.ts
  src/app/shared/services/rootInjectorGuard.ts
  src/app/shared/shared.module.ts
  src/noc/noc.module.ts
  src/work-allocation/components/work-allocation.components.module.ts
  src/work-allocation/work-allocation.module.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1006

#998 PR for - Error when user returns to previous page and correctly popul…
  package.json
  test/ngIntegration/tests/stepDefinitions/caseEditpage.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-998

#1013 Hot fix/wa fixes
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1013

#1012 EUI-3796 WA pact tests added
  Jenkinsfile_CNP
  api/test/pact/pact-tests/wa/assignTask.spec.ts
  api/test/pact/pact-tests/wa/cancelTask.spec.ts
  api/test/pact/pact-tests/wa/claimTask.spec.ts
  api/test/pact/pact-tests/wa/completeTask.spec.ts
  api/test/pact/pact-tests/wa/getTaskById.spec.ts
  api/test/pact/pact-tests/wa/searchForCompletableTasks.spec.ts
  api/test/pact/pact-tests/wa/searchTasks.spec.ts
  api/test/pact/pact-tests/wa/unclaimTask.spec.ts
  api/test/pact/pactUtil.ts
  api/test/pact/publish/publish.ts
  api/test/pacts/xui_get_work_allocation_task-workallocation_api.json
  api/test/pacts/xui_work-allocation_caseworker_get_by_location_and_service-workallocation_api_caseworker.json
  api/test/pacts/xui_work-allocation_caseworker_get_by_service-workallocation_api_caseworker.json
  api/test/pacts/xui_work_allocation_caseworker_get_by_id-workallocation_api_caseworker.json
  api/test/pacts/xui_work_allocation_caseworker_get_by_location-workallocation_api_caseworker.json
  api/test/pacts/xui_work_allocation_caseworker_post_search-workallocation_api_caseworker.json
  api/test/pacts/xui_work_allocation_location_get_all-workallocation_api_location.json
  api/test/pacts/xui_work_allocation_location_get_by_id-workallocation_api_location.json
  api/test/pacts/xui_work_allocation_post_task-workallocation_api_post.json
  api/test/pacts/xui_work_allocation_task_assign-workallocation_api_assign.json
  api/test/pacts/xui_work_allocation_task_cancel-workallocation_api_cancel.json
  api/test/pacts/xui_work_allocation_task_claim-workallocation_api_claim.json
  api/test/pacts/xui_work_allocation_task_complete-workallocation_api_complete.json
  api/test/pacts/xui_work_allocation_task_unclaim-workallocation_api_unclaim.json
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1012

#1015 adding spinner for WA
  src/work-allocation/containers/available-tasks/available-tasks.component.html
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.html
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.html
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1015

#1016 Urgent fix to show user location on Task Manager
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.html
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1016

#1021 WA hotfixes New location and tole changes
  api/workAllocation/constants/locations.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
  src/work-allocation/guards/tribunal-caseworker-guard.ts
  test/e2e/config/conf.js
  test/e2e/features/app/TCSearchCaseandCaseList.feature
  test/e2e/features/app/searchCase.feature
  test/e2e/features/app/workAllocation.feature
  test/integration/tests/workAllocation.spec.ts
  test/ngIntegration/tests/features/navigationHeader.feature
  test/nodeMock/workAllocation/mockData.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1021

#1025 logged in User might have IDAM roles but not Role Management.
  src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1025
