Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-08, with the labels that each got.

#1219 Add tests to the add exclusion check answers component
  src/role-access/containers/add-exclusion/check-answers/check-answers.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1219

#1215 EUI-4260 text change done
  src/app/containers/app/app.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1215

#1113 EUI 4002 screen width
  src/app/containers/app/app.component.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1113

#1209 EUI-4305 media viewer script
  test/e2e/config/conf.js
  test/e2e/features/app/mediaViewer.feature
  test/e2e/features/pageObjects/hearingRecordingsCase.js
  test/e2e/features/step_definitions/caseManager.steps.js
  test/e2e/features/step_definitions/hearingRecordingsCase.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/support.steps.js
  test/e2e/utils/ArrayUtil.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1209

#1221 feature/EUI-3615-allocate-role-page-flow
  api/exclusions/exclusionService.ts
  src/role-access/components/choose-radio-option/choose-radio-option.component.ts
  src/role-access/constants/allocate-role-navigation-visibility-states.ts
  src/role-access/constants/allocate-role-page-visibility-states.ts
  src/role-access/constants/role-access.constants.ts
  src/role-access/containers/add-exclusion/add-exclusion-check-answers/add-exclusion-check-answers.component.html
  src/role-access/containers/add-exclusion/add-exclusion-check-answers/add-exclusion-check-answers.component.spec.ts
  src/role-access/containers/add-exclusion/add-exclusion-check-answers/add-exclusion-check-answers.component.ts
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.html
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.ts
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.html
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.spec.ts
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.ts
  src/role-access/containers/add-exclusion/index.ts
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.html
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.html
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/allocate-role/allocate-role-navigation/allocate-role-navigation.component.html
  src/role-access/containers/allocate-role/allocate-role-navigation/allocate-role-navigation.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-navigation/allocate-role-navigation.component.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.html
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts
  src/role-access/containers/allocate-role/choose-allocate-to/choose-allocate-to.component.html
  src/role-access/containers/allocate-role/choose-allocate-to/choose-allocate-to.component.spec.ts
  src/role-access/containers/allocate-role/choose-allocate-to/choose-allocate-to.component.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.html
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.html
  src/role-access/containers/allocate-role/choose-role/choose-role.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
  src/role-access/containers/allocate-role/index.ts
  src/role-access/containers/index.ts
  src/role-access/models/allocate-role-navigation-event.enum.ts
  src/role-access/models/allocate-role-navigation.interface.ts
  src/role-access/models/allocate-role-state-data.interface.ts
  src/role-access/models/allocate-role-state.enum.ts
  src/role-access/models/allocate-role.enum.ts
  src/role-access/models/enums/allocation-text.ts
  src/role-access/models/exclusion-state-data.interface.ts
  src/role-access/models/index.ts
  src/role-access/role-access.routes.ts
  src/role-access/store/actions/allocate-role.action.ts
  src/role-access/store/actions/index.ts
  src/role-access/store/reducers/allocate-role.reducer.ts
  src/role-access/store/reducers/index.ts
  src/role-access/store/selectors/allocate-role.selectors.ts
  src/role-access/store/selectors/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1221

#1217 upgrade nodejs chart to 2.3.7
  charts/xui-webapp/Chart.yaml
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.scss
  test/e2e/config/conf.js
  test/e2e/features/app/mediaViewer.feature
  test/e2e/features/pageObjects/hearingRecordingsCase.js
  test/e2e/features/step_definitions/caseManager.steps.js
  test/e2e/features/step_definitions/hearingRecordingsCase.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/support.steps.js
  test/e2e/utils/ArrayUtil.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1217

#1218 Feature/e UI 4171 delete exclusion functionality
  api/exclusions/exclusionService.spec.ts
  api/exclusions/exclusionService.ts
  api/exclusions/routes.ts
  api/routes.ts
  api/user/routes.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.html
  src/role-access/containers/delete-exclusion/delete-exclusion.component.spec.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.ts
  src/role-access/models/enums/exclusion-text.ts
  src/role-access/models/enums/index.ts
  src/role-access/models/enums/info-message-type.ts
  src/role-access/services/role-exclusions.service.spec.ts
  src/role-access/services/role-exclusions.service.ts
  src/role-access/store/effects/exclusion.effects.ts
  src/role-access/utils/index.ts
  src/role-access/utils/role-access-utils.spec.ts
  src/role-access/utils/role-access-utils.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1218

#1117 test MV video support on v2.7.6
  package.json
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.html
  test/e2e/features/app/iaCompleteCreateCaseJourney.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1117

#1199 changes to cancel task success description
  src/work-allocation-2/containers/all-work-home/all-work-home.component.html
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/enums/info-message.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1199

#1231 Create PR for MV upgrade hotfix
  README.md
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1231

#1223 Feature/e UI 3818 duration access
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.html
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.scss
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
  src/role-access/models/allocate-role-state-data.interface.ts
  src/role-access/models/allocate-role.enum.ts
  src/role-access/role-access.module.ts
  src/role-access/store/actions/allocate-role.action.ts
  src/role-access/store/reducers/allocate-role.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1223

#1226 Feature/e UI 3814 allocate find person display
  package.json
  src/role-access/constants/role-access.constants.ts
  src/role-access/containers/add-exclusion/add-exclusion-check-answers/add-exclusion-check-answers.component.spec.ts
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.html
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.spec.ts
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.ts
  src/role-access/containers/add-exclusion/choose-person-role/choose-person-role.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.html
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
  src/role-access/models/allocate-role-state-data.interface.ts
  src/role-access/models/allocate-role.enum.ts
  src/role-access/models/exclusion-state-data.interface.ts
  src/role-access/models/exclusion.enum.ts
  src/role-access/models/index.ts
  src/role-access/models/person-model.ts
  src/role-access/store/actions/allocate-role.action.ts
  src/role-access/store/actions/exclusion.action.ts
  src/role-access/store/index.ts
  src/role-access/store/reducers/allocate-role.reducer.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/models/dtos/index.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1226

#917 Feature/e UI 3425 document secure mode phillip whitaker
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/health/index.ts
  api/proxy.config.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  proxy.config.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/cases/containers/case-create-submit/case-create-submit.component.spec.ts
  test/e2e/features/pageObjects/CaseListPage.js
  test/e2e/features/step_definitions/caseList.steps.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-917

#1240 fix for invalid dates
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1240

#1208 4.3.0-rc.1
  api/application.ts
  api/configuration/references.ts
  api/health/index.ts
  api/proxy.config.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.aat.template.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  proxy.config.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1208

#1241 Add task list filter apply work
  api/workAllocation2/constants/locations.ts
  api/workAllocation2/taskService.mock.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1241

#1244 allocate link directive
  api/user/constants.ts
  api/user/interfaces/user-type.ts
  api/workAllocation2/constants/roles.mock.data.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/caseRole.ts
  api/workAllocation2/roleService.spec.ts
  api/workAllocation2/roleService.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/util.ts
  src/cases/case-feature.routes.ts
  src/cases/cases.module.ts
  src/cases/components/roles-and-access/roles-and-access.component.html
  src/cases/components/roles-and-access/roles-and-access.component.spec.ts
  src/cases/components/roles-and-access/roles-and-access.component.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.html
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/cases/directives/index.ts
  src/cases/directives/show-allocate-link.directive.spec.ts
  src/cases/directives/show-allocate-link.directive.ts
  src/cases/resolvers/case-allocate-role-link-resolver.service.spec.ts
  src/cases/resolvers/case-allocate-role-link-resolver.service.ts
  src/cases/resolvers/case-roles-resolver.service.spec.ts
  src/role-access/components/case-roles-table/case-roles-table.component.html
  src/role-access/components/case-roles-table/case-roles-table.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1244

#1211 remove the busines logic from ccd-config
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1211

#1253 Feature/e UI 4070 find person
  api/workAllocation2/constants/mock.data.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1253

#1256 fix sonar
  sonar-project.properties
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1256

#1260 case allocator role changes
  api/user/constants.ts
  api/user/index.spec.ts
  api/user/index.ts
  api/user/interfaces/roleAssignment.ts
  api/user/utils.spec.ts
  api/user/utils.ts
  api/workAllocation2/index.ts
  api/workAllocation2/roleService.spec.ts
  api/workAllocation2/roleService.ts
  api/workAllocation2/util.ts
  src/app/containers/app-header/app-header.component.spec.ts
  src/app/models/user-details.model.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/cases/case-feature.routes.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/noc/guards/noc-guard.spec.ts
  src/role-access/components/case-roles-table/case-roles-table.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1260

#1263 test enhancement with retry logic for spinner
  test/e2e/features/pageObjects/CaseListPage.js
  test/e2e/features/pageObjects/searchPage.js
  test/e2e/features/pageObjects/workAllocation/taskManagerPage.js
  test/e2e/features/step_definitions/searchCase.steps.js
  test/integration/tests/utils/request.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1263

#1261 Update task-list-filter.component.ts
  package.json
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.spec.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1261

#1269 remove selected locations
  src/work-allocation-2/components/my-cases-filter/my-cases-filter.component.html
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.html
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1269

#1270 Merge master feature/release2 wa2
  api/user/index.ts
  api/workAllocation2/caseWorkerService.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/work-allocation-2/components/task-field/task-field.component.ts
  src/work-allocation-2/containers/all-work-home/all-work-home.component.scss
  src/work-allocation-2/containers/all-work-task/all-work-task.component.scss
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/enums/index.ts
  src/work-allocation-2/enums/task-field-type.ts
  src/work-allocation-2/enums/task-sort.ts
  src/work-allocation-2/models/tasks/task-field-config.model.ts
  src/work-allocation-2/models/tasks/task-sort-field.model.ts
  src/work-allocation-2/pipes/caseworker-display-name.pipe.spec.ts
  src/work-allocation-2/pipes/days-from-today.pipe.spec.ts
  src/work-allocation-2/pipes/integer.pipe.spec.ts
  src/work-allocation-2/pipes/two-dp.pipe.spec.ts
  src/work-allocation-2/pipes/yes-no.pipe.spec.ts
  test/e2e/features/pageObjects/CaseListPage.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/hearingRecordingsCase.js
  test/e2e/features/pageObjects/searchPage.js
  test/e2e/features/pageObjects/workAllocation/taskListTable.js
  test/e2e/features/pageObjects/workAllocation/taskManagerPage.js
  test/e2e/features/step_definitions/searchCase.steps.js
  test/e2e/features/step_definitions/workallocation/common.steps.js
  test/e2e/support/customWaits.js
  test/e2e/support/hooks.js
  test/integration/tests/utils/request.ts
  test/ngIntegration/config/protractor-cucumber.conf.js
  test/ngIntegration/tests/features/workallocation2/myWork_AvailableTasks.feature
  test/ngIntegration/tests/stepDefinitions/workallocation/wa.steps.js
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1270

#1282 Feature/replace role api aat
  api/user/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1282
