Repository hmcts/rpx-xui-webapp, pull requests merged in 2021-09, with the labels that each got.

#1280 Feature/e UI 3887 tasks api
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/index.ts
  api/workAllocation2/roleService.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/taskService.mock.ts
  api/workAllocation2/taskService.ts
  src/app/resolvers/case-tasks-resolver.service.spec.ts
  src/app/resolvers/case-tasks-resolver.service.ts
  src/cases/case-feature.routes.ts
  src/cases/components/index.ts
  src/cases/components/task-alert-banner/task-alert-banner.component.html
  src/cases/components/task-alert-banner/task-alert-banner.component.scss
  src/cases/components/task-alert-banner/task-alert-banner.component.spec.ts
  src/cases/components/task-alert-banner/task-alert-banner.component.ts
  src/cases/containers/tasks-container/tasks-container.component.html
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/work-allocation-2/models/tasks/task.model.ts
  src/work-allocation-2/tests/utils.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1280

#1265 feature/EUI-3911
  api/roleAccess/index.ts
  api/roleAccess/roleAccessService.mock.ts
  api/roleAccess/roleAssignmentService.ts
  api/roleAccess/routes.ts
  api/workAllocation2/constants/roles.mock.data.ts
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/caseRole.ts
  api/workAllocation2/roleService.mock.ts
  api/workAllocation2/roleService.ts
  api/workAllocation2/routes.ts
  package.json
  src/app/resolvers/case-roles-resolver.service.spec.ts
  src/app/resolvers/case-roles-resolver.service.ts
  src/cases/components/roles-and-access/roles-and-access.component.html
  src/cases/components/roles-and-access/roles-and-access.component.ts
  src/cases/directives/show-allocate-link.directive.spec.ts
  src/cases/directives/show-allocate-link.directive.ts
  src/cases/models/user-type.ts
  src/role-access/components/answers/answers.component.html
  src/role-access/components/case-roles-table/case-roles-table.component.html
  src/role-access/components/case-roles-table/case-roles-table.component.ts
  src/role-access/constants/allocate-role-navigation-visibility-states.ts
  src/role-access/constants/role-access.constants.ts
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/allocate-role/allocate-role-navigation/allocate-role-navigation.component.html
  src/role-access/containers/allocate-role/allocate-role-navigation/allocate-role-navigation.component.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.html
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts
  src/role-access/containers/allocate-role/choose-allocate-to/choose-allocate-to.component.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
  src/role-access/containers/remove-role/remove-role.component.ts
  src/role-access/models/allocate-role-state-data.interface.ts
  src/role-access/models/allocate-role.enum.ts
  src/role-access/models/answer.model.ts
  src/role-access/models/case-role.interface.ts
  src/role-access/models/enums/allocation-text.ts
  src/role-access/models/enums/index.ts
  src/role-access/models/index.ts
  src/role-access/role-access.routes.ts
  src/role-access/services/allocate-role.service.ts
  src/role-access/store/actions/allocate-role.action.ts
  src/role-access/store/effects/allocate-role.effects.ts
  src/role-access/store/reducers/allocate-role.reducer.ts
  src/role-access/store/reducers/exclusion.reducer.ts
  test/accessibility/tests/workAllocation/reallocatePages.test.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1265

#1284 parallelise unit test
  package.json
  src/cases/containers/case-create-submit/case-create-submit.component.spec.ts
  src/cases/containers/case-create/case-create.component.spec.ts
  src/cases/containers/case-home/case-home.component.spec.ts
  src/cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/karma.conf.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1284

#1285 case task component
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/taskService.mock.ts
  api/workAllocation2/utils.spec.ts
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.scss
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/components/index.ts
  src/cases/containers/tasks-container/tasks-container.component.html
  src/cases/containers/tasks-container/tasks-container.component.scss
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/work-allocation-2/components/task-field/task-field.component.spec.ts
  src/work-allocation-2/components/work-field/work-field.component.spec.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/models/tasks/task.model.ts
  src/work-allocation-2/tests/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1285

#1290 My cases for Judicial and Legla ops
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.spec.ts
  src/work-allocation-2/tests/utils.spec.ts
  test/e2e/features/pageObjects/workAllocation/allWorkPage.js
  test/integration/tests/workallocation/release2.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1290

#1303 fix karma coverage report
  package.json
  src/karma.conf.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1303

#1302 fix karma coverage report
  package.json
  sonar-project.properties
  src/karma.conf.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1302

#1297 fix for the date format
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1297

#1295 Feature/e UI 3576 next steps active tasks
  api/workAllocation2/constants/mock.data.ts
  package.json
  sonar-project.properties
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/utils/utils.ts
  src/karma.conf.js
  src/work-allocation-2/components/task-field/task-field.component.spec.ts
  src/work-allocation-2/components/work-field/work-field.component.spec.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/models/tasks/task.model.ts
  src/work-allocation-2/tests/utils.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1295

#1301 Feature/e UI 4456 code cleanup
  api/user/index.ts
  src/app/containers/app-header/app-header.component.spec.ts
  src/app/models/user-details.model.ts
  src/app/store/reducers/app-config.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/cases/components/roles-and-access/roles-and-access.component.html
  src/cases/components/roles-and-access/roles-and-access.component.spec.ts
  src/cases/components/roles-and-access/roles-and-access.component.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.html
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/role-access/components/case-roles-table/case-roles-table.component.html
  src/role-access/components/case-roles-table/case-roles-table.component.spec.ts
  src/role-access/components/case-roles-table/case-roles-table.component.ts
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.ts
  src/role-access/containers/add-exclusion/choose-exclusion/choose-exclusion.component.spec.ts
  src/role-access/containers/add-exclusion/choose-exclusion/choose-exclusion.component.ts
  src/role-access/models/exclusion-state-data.interface.ts
  src/role-access/store/actions/exclusion.action.ts
  src/role-access/store/reducers/exclusion.reducer.ts
  src/role-access/testing/app-initial-state.mock.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1301

#1306 refactor code clean up
  src/app/containers/app-header/app-header.component.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1306

#1305 feature/EUI-3881-fix-bug
  package.json
  sonar-project.properties
  src/app/app-initilizer.ts
  src/app/store/reducers/app-config.reducer.ts
  src/work-allocation-2/components/case-name-field/case-name-field.component.html
  src/work-allocation-2/components/case-name-field/case-name-field.component.spec.ts
  src/work-allocation-2/components/case-name-field/case-name-field.component.ts
  src/work-allocation-2/components/work-field/work-field.component.spec.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1305

#1286 Feature/e UI 3614 and 3640 due date
  api/workAllocation2/constants/mock.data.ts
  src/cases/cases.module.ts
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/components/task-alert-banner/task-alert-banner.component.scss
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/components/index.ts
  src/work-allocation-2/components/my-cases-filter/my-cases-filter.component.ts
  src/work-allocation-2/components/priority-field/priority-field.component.html
  src/work-allocation-2/components/priority-field/priority-field.component.spec.ts
  src/work-allocation-2/components/priority-field/priority-field.component.ts
  src/work-allocation-2/components/priority-field/priority.module.ts
  src/work-allocation-2/components/task-field/task-field.component.html
  src/work-allocation-2/components/task-field/task-field.component.spec.ts
  src/work-allocation-2/components/work-allocation.components.module.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/enums/field-type.ts
  src/work-allocation-2/enums/index.ts
  src/work-allocation-2/enums/task-field-type.ts
  src/work-allocation-2/enums/task-priority.ts
  src/work-allocation-2/models/tasks/task-field-config.model.ts
  src/work-allocation-2/work-allocation2.module.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1286

#1307 Make accessibility fixes
  api/roleAccess/exclusionService.spec.ts
  src/role-access/components/choose-radio-option/choose-radio-option.component.html
  src/role-access/components/choose-radio-option/choose-radio-option.component.scss
  src/role-access/components/choose-radio-option/choose-radio-option.component.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.html
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.scss
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.html
  test/accessibility/tests/workAllocation/myWork.test.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1307

#1313 feature/EUI-4476-demo-comments
  api/workAllocation2/caseService.mock.ts
  api/workAllocation2/constants/mock.data.ts
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.scss
  src/role-access/components/case-roles-table/case-roles-table.component.html
  src/role-access/components/exclusions-table/exclusions-table.component.html
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.ts
  src/style/app.scss
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/components/priority-field/priority-field.component.ts
  src/work-allocation-2/components/task-field/task-field.component.html
  src/work-allocation-2/components/task-field/task-field.component.ts
  src/work-allocation-2/components/work-field/work-field.component.html
  src/work-allocation-2/components/work-field/work-field.component.ts
  src/work-allocation-2/containers/my-cases/my-cases.component.html
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.html
  src/work-allocation-2/containers/task-list/task-list.component.scss
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/containers/work-case-list/work-case-list.component.html
  src/work-allocation-2/containers/work-case-list/work-case-list.component.scss
  src/work-allocation-2/containers/work-case-list/work-case-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1313

#1283 Nightly build fixes
  Jenkinsfile_CNP
  api/user/index.ts
  api/workAllocation2/util.ts
  test/e2e/features/pageObjects/common/CaseManager.js
  test/integration/tests/nodeApp_endpoints.spec.ts
  test/ngIntegration/util/browserUtil.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1283

#1323 Feature/role assign idam role merge
  api/user/index.ts
  api/user/utils.spec.ts
  api/user/utils.ts
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/app/app.constants.ts
  src/app/components/get-help/get-help.component.ts
  src/app/containers/app-header-signed-out/app-header-signed-out.component.spec.ts
  src/app/containers/app-header-signed-out/app-header-signed-out.component.ts
  src/app/containers/app-header/app-header.component.spec.ts
  src/app/containers/app-header/app-header.component.ts
  src/app/containers/terms-and-conditions/terms-and-conditions.component.spec.ts
  src/app/containers/terms-and-conditions/terms-and-conditions.component.ts
  src/app/models/theme.model.ts
  src/app/resolvers/case-tasks-resolver.service.spec.ts
  src/app/shared/services/environment.service.ts
  src/app/store/effects/acceptTC.effects.ts
  src/app/store/effects/app.effects.ts
  src/cases/case-feature.routes.ts
  src/cases/containers/case-create-submit/case-create-submit.component.ts
  src/cases/containers/case-create/case-create.component.spec.ts
  src/cases/containers/case-home/case-home.component.spec.ts
  src/cases/containers/case-home/case-home.component.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/converters/case-converters.spec.ts
  src/cases/store/effects/case-create.effects.spec.ts
  src/noc/containers/noc-q-and-a/noc-q-and-a.component.spec.ts
  src/noc/guards/noc-guard.spec.ts
  src/noc/guards/noc-guard.ts
  src/noc/noc.routes.ts
  src/role-access/testing/app-initial-state.mock.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1323

#1308 Feature/e UI 4273 display filters
  api/workAllocation2/caseService.mock.ts
  api/workAllocation2/caseService.ts
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/interfaces/jurisdiction.ts
  api/workAllocation2/interfaces/taskSearchParameter.ts
  package.json
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/app/app.constants.ts
  src/app/models/user-details.model.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.html
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.scss
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.html
  src/work-allocation-2/containers/all-work-case/all-work-case.component.scss
  src/work-allocation-2/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1308

#1330 Bugfix/eu 4511 data correction
  api/workAllocation2/constants/mock.data.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1330

#1314 EUI-4469 Live Defect - Google Tag Manager broken
  src/app/containers/app/app.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1314

#1317 Feature/e UI 3477 all work tasks filters
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/taskService.mock.ts
  src/app/models/user-details.model.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.html
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.scss
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.spec.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.html
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/index.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.html
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.spec.ts
  src/work-allocation-2/containers/task-manager-list/task-manager-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1317

#1311 EUI-4210-from-master
  package.json
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/components/case-alert/alert.component.ts
  src/cases/containers/case-create/case-create.component.spec.ts
  src/cases/containers/case-create/case-create.component.ts
  src/cases/containers/case-details/case-details.component.spec.ts
  src/cases/containers/case-details/case-details.component.ts
  src/cases/resolvers/activity.resolver.ts
  src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1311

#1321 Feature/e UI 3841
  src/cases/containers/case-home/case-home.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1321

#1332 Hotfix/e UI 4469 prod cookie banner aa
  src/app/containers/app/app.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1332

#1333 Hotfix/e UI 4488 fix action banner
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/taskService.mock.ts
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/components/case-alert/alert.component.ts
  src/cases/containers/case-details-home/case-details-home.component.spec.ts
  src/cases/containers/case-details-home/case-details-home.component.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.scss
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.scss
  src/work-allocation-2/containers/all-work-case/all-work-case.component.scss
  src/work-allocation-2/containers/all-work-task/all-work-task.component.scss
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/containers/info-message-container/info-message-container.component.ts
  src/work-allocation-2/services/info-message-comms.service.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1333

#1326 Feature/e UI 4200 task error
  api/workAllocation2/taskService.mock.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.ts
  src/work-allocation-2/utils/work-allocation-utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1326
