Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-03, with the labels that each got.

#1809 ngIntegration BDD tags fix to disable tests in master pipeline
  Jenkinsfile_nightly
  test/ngIntegration/config/protractor-cucumber.conf.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1809

#1807 story/EUI-5126
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.html
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.html
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/converters/hearing-panel.answer.converter.spec.ts
  src/hearings/converters/hearing-panel.answer.converter.ts
  src/hearings/converters/judge-exclusion.answer.converter.spec.ts
  src/hearings/converters/judge-exclusion.answer.converter.ts
  src/hearings/converters/judge-exclusion.hidden.converter.spec.ts
  src/hearings/converters/judge-exclusion.hidden.converter.ts
  src/hearings/converters/judge-name.answer.converter.spec.ts
  src/hearings/converters/judge-name.answer.converter.ts
  src/hearings/converters/judge-name.hidden.converter.spec.ts
  src/hearings/converters/judge-name.hidden.converter.ts
  src/hearings/converters/judge-types.answer.converter.spec.ts
  src/hearings/converters/judge-types.answer.converter.ts
  src/hearings/converters/judge-types.hidden.converter.spec.ts
  src/hearings/converters/judge-types.hidden.converter.ts
  src/hearings/converters/need-judge.answer.converter.spec.ts
  src/hearings/converters/need-judge.answer.converter.ts
  src/hearings/converters/panel-exclusion.answer.converter.spec.ts
  src/hearings/converters/panel-exclusion.answer.converter.ts
  src/hearings/converters/panel-exclusion.hidden.converter.spec.ts
  src/hearings/converters/panel-exclusion.hidden.converter.ts
  src/hearings/converters/panel-inclusion.answer.converter.spec.ts
  src/hearings/converters/panel-inclusion.answer.converter.ts
  src/hearings/converters/panel-inclusion.hidden.converter.spec.ts
  src/hearings/converters/panel-inclusion.hidden.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/pipes/show-hide.pipe.ts
  src/hearings/resolvers/ judicial-user-search-resolver.resolve.ts
  src/hearings/resolvers/judge-types-resolver.service.spec.ts
  src/hearings/resolvers/judge-types-resolver.service.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1807

#1794 Feature/e UI 5093 hearings actuals hearing timings
  api/hearings/hearing.mock.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/components/hearing-actuals-summary/hearing-actuals-summary.component.scss
  src/hearings/components/hearing-summary/hearing-summary.component.html
  src/hearings/components/hearing-summary/hearing-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.scss
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals.component.scss
  src/hearings/containers/hearing-actuals/hearing-actuals.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals.component.ts
  src/hearings/containers/hearing-actuals/index.ts
  src/hearings/containers/index.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/pipes/hearing-update-link.pipe.ts
  src/hearings/pipes/hearings.pipes.module.ts
  src/hearings/services/hearings.service.ts
  src/hearings/store/actions/hearing-actuals.action.spec.ts
  src/hearings/store/actions/hearing-actuals.action.ts
  src/hearings/store/effects/hearing-actuals.effects.spec.ts
  src/hearings/store/effects/hearing-actuals.effects.ts
  src/hearings/store/reducers/hearing-actuals.reducer.ts
  src/hearings/utils/validators.utils.spec.ts
  src/hearings/utils/validators.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1794

#1804 ADMIN user name disaapering fix
  src/cases/components/roles-and-access/roles-and-access.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1804

#1818 request hearing journey pre-populating missing default values
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/models/panelRequirements.model.ts
  api/hearings/models/serviceHearingValues.model.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/models/serviceHearingValues.model.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1818

#1812 story/EUI-5013
  src/hearings/converters/panel-roles.answer.converter.spec.ts
  src/hearings/converters/panel-roles.answer.converter.ts
  src/hearings/converters/panel-roles.hidden.converter.spec.ts
  src/hearings/converters/panel-roles.hidden.converter.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/pipes/show-hide.pipe.ts
  src/hearings/resolvers/panel-roles-resolver.service.spec.ts
  src/hearings/resolvers/panel-roles-resolver.service.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1812

#1814 EUI-5004-amend-hearing-requirement
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/components/hearing-actuals-summary/hearing-actuals-summary.component.scss
  src/hearings/components/hearing-amend-warning-msg/hearing-amend-warning-msg.component.html
  src/hearings/components/hearing-amend-warning-msg/hearing-amend-warning-msg.component.spec.ts
  src/hearings/components/hearing-amend-warning-msg/hearing-amend-warning-msg.component.ts
  src/hearings/components/index.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1814

#1821 story/EUI-4993 hearing view edit
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/models/hearingResponse.model.ts
  api/hearings/models/hearings.enum.ts
  src/hearings/converters/date-request-submitted.answer.converter.spec.ts
  src/hearings/converters/date-request-submitted.answer.converter.ts
  src/hearings/converters/status.answer.converter.spec.ts
  src/hearings/converters/status.answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingResponse.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1821

#1822 Feature/e UI 5066
  api/hearings/models/hearings.enum.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/models/hearings.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1822

#1824 Feature/e UI 5007
  src/hearings/converters/stage.amended.converter.spec.ts
  src/hearings/converters/stage.amended.converter.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1824

#1830 EUI 5023- Amend - Participant attendance
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/converters/how-many-people-attend.amended.converter.spec.ts
  src/hearings/converters/how-many-people-attend.amended.converter.ts
  src/hearings/converters/how-party-attend.amended.converter.spec.ts
  src/hearings/converters/how-party-attend.amended.converter.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1830

#1831 Eui 5446 CVE fix temp
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1831

#1820 EUI-5095 Hearing stage and result happy path
  api/hearings/data/hearing-actuals.mock.data.ts
  api/hearings/index.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.html
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/resolvers/ref-data-resolver.resolve.spec.ts
  src/hearings/store/actions/hearing-actuals.action.spec.ts
  src/hearings/store/actions/hearing-actuals.action.ts
  src/hearings/store/effects/hearing-actuals.effects.spec.ts
  src/hearings/store/effects/hearing-actuals.effects.ts
  src/hearings/store/reducers/hearing-actuals.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1820

#1829 EUI-5189
  api/hearings/models/hearings.enum.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/is-amended.pipe.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1829

#1836 bug/EUI-5433 fixed hearing panel bug and lint fix
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/pipes/is-amended.pipe.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1836

#1825 Feature/e UI 5317 manage link active tasks
  api/workAllocation2/constants/actions.ts
  api/workAllocation2/index.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.scss
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1825

#1833 introduce caseType and jurisdiction in searchForCompletable
  api/workAllocation2/index.ts
  api/workAllocation2/routes.ts
  package.json
  src/cases/containers/case-details-home/case-details-home.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1833

#1827 Update node base chart to 2.4.1
  Dockerfile
  README.md
  charts/xui-webapp/Chart.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1827

#1839 Add reset button space
  src/work-allocation-2/containers/task-list/task-list.component.html
  src/work-allocation-2/containers/task-list/task-list.component.scss
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1839

#1837 story/EUI-5032
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/converters/hearing-panel.amended.converter.spec.ts
  src/hearings/converters/hearing-panel.amended.converter.ts
  src/hearings/converters/panel-exclusion.amended.converter.spec.ts
  src/hearings/converters/panel-exclusion.amended.converter.ts
  src/hearings/converters/panel-inclusion.amended.converter.spec.ts
  src/hearings/converters/panel-inclusion.amended.converter.ts
  src/hearings/converters/panel-roles.amended.converter.spec.ts
  src/hearings/converters/panel-roles.amended.converter.ts
  src/hearings/pipes/is-amended.pipe.spec.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1837

#1835 PACT test updated with correct state matching provider tests.
  api/test/pact/pact-tests/accessManagement/getRoleAssignments.spec.ts
  api/test/pact/pact-tests/rdCaseworker/getAllCaseworkers.spec.ts
  api/test/pact/pact-tests/rdCaseworker/getCaseworkerForLocation.spec.ts
  api/test/pact/pact-tests/rdCaseworker/getCaseworkerForService.spec.ts
  api/test/pact/pact-tests/rdJudicial/getJudicialUsers.spec.ts
  api/test/pact/pact-tests/rdLocation/getAllLocations.spec.ts
  api/test/pact/pact-tests/rolesAccess/addExclusion.spec.ts
  api/test/pact/pact-tests/rolesAccess/allocateRole.spec.ts
  api/test/pact/pact-tests/rolesAccess/deleteExclusion.spec.ts
  api/test/pact/pact-tests/rolesAccess/deleteRole.spec.ts
  api/test/pact/pact-tests/rolesAccess/getRoles.spec.ts
  api/test/pact/pact-tests/rolesAccess/roleAssignmentQuery.spec.ts
  api/test/pact/pact-tests/rolesAccess/roleAssignmentsWithGrantType.spec.ts
  api/test/pact/pact-tests/utils/matchers.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1835

#1834 Filter by work types only when all are not selected
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1834

#1842 EUI-5073
  api/hearings/data/hearingLists.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/models/hearingList.model.ts
  api/hearings/models/hearings.enum.ts
  api/hearings/models/panelPreference.model.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingList.model.ts
  src/hearings/models/panelPreference.model.ts
  src/hearings/store/effects/hearing-list.effects.spec.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-list.reducer.spec.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1842

#1840 amended flag updates for Judge/Hearing duration/length details page
  src/hearings/converters/hearing-length.amended.converter.spec.ts
  src/hearings/converters/hearing-length.amended.converter.ts
  src/hearings/converters/hearing-priority.amended.converter.spec.ts
  src/hearings/converters/hearing-priority.amended.converter.ts
  src/hearings/converters/hearing-specific-date.amended.converter.spec.ts
  src/hearings/converters/hearing-specific-date.amended.converter.ts
  src/hearings/converters/judge-exclusion.amended.converter.spec.ts
  src/hearings/converters/judge-exclusion.amended.converter.ts
  src/hearings/converters/judge-name.amended.converter.spec.ts
  src/hearings/converters/judge-name.amended.converter.ts
  src/hearings/converters/judge-types.amended.converter.spec.ts
  src/hearings/converters/judge-types.amended.converter.ts
  src/hearings/converters/need-judge.amended.converter.spec.ts
  src/hearings/converters/need-judge.amended.converter.ts
  src/hearings/converters/need-judge.answer.converter.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1840

#1853 Eui 5474 CVE fix temp
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1853

#1808 Feature/e UI 5099 hearing actuals display participants
  api/hearings/data/hearing-actuals.mock.data.ts
  api/prd/lov/data/lov.mock.data.ts
  api/prd/lov/index.ts
  api/prd/lov/lov.mock.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.scss
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/containers/hearing-actuals/index.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/resolvers/hearing-actual-party-channel-resolver.service.spec.ts
  src/hearings/resolvers/hearing-actual-party-channel-resolver.service.ts
  src/hearings/resolvers/hearing-actual-role-resolver.service.spec.ts
  src/hearings/resolvers/hearing-actual-role-resolver.service.ts
  src/hearings/resolvers/ref-data-resolver.resolve.ts
  src/hearings/services/lov-ref-data.service.spec.ts
  src/hearings/services/lov-ref-data.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1808

#1673 Integrate Ways To Pay
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/user/index.spec.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/models/environmentConfig.model.ts
  test/integration/tests/config/config.ts
  test/integration/tests/nodeApp_endpoints.spec.ts
  test/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/tasksTab.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1673

#1838 EUI-5088 hide non relevant filter section
  api/roleAccess/index.ts
  api/workAllocation2/index.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.html
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.spec.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation-2/containers/my-cases/my-cases.component.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  test/e2e/features/pageObjects/workAllocation/myWorkPage.js
  test/e2e/features/step_definitions/workallocation/workFilter.steps.js
  test/ngIntegration/tests/features/workallocation2/workFilters.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1838

#1859 Add functionality of radio selection change
  api/roleAccess/index.ts
  package.json
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1859

#1864 EUI-5195 Request hearing check your answers unhappy path
  api/hearings/index.ts
  src/hearings/components/hearing-summary/hearing-summary.component.html
  src/hearings/components/hearing-summary/hearing-summary.component.spec.ts
  src/hearings/components/hearing-summary/hearing-summary.component.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/store/actions/hearing-request.action.spec.ts
  src/hearings/store/actions/hearing-request.action.ts
  src/hearings/store/effects/hearing-request.effects.spec.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/store/reducers/hearing-request.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1864

#1860 Feature/e UI 5248 participants page api
  api/hearings/data/hearing-actuals.mock.data.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearingActualsMainModel.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearings.pipes.module.ts
  src/hearings/pipes/party-channel-display-value.pipe.ts
  src/hearings/pipes/party-role-display-value.pipe.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1860

#1870 Eui 5488 CVE fix temp
  test/e2e/features/step_definitions/workallocation/allocateRoles.steps.js
  test/e2e/features/step_definitions/workallocation/caseRolesAccess.steps.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1870

#1844 EUI-5407 Hearing actuals data model changes
  api/hearings/data/hearing-actuals.mock.data.ts
  api/hearings/models/hearingActualsMainModel.ts
  src/hearings/components/hearing-actuals-case-title/hearing-actuals-case-title.component.html
  src/hearings/components/hearing-actuals-case-title/hearing-actuals-case-title.component.spec.ts
  src/hearings/components/hearing-actuals-case-title/hearing-actuals-case-title.component.ts
  src/hearings/components/index.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.html
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingActualsMainModel.ts
  src/hearings/store/actions/hearing-actuals.action.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1844

#1869 Feature/e UI 5097
  api/hearings/hearing.mock.ts
  api/prd/lov/data/lov.mock.data.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.spec.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.ts
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1869

#1867 Feature/e UI 5403 submit hearing api call failure
  api/hearings/hearing.mock.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/store/actions/hearing-actuals.action.spec.ts
  src/hearings/store/actions/hearing-actuals.action.ts
  src/hearings/store/effects/hearing-actuals.effects.spec.ts
  src/hearings/store/effects/hearing-actuals.effects.ts
  src/hearings/store/reducers/hearing-actuals.reducer.spec.ts
  src/hearings/store/reducers/hearing-actuals.reducer.ts
  src/hearings/store/selectors/hearing-actuals.selectors.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1867

#1875 feature/EUI-5409: demo
  api/hearings/hearing.mock.ts
  api/prd/caseFlag/caseFlag.mock.ts
  api/prd/judicial/judicial.mock.ts
  api/prd/location/location.mock.ts
  api/prd/lov/lov.mock.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1875

#1878 EUI-5475 task not completed when multiple tasks
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1878

#1880 EUI-5512 Incorrect user name displayed on the validation message
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1880

#1883 If task has been unassigned or reassigned then pass true
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1883

#1876 upgraded ccd-ui-toolkit for preview link
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1876

#1888 EUI-5496 Update toolkit version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1888

#1889 CVEs tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1889

#1866 feature/EUI-5409
  api/hearings/data/hearingLists.mock.data.ts
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/models/individualDetails.model.ts
  api/hearings/models/organisationDetails.model.ts
  api/hearings/models/partyDetails.model.ts
  api/hearings/models/partyFlags.model.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/hearings/components/case-flags/case-flags.component.spec.ts
  src/hearings/components/case-flags/case-flags.component.ts
  src/hearings/components/hearing-amend-warning-msg/hearing-amend-warning-msg.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.html
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/index.ts
  src/hearings/containers/view-hearing/index.ts
  src/hearings/converters/case-flag.amended.converter.spec.ts
  src/hearings/converters/case-flag.amended.converter.ts
  src/hearings/converters/case-flag.answer.converter.spec.ts
  src/hearings/converters/case-flag.answer.converter.ts
  src/hearings/converters/hearing-specific-date.amended.converter.spec.ts
  src/hearings/converters/how-party-attend.amended.converter.spec.ts
  src/hearings/converters/how-party-attend.amended.converter.ts
  src/hearings/converters/participant-attendence.answer.converter.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/actualsSection.ts
  src/hearings/models/hearingActualsPartyDetails.model.ts
  src/hearings/models/hearingConditions.ts
  src/hearings/models/individualDetails.model.ts
  src/hearings/models/organisationDetails.model.ts
  src/hearings/models/partyDetails.model.ts
  src/hearings/models/partyFlags.model.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/is-amended.pipe.spec.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/resolvers/judicial-user-search-resolver.resolve.spec.ts
  src/hearings/resolvers/judicial-user-search-resolver.resolve.ts
  src/hearings/resolvers/judicial-user-search-response-resolver.resolve.spec.ts
  src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
  src/hearings/utils/case-flags.utils.ts
  src/hearings/utils/hearings.utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1866

#1893 Complete to be shown on Manage
  api/workAllocation2/constants/actions.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1893

#1898 Eui 5563 CVE fix temp
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1898

#1899 Update index.ts
  api/workAllocation2/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1899

#1903 Add in release version
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1903

#1811 WA release 2 and 2.1 Bug fixes
  api/workAllocation2/constants/actions.ts
  api/workAllocation2/index.ts
  api/workAllocation2/routes.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  package.json
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.scss
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/components/roles-and-access/roles-and-access.component.ts
  src/cases/containers/case-details-home/case-details-home.component.spec.ts
  src/cases/containers/case-details-home/case-details-home.component.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/role-access/services/allocate-role.service.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  test/dataModels/workAllocation.js
  test/e2e/features/pageObjects/workAllocation/taskForEventValidatiosPage.js
  test/e2e/features/step_definitions/workallocation/taskEventCompletion.steps.js
  test/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/tasksTab.feature
  test/ngIntegration/tests/features/workallocation2/rolesAccess/exclusionsChangeLink.feature
  test/ngIntegration/tests/features/workallocation2/taskEventCompletion/taskEventCompletion.feature
  test/ngIntegration/tests/stepDefinitions/common.steps.js
  test/ngIntegration/tests/stepDefinitions/mockCase.steps.js
  test/ngIntegration/tests/stepDefinitions/workallocation/taskEventCompletion.steps.js
  test/nodeMock/workAllocation/mockData.js
  test/nodeMock/workAllocation/reqResMapping.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1811

#1868 EUI-4454 Service failure error handling on hearings tab part 1
  api/hearings/data/hearingLists.mock.data.ts
  api/hearings/hearing.mock.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/components/error-page/error-page.component.html
  src/hearings/components/error-page/error-page.component.scss
  src/hearings/components/error-page/error-page.component.spec.ts
  src/hearings/components/error-page/error-page.component.ts
  src/hearings/components/index.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/hearings.routes.ts
  src/hearings/resolvers/additional-facilities.resolver.ts
  src/hearings/resolvers/adjourn-hearing-actual-reason.resolver.ts
  src/hearings/resolvers/cancel-hearing-actual-reason.resolver.ts
  src/hearings/resolvers/hearing-actual-party-channel-resolver.service.ts
  src/hearings/resolvers/hearing-actual-role-resolver.service.ts
  src/hearings/resolvers/hearing-change-reason.resolver.ts
  src/hearings/resolvers/hearing-stage.resolver.ts
  src/hearings/resolvers/judge-types-resolver.service.ts
  src/hearings/resolvers/panel-roles-resolver.service.ts
  src/hearings/resolvers/party-channels-resolver.service.ts
  src/hearings/resolvers/ref-data-resolver.resolve.spec.ts
  src/hearings/resolvers/ref-data-resolver.resolve.ts
  src/hearings/store/actions/hearing-actuals.action.spec.ts
  src/hearings/store/actions/hearing-actuals.action.ts
  src/hearings/store/actions/hearing-request.action.spec.ts
  src/hearings/store/actions/hearing-request.action.ts
  src/hearings/store/actions/hearing-values.action.spec.ts
  src/hearings/store/actions/hearing-values.action.ts
  src/hearings/store/effects/hearing-actuals.effects.spec.ts
  src/hearings/store/effects/hearing-actuals.effects.ts
  src/hearings/store/effects/hearing-request.effects.spec.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/effects/hearing-values.effects.ts
  src/hearings/store/reducers/hearing-actuals.reducer.spec.ts
  src/hearings/store/reducers/hearing-actuals.reducer.ts
  src/hearings/store/reducers/hearing-request.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
  src/hearings/store/reducers/hearing-values.reducer.ts
  src/hearings/store/selectors/hearing-actuals.selectors.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1868

#1909 Feature/EUI-5110 - view details of Hearings from Hearings tab- Request failed
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/models/hearingResponse.model.ts
  api/hearings/models/hearings.enum.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/containers/view-hearing/hearing-request-failed-summary/hearing-request-failed-summary.component.html
  src/hearings/containers/view-hearing/hearing-request-failed-summary/hearing-request-failed-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-request-failed-summary/hearing-request-failed-summary.component.ts
  src/hearings/containers/view-hearing/index.ts
  src/hearings/converters/date-request-failed.answer.converter.spec.ts
  src/hearings/converters/date-request-failed.answer.converter.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearingResponse.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/templates/hearing-request-failed-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1909

#1910 cve temp fix
  test/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/tasksTab.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1910

#1907 EUI-4783 scenarios implimented
  src/app/app.module.ts
  src/app/app.routes.ts
  src/booking/containers/booking-check/booking-check.component.spec.ts
  src/booking/containers/booking-check/booking-check.component.ts
  src/booking/containers/index.ts
  src/booking/containers/utils/booking-error-handler.ts
  src/booking/containers/utils/booking-service-down/booking-service-down.component.html
  src/booking/containers/utils/booking-service-down/booking-service-down.component.ts
  src/booking/containers/utils/refresh-booking-service-down/refresh-booking-service-down.component.html
  src/booking/containers/utils/refresh-booking-service-down/refresh-booking-service-down.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1907

#1908 Feature/e UI 5130
  api/hearings/hearing.mock.ts
  src/app/services/role-category-mapping/role-category-mapping.service.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/cases/services/search-filter.service.ts
  src/cases/utils/utils.spec.ts
  src/cases/utils/utils.ts
  src/hearings/components/index.ts
  src/hearings/guards/hearings-edit-guard.spec.ts
  src/hearings/guards/hearings-edit-guard.ts
  src/hearings/guards/hearings-guard.spec.ts
  src/hearings/guards/hearings-guard.ts
  src/hearings/guards/hearings-view-guard.spec.ts
  src/hearings/guards/hearings-view-guard.ts
  src/hearings/hearings.module.ts
  src/hearings/hearings.routes.ts
  src/role-access/containers/remove-role/remove-role.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1908

#1913 cve temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1913

#1916 EUI-5476: init hearings link store
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingLinksStateData.model.ts
  src/hearings/store/actions/hearing-links.action.spec.ts
  src/hearings/store/actions/hearing-links.action.ts
  src/hearings/store/actions/index.ts
  src/hearings/store/effects/hearing-links.effects.spec.ts
  src/hearings/store/effects/hearing-links.effects.ts
  src/hearings/store/effects/index.ts
  src/hearings/store/reducers/hearing-links.reducer.spec.ts
  src/hearings/store/reducers/hearing-links.reducer.ts
  src/hearings/store/reducers/index.ts
  src/hearings/store/selectors/hearing-links.selectors.spec.ts
  src/hearings/store/selectors/hearing-links.selectors.ts
  src/hearings/store/selectors/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1916

#1920 WA1 task list api test fix/updates - master build test FT fixes
  test/integration/tests/workallocation/release1.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1920

#1914 EUI-5232 Cache reference data in resolver or node layer api
  src/hearings/resolvers/additional-facilities.resolver.ts
  src/hearings/resolvers/adjourn-hearing-actual-reason.resolver.ts
  src/hearings/resolvers/cancel-hearing-actual-reason.resolver.ts
  src/hearings/resolvers/court-locations-resolver.resolve.ts
  src/hearings/resolvers/hearing-actual-party-channel-resolver.service.ts
  src/hearings/resolvers/hearing-actual-role-resolver.service.ts
  src/hearings/resolvers/hearing-change-reason.resolver.ts
  src/hearings/resolvers/hearing-stage.resolver.ts
  src/hearings/resolvers/judge-types-resolver.service.ts
  src/hearings/resolvers/panel-roles-resolver.service.ts
  src/hearings/resolvers/party-channels-resolver.service.ts
  src/hearings/resolvers/ref-data-resolver.resolve.spec.ts
  src/hearings/resolvers/ref-data-resolver.resolve.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1914

#1924 cve temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1924

#1925 remove dashes in caseId
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1925

#1918 EUI-5590 - Specific Access Request approved
  src/role-access/containers/specific-access/specific-access-approved/specific-access-approved.component.html
  src/role-access/containers/specific-access/specific-access-approved/specific-access-approved.component.spec.ts
  src/role-access/containers/specific-access/specific-access-approved/specific-access-approved.component.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1918

#1919 Feature/e UI 5543 hearing attendance page model changes
  api/hearings/data/hearingLists.mock.data.ts
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/models/partyDetails.model.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.scss
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/converters/judge-exclusion.amended.converter.spec.ts
  src/hearings/converters/participant-attendence.answer.converter.ts
  src/hearings/converters/party-channels-answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/partyDetails.model.ts
  src/hearings/pipes/is-amended.pipe.spec.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1919
