Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-10, with the labels that each got.

#2263 MC Release 6.8.0
  package.json
  src/app/app.routes.ts
  src/assets/images/icon-tag-remove-cross-white.svg
  src/noc/containers/noc-errors/noc-error.component.html
  test/accessibility/config/pa11yProtractor.conf.js
  test/accessibility/tests/caseList.test.js
  test/accessibility/tests/footerPages.test.js
  test/accessibility/tests/workAllocation.test.js
  test/accessibility/tests/workAllocation/myWork.test.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2263

#2362 bug/EUI-6852
  src/app/components/routing/application-routing.component.spec.ts
  src/app/components/routing/application-routing.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2362

#2364 EUI-6823 display name
  api/workAllocation/caseWorkerService.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.spec.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
  src/role-access/role-access.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2364

#2363 EUI-6830 Fix the issue on cancel link navigation
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2363

#2370 EUI-6828 Fix missing request from
  api/workAllocation/caseWorkerService.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2370

#2373 EUI-6850 Set access management true
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2373

#2365 bug/EUI-6849 fix case name internal
  api/workAllocation/interfaces/case.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2365

#2376 Hearings yaml config update
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2376

#2374 EUI-6881 Duplicate LOV values in Demo
  api/prd/lov/index.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/services/lov-ref-data.service.spec.ts
  src/hearings/services/lov-ref-data.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2374

#2378 EUI-6898 Hearings update text for error screen
  src/hearings/models/hearings.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2378

#2377 Bug/e UI 6877
  api/accessManagement/index.spec.ts
  api/accessManagement/index.ts
  api/configuration/references.ts
  config/default.json
  src/booking/containers/booking-check/booking-check.component.ts
  src/booking/containers/booking-home/booking-home.component.ts
  src/booking/services/booking.service.spec.ts
  src/booking/services/booking.service.ts
  src/work-allocation/components/task-list-filter/task-list-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2377

#2382 Bug/EUI 6850 global search returning empty tabs
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2382

#2381 bug/EUI-6825-fix
  api/locations/index.ts
  src/booking/containers/booking-home/booking-home.component.ts
  src/work-allocation/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation/resolvers/location-resolver.service.ts
  test/e2e/features/step_definitions/workallocation/workFilter.steps.js
  test/integration/tests/mocha.json
  test/integration/tests/workallocation/locations.spec.ts
  test/ngIntegration/tests/features/workAccessBookingUI/featureToggle-guard.feature
  test/ngIntegration/tests/features/workAllocation/taskActions.feature
  test/ngIntegration/tests/features/workAllocation/taskListAvailableTasks.feature
  test/ngIntegration/tests/features/workAllocation/taskListMyTasks.feature
  test/ngIntegration/tests/features/workAllocation/taskManager.feature
  test/ngIntegration/tests/features/workallocation2/myWorkFilters/filtersServicesAndLocations.feature
  test/ngIntegration/tests/features/workallocation2/myWorkFilters/workFilter_unhappyPath.feature
  test/ngIntegration/tests/features/workallocation2/myWorkFilters/workFilters.feature
  test/ngIntegration/tests/stepDefinitions/bookingsMock.steps.js
  test/ngIntegration/tests/stepDefinitions/workallocation/common.steps.js
  test/ngIntegration/tests/stepDefinitions/workallocation/wa2.steps.js
  test/ngIntegration/tests/stepDefinitions/workallocation/waCommon.steps.js
  test/ngIntegration/util/cucumberHooks.js
  test/nodeMock/workAllocation/mockData.js
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2381

#2383 fix 6890
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2383

#2384 EUI-6896
  src/cases/components/task-alert-banner/task-alert-banner.component.html
  src/cases/components/task-alert-banner/task-alert-banner.component.spec.ts
  src/cases/components/task-alert-banner/task-alert-banner.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2384

#2389 Bug/EUI 6888
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2389

#2379 Hearings mvp fixes
  api/prd/lov/index.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/services/lov-ref-data.service.spec.ts
  src/hearings/services/lov-ref-data.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2379

#2391 bug/EUI-6897
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/my-access/my-access.component.spec.ts
  src/work-allocation/containers/my-cases/my-cases.component.spec.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.spec.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2391

#2368 Bug/e UI 6829 case access reason
  api/roleAccess/index.ts
  api/user/interfaces/roleAssignment.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2368

#2395 Bug/EUI 6921
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2395

#2398 cve tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2398

#2375 EUI-5338 update email address
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2375

#1287 EUI-4440 cookies test script
  test/e2e/features/app/cookieBanner.feature
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/pageObjects/common/cookieBanner.js
  test/e2e/features/step_definitions/cookieBanner.steps.js
Labels: ns:xui, prd:xui, stale, rel:xui-webapp-pr-1287

#2402 bug/EUI-6940
  src/app/components/case-reference-search-box/case-reference-search-box.component.spec.ts
  src/app/components/case-reference-search-box/case-reference-search-box.component.ts
  src/cases/case-feature.routes.ts
  src/cases/containers/case-loader/case-loader.component.spec.ts
  src/cases/containers/case-loader/case-loader.component.ts
  src/cases/containers/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2402

#2403 Fix issue with roleCatogory
  api/workAllocation/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2403

#2392 E UI 6867
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2392

#2405 bug/EUI-6959
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2405

#2410 Feature/form control changes 2 ii
  api/staff-ref-data/index.ts
  api/staff-ref-data/routes.ts
  api/staff-ref-data/staff-ref-data.mock.ts
  api/workAllocation/index.ts
  package.json
  src/staff-administrator/components/staff-adv-filter/staff-adv-filter.component.ts
  src/staff-administrator/resolvers/staff-filter-options-resolver.service.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
  src/staff-administrator/test-data/staff-filter-options.test.data.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2410

#2411 EUI-6927 text change
  src/role-access/containers/specific-access/specific-access-duplicate-record/specific-access-duplicate-record.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2411

#2415 Bug/EUI 6968
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2415

#2419 Update success message
  src/role-access/containers/specific-access/specific-access-approved/specific-access-approved.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2419

#2418 Bug/EUI 6931
  src/role-access/services/allocate-role.service.spec.ts
  src/role-access/services/allocate-role.service.ts
  src/role-access/services/duration-helper.service.spec.ts
  src/role-access/services/duration-helper.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2418

#2423 EUI-5481: Case File View - CCD API endpoint for Categories and Documents
  api/proxy.config.ts
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2423

#2422 Bug/e UI 6963
  api/challengedAccess/index.ts
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/index.ts
  api/roleAccess/models/allocate-role-state-data.interface.ts
  api/specificAccessOrchastrator/index.ts
  api/workAllocation/index.ts
  src/work-allocation/containers/my-access/my-access.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2422

#2416 EUI-6822 Two sections for the case file view
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2416

#2427 bug/EUI-6975 fix
  package.json
  src/cases/components/roles-and-access/roles-and-access.component.html
  src/cases/components/roles-and-access/roles-and-access.component.spec.ts
  src/cases/components/roles-and-access/roles-and-access.component.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2427

#2426 Bug/EUI 6931
  api/workAllocation/util.ts
  src/role-access/services/duration-helper.service.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2426

#2417 Bugfix/e UI 6930 specific rejection view
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/models/allocate-role-state-data.interface.ts
  api/user/interfaces/roleAssignment.ts
  api/workAllocation/interfaces/roleCaseData.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  src/app/app.constants.ts
  src/role-access/containers/index.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.html
  src/role-access/containers/rejected-request-view/rejected-request-view.component.scss
  src/role-access/containers/rejected-request-view/rejected-request-view.component.spec.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.ts
  src/role-access/containers/specific-access/specific-access-information/specific-access-information.component.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.html
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
  src/role-access/models/enums/answer-text.ts
  src/role-access/models/specific-access-state-data.interface.ts
  src/role-access/role-access.routes.ts
  src/role-access/store/actions/specific-access.action.ts
  src/role-access/store/reducers/specific-access.reducer.spec.ts
  src/role-access/store/reducers/specific-access.reducer.ts
  src/work-allocation/components/access-view-field/access-view-field.component.html
  src/work-allocation/components/access-view-field/access-view-field.component.scss
  src/work-allocation/components/access-view-field/access-view-field.component.spec.ts
  src/work-allocation/components/access-view-field/access-view-field.component.ts
  src/work-allocation/components/case-name-field/case-name-field.component.html
  src/work-allocation/components/case-name-field/case-name-field.component.spec.ts
  src/work-allocation/components/case-name-field/case-name-field.component.ts
  src/work-allocation/components/constants/config.constants.ts
  src/work-allocation/components/index.ts
  src/work-allocation/components/work-field/work-field.component.html
  src/work-allocation/components/work-field/work-field.component.spec.ts
  src/work-allocation/enums/field-type.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2417

#2401 Hearings mvp fixes v2
  api/prd/lov/index.ts
  src/cases/case-feature.routes.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/cases/containers/case-hearings/case-hearings.component.html
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/utils/hearings.utils.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2401

#2433 bug/EUI-6981
  package.json
  src/booking/containers/booking-location/booking-location.component.html
  src/booking/containers/booking-location/booking-location.component.spec.ts
  src/booking/containers/booking-location/booking-location.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2433

#2435 Bug/EUI 7007
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2435

#2438 Bug/EUI 7008
  src/work-allocation/components/case-name-field/case-name-field.component.spec.ts
  src/work-allocation/components/case-name-field/case-name-field.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2438

#2442 EUI-5481/EUI-6815: Case File View - CCD API endpoints
  proxy.config.json
  proxyTest.config.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2442

#2441 bug/EUI-7019
  src/booking/containers/booking-check/booking-check.component.spec.ts
  src/booking/containers/booking-check/booking-check.component.ts
  src/booking/containers/booking-date/booking-date.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2441

#2439 bug/EUI-6977 fix
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2439

#2445 Bug/EUI 7011
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/user/interfaces/roleAssignment.ts
  api/workAllocation/interfaces/roleCaseData.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.spec.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
  src/work-allocation/components/access-view-field/access-view-field.component.spec.ts
  src/work-allocation/components/access-view-field/access-view-field.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2445

#2443 replaced error code from 500 to 422
  api/caseshare/real-api.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2443
