Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-11, with the labels that each got.

#2449 EUI-6965: Case File View - ComponentLauncher mechanism
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2449

#2450 bug/EUI-7014
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/index.ts
  api/user/interfaces/roleAssignment.ts
  api/workAllocation/interfaces/roleCaseData.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.ts
  src/work-allocation/components/access-view-field/access-view-field.component.spec.ts
  src/work-allocation/components/access-view-field/access-view-field.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2450

#2451 Bug/EUI 6978
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.spec.ts
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.ts
  src/role-access/services/duration-helper.service.spec.ts
  src/role-access/services/duration-helper.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2451

#2400 Mc release 6.9.0
  package.json
  src/app/app.constants.ts
  test/e2e/features/app/cookieBanner.feature
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/pageObjects/common/cookieBanner.js
  test/e2e/features/step_definitions/cookieBanner.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2400

#2452 bug/EUI-6977 fix
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.spec.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2452

#2372 CR-52 JOH typeahead common feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2372

#1928 EUI-5479: Create Case Flag - Reference Data integration
  api/proxy.config.ts
  proxy.config.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
Labels: ns:xui, prd:xui, pinned, rel:xui-webapp-pr-1928

#2456 bug/EUI-7026 get previous date
  src/booking/containers/booking-home/booking-home.component.html
  src/booking/containers/booking-home/booking-home.component.spec.ts
  src/booking/containers/booking-home/booking-home.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2456

#2455 Feature/e UI 6994 revised
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2455

#2463 EUI-7088 Hearings Private Law Integration
  api/configuration/references.ts
  api/hearings/services.index.ts
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2463

#2460 Feature/EUI 6739
  api/staff-ref-data/staff-ref-data.mock.ts
  package.json
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
  src/staff-administrator/resolvers/staff-filter-options-resolver.service.ts
  src/staff-administrator/test-data/staff-filter-options.test.data.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2460

#2468 EUI-7088 Hearings Private Law Integration V2
  api/configuration/references.ts
  api/hearings/services.index.ts
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2468

#2459 Feature/e UI 6768 wa service config
  api/test/pact/pact-tests/utils/configOverride.ts
  api/workAllocation/index.ts
  package.json
  src/app/app.constants.ts
  src/app/components/routing/application-routing.component.spec.ts
  src/app/components/routing/application-routing.component.ts
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/cases/case-feature.routes.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/work-allocation/guards/index.ts
  src/work-allocation/guards/work-allocation-feature-toggle.guard.spec.ts
  src/work-allocation/guards/work-allocation-feature-toggle.guard.ts
  src/work-allocation/models/common/service-config.model.ts
  src/work-allocation/services/work-allocation-case.service.spec.ts
  src/work-allocation/services/work-allocation-case.service.ts
  src/work-allocation/services/work-allocation-feature.service.spec.ts
  src/work-allocation/services/work-allocation-feature.service.ts
  src/work-allocation/work-allocation-feature.routes.ts
  src/work-allocation/work-allocation.module.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2459

#2477 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2477

#2479 EUI-7088 Refactor Hearings config to allow Private Law V2
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2479

#2461 bug/EUI-7044
  src/search/containers/search-results/search-results.component.ts
  test/e2e/features/pageObjects/caseAccessManagement/caseDetailsBasicView.js
  test/e2e/features/step_definitions/caseDetails.steps.js
  test/ngIntegration/tests/features/globalSearch.feature
  test/ngIntegration/tests/features/workallocation2/rolesAccess/manageLinkActions.feature
  test/ngIntegration/tests/stepDefinitions/mockCase.steps.js
  test/ngIntegration/util/cucumberHooks.js
  test/nodeMock/nodeApp/mockData.js
  test/nodeMock/reqResMapping.js
  test/nodeMock/workAllocation/reqResMapping.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2461

#2476 EUI-7116: Fix for empty case-level Flags field missing
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2476

#2474 Add location field as mandatory in filter
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2474

#2483 Update CCD toolkit package
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2483

#2466 Hearings MVP Fixes V3
  api/configuration/references.ts
  api/hearings/services.index.ts
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2466

#2484 EUI-6974 V3 tech ticket for icon
  package.json
  src/assets/images/document.png
  src/assets/images/folder.png
  src/cases/cases.module.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2484

#2481 update ccd ui toolkit version
  package.json
  src/assets/images/document.png
  src/assets/images/folder.png
  src/cases/cases.module.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2481

#2424 Feature/EUI 6402
  package.json
  src/booking/containers/booking-date/booking-date.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/containers/staff-user-check-answers-container/staff-user-check-answers-container.component.html
  src/staff-administrator/containers/staff-user-check-answers-container/staff-user-check-answers-container.component.scss
  src/staff-administrator/containers/staff-user-check-answers-container/staff-user-check-answers-container.component.spec.ts
  src/staff-administrator/containers/staff-user-check-answers-container/staff-user-check-answers-container.component.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/test-data/staff-filter-options.test.data.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2424

#2485 Redirect user to the back step when user hits the cancel button and r…
  package.json
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2485

#2501 EUI-7177 Added missing Accessibility help statement to page
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2501

#2500 WA-access changes (#2493)
  src/app/app.constants.ts
  src/work-allocation/containers/task-home/task-home.component.spec.ts
  src/work-allocation/containers/task-home/task-home.component.ts
  src/work-allocation/guards/index.ts
  src/work-allocation/guards/wa-access-guard.spec.ts
  src/work-allocation/guards/wa-access-guard.ts
  src/work-allocation/work-allocation-feature.routes.ts
  src/work-allocation/work-allocation.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2500

#2505 EUI-7204 Hearings - Panel member information not required for private law
  src/hearings/resolvers/ref-data-resolver.resolve.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2505

#2509 EUI-7224 Menu items fix
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2509

#2510 EUI-7210/EUI-7225: Case Flags defect fixes
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2510

#2502 Add unassign action
  src/app/app.constants.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.ts
  src/work-allocation/services/work-allocation-task.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2502

#2494 Feature/EUI 6966
  api/workAllocation/index.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/enums/index.ts
  src/work-allocation/enums/task-context.ts
  src/work-allocation/models/dtos/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2494

#2519 Removing jurisdictions
  api/waSupportedJurisdictions/index.spec.ts
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2519

#2467 bug/EUI-6913
  api/user/index.ts
  api/user/interfaces/roleAssignment.ts
  api/user/utils.spec.ts
  api/user/utils.ts
  package.json
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
  src/role-access/models/allocate-role.enum.ts
  src/role-access/store/actions/specific-access.action.ts
  src/role-access/store/reducers/specific-access.reducer.ts
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-access/my-access.component.ts
  src/work-allocation/containers/my-cases/my-cases.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.ts
  src/work-allocation/containers/task-assignment-choose-role/task-assignment-choose-role.component.ts
  src/work-allocation/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/resolvers/location-resolver.service.ts
  src/work-allocation/services/work-allocation-task.service.ts
  src/work-allocation/utils/work-allocation-utils.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2467

#2495 Feature/e UI 5387
  angular.json
  package.json
  src/app/containers/app/app.component.ts
  src/assets/images/document.png
  src/assets/img/sort/sort-arrows.svg
  src/assets/img/sort/sort-down-arrow.svg
  src/assets/img/sort/sort-up-arrow.svg
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2495

#2486 EUI-6826: Case File View - display of standard error message
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2486

#2526 Case link unlink integration bugs
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2526

#2512 Add supported role categories
  api/roleAccess/exclusionService.spec.ts
  api/roleAccess/index.ts
  api/test/pact/pact-tests/rolesAccess/roleAssignmentQuery.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2512

#2513 EUI-7160 Case file view hand icon for the folder clicking
  package.json
  src/assets/images/folder-open.png
  src/assets/images/folder.png
  src/assets/images/icon-search-black.svg
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2513

#2454 mc-release-6.10.0
  api/proxy.config.ts
  package.json
  proxy.config.json
  proxyTest.config.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  test/e2e/features/app/TCCreateCase.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2454

#2503 Feature/e UI 7166
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2503

#2511 Remaining filter changes
  package.json
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.spec.ts
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation/utils/work-allocation-utils.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2511

#2531 EUI-7219 Case link unlink case name missing
  api/proxy.config.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2531

#2536 EUI-7219 Case name missing unlink journey
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2536
