Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-09, with the labels that each got.

#2284 EUI-6320
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/models/hearingDetails.model.ts
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.spec.ts
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingDetails.model.ts
  src/hearings/store/reducers/hearing-request-to-compare.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2284

#2290 EUI-6691
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2290

#2295 EUI-6680/81 - linking unlinking bug fixes
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2295

#2191 EUI-6328-tab-redirection-issue
  package.json
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  test/e2e/features/app/mediaViewer.feature
  test/e2e/features/pageObjects/hearingRecordingsCase.js
  test/e2e/features/step_definitions/hearingRecordingsCase.steps.js
  test/e2e/features/step_definitions/workallocation/caseRolesAccess.steps.js
  test/ngIntegration/tests/features/workallocation2/availableTasks/availableTasks_manageLinks.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2191

#2298 EUI-6717
  api/hearings/data/hearingLists.mock.data.ts
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/models/hearingDaySchedule.model.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingDaySchedule.model.ts
  src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
  src/hearings/store/effects/hearing-list.effects.spec.ts
  src/hearings/store/reducers/hearing-list.reducer.spec.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2298

#2299 Revert "EUI-6328-tab-redirection-issue"
  package.json
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  test/e2e/features/app/mediaViewer.feature
  test/e2e/features/pageObjects/hearingRecordingsCase.js
  test/e2e/features/step_definitions/hearingRecordingsCase.steps.js
  test/e2e/features/step_definitions/workallocation/caseRolesAccess.steps.js
  test/ngIntegration/tests/features/workallocation2/availableTasks/availableTasks_manageLinks.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2299

#2294 EUI 6705 fee pay judge existing booking alignment
  src/booking/containers/booking-home/booking-home.component.html
  src/booking/containers/booking-home/booking-home.component.scss
  src/booking/containers/booking-home/booking-home.component.spec.ts
  src/booking/containers/booking-home/booking-home.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2294

#2301 added validation to session data on searchCases request
  api/searchCases/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2301

#2251 Update app.routes.ts
  src/app/app.routes.ts
  test/accessibility/config/pa11yProtractor.conf.js
  test/accessibility/tests/caseList.test.js
  test/accessibility/tests/footerPages.test.js
  test/accessibility/tests/workAllocation.test.js
  test/accessibility/tests/workAllocation/myWork.test.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2251

#2304 Feature/e UI 6452
  src/app/app.routes.ts
  src/staff-administrator/components/staff-search/staff-search.component.html
  src/staff-administrator/components/staff-search/staff-search.component.scss
  src/staff-administrator/components/staff-search/staff-search.component.spec.ts
  src/staff-administrator/components/staff-search/staff-search.component.ts
  src/staff-administrator/components/staff-user-list/staff-user-list.component.html
  src/staff-administrator/components/staff-user-list/staff-user-list.component.scss
  src/staff-administrator/components/staff-user-list/staff-user-list.component.spec.ts
  src/staff-administrator/components/staff-user-list/staff-user-list.component.ts
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.html
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.scss
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.spec.ts
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/staff-administrator.routes.ts
  src/staff-ref-data/containers/staff-ref-data-home/staff-ref-data-home.component.html
  src/staff-ref-data/containers/staff-ref-data-home/staff-ref-data-home.component.spec.ts
  src/staff-ref-data/containers/staff-ref-data-home/staff-ref-data-home.component.ts
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users-filters/staff-ref-data-users-filters.component.html
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users-filters/staff-ref-data-users-filters.component.scss
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users-filters/staff-ref-data-users-filters.component.spec.ts
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users-filters/staff-ref-data-users-filters.component.ts
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users-list/staff-ref-data-users-list.component.html
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users-list/staff-ref-data-users-list.component.spec.ts
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users-list/staff-ref-data-users-list.component.ts
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users.component.html
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users.component.scss
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users.component.spec.ts
  src/staff-ref-data/containers/staff-ref-data-users/staff-ref-data-users.component.ts
  src/staff-ref-data/staff-ref-data-feature.routes.ts
  src/staff-ref-data/staff-ref-data.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2304

#2297 updated roles for global search
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2297

#2312 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2312

#2313 EUI-6727 - Fix issue with bookable type
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  test/e2e/config/appTestConfig.js
  test/ngIntegration/tests/features/workAccessBookingUI/workAccess.feature
  test/ngIntegration/tests/stepDefinitions/workallocation/waCommon.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2313

#2311 EUI-6328-testing
  package.json
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  test/e2e/features/app/mediaViewer.feature
  test/e2e/features/pageObjects/hearingRecordingsCase.js
  test/e2e/features/step_definitions/hearingRecordingsCase.steps.js
  test/e2e/features/step_definitions/workallocation/caseRolesAccess.steps.js
  test/ngIntegration/tests/features/workallocation2/availableTasks/availableTasks_manageLinks.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2311

#2320 Feature/release4 wa4 update common lib
  package.json
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2320

#2317 EUI-6735
  package.json
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.spec.ts
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.ts
  src/hearings/converters/judge-exclusion.answer.converter.ts
  src/hearings/converters/judge-name.answer.converter.ts
  src/hearings/converters/judicial-members.answer.converter.ts
  src/hearings/converters/panel-exclusion.answer.converter.ts
  src/hearings/converters/panel-inclusion.answer.converter.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2317

#2319 EUI-6597
  api/common/mockService.ts
  api/staff-ref-data/index.ts
  api/staff-ref-data/routes.ts
  api/staff-ref-data/staff-ref-data.mock.ts
  package.json
  src/staff-administrator/components/staff-search/staff-search.component.html
  src/staff-administrator/components/staff-search/staff-search.component.spec.ts
  src/staff-administrator/components/staff-search/staff-search.component.ts
  src/staff-administrator/components/staff-user-list/staff-user-list.component.html
  src/staff-administrator/components/staff-user-list/staff-user-list.component.spec.ts
  src/staff-administrator/components/staff-user-list/staff-user-list.component.ts
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.html
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.spec.ts
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.spec.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
  src/staff-administrator/services/staff-data-filter.service.spec.ts
  src/staff-administrator/services/staff-data-filter.service.ts
  src/staff-administrator/staff-administrator.module.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2319

#2331 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2331

#2324 EUI-6587 - Remove hearing date changes
  api/workAllocation/index.ts
  api/workAllocation/interfaces/case.ts
  api/workAllocation/util.ts
  src/work-allocation/components/constants/config.constants.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  test/e2e/features/pageObjects/createCaseStartPage.js
  test/e2e/features/step_definitions/caseManager.steps.js
  test/e2e/features/step_definitions/workallocation/common.steps.js
  test/e2e/utils/request.js
  test/ngIntegration/tests/features/workallocation2/allWork/allwork.feature
  test/ngIntegration/tests/features/workallocation2/allWork/allwork_paginationSorting.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/allWorkCases.feature
  test/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks.feature
  test/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks_paginationSorting.feature
  test/ngIntegration/tests/features/workallocation2/myCases/myCases.feature
  test/ngIntegration/tests/features/workallocation2/myCases/myCases_pagination.feature
  test/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks.feature
  test/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks_paginationSorting.feature
  test/ngIntegration/tests/stepDefinitions/workallocation/wa2.steps.js
  test/nodeMock/nodeApp/reqResMapping.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2324

#2337 EUI-6812 Null value for parties
  src/hearings/converters/party-channels-answer.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2337

#2340 EUI-6812 Sonarcloud failures fix
  src/hearings/converters/party-channels-answer.converter.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2340

#2338 Hotfix/specific access fix
  api/specificAccessOrchastrator/index.spec.ts
  api/specificAccessOrchastrator/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2338

#2341 EUI-6812 Sonarcloud failures fix v2
  src/hearings/converters/party-channels-answer.converter.spec.ts
  src/hearings/converters/party-channels-answer.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2341

#2339 EUI-6401
  package.json
  src/staff-administrator/components/staff-user-list/staff-user-list.component.html
  src/staff-administrator/components/staff-user-list/staff-user-list.component.spec.ts
  src/staff-administrator/containers/staff-add-user/staff-add-user.component.html
  src/staff-administrator/containers/staff-add-user/staff-add-user.component.scss
  src/staff-administrator/containers/staff-add-user/staff-add-user.component.spec.ts
  src/staff-administrator/containers/staff-add-user/staff-add-user.component.ts
  src/staff-administrator/containers/staff-edit-user/staff-edit-user.component.html
  src/staff-administrator/containers/staff-edit-user/staff-edit-user.component.scss
  src/staff-administrator/containers/staff-edit-user/staff-edit-user.component.spec.ts
  src/staff-administrator/containers/staff-edit-user/staff-edit-user.component.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/staff-administrator.routes.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2339

#2343 EUI-6818 Set wa2 default for feature toggle service
  src/work-allocation/services/work-allocation-feature.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2343

#2345 Hotfix/specific access fix
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/specificAccessOrchastrator/index.ts
  api/workAllocation/index.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2345

#2348 Update app.routes.ts
  src/app/app.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2348

#2332 Tasks tab on assign to me and go to tasks fix
  api/workAllocation/constants/actions.ts
  src/work-allocation/components/case-name-field/case-name-field.component.spec.ts
  src/work-allocation/components/case-name-field/case-name-field.component.ts
  src/work-allocation/components/work-field/work-field.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2332

#2310 EUI-6695 Add service filter
  src/staff-administrator/components/staff-search/staff-search.component.spec.ts
  src/staff-administrator/components/staff-search/staff-search.component.ts
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.spec.ts
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2310

#2329 Feature/e UI 6780
  api/locations/index.ts
  src/booking/containers/booking-date/booking-date.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2329

#2349 Feature/e UI 6597
  api/staff-ref-data/mock-data/staff-ref-users-list.mock.data.ts
  api/staff-ref-data/staff-ref-data.mock.ts
  package.json
  src/staff-administrator/components/staff-search/staff-search.component.html
  src/staff-administrator/components/staff-search/staff-search.component.ts
  src/staff-administrator/components/staff-user-list/staff-user-list.component.html
  src/staff-administrator/containers/staff-edit-user/staff-edit-user.component.spec.ts
  src/staff-administrator/containers/staff-edit-user/staff-edit-user.component.ts
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2349

#2344 EUI-6405 - Display user details
  api/staff-ref-data/index.ts
  api/staff-ref-data/mock-data/staff-ref-users-list.mock.data.ts
  api/staff-ref-data/models/staff-data-user.model.ts
  api/staff-ref-data/routes.ts
  api/staff-ref-data/staff-ref-data.mock.ts
  src/staff-administrator/components/staff-search/staff-search.component.spec.ts
  src/staff-administrator/components/staff-search/staff-search.component.ts
  src/staff-administrator/components/staff-status/staff-status.component.html
  src/staff-administrator/components/staff-status/staff-status.component.scss
  src/staff-administrator/components/staff-status/staff-status.component.spec.ts
  src/staff-administrator/components/staff-status/staff-status.component.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.scss
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/components/staff-user-list/staff-user-list.component.html
  src/staff-administrator/components/staff-user-list/staff-user-list.component.spec.ts
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.spec.ts
  src/staff-administrator/containers/staff-user-details-container/staff-user-details-container.component.html
  src/staff-administrator/containers/staff-user-details-container/staff-user-details-container.component.scss
  src/staff-administrator/containers/staff-user-details-container/staff-user-details-container.component.spec.ts
  src/staff-administrator/containers/staff-user-details-container/staff-user-details-container.component.ts
  src/staff-administrator/models/staff-user.model.ts
  src/staff-administrator/resolvers/staff-user-details-resolver.service.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.spec.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/staff-administrator.routes.ts
  src/staff-administrator/test-data/staff-user-details.test.data.ts
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2344

#2335 private law config
  api/globalSearch/index.spec.ts
  api/locations/data/serviceCourtType.mapping.ts
  api/serviceRefData/index.spec.ts
  api/waSupportedJurisdictions/index.spec.ts
  config/default.json
  src/app/app.constants.ts
  src/app/components/routing/application-routing.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2335

#2357 EUI-6837-remove healthCheck call
  src/app/shared/shared.module.ts
  src/cases/case-feature.routes.ts
  src/hearings/hearings.routes.ts
  src/noc/noc.routes.ts
  src/role-access/role-access.routes.ts
  src/work-allocation-2/work-allocation-feature.routes.ts
  src/work-allocation/work-allocation-feature.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2357

#2358 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2358

#2354 Bug/e UI 6825
  api/workAllocation/locationController.ts
  api/workAllocation/locationService.ts
  src/booking/containers/booking-home/booking-home.component.ts
  src/work-allocation/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation/services/location-data.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2354
