Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-01, with the labels that each got.

#1585 Feature/EUI-4867 Judge screen
  api/hearings/data/reference.mock.data.ts
  package.json
  src/hearings/components/hearing-judge-name/hearing-judge-name.component.html
  src/hearings/components/hearing-judge-name/hearing-judge-name.component.scss
  src/hearings/components/hearing-judge-name/hearing-judge-name.component.spec.ts
  src/hearings/components/hearing-judge-name/hearing-judge-name.component.ts
  src/hearings/components/index.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.html
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1585

#1600 Task reassign state management
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment-choose-role/task-assignment-choose-role.component.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1600

#1557 EUI-4905 Enabling FT's on pipelines
  api/roleAccess/exclusionService.ts
  charts/xui-webapp/Chart.yaml
  package.json
  test/dataModels/nodeApp.js
  test/e2e/features/app/TCCreateCase.feature
  test/e2e/features/app/TCSearchCaseandCaseList.feature
  test/e2e/features/app/caseListSelection.feature
  test/e2e/features/app/exuiVsccdUI.feature
  test/e2e/features/app/searchCase.feature
  test/e2e/features/app/shareCase.feature
  test/e2e/features/app/timestamp.feature
  test/e2e/features/app/workAllocation/workallocation2.feature
  test/e2e/features/pageObjects/CaseListPage.js
  test/e2e/features/pageObjects/caseEditPage.js
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/pageObjects/common/application.js
  test/e2e/features/pageObjects/createCaseStartPage.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/hearingRecordingsCase.js
  test/e2e/features/pageObjects/searchPage.js
  test/e2e/features/pageObjects/workAllocation/taskListPage.js
  test/e2e/features/pageObjects/workAllocation/taskManagerPage.js
  test/e2e/features/pageObjects/workAllocation/waTable.js
  test/e2e/features/step_definitions/caseList.steps.js
  test/e2e/features/step_definitions/caseManager.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/navigationHeader.steps.js
  test/e2e/features/step_definitions/searchCase.steps.js
  test/e2e/features/step_definitions/testCaseType.steps.js
  test/e2e/support/browserLogs.js
  test/e2e/support/customWaits.js
  test/e2e/support/hooks.js
  test/e2e/support/reportLogger.js
  test/e2e/support/runtimeTestData.js
  test/e2e/utils/ccdApi.js
  test/integration/tests/ccd_endpoints.spec.ts
  test/integration/tests/config/config.ts
  test/integration/tests/nodeApp_endpoints.spec.ts
  test/integration/tests/utils/authUtil.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1557

#1605 final
  api/hearings/data/reference.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.scss
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/models/hearingDetails.model.ts
  src/hearings/models/partyDetails.model.ts
  src/hearings/store/reducers/hearing-conditions.reducer.spec.ts
  src/hearings/utils/validators.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1605

#1615 Add CVEs to known list
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1615

#1612 feature/EUI-4896-hearing-flags
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/models/partyFlags.model.ts
  api/hearings/models/serviceHearingValues.model.ts
  src/hearings/components/case-flags/case-flags.component.html
  src/hearings/components/case-flags/case-flags.component.scss
  src/hearings/components/case-flags/case-flags.component.spec.ts
  src/hearings/components/case-flags/case-flags.component.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.scss
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.ts
  src/hearings/components/index.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.html
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.scss
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/caseFlagGroup.model.ts
  src/hearings/models/caseFlagReference.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/models/partyFlags.model.ts
  src/hearings/resolvers/case-flags.resolver.spec.ts
  src/hearings/resolvers/case-flags.resolver.ts
  src/hearings/resolvers/ref-data-resolver.resolve.spec.ts
  src/hearings/resolvers/ref-data-resolver.resolve.ts
  src/hearings/services/case-flags-ref-data.service.spec.ts
  src/hearings/services/case-flags-ref-data.service.ts
  src/hearings/utils/page-flow.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1612

#1609 E UI 4686 request hearings hearing venue details
  api/hearings/models/hearings.enum.ts
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.scss
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.spec.ts
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.ts
  src/hearings/models/hearingLocation.model.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1609

#1624 E2E test step enhancements and updates
  test/e2e/documents/dummy1.pdf
  test/e2e/features/app/mediaViewer.feature
  test/e2e/features/pageObjects/CaseListPage.js
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/support/customWaits.js
  test/integration/tests/ccd_endpoints.spec.ts
  test/integration/tests/config/config.ts
  test/integration/tests/evidenceManager.spec.ts
  test/integration/tests/nodeApp_endpoints.spec.ts
  test/integration/tests/postcodeLookup.spec.ts
  test/integration/tests/prdApi.spec.ts
  test/integration/tests/workallocation/findPerson.spec.ts
  test/integration/tests/workallocation/release1.spec.ts
  test/integration/tests/workallocation/release2.spec.ts
  test/integration/tests/workallocation/release2Cases.spec.ts
  test/integration/tests/workallocation/release2Tasks.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1624

#1626 Making OWN same as EXECUTE
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  test/dataModels/workAllocation.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1626

#1566 EUI-4857 WA case category in my cases and all cases
  api/workAllocation2/interfaces/case.ts
  api/workAllocation2/interfaces/roleCaseData.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1566

#1634 CVE temp
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1634

#1625 tasks to url append
  src/work-allocation-2/components/task-name-field/task-name-field.component.spec.ts
  src/work-allocation-2/components/task-name-field/task-name-field.component.ts
  src/work-allocation-2/components/work-field/work-field.component.spec.ts
  test/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks.feature
  test/ngIntegration/tests/features/workallocation2/workFilter_unhappyPath.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1625

#1631 E UI 4947 flickering
  package.json
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.html
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.scss
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.spec.ts
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1631

#1607 EUI-4351 select view task cases
  api/accessManagement/data/booking.mock.data.ts
  src/booking/booking.routes.ts
  src/booking/containers/booking-home/booking-home.component.spec.ts
  src/booking/containers/booking-home/booking-home.component.ts
  src/booking/containers/booking-wrapper/booking-wrapper.component.ts
  src/booking/models/booking-process.interface.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.spec.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
  test/accessibility/tests/workAllocation/myWork.test.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1607

#1628 EUI-4100 Task check at start multiple tasks
  package.json
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/components/case-task/case-task.util.spec.ts
  src/cases/components/case-task/case-task.util.ts
  test/e2e/features/step_definitions/workallocation/caseDetailsTasksTab.steps.js
  test/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/tasksTab.feature
  test/ngIntegration/tests/stepDefinitions/mockCase.steps.js
  test/nodeMock/ccd/ccdApi.js
  test/nodeMock/ccd/reqResMapping.js
  test/nodeMock/workAllocation/mockData.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1628

#1620 E UI 4952 refactoring search location component
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.spec.ts
  yarn-audit-known-issues
  yarn-audit-known-issuesyarn
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1620

#1633 Feature/e UI 4835 b
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-check-answers/hearing-check-answers.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.html
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-stage/hearing-stage.component.spec.ts
  src/hearings/containers/request-hearing/hearing-stage/hearing-stage.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.spec.ts
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.ts
  src/hearings/containers/request-hearing/hearing-welsh/hearing-welsh.component.spec.ts
  src/hearings/containers/request-hearing/hearing-welsh/hearing-welsh.component.ts
  src/hearings/containers/request-hearing/hearing.store.state.test.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.spec.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1633

#1644 MC CVE temp1
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1644

#1606 feature-hearing toolkit integrated
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1606

#1650 Feature/e UI 5116 unit tests
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/containers/case-details/case-details.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.spec.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.spec.ts
  src/role-access/containers/remove-role/remove-role.component.spec.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.spec.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation-2/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation-2/containers/task-home/task-home.component.spec.ts
  src/work-allocation/containers/info-message-container/info-message-container.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  test/e2e/features/step_definitions/loginLogout.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1650

#1570 Hotfix/paydowngrade
  package.json
  src/refunds/refunds/refunds.component.html
  test/e2e/features/app/mediaViewer.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1570

#1663 Revert "Hotfix/paydowngrade"
  package.json
  src/refunds/refunds/refunds.component.html
  test/e2e/features/app/mediaViewer.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1663

#1648 media viewer version upgrade
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1648

#1665 bug/EUI-5048
  package.json
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.html
  src/hearings/containers/request-hearing/request-hearing.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  test/accessibility/tests/caseDetailsPage.test.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1665

#1671 feature/EUI-4787
  api/hearings/models/hearingStatusMappings.ts
  src/hearings/pipes/hearings-badge.pipe.spec.ts
  src/hearings/pipes/hearings-badge.pipe.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1671

#1656 E UI 4724 cancel hearing functionality story
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/hearing.mock.ts
  api/hearings/index.ts
  api/hearings/models/hearings.enum.ts
  api/hearings/routes.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/hearings/containers/cancel-hearing/cancel-hearing.component.html
  src/hearings/containers/cancel-hearing/cancel-hearing.component.spec.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing.store.state.test.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.spec.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearingCancelRequestBody.ts
  src/hearings/models/hearingDetails.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
  src/hearings/store/actions/hearing-request.action.ts
  src/hearings/store/effects/hearing-request.effects.spec.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1656

#1655 EUI-4715 - Hearing timing
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/utils/validators.utils.spec.ts
  src/hearings/utils/validators.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1655

#1664 EUI-4794 hearing instructions
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.html
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.spec.ts
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/models/hearings.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1664

#1642 panel selection
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.html
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.scss
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.html
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.html
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/models/hearings.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1642

#1598 Feature/WA Task event completion webapp changes
  api/auth/index.ts
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/index.ts
  api/workAllocation2/routes.ts
  package.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/components/case-task/case-task.util.spec.ts
  src/cases/components/case-task/case-task.util.ts
  src/work-allocation/services/work-allocation-task.service.ts
  test/e2e/features/step_definitions/workallocation/caseDetailsTasksTab.steps.js
  test/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/tasksTab.feature
  test/ngIntegration/tests/stepDefinitions/mockCase.steps.js
  test/nodeMock/ccd/ccdApi.js
  test/nodeMock/ccd/reqResMapping.js
  test/nodeMock/workAllocation/mockData.js
  tsconfig.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1598

#1676 Use getTasksByCaseId
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1676

#1680 remove validation for same role to be added multiple times
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1680

#1698 XUI MC CVEs temp fix
  api/user/index.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1698
