Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-04, with the labels that each got.

#1922 EUI-5583 View details waiting to be listed for JOH
  api/hearings/data/hearingLists.mock.data.ts
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/models/hearingStatusMappings.ts
  api/hearings/models/hearings.enum.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.html
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.ts
  src/hearings/containers/view-hearing/index.ts
  src/hearings/converters/need-judge.answer.converter.ts
  src/hearings/converters/participant-attendence.answer.converter.ts
  src/hearings/converters/party-channels-answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/templates/hearing-view-only-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1922

#1929 Feature/EUI 5079 - venue amended flag
  src/hearings/converters/venue.amended.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1929

#1923 search judicial
  api/hearings/data/hearing-actuals.mock.data.ts
  api/prd/judicial/index.ts
  api/prd/judicial/judicial.mock.ts
  api/prd/judicial/routes.ts
  package.json
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
  src/hearings/components/hearing-judge-name/hearing-judge-name.component.html
  src/hearings/components/hearing-judge-name/hearing-judge-name.component.scss
  src/hearings/components/hearing-judge-name/hearing-judge-name.component.spec.ts
  src/hearings/components/hearing-judge-name/hearing-judge-name.component.ts
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.html
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.scss
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.spec.ts
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.ts
  src/hearings/components/index.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.html
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.html
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/models/person.model.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1923

#1921 feature/EUI-4447
  src/app/models/user-details.model.ts
  src/app/services/role-category-mapping/role-category-mapping.service.spec.ts
  src/app/services/role-category-mapping/role-category-mapping.service.stub.ts
  src/app/services/role-category-mapping/role-category-mapping.service.ts
  src/cases/containers/case-hearings/case-hearings.component.html
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/guards/hearings-edit-guard.spec.ts
  src/hearings/guards/hearings-edit-guard.ts
  src/hearings/guards/hearings-guard.spec.ts
  src/hearings/guards/hearings-view-guard.spec.ts
  src/hearings/guards/hearings-view-guard.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1921

#1927 story/EUI-5586
  api/hearings/data/hearing-actuals.mock.data.ts
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/hearing.mock.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
  src/hearings/containers/view-hearing/hearing-view-actual-summary/hearing-view-actual-summary.component.html
  src/hearings/containers/view-hearing/hearing-view-actual-summary/hearing-view-actual-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-view-actual-summary/hearing-view-actual-summary.component.ts
  src/hearings/containers/view-hearing/index.ts
  src/hearings/hearings.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1927

#1930 EUI-5205 Linked hearings journey display of linked page
  api/hearings/data/serviceHearingValues.mock.data.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.html
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.spec.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
  src/hearings/containers/request-hearing/index.ts
  src/hearings/converters/linked-hearings.amended.converter.spec.ts
  src/hearings/converters/linked-hearings.amended.converter.ts
  src/hearings/converters/linked-hearings.answer.converter.spec.ts
  src/hearings/converters/linked-hearings.answer.converter.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/pipes/is-amended.pipe.spec.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
  src/hearings/templates/hearing-view-only-summary.template.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1930

#1938 introduce clicked
  package.json
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1938

#1939 CVEs temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1939

#1944 Feature/e UI 5605 specific access request more info
  src/role-access/containers/specific-access/specific-access-denied/specific-access-denied.component.html
  src/role-access/containers/specific-access/specific-access-denied/specific-access-denied.component.spec.ts
  src/role-access/containers/specific-access/specific-access-denied/specific-access-denied.component.ts
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.spec.ts
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.ts
  src/role-access/containers/specific-access/specific-access-information/specific-access-information.component.html
  src/role-access/containers/specific-access/specific-access-information/specific-access-information.component.spec.ts
  src/role-access/containers/specific-access/specific-access-information/specific-access-information.component.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.html
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.spec.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
  src/role-access/models/displayed-access-reason.interface.ts
  src/role-access/models/enums/access-reason.ts
  src/role-access/models/enums/index.ts
  src/role-access/models/index.ts
  src/role-access/models/request-access-details.interface.ts
  src/role-access/models/specific-access-form-data.interface.ts
  src/role-access/models/specific-access-state-data.interface.ts
  src/role-access/role-access.routes.ts
  src/role-access/services/duration-helper.service.spec.ts
  src/role-access/services/duration-helper.service.ts
  src/role-access/store/actions/specific-access.action.ts
  src/role-access/store/reducers/specific-access.reducer.spec.ts
  src/role-access/store/reducers/specific-access.reducer.ts
  src/role-access/store/selectors/specific-access.selectors.ts
  src/work-allocation-2/containers/my-cases/my-cases.component.spec.ts
  test/ngIntegration/tests/stepDefinitions/mockCase.steps.js
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1944

#1943 Feature/e UI 5603 add ccd tag rearrange code
  package.json
  src/role-access/constants/specific-access-page-visibility-states.ts
  src/role-access/containers/specific-access/specific-access-approved/specific-access-approved.component.ts
  src/role-access/containers/specific-access/specific-access-denied/specific-access-denied.component.html
  src/role-access/containers/specific-access/specific-access-denied/specific-access-denied.component.spec.ts
  src/role-access/containers/specific-access/specific-access-denied/specific-access-denied.component.ts
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.spec.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1943

#1823 mc-release-4.10.0
  package.json
  src/style/app.scss
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1823

#1953 EUI-5650-private-law-production-onboarding
  config/default.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1953

#1957 CVEs temp fix
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1957

#1761 EUI-4860-Media Viewer: Toolbar disappearing
  src/index.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1761

#1936 EUI:5633: Replaced HTTP userInfo call with session storage which retr…
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  tslint.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1936

#1963 CVEs temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1963

#1958 Feature/e UI 5659 spinner allocation
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.html
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.spec.ts
  src/role-access/containers/add-exclusion/add-exclusion-home/add-exclusion-home.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.html
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.html
  src/role-access/containers/delete-exclusion/delete-exclusion.component.spec.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.ts
  src/role-access/containers/remove-role/remove-role.component.html
  src/role-access/containers/remove-role/remove-role.component.spec.ts
  src/role-access/containers/remove-role/remove-role.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1958

#1965 feature/EUI-5645
  api/auth/index.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/converters/judge-exclusion.answer.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1965

#1967 amend flag bugfix on priority hearings page
  src/hearings/converters/hearing-specific-date.amended.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1967

#1962 EUI-5406 Hearing actuals styling issues
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals.component.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1962

#1971 EUI-4744 fail scenarios implimented
  api/accessManagement/data/booking.mock.data.ts
  api/accessManagement/index.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/booking/containers/booking-home/booking-home.component.spec.ts
  src/booking/containers/booking-home/booking-home.component.ts
  src/booking/containers/index.ts
  src/booking/containers/utils/booking-system-error/booking-system-error.component.html
  src/booking/containers/utils/booking-system-error/booking-system-error.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1971

#1977 CVE tmp fix
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1977

#1978 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1978

#1979 CCD-UI-ToolKit change event if it does not have Fields or Pages then we directly take them to the submit event
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1979
