Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-05, with the labels that each got.

#1955 EUI-4284-package-update
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1955

#1992 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1992

#1994 Update CVEs list
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1994

#1999 rectified some test issue
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1999

#1961 story/EUI-5200
  api/hearings/data/linkHearings.mock.data.ts
  api/hearings/hearing.mock.ts
  api/hearings/models/linkHearings.model.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/components/linked-hearings-case-title/linked-hearings-case-title.component.html
  src/hearings/components/linked-hearings-case-title/linked-hearings-case-title.component.spec.ts
  src/hearings/components/linked-hearings-case-title/linked-hearings-case-title.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.html
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.scss
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.spec.ts
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-final-confirmation/linked-hearings-final-confirmation.component.spec.ts
  src/hearings/containers/linked-hearings/linked-hearings-final-confirmation/linked-hearings-final-confirmation.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.html
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.spec.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.html
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.scss
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.spec.ts
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.ts
  src/hearings/containers/linked-hearings/linked-hearings.component.html
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/models/linkHearings.model.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
  src/hearings/store/actions/hearing-links.action.spec.ts
  src/hearings/store/actions/hearing-links.action.ts
  src/hearings/store/effects/hearing-links.effects.spec.ts
  src/hearings/store/effects/hearing-links.effects.ts
  src/hearings/store/reducers/hearing-links.reducer.spec.ts
  src/hearings/store/reducers/hearing-links.reducer.ts
  src/hearings/utils/validators.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1961

#1995 EUI-5729 initial commit
  api/common/crudService.ts
  api/proxy.config.ts
  api/routes.ts
  api/specificAccessOrchastrator/index.spec.ts
  api/specificAccessOrchastrator/index.ts
  api/specificAccessOrchastrator/routes.ts
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1995

#1983 Feature/actual integrate
  api/hearings/data/hearing-actuals.mock.data.ts
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/data/linkHearings.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/hearing.mock.ts
  api/hearings/models/hearingActualsMainModel.ts
  api/hearings/models/hearingDetails.model.ts
  api/hearings/models/serviceHearingValues.model.ts
  api/hearings/routes.ts
  api/prd/lov/data/lov.mock.data.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals.component.ts
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.html
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.html
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.ts
  src/hearings/containers/request-hearing/hearing-change-reason/hearing-change-reason.component.spec.ts
  src/hearings/containers/request-hearing/hearing-change-reason/hearing-change-reason.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.html
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.spec.ts
  src/hearings/containers/view-hearing/hearing-request-failed-summary/hearing-request-failed-summary.component.html
  src/hearings/converters/judge-types.amended.converter.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingActualsMainModel.ts
  src/hearings/models/hearingDetails.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/models/serviceHearingValues.model.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
  src/hearings/store/actions/hearing-actuals.action.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-request-to-compare.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1983

#2005 Feature/e UI 5844 challenged access
  api/challengedAccess/index.ts
  api/challengedAccess/routes.ts
  api/routes.ts
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2005

#2009 EUI-5613 Linked cases setup
  package.json
  src/assets/getCase.json
  src/assets/getCaseReasons.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2009

#2013 story/EUI-5681 case check
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2013

#1972 Initial specific access role changes
  api/accessManagement/index.ts
  api/accessManagement/routes.ts
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/index.ts
  api/roleAccess/models/allocate-role-state-data.interface.ts
  api/roleAccess/routes.ts
  api/routes.ts
  api/workAllocation2/index.ts
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.spec.ts
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts
  src/role-access/models/specific-access-state-data.interface.ts
  src/role-access/services/allocate-role.service.spec.ts
  src/role-access/services/allocate-role.service.ts
  src/role-access/store/actions/specific-access.action.ts
  src/role-access/store/effects/index.ts
  src/role-access/store/effects/specific-access.effects.spec.ts
  src/role-access/store/effects/specific-access.effects.ts
  src/role-access/store/reducers/specific-access.reducer.spec.ts
  src/role-access/store/reducers/specific-access.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1972

#2017 FT fix env var read issue
  test/e2e/config/appTestConfig.js
  test/e2e/features/step_definitions/workallocation/caseDetailsTasksTab.steps.js
  test/integration/tests/config/config.ts
  test/ngIntegration/config/protractor-cucumber.conf.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2017

#2006 EUI-5859-put-actual
  api/common/crudService.ts
  api/hearings/data/hearing-actuals.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/hmc.index.ts
  api/hearings/models/hearingActualsMainModel.ts
  api/hearings/services.index.ts
  api/prd/lov/data/lov.mock.data.ts
  api/prd/lov/index.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/containers/request-hearing/hearing-change-reason/hearing-change-reason.component.html
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingActualsMainModel.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
  src/hearings/store/actions/hearing-links.action.ts
  src/hearings/store/effects/hearing-actuals.effects.ts
  src/hearings/store/effects/hearing-links.effects.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2006

#2015 EUI-5617 Manage case link event
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2015

#2018 story/EUI-5691
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2018

#2023 EUI-5619 Unlink case list display
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2023

#2000 Basic test for probate refund pages.
  api/test/pact/pact-tests/rdJudicial/getJudicialUsers.spec.ts
  test/e2e/config/conf.js
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/probateRefunds.feature
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/refundsPage.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/refunds.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2000

#2021 EUI-5701-case-cat
  api/hearings/data/hearing-actuals.mock.data.ts
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/models/caseCategory.model.ts
  api/prd/lov/data/lov.mock.data.ts
  api/prd/lov/index.ts
  config/default.json
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/converters/additional-facilities.answer.converter.ts
  src/hearings/converters/hearing-priority.answer.converter.ts
  src/hearings/converters/stage.answer.converter.ts
  src/hearings/converters/type-from-request.answer.converter.spec.ts
  src/hearings/converters/type-from-request.answer.converter.ts
  src/hearings/converters/type.answer.converter.spec.ts
  src/hearings/converters/type.answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/caseCategory.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/resolvers/case-types.resolver.spec.ts
  src/hearings/resolvers/case-types.resolver.ts
  src/hearings/resolvers/ref-data-resolver.resolve.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
  src/hearings/utils/case-types.utils.spec.ts
  src/hearings/utils/case-types.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2021

#2032 EUI-5626 Unlink cases check your answers page
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2032

#2036 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2036

#2041 EUI-5732 unlink case page exceptions
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2041

#2030 EUI-5903 package update
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2030

#2046 EUI-5757 Manage case links exception page
  package.json
  src/assets/getCaseNoLinkedCases.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2046

#2042 EUI-5940-case-share-issue
  api/caseshare/real-api.ts
  api/test/pact/pact-tests/rdJudicial/getJudicialUsers.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2042
