Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-07, with the labels that each got.

#2119 bug/EUI-6230
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2119

#2128 Functionality change to add role check
  src/app/app-utils.ts
  src/app/app.constants.ts
  src/cases/cases.module.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.html
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/work-allocation-2/work-allocation2.module.ts
  test/e2e/features/app/TCCreateCase.feature
  test/e2e/features/app/TCSearchCaseandCaseList.feature
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/workAllocation/r1/workAllocation.feature
  test/e2e/features/pageObjects/common/CaseManager.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/utils/request.js
  test/ngIntegration/tests/features/navigationHeader.feature
  test/ngIntegration/tests/features/workAllocation/taskActions.feature
  test/ngIntegration/tests/features/workAllocation/taskListAvailableTasks.feature
  test/ngIntegration/tests/features/workAllocation/taskListMyTasks.feature
  test/ngIntegration/tests/features/workAllocation/taskManager.feature
  test/ngIntegration/util/browserUtil.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2128

#2130 EUI-5734 Multiday request hearing display
  charts/xui-webapp/Chart.yaml
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.html
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearings.enum.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2130

#2134 EUI-6124 all work filtering label
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2134

#2126 EUI-6011 nexh hearing column shorting
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/case.ts
  api/workAllocation2/util.ts
  src/work-allocation-2/components/constants/config.constants.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2126

#2137 EUI-5764 Multiday check your answers page
  src/hearings/converters/hearing-length.answer.converter.spec.ts
  src/hearings/converters/hearing-length.answer.converter.ts
  src/hearings/converters/hearing-specific-date.answer.converter.spec.ts
  src/hearings/converters/hearing-specific-date.answer.converter.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2137

#2142 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2142

#2145 EUI-6315
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2145

#2117 Linked hearing int
  api/hearings/hmc.index.ts
  api/hearings/models/linkHearings.model.ts
  api/hearings/routes.ts
  api/hearings/services.index.ts
  src/hearings/components/error-page/error-page.component.html
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.html
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.spec.ts
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-final-confirmation/linked-hearings-final-confirmation.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.html
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.spec.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.html
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.scss
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.spec.ts
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.ts
  src/hearings/containers/linked-hearings/linked-hearings.component.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.html
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearingLinksStateData.model.ts
  src/hearings/models/linkHearings.model.ts
  src/hearings/resolvers/linked-case-resolver.resolve.spec.ts
  src/hearings/resolvers/linked-case-resolver.resolve.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
  src/hearings/store/actions/hearing-links.action.ts
  src/hearings/store/effects/hearing-links.effects.spec.ts
  src/hearings/store/effects/hearing-links.effects.ts
  src/hearings/store/reducers/hearing-links.reducer.spec.ts
  src/hearings/store/reducers/hearing-links.reducer.ts
  src/hearings/store/selectors/hearing-links.selectors.ts
  src/hearings/utils/validators.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2117

#2147 fix to not show dateRangeEnd when it's undefined
  src/hearings/converters/hearing-specific-date.answer.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2147

#2143 EUI-6198: Case Flags table styling changes
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2143

#2150 bug/EUI-6278
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/converters/hearing-specific-date.answer.converter.spec.ts
  src/hearings/converters/hearing-specific-date.answer.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2150

#2152 EUI-5752 Hearing length exceptions
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/utils/validators.utils.spec.ts
  src/hearings/utils/validators.utils.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2152

#2155 EUI-5408 EUI-5655 EUI-5667
  api/hearings/data/linkHearings.mock.data.ts
  src/hearings/components/multi-level-selector/multi-level-selector.component.html
  src/hearings/containers/request-hearing/hearing-change-reasons/hearing-change-reasons.component.html
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.html
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2155

#2078 Manage Cases release 6.6.0
  package.json
  src/app/components/header/header.component.html
  src/app/components/header/header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/phase-banner/phase-banner.component.html
  src/app/components/phase-banner/phase-banner.component.spec.ts
  src/style/app.scss
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2078

#2157 Bug/e UI 5589 error
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2157

#2161 EUI-6352
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/resolvers/ref-data-resolver.resolve.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/effects/hearing-values.effects.ts
  src/hearings/store/reducers/hearing-values.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2161

#2160 story/EUI-5987 paper hearings
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2160

#2158 Bug fixes
  src/hearings/components/linked-hearings-case-title/linked-hearings-case-title.component.html
  src/hearings/components/linked-hearings-case-title/linked-hearings-case-title.component.spec.ts
  src/hearings/components/linked-hearings-case-title/linked-hearings-case-title.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.html
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.html
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.spec.ts
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.ts
  src/hearings/models/hearings.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2158

#2162 EUI-6289 role back implimented
  api/roleAccess/index.ts
  api/roleAccess/routes.ts
  api/workAllocation2/index.ts
  src/role-access/services/allocate-role.service.spec.ts
  src/role-access/services/allocate-role.service.ts
  src/work-allocation-2/containers/task-home/task-home.component.ts
  src/work-allocation-2/containers/work-case-list/work-case-list.component.html
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2162

#2168 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2168

#2167 Bugfix/e UI 6067
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2167

#2177 story/EUI-6018
  src/hearings/converters/is-paper-hearing.answer.converter.spec.ts
  src/hearings/converters/is-paper-hearing.answer.converter.ts
  src/hearings/converters/paper-hearing.hidden.converter.spec.ts
  src/hearings/converters/paper-hearing.hidden.converter.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/pipes/show-hide.pipe.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2177

#2178 Upgrade node basechart
  charts/xui-webapp/Chart.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2178

#2179 EUI-6291 names appearing under task fix
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2179

#2165 EUI-5945 | multiday - design a page to display multiday actual hearings.
  api/hearings/data/hearing-actuals.mock.data.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.scss
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/utils/actual-hearings.utils.spec.ts
  src/hearings/utils/actual-hearings.utils.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2165

#2181 story/EUI-6034 paper hearing
  src/hearings/converters/is-paper-hearing.amended.converter.spec.ts
  src/hearings/converters/is-paper-hearing.amended.converter.ts
  src/hearings/pipes/is-amended.pipe.spec.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2181

#2183 EUI-5979
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2183

#2148 EUI-6286-message not appearing
  package.json
  src/cases/store/effects/case-create.effects.ts
  test/ngIntegration/tests/features/workAccessBookingUI/featureToggle-guard.feature
  test/ngIntegration/tests/features/workallocation2/allWork/allWork_filters.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/Cases_caseActionWorkflow.feature
  test/ngIntegration/tests/features/workallocation2/rolesAccess/allocateRole_Judiciary.feature
  test/ngIntegration/tests/features/workallocation2/rolesAccess/allocateRole_Judiciary_changeLink.feature
  test/ngIntegration/tests/features/workallocation2/rolesAccess/allocateRole_LegalOps.feature
  test/ngIntegration/tests/features/workallocation2/rolesAccess/manageLinkActions.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2148

#2190 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2190

#2192 show paper hearing status & ngIf for attendence if paperHearing
  src/hearings/components/listing-information-summary/listing-information-summary.component.html
  src/hearings/components/listing-information-summary/listing-information-summary.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2192

#2173 EUI-6291 full name implimantation
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2173

#2195 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2195

#2186 Feature/e UI 5971
  src/cases/store/actions/organisations-list.action.spec.ts
  src/hearings/components/hearing-actual-summary-single-day/hearing-actual-summary-single-day.component.html
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.scss
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.scss
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/utils/actual-hearings.utils.spec.ts
  src/hearings/utils/actual-hearings.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2186

#2200 story/EUI-6484 added if condition
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2200
