Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-02, with the labels that each got.

#1683 Feature/e UI 4651 location search filter in tasks tab
  api/workAllocation2/index.ts
  package.json
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.scss
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.spec.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.scss
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.html
  src/work-allocation-2/containers/all-work-case/all-work-case.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.html
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1683

#1695 Feature/refunds perf test
  package.json
  src/refunds/refunds/refunds.component.html
  test/e2e/features/app/mediaViewer.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1695

#1699 applied visual bug changes
  api/hearings/data/reference.mock.data.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1699

#1700 adding queryParams service as Jurisdiction
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/tests/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1700

#1703 Bug/finalise integration locations
  api/locations/data/location.mock.data.ts
  api/locations/data/locationType.enum.ts
  api/locations/index.ts
  api/locations/location.mock.ts
  api/locations/models/location.model.ts
  package.json
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.spec.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  test/integration/tests/workallocation/locations.spec.ts
  test/nodeMock/workAllocation/mockData.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1703

#1704 Feature/e UI 5212 textarea pw
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1704

#1685 E UI 5037 display tech tick retrieve data create
  api/hearings/data/hearingResponse.mock.data.ts
  api/hearings/hearing.mock.ts
  api/hearings/index.ts
  api/hearings/models/caseCategory.model.ts
  api/hearings/models/caseDetails.model.ts
  api/hearings/models/hearingDetails.model.ts
  api/hearings/models/hearingResponse.model.ts
  api/hearings/models/hearingResponseMain.model.ts
  api/hearings/models/panelPreference.model.ts
  api/hearings/models/panelRequirements.model.ts
  api/hearings/models/requestDetails.model.ts
  api/hearings/routes.ts
  api/user/index.spec.ts
  src/hearings/models/hearingResponse.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1685

#1688 Enable Fortify on nightly
  Jenkinsfile_nightly
  package.json
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1688

#1705 find person bug fix
  api/workAllocation2/personService.ts
  package.json
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  test/e2e/features/step_definitions/workallocation/allocateRoles.steps.js
  test/e2e/support/hooks.js
  test/nodeMock/workAllocation/mockData.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1705

#1709 EUI-5068-case-flags
  api/hearings/data/reference.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  sonar-project.properties
  src/hearings/components/case-flags/case-flags.component.spec.ts
  src/hearings/components/case-flags/case-flags.component.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.spec.ts
  src/hearings/components/hearing-summary/hearing-summary.component.spec.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-stage/hearing-stage.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.spec.ts
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-welsh/hearing-welsh.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.spec.ts
  src/hearings/converters/case-name.converter.spec.ts
  src/hearings/converters/default.converter.spec.ts
  src/hearings/converters/type.converter.spec.ts
  src/hearings/hearing.store.state.test.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/store/effects/hearing-request.effects.spec.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1709

#1652 EUI-4766: Content changes as per prescribed wording
  src/noc/constants/nocErrorMap.enum.ts
  src/noc/containers/noc-affirmation/noc-affirmation.component.html
  src/noc/containers/noc-case-ref/noc-case-ref.component.html
  src/noc/containers/noc-case-ref/noc-case-ref.component.ts
  src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.html
  src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.ts
  src/noc/containers/noc-check-your-answers/noc-check-your-answers.component.ts
  src/noc/containers/noc-errors/noc-error.component.html
  src/noc/containers/noc-field/date/noc-date-field.component.ts
  src/noc/containers/noc-field/datetime/noc-datetime-field.component.ts
  src/noc/containers/noc-field/noc-field.component.ts
  src/noc/containers/noc-field/time/noc-time-field.component.ts
  src/noc/containers/noc-field/yes-no/noc-yes-no-field.component.ts
  src/noc/containers/noc-field/yes-no/yes-no.service.ts
  src/noc/containers/noc-navigation/noc-navigation.component.spec.ts
  src/noc/containers/noc-navigation/noc-navigation.component.ts
  src/noc/containers/noc-q-and-a/noc-q-and-a.component.html
  src/noc/containers/noc-submit-success/noc-submit-success.component.html
  src/noc/containers/noc-submit-success/noc-submit-success.component.ts
  src/noc/noc.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1652

#1662 available tasks query changes
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
  src/work-allocation-2/models/dtos/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1662

#1702 Update case-manager-filter.component.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1702

#1714 E UI 4878 hearing generic selection
  api/hearings/data/reference.mock.data.ts
  api/hearings/models/refData.model.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.ts
  src/hearings/components/index.ts
  src/hearings/components/multi-level-selector/multi-level-selector.component.html
  src/hearings/components/multi-level-selector/multi-level-selector.component.scss
  src/hearings/components/multi-level-selector/multi-level-selector.component.spec.ts
  src/hearings/components/multi-level-selector/multi-level-selector.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.html
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/models/refData.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1714

#1672 Ensuring task type/role_category is used
  api/workAllocation2/index.ts
  src/role-access/models/allocate-role.enum.ts
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/utils/work-allocation-utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1672

#1727 Eui 5253 CVE fix temp
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1727

#1716 chose role not selecteed by default
  src/role-access/components/choose-radio-option/choose-radio-option.component.html
  src/role-access/components/choose-radio-option/choose-radio-option.component.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
  src/role-access/store/reducers/exclusion.reducer.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1716

#1721 throw error if invalid Role category is sent
  api/workAllocation2/constants/task-roles.mock.data.ts
  src/work-allocation-2/utils/work-allocation-utils.spec.ts
  src/work-allocation-2/utils/work-allocation-utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1721

#1722 display judicial user
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1722

#1718 Set Assignee Name from caseworkers
  src/work-allocation-2/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1718

#1725 Feature/e UI 5009 additional facilities
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/converters/additional-facilities.converter.spec.ts
  src/hearings/converters/additional-facilities.converter.ts
  src/hearings/converters/additional-security.converter.spec.ts
  src/hearings/converters/additional-security.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/resolvers/additional-facilities.resolver.spec.ts
  src/hearings/resolvers/additional-facilities.resolver.ts
  src/hearings/resolvers/ref-data-resolver.resolve.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1725

#1707 feature/hearings-4-9-0-rc1
  README.md
  api/lib/error.handler.ts
  api/lib/log4jui.ts
  api/lib/middleware/proxy.ts
  api/organisations/index.ts
  api/searchCases/index.ts
  api/user/index.spec.ts
  api/user/index.ts
  api/workAllocation2/util.ts
  charts/xui-webapp/values.preview.template.yaml
  package.json
  test/e2e/config/conf.js
  test/integration/tests/config/config.ts
  test/integration/tests/workallocation/release1.spec.ts
  tsconfig.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1707

#1737 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1737

#1733 Change the Pagination url
  api/workAllocation2/index.spec.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1733

#1744 Eui 5279 CVE fix temp
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1744

#1742 422 error giving message
  src/role-access/components/index.ts
  src/role-access/components/user-not-assignable/user-not-assignable.component.html
  src/role-access/components/user-not-assignable/user-not-assignable.component.ts
  src/role-access/models/enums/redirect-urls.ts
  src/role-access/role-access.routes.ts
  src/role-access/store/effects/allocate-role.effects.spec.ts
  src/role-access/store/effects/allocate-role.effects.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1742

#1746 Update case-manager-filter.component.ts
  src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1746

#1732 Feature/e UI 4984 anchor back forward
  src/hearings/components/hearing-summary/hearing-summary.component.html
  src/hearings/components/hearing-summary/hearing-summary.component.spec.ts
  src/hearings/components/hearing-summary/hearing-summary.component.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/converters/case-number.answer.converter.spec.ts
  src/hearings/converters/case-number.answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/answer.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/models/section.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/store/effects/hearing-request.effects.spec.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1732

#1750 On Change button should pass the Service
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1750

#1738 added converter for additional instructions
  src/hearings/converters/additional-instructions.answer.converter.spec.ts
  src/hearings/converters/additional-instructions.answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1738

#1745 Bug/e UI 5277 case name
  api/workAllocation2/interfaces/case.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1745

#1751 Fixing issues and adding tests
  src/work-allocation-2/containers/all-work-task/all-work-task.component.html
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.html
  src/work-allocation-2/containers/my-tasks/my-tasks.component.html
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.html
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/task-list/task-list.component.scss
  src/work-allocation-2/containers/task-list/task-list.component.spec.ts
  src/work-allocation-2/containers/task-list/task-list.component.ts
  src/work-allocation-2/models/tasks/index.ts
  src/work-allocation-2/models/tasks/task-field-config.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1751

#1756 feature/EUI-5259-workaround
  api/workAllocation2/constants/mock.data.ts
  api/workAllocation2/interfaces/person.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/models/person.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1756

#1739 Feature/e UI 5012 request hearing page flow functional and check your answer page connector
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/converters/answer.converter.ts
  src/hearings/converters/number-of-attendances-answer.converter.ts
  src/hearings/converters/party-channels-answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/resolvers/party-channels-resolver.service.spec.ts
  src/hearings/resolvers/party-channels-resolver.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1739

#1728 E UI 4883 request hearing panel hearing checkboxes
  src/hearings/components/multi-level-selector/multi-level-selector.component.html
  src/hearings/components/multi-level-selector/multi-level-selector.component.spec.ts
  src/hearings/components/multi-level-selector/multi-level-selector.component.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.html
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/models/hearings.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1728

#1752 Feature/e UI 5014
  api/hearings/data/hearingResponse.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.html
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/converters/hearing-length.answer.converter.spec.ts
  src/hearings/converters/hearing-length.answer.converter.ts
  src/hearings/converters/hearing-priority.answer.converter.spec.ts
  src/hearings/converters/hearing-priority.answer.converter.ts
  src/hearings/converters/hearing-specific-date.answer.converter.spec.ts
  src/hearings/converters/hearing-specific-date.answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1752

#1765 media view test step update
  charts/xui-webapp/Chart.yaml
  test/e2e/features/pageObjects/hearingRecordingsCase.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1765

#1755 bug/EUI-4936 calculated business days between two days
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/utils/validators.utils.spec.ts
  src/hearings/utils/validators.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1755

#1769 EUI-5245 Create mock API for put hearing actuals
  api/hearings/hearing.mock.ts
  api/hearings/index.ts
  api/hearings/routes.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1769

#1759 EUI-4978 Request hearing check your answers happy path
  src/hearings/components/hearing-confirmation/hearing-confirmation.component.html
  src/hearings/components/hearing-confirmation/hearing-confirmation.component.spec.ts
  src/hearings/components/hearing-confirmation/hearing-confirmation.component.ts
  src/hearings/components/index.ts
  src/hearings/containers/request-hearing/hearing-final-confirmation/hearing-final-confirmation.component.html
  src/hearings/containers/request-hearing/hearing-final-confirmation/hearing-final-confirmation.component.spec.ts
  src/hearings/containers/request-hearing/hearing-final-confirmation/hearing-final-confirmation.component.ts
  src/hearings/containers/request-hearing/index.ts
  src/hearings/containers/request-hearing/request-hearing.component.html
  src/hearings/containers/request-hearing/request-hearing.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/hearings.routes.ts
  src/hearings/store/effects/hearing-request.effects.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1759

#1741 update refunds package
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1741

#1771 EUI-5246 Create mock API for post hearing actuals
  api/hearings/hearing.mock.ts
  api/hearings/index.ts
  api/hearings/routes.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1771

#1757 Enable judicial workers by services for all work lists
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/role-access/models/index.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
  src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation-2/containers/task-action/task-action-container.component.ts
  src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation-2/models/dtos/index.ts
  test/dataModels/workAllocation.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1757

#1772 Feature/e UI 5245 create mock api for put /hearing actuals
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingActualsStateData.model.ts
  src/hearings/store/actions/hearing-actuals.action.spec.ts
  src/hearings/store/actions/hearing-actuals.action.ts
  src/hearings/store/actions/index.ts
  src/hearings/store/effects/hearing-actuals.effects.spec.ts
  src/hearings/store/effects/hearing-actuals.effects.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/effects/index.ts
  src/hearings/store/reducers/hearing-actuals.reducer.spec.ts
  src/hearings/store/reducers/hearing-actuals.reducer.ts
  src/hearings/store/reducers/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1772

#1781 ccpay version updated
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1781

#1764 EUI-5303: Search cases criteria wording
  src/search/containers/search-form/search-form.component.html
  src/search/containers/search-form/search-form.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1764

#1768 bug/EUI-5300 find persons debounce
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1768

#1780 EUI-5309 - Additional facilities answer page updates
  src/hearings/converters/additional-facilities.answer.converter.spec.ts
  src/hearings/converters/additional-facilities.answer.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1780

#1776 EUI-4429-unable-to-amend-case
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1776

#1773 Feature/e UI 5092 hearings actuals details page
  api/hearings/models/hearingStatusMappings.ts
  api/hearings/models/hearings.enum.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/components/hearing-actuals-summary/hearing-actuals-summary.component.html
  src/hearings/components/hearing-actuals-summary/hearing-actuals-summary.component.spec.ts
  src/hearings/components/hearing-actuals-summary/hearing-actuals-summary.component.ts
  src/hearings/components/index.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals.component.scss
  src/hearings/containers/hearing-actuals/hearing-actuals.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals.component.ts
  src/hearings/containers/hearing-actuals/index.ts
  src/hearings/containers/index.ts
  src/hearings/containers/request-hearing/index.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/actualsSection.ts
  src/hearings/models/hearingActualsPartyDetails.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/models/section.ts
  src/hearings/templates/hearing-actual-add-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1773

#1697 EUI-5128-Testing
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, pinned, rel:xui-webapp-pr-1697

#1787 Bug/e UI 5339 role by service
  api/roleAccess/models/roleType.ts
  api/roleAccess/roleAssignmentService.ts
  api/roleAccess/routes.ts
  api/test/pact/pact-tests/rolesAccess/getRoles.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
  src/role-access/models/role.model.ts
  src/role-access/resolvers/role-allocations.resolver.spec.ts
  src/role-access/resolvers/role-allocations.resolver.ts
  src/role-access/role-access.routes.ts
  src/role-access/services/allocate-role.service.spec.ts
  src/role-access/services/allocate-role.service.ts
  src/role-access/utils/role-access-utils.ts
  src/work-allocation-2/containers/all-work-case/all-work-case.component.ts
  src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation-2/services/caseworker-data.service.ts
  src/work-allocation-2/utils/work-allocation-utils.ts
  test/nodeMock/workAllocation/mockData.js
  test/nodeMock/workAllocation/reqResMapping.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1787

#1789 story/EUI-5261 updated panel members
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/resolvers/ judicial-user-search-resolver.resolve.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1789

#1797 Change version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1797

#1785 EUI-5094 Hearing stage and result page
  api/prd/lov/data/lov.mock.data.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.html
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.scss
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.ts
  src/hearings/containers/hearing-actuals/index.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/resolvers/adjourn-hearing-actual-reason.resolver.spec.ts
  src/hearings/resolvers/adjourn-hearing-actual-reason.resolver.ts
  src/hearings/resolvers/cancel-hearing-actual-reason.resolver.spec.ts
  src/hearings/resolvers/cancel-hearing-actual-reason.resolver.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1785
