Repository hmcts/rpx-xui-webapp, pull requests merged in 2022-06, with the labels that each got.

#2066 CVE & Redis Upgrade
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2066

#2068 story/EUI-6028
  api/hearings/models/hearingWindow.model.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/converters/hearing-specific-date.answer.converter.spec.ts
  src/hearings/converters/hearing-specific-date.answer.converter.ts
  src/hearings/models/hearingWindow.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2068

#2044 EUI-5430-servicevalue-api-integration
  api/hearings/data/defaultScreenFlow.data.ts
  api/hearings/models/serviceHearingValues.model.ts
  api/hearings/services.index.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
  src/hearings/store/effects/hearing-values.effects.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2044

#2073 EUI-5930 caselink reason api integration
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/proxy.config.ts
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  proxy.config.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/assets/getCase.json
  src/assets/getLinkedCases.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2073

#1770 EUI-5307 - feedback link accessibility
  src/app/components/phase-banner/phase-banner.component.html
  src/app/components/phase-banner/phase-banner.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1770

#1758 EUI 5306 skip to content link
  src/app/components/header/header.component.html
  src/app/components/header/header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/style/app.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1758

#2075 story/EUI-6031
  src/cases/case-feature.routes.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/pipes/hearings.pipes.module.ts
  src/hearings/pipes/stage-display-value.pipe.spec.ts
  src/hearings/pipes/stage-display-value.pipe.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2075

#2059 EUI-4487 my-access-specific access aprroved count
  api/challengedAccess/index.ts
  api/labellingRole/index.ts
  api/roleAccess/index.ts
  api/roleAccess/routes.ts
  api/user/interfaces/roleAssignment.ts
  api/workAllocation2/interfaces/roleCaseData.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  package.json
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/role-access/services/allocate-role.service.spec.ts
  src/role-access/services/allocate-role.service.ts
  src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation-2/containers/my-access/my-access.component.html
  src/work-allocation-2/containers/my-cases/my-cases.component.spec.ts
  src/work-allocation-2/containers/task-home/task-home.component.ts
  src/work-allocation-2/containers/work-case-list/work-case-list.component.html
  src/work-allocation-2/containers/work-case-list/work-case-list.component.ts
  src/work-allocation-2/models/tasks/task.model.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2059

#2081 bug/EUI-6049 fix
  api/hearings/models/hearingDaySchedule.model.ts
  api/hearings/models/hearingResponse.model.ts
  api/hearings/models/partyDetails.model.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/hearings/converters/court-location.answer.converter.spec.ts
  src/hearings/converters/court-location.answer.converter.ts
  src/hearings/converters/date-response-submitted-time.answer.converter.ts
  src/hearings/converters/date-response-submitted.answer.converter.spec.ts
  src/hearings/converters/date-response-submitted.answer.converter.ts
  src/hearings/converters/hearing-response-length.answer.converter.spec.ts
  src/hearings/converters/hearing-response-length.answer.converter.ts
  src/hearings/converters/participant-attendence.answer.converter.spec.ts
  src/hearings/converters/participant-attendence.answer.converter.ts
  src/hearings/converters/room-id.answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingDaySchedule.model.ts
  src/hearings/models/hearingResponse.model.ts
  src/hearings/models/partyDetails.model.ts
  src/hearings/resolvers/court-locations-resolver.resolve.ts
  src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
  src/hearings/store/effects/hearing-list.effects.spec.ts
  src/hearings/store/reducers/hearing-list.reducer.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2081

#2072 EUI-5597: Integrate Boooking APIs - get and create Booking
  api/accessManagement/index.spec.ts
  api/accessManagement/index.ts
  api/accessManagement/routes.ts
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/waSupportedJurisdictions/index.spec.ts
  api/workAllocation2/locationController.ts
  api/workAllocation2/locationService.ts
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  src/booking/booking.routes.ts
  src/booking/containers/booking-check/booking-check.component.spec.ts
  src/booking/containers/booking-check/booking-check.component.ts
  src/booking/containers/booking-home/booking-home.component.html
  src/booking/containers/booking-home/booking-home.component.spec.ts
  src/booking/containers/booking-home/booking-home.component.ts
  src/booking/containers/booking-wrapper/booking-wrapper.component.html
  src/booking/containers/booking-wrapper/booking-wrapper.component.spec.ts
  src/booking/containers/booking-wrapper/booking-wrapper.component.ts
  src/booking/models/booking-request.interface.ts
  src/booking/models/booking.interface.ts
  src/booking/services/booking.service.spec.ts
  src/booking/services/booking.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2072

#2077 EUI-5931 - ccd package for display case name
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2077

#2082 EUI-5342 Update case flag
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2082

#2085 null check
  src/hearings/containers/view-hearing/hearing-adjourned-summary/hearing-adjourned-summary.component.html
  src/hearings/containers/view-hearing/hearing-completed-summary/hearing-completed-summary.component.html
  src/hearings/containers/view-hearing/hearing-view-actual-summary/hearing-view-actual-summary.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2085

#2087 bug/EUI-6063 Date fix
  src/hearings/converters/hearing-specific-date.amended.converter.spec.ts
  src/hearings/converters/hearing-specific-date.amended.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2087

#2090 EUI-6025
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2090

#2097 additional and attendence fix
  src/hearings/converters/additional-facilities.amended.converter.ts
  src/hearings/converters/how-party-attend.amended.converter.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2097

#2092 EUI-6070 Update case flag comments always mandatory
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2092

#2084 Feature/e UI 4512 my cases alert2
  api/roleAccess/index.ts
  api/roleAccess/routes.ts
  api/workAllocation2/interfaces/case.ts
  api/workAllocation2/interfaces/roleCaseData.ts
  api/workAllocation2/util.ts
  api/workAllocation2/utils.spec.ts
  src/role-access/services/allocate-role.service.spec.ts
  src/role-access/services/allocate-role.service.ts
  src/work-allocation-2/components/exui-roundel-badge/exui-roundel-badge.component.html
  src/work-allocation-2/components/exui-roundel-badge/exui-roundel-badge.component.spec.ts
  src/work-allocation-2/components/exui-roundel-badge/exui-roundel-badge.component.ts
  src/work-allocation-2/components/index.ts
  src/work-allocation-2/containers/task-home/task-home.component.ts
  src/work-allocation-2/containers/work-case-list/work-case-list.component.html
  src/work-allocation-2/models/tasks/task.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2084

#2099 Feature/e UI 5174 reset all work filters
  src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2099

#2098 Sort Cases by isNew
  api/workAllocation2/index.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2098

#2101 hearing-bugs-june24
  api/hearings/models/hearingStatusMappings.ts
  api/hearings/models/hearings.enum.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/converters/hearing-specific-date.answer.converter.spec.ts
  src/hearings/converters/hearing-specific-date.answer.converter.ts
  src/hearings/models/hearingStatusMappings.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/utils/validators.utils.spec.ts
  src/hearings/utils/validators.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2101

#2105 EUI-5884- linked cases top table api integration
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2105

#2106 EUI-6164 Reasonable adjustment sign language interpreter
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2106

#2111 EUI-6168: Manage Case Flags - Review Flag Details page
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2111

#2113 EUI-5886- linked cases bottom table api integration
  api/proxy.config.ts
  package.json
  proxy.config.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2113

#2109 EUI-6042 Next Hearing date column
  api/workAllocation2/index.ts
  api/workAllocation2/interfaces/case.ts
  src/work-allocation-2/components/constants/config.constants.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2109

#2112 EUI-5872 Select flag type screen display party and case level flags
  charts/xui-webapp/Chart.yaml
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2112

#2114 Test update and Chart cleanup
  README.md
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  test/accessibility/config/pa11yProtractor.conf.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2114
