Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-10, with the labels that each got.

#3300 Use CHANGE_ID instead of causing conflicts on every PR
  .github/workflows/populate-preview-deployment-id.yaml
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3300

#3301 Don't do production builds for CI, they are only needed in the docker container
  Jenkinsfile_CNP
  angular.json
  api/package.json
  package.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3301

#3285 SIDM-8900 xui fix
  api/test/pact/mocks/openid-well-known-configuration.mock.ts
  api/test/pact/pact-tests/idam/oidc.spec.ts
  package.json
  test_codecept/codeceptCommon/hooks.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3285

#3311 Ex UI 629 failing build fixes
  angular.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3311

#3227 EUI-8736 JRD e-Links API V2
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/prd/judicial/data/judicial.mock.data.ts
  api/prd/judicial/index.ts
  api/prd/judicial/models/judicialUser.model.ts
  api/roleAccess/exclusionService.spec.ts
  api/roleAccess/exclusionService.ts
  api/workAllocation/personService.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  src/hearings/components/hearing-judge-names-list/hearing-judge-names-list.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/judicialUser.model.ts
  test_codecept/e2e/features/app/globalSearch/searchPage.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3227, enable_keep_helm

#3277 exui-834-preferredHearingChannel set to NA for paperHearing
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3277

#3257 exui-771-update task link based on hash key
  angular.json
  src/cases/components/case-task/case-task.util.spec.ts
  src/cases/components/case-task/case-task.util.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3257

#3320 fix functional tests that require deleted account
  .gitignore
  api/.yarn/install-state.gz
  test_codecept/e2e/config/appTestConfig.js
  test_codecept/e2e/features/app/TCSearchCaseandCaseList.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3320

#3316 Feature/EUI 8895
  package.json
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3316

#3303 exui-837-Data loss stepping back/forward through journey
  .github/renovate.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3303

#3333 EXUI-324: (Optionally) Increase resources in Preview
  README.md
  charts/xui-webapp/values.srt.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3333

#3336 Update custom-environment-variables.json to correct error
  config/custom-environment-variables.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3336

#3343 Update Chart.yaml
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3343

#3315 exui-848
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3315

#3337 Add feature toggle for case file view version 1.1
  package.json
  src/app/app.constants.ts
  src/app/services/ccd-config/ccd-case.config.ts
  test_codecept/backendMock/app.js
  test_codecept/backendMock/configCopy.js
  test_codecept/backendMock/local-mock.json
  test_codecept/backendMock/services/caseFileView/categoriesAndDocuments.js
  test_codecept/backendMock/services/caseFileView/index.js
  test_codecept/backendMock/services/caseFileView/routes.js
  test_codecept/backendMock/services/ccd/caseDetails_data.js
  test_codecept/backendMock/services/ccd/caseFileViewTabConfig.js
  test_codecept/backendMock/services/ccd/routes.js
  test_codecept/backendMock/services/evidenceManagement/Blank_Order_Directions_C21.pdf
  test_codecept/backendMock/services/evidenceManagement/Blank_Order_Directions_C21_Welsh.pdf
  test_codecept/backendMock/services/evidenceManagement/Draft_C100_application.pdf
  test_codecept/backendMock/services/evidenceManagement/dummy.pdf
  test_codecept/backendMock/services/evidenceManagement/index.js
  test_codecept/backendMock/services/evidenceManagement/routes.js
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/e2e/features/pageObjects/caseFileViewPage.js
  test_codecept/e2e/features/step_definitions/caseDetails.steps.js
  test_codecept/e2e/features/step_definitions/caseFileView.steps.js
  test_codecept/e2e/features/step_definitions/navigationHeader.steps.js
  test_codecept/e2e/features/step_definitions/support.steps.js
  test_codecept/ngIntegration/tests/features/caseFileView/caseFileView.feature
  test_codecept/ngIntegration/tests/features/caseFileView/caseFileViewSort.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allWork_filters.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myWorkFilters/workFilters.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3337

#3346 Hotfix/exui 1006
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3346

#3349 Fix for big cot-539
  src/hearings/converters/hearing-specific-date.answer.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3349
