Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-03, with the labels that each got.

#2823 EUI-7611: Case Flags v2 - Confirm flag status step validation
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2823

#2671 Feature/e UI 7231 integrate staff ref api refactor
  api/serviceRefData/index.spec.ts
  api/staff-ref-data/index.ts
  api/staff-ref-data/mock-staff-ref-data-api.ts
  api/staff-ref-data/models/staff-ref-data.model.ts
  api/staff-ref-data/real-api.ts
  api/staff-ref-data/real-staff-ref-data-api.ts
  api/staff-ref-data/routes.ts
  api/staff-ref-data/staff-ref-data.controller.ts
  api/staff-ref-data/staff-ref-data.service.ts
  config/default.json
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2671

#2825 EUI-7895 Multi day hearing judge not displayed in the listing information
  src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2825

#2829 EUI-7901 Hearing actuals pause time has incorrect values
  src/hearings/containers/hearing-actuals/hearing-actual-edit-summary/hearing-actual-summary.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2829

#2826 EUI-7798: Sorted skill label issue
  api/.env.defaults
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2826

#2831 Resolved the unit test in r4 and have the latest from master
  package.json
  sonar-project.properties
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/containers/info-message-container/info-message-container.component.spec.ts
  src/style/app.scss
  test/integration/tests/config/config.ts
  yarn-audit-known-issuesyarn
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2831

#2815 enable fine grain task permissions for all search Task
  api/test/pact/pact-tests/wa2/searchTasks.spec.ts
  api/workAllocation/index.ts
  api/workAllocation/util.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2815

#2833 EUI-7916 Hearing Actuals getting error when participants are not confirmed
  src/hearings/containers/hearing-actuals/hearing-actual-edit-summary/hearing-actual-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-edit-summary/hearing-actual-summary.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2833

#2817 Bug/EUI 6972
  api/.env.defaults
  package.json
  sonar-project.properties
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/style/app.scss
  test/integration/tests/config/config.ts
  yarn-audit-known-issuesyarn
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2817

#2834 EUI-7922 Hearing Actuals unknown error when confirming time and participants
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actual-summary-base/hearing-actual-summary-base.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2834

#2841 Bug/EUI 7868 assign to me issue
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/task-list/task-list.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2841

#2814 EUI-6798 Hearings tab display by case type basis
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/cases/models/feature-variation.model.ts
  src/cases/utils/utils.spec.ts
  src/cases/utils/utils.ts
  src/hearings/guards/hearings-edit-guard.spec.ts
  src/hearings/guards/hearings-edit-guard.ts
  src/hearings/guards/hearings-guard.spec.ts
  src/hearings/guards/hearings-guard.ts
  src/hearings/guards/hearings-view-guard.spec.ts
  src/hearings/guards/hearings-view-guard.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2814

#2847 staff admin role key fixed
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2847

#2813 Previously it was text now changed to warningText
  src/work-allocation/components/derived-icon-field/derived-icon-field.component.ts
  src/work-allocation/tests/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2813

#2836 EUI-7777/EUI-7842/EUI-7900: Case Flags v2 - UI amendments for Manage Case Flags pages
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2836

#2822 EUI-6783: Added common lib for clear selected unhappy
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2822

#2850 EUI-7665: case-details Alignment issues - r4
  package.json
  src/work-allocation/components/task-field/task-field.component.scss
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2850

#2840 EUI-6408: Added copy functionality
  package.json
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.spec.ts
  src/staff-administrator/models/staff-user.model.ts
  src/staff-administrator/resolvers/staff-filter-options-locations.resolver.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/staff-administrator.routes.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2840

#2851 show end date for denied access
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/specificAccessOrchastrator/index.spec.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.html
  src/role-access/containers/rejected-request-view/rejected-request-view.component.ts
  src/work-allocation/components/access-view-field/access-view-field.component.spec.ts
  src/work-allocation/components/access-view-field/access-view-field.component.ts
  src/work-allocation/components/work-field/work-field.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2851

#1956 EUI-5608-onboard-adoption
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-1956

#2530 EUI-6221 Updated Google paths for Content Security Policy
  config/default.json
  src/web.config
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2530

#2308 EUI-6183
  src/app/app.routes.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2308

#2853 EUI-7932: Case Flags v2 - Add translations to flag step validation
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2853

#2446 eui-7027-update error message
  src/noc/containers/noc-fill-form-offline/noc-fill-form-offline.component.html
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2446

#2533 EUI-7277-message banner disappear
  src/cases/store/effects/case-create.effects.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2533

#2857 EUI-7354: Case Flags v2 - Filter out "Inactive" and "Not approved" flags from selection
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2857

#2799 task/EUI-7331 cache iisue
  src/app/components/get-help/get-help.component.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2799

#2835 remove duplicates
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2835

#2846 Feature/e UI 6130 task name filter
  api/workAllocation/index.ts
  api/workAllocation/routes.ts
  package.json
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/services/work-allocation-task.service.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2846

#2848 Feature/e UI 7908
  src/staff-administrator/components/staff-suspended-banner/staff-suspended-banner.component.html
  src/staff-administrator/components/staff-suspended-banner/staff-suspended-banner.component.ts
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.html
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.scss
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/staff-administrator.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2848

#2859 Add the relevant fix
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2859

#2550 Adding in the userIncluded filter setting true
  package.json
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2550

#2861 7917
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/staff-administrator/components/staff-users/services/staff-data-filter/staff-data-filter.service.spec.ts
  src/staff-administrator/components/staff-users/services/staff-data-filter/staff-data-filter.service.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.html
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.spec.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.ts
  src/staff-administrator/staff-administrator.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2861

#2852 EUI-7946: Consolidated PR for MC Release
  package.json
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/containers/app/app.component.scss
  src/work-allocation/containers/task-assignment-choose-role/task-assignment-choose-role.component.html
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2852

#2870 Fix the UnAssign
  api/workAllocation/constants/actions.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2870

#2875 Bug/EUI 8005
  src/app/containers/app/app.component.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2875

#2876 next hearing Date
  api/.env.defaults
  api/workAllocation/index.ts
  api/workAllocation/util.ts
  src/work-allocation/components/constants/config.constants.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2876

#2858 Feature/e UI 7797
  api/staff-ref-data/mock-data/staff-ref-users-list.mock.data.ts
  api/staff-ref-data/mock-staff-ref-data-api.ts
  api/staff-ref-data/models/staff-data-user.model.ts
  api/staff-ref-data/real-staff-ref-data-api.ts
  api/staff-ref-data/routes.ts
  api/staff-ref-data/staff-ref-data.controller.ts
  api/staff-ref-data/staff-ref-data.service.ts
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.spec.ts
  src/role-access/services/duration-helper.service.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.html
  src/staff-administrator/components/staff-status/staff-status.component.html
  src/staff-administrator/components/staff-status/staff-status.component.scss
  src/staff-administrator/components/staff-status/staff-status.component.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.html
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.ts
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.html
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/models/staff-user-status.enum.ts
  src/staff-administrator/models/staff-user.model.ts
  src/staff-administrator/resolvers/staff-user-details-resolver.service.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.spec.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2858

#2868 Tech/e UI 7972 staff UI display improvements
  api/staff-ref-data/models/staff-data-user.model.ts
  api/staff-ref-data/real-staff-ref-data-api.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2868

#2866 EUI-7923
  api/common/crudService.ts
  api/staff-ref-data/real-staff-ref-data-api.ts
  package.json
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.spec.ts
  src/role-access/services/duration-helper.service.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  src/staff-administrator/components/staff-users/services/staff-data-filter/staff-data-filter.service.spec.ts
  src/staff-administrator/components/staff-users/services/staff-data-filter/staff-data-filter.service.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.spec.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
  src/staff-administrator/components/staff-users/staff-search/staff-search.component.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.html
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.spec.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.ts
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/containers/staff-users/staff-users.component.ts
  src/staff-administrator/models/staff-add-edit-user-form-id.enum.ts
  src/staff-administrator/models/staff-job-titles.ts
  src/staff-administrator/models/staff-search-filters.model.ts
  src/staff-administrator/models/staff-user-list-data.model.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.spec.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/staff-administrator.routes.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2866

#2734 Refunds V2 web component integration
  api/configuration/references.ts
  api/proxy.config.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/refunds/refunds/refunds.component.html
  src/refunds/refunds/refunds.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2734

#2879 Revert "Refunds V2 web component integration"
  api/configuration/references.ts
  api/proxy.config.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/refunds/refunds/refunds.component.html
  src/refunds/refunds/refunds.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2879

#2869 EUI-7351 Reasonable adjustments review flag details screen
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2869

#2871 Feature/EUI 7810
  api/staff-ref-data/models/staff-data-user.model.ts
  src/app/shared/enums/info-message.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  src/staff-administrator/components/staff-status/staff-status.component.html
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.html
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.scss
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/containers/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/models/staff-user.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2871

#2881 Merge 3.5 into r4
  package.json
  src/app/app.routes.ts
  src/work-allocation/components/work-field/work-field.component.ts
  src/work-allocation/containers/my-cases/my-cases.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2881

#2882 EUI-7375 Reasonable adjustments manage support display CYA page
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2882

#2694 EUI-6880: Dynamic Multi select
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2694

#2891 remove mock code
  api/workAllocation/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2891

#2873 EUI-8000: Hotfix - Case file view move logic
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2873

#2888 Feature/e UI 8015
  package.json
  src/booking/containers/booking-location/booking-location.component.html
  src/role-access/services/duration-helper.service.spec.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
  src/staff-administrator/resolvers/staff-filter-options-services.resolver.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2888

#2628 EUI-6573: Added pipe to error message component
  package.json
  src/app/components/error-message/error-message.component.html
  src/app/components/error-message/error-message.component.spec.ts
  src/app/shared/test/mock-rpx-translate.pipe.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2628

#2894 Rollback serviceRefDataMapping refData
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2894
