Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-05, with the labels that each got.

#2970 Feature/release4 wa4 updated
  api/common/crudService.ts
  package.json
  src/app/containers/info-message-container/info-message-container.component.ts
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/booking/containers/booking-date/booking-date.component.spec.ts
  src/booking/containers/booking-home/booking-home.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/case-details-home/case-details-home.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-select-location/staff-select-location.component.ts
  src/work-allocation/components/priority-field/priority-field.component.spec.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/my-cases/my-cases.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation/utils/work-allocation-utils.ts
  yarn.lock
  yarnaudit.sh
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2970

#2979 fix sonarcloud issues
  src/cases/components/case-task/case-task.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2979

#2741 welsh feature toggle
  src/app/components/phase-banner/phase-banner.component.html
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2741

#2971 Bug/EUI 8357
  src/work-allocation/components/constants/config.constants.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2971

#2976 EUI-8356
  src/booking/containers/booking-check/booking-check.component.spec.ts
  src/booking/containers/booking-check/booking-check.component.ts
  src/booking/containers/booking-date/booking-date.component.ts
  src/booking/containers/booking-wrapper/booking-wrapper.component.html
  src/booking/containers/booking-wrapper/booking-wrapper.component.scss
  src/booking/models/booking-date.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2976

#2982 Bug/EUI 8345
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2982

#2897 EXUI-114-manageLabellingRoleAssignment-504-error
  api/roleAccess/index.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2897

#2987 Yarn audit known issues
  src/role-access/services/duration-helper.service.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2987

#2997 Temporarily exclude files from Sonar scan for WA R4
  sonar-project.properties
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2997

#2972 EUI-8286 Reasonable Adjustments CYA hide event summary section
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2972

#2941 EXUI-228: Upgrade ccpay to 5.2.3
  package.json
  test_codecept/e2e/features/app/workAllocation/workallocation2.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2941

#2990 package file check in
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2990

#3003 update ccd toolkit
  package.json
  src/app/app.module.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3003

#3011 Feature/EUI 8139
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3011

#3010 EXUI-249 Ensure ng-idle package version is same as common lib
  package.json
  test/e2e/features/app/workAllocation/workallocation2.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3010

#2995 EXUI-263 Fix 'My Work' showing for accounts with incorrect permissions
  src/work-allocation/resolvers/location-resolver.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2995

#3017 Temp disable fortify and mutation tests
  Jenkinsfile_nightly
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3017

#3016 Proposed R4 Improvements branch
  api/locations/index.spec.ts
  api/locations/index.ts
  package.json
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html
  src/work-allocation/components/task-field/task-field.component.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/my-cases/my-cases.component.spec.ts
  src/work-allocation/resolvers/location-resolver.service.ts
  src/work-allocation/resolvers/location.resolver.spec.ts
  src/work-allocation/utils/work-allocation-utils.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3016

#3033 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3033

#3039 EXUI-110 Flickering tabs bug fix
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3039

#3028 Feature/EUI 8231
  package.json
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/case-home/case-home.component.spec.ts
  src/cases/containers/case-home/case-home.component.ts
  src/cases/store/effects/case-create.effects.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.html
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  src/work-allocation/containers/work-case-list/work-case-list.component.spec.ts
  yarn-audit-known-issues
  yarn.lock
  yarnaudit.sh
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3028

#2615 story/EUI-7435
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/converters/participant-channel-attendance.converter.spec.ts
  src/hearings/converters/participant-channel-attendance.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2615

#3029 EXUI-296 Add ET help details
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3029

#3012 Feature/e UI 8361
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3012
