Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-01, with the labels that each got.

#2621 MC CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2621

#2529 Feature/e UI 7139 filter skill by service
  package.json
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2529

#2625 yarn
  yarn-audit-known-issues
  yarn.lock
Labels: add-or-update

#2627 cve tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2627

#2629 EUI-7449 Grouped hearings of different linked cases for the same slot fails
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.html
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2629

#2638 PrL Angular 11
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
  src/hearings/components/hearing-summary/hearing-summary.component.html
  src/hearings/components/listing-information-summary/listing-information-summary.component.html
  src/hearings/components/listing-information-summary/listing-information-summary.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.html
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.html
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.spec.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
  src/hearings/containers/view-hearing/hearing-adjourned-summary/hearing-adjourned-summary.component.html
  src/hearings/containers/view-hearing/hearing-adjourned-summary/hearing-adjourned-summary.component.ts
  src/hearings/hearings.routes.ts
  src/hearings/pipes/convert-array-to-string.pipe.spec.ts
  src/hearings/pipes/convert-array-to-string.pipe.ts
  src/hearings/pipes/hearings.pipes.module.ts
  src/hearings/services/hearings.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2638

#2637 Temporarily comment out a11y tests hang in nightly runs.
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2637

#2630 EUI-7483 Linked hearings displayed twice when clicking on change option
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.html
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2630

#2642 fix path for mutation test.
  api/challengedAccess/index.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2642

#2650 disabled pa11y tests.
  package.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2650

#2626 Bug/EUI 7476
  api/specificAccessOrchastrator/index.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2626

#2653 Feature/merge from master to r3.5
  Jenkinsfile_nightly
  api/challengedAccess/index.ts
  package.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2653

#2598 EUI-6584
  package.json
  src/app/components/header/header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/phase-banner/phase-banner.component.spec.ts
  src/booking/containers/booking-date/booking-date.component.spec.ts
  src/cases/containers/case-list/case-list.component.spec.ts
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.html
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.spec.ts
  src/search/containers/search-results/search-results.component.spec.ts
  src/work-allocation/components/task-field/task-field.component.spec.ts
  src/work-allocation/components/work-allocation.components.module.ts
  src/work-allocation/components/work-field/work-field.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2598

#2618 EUI-6591
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2618

#2663 EUI-7481 Case file view move document buttons not displayed
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2663

#2662 fixed incorrect viewchild static value
  package.json
  src/noc/containers/noc-field/noc-field.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2662

#2649 EUI-7496: Case File View - Media Viewer scrolling behaviour fix
  package.json
  test/e2e/features/app/TCCreateCase.feature
  test/e2e/features/app/judicialBookingUI/judicialBookingUI.feature
  test/e2e/features/app/shareCase.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2649

#2668 EUI-7521 CaseLink properties and layout have changed in latest xui image
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2668

#2595 EUI-7430
  api/user/utils.spec.ts
  api/user/utils.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2595

#2581 Feature/e UI 6411 & 6422
  api/staff-ref-data/index.ts
  api/staff-ref-data/routes.ts
  api/staff-ref-data/staff-ref-data.mock.ts
  package.json
  src/staff-administrator/components/staff-suspended-banner/staff-suspended-banner.component.html
  src/staff-administrator/components/staff-suspended-banner/staff-suspended-banner.component.scss
  src/staff-administrator/components/staff-suspended-banner/staff-suspended-banner.component.spec.ts
  src/staff-administrator/components/staff-suspended-banner/staff-suspended-banner.component.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/models/staff-user.model.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
  src/staff-administrator/staff-administrator.module.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2581

#2676 EUI-6774 CR-54 Multiday split judge name from judicial members
  src/hearings/components/listing-information-summary/listing-information-summary.component.html
  src/hearings/components/listing-information-summary/listing-information-summary.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2676

#2667 Add specific access ctsc role request
  api/roleAccess/dtos/to-role-assignment-dto.ts
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2667

#2675 Fix the issue with unassign
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2675

#2679 EUI-7563 Hearings Unable to view listed hearings
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts
  src/hearings/models/linkHearings.model.ts
  src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2679

#2678 Bug/EUI 7548
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2678

#2690 EUI-7591 JOH seeing request hearing button
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2690

#2685 region id update
  api/hearings/data/defaultScreenFlow.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/models/hearings.enum.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.ts
  src/hearings/converters/welsh.hidden.converter.spec.ts
  src/hearings/converters/welsh.hidden.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/show-hide.pipe.spec.ts
  src/hearings/store/reducers/hearing-conditions.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
  src/hearings/utils/page-flow.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2685

#2691 Story/e UI 7494 view details actuals
  api/hearings/data/hearingRequests.mock.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/models/hearingDetails.model.ts
  api/hearings/models/serviceHearingValues.model.ts
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
  src/hearings/components/listing-information-summary/listing-information-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.scss
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.spec.ts
  src/hearings/converters/additional-security.amended.converter.spec.ts
  src/hearings/converters/participant-channel-attendance.converter.spec.ts
  src/hearings/converters/participant-channel-attendance.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearingDetails.model.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/models/serviceHearingValues.model.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-request-to-compare.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2691

#2689 Force TimeoutNotif service reset on staySignedIn
  src/app/containers/app/app.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2689

#2698 EUI-7602 EUI-7598
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2698

#2683 Update package
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2683

#2705 Feature/EUI 7339 master region filter
  api/locations/index.spec.ts
  api/locations/index.ts
  api/workAllocation/locationController.ts
  api/workAllocation/locationService.ts
  api/workAllocation/routes.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/models/user-details.model.ts
  src/work-allocation/components/task-list-filter/task-list-filter.component.spec.ts
  src/work-allocation/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation/models/dtos/index.ts
  src/work-allocation/resolvers/location-resolver.service.ts
  src/work-allocation/resolvers/location.resolver.spec.ts
  src/work-allocation/services/location-data.service.spec.ts
  src/work-allocation/services/location-data.service.ts
  src/work-allocation/utils/work-allocation-utils.spec.ts
  src/work-allocation/utils/work-allocation-utils.ts
  src/work-allocation/work-allocation.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2705

#2704 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2704

#2692 Resolved issue with multiple subscriptions
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2692

#2715 Update max records
  api/workAllocation/caseWorkerService.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2715

#2714 EUI-7591 SSCS SIT Release
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2714

#2696 story/EUI-7595
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.spec.ts
  src/hearings/converters/additional-security.amended.converter.spec.ts
  src/hearings/converters/participant-channel-attendance.converter.spec.ts
  src/hearings/converters/participant-channel-attendance.converter.ts
  src/hearings/converters/participant-channel-attendence.amended.converter.spec.ts
  src/hearings/converters/participant-channel-attendence.amended.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingDetails.model.ts
  src/hearings/models/serviceHearingValues.model.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/reducers/hearing-request-to-compare.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.spec.ts
  src/hearings/store/reducers/hearing-request.reducer.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2696

#2710 Bug/EUI 7635
  package.json
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.html
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2710

#2632 EUI-6572
  package.json
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/case-search/case-search.component.spec.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2632

#2616 update to angular 11 + change tests for case-share
  package.json
  src/cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/cases/containers/case-share-confirm/case-share-confirm.component.spec.ts
  src/cases/containers/case-share/case-share.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2616

#2717 EUI-7650 Email and phone number details of the participant are not sent to LA
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2717

#2723 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2723

#2730 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2730

#2560 added version of toolkit for testing
  package.json
  yarn-audit-known-issuesyarn
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2560

#2729 EUI-7679 Hearings display hearings sub channel value
  src/hearings/components/hearing-actual-summary-single-day/hearing-actual-summary-single-day.component.spec.ts
  src/hearings/components/hearing-actual-summary-single-day/hearing-actual-summary-single-day.component.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/converters/judge-exclusion.answer.converter.spec.ts
  src/hearings/converters/judge-name.answer.converter.spec.ts
  src/hearings/converters/judicial-members.answer.converter.spec.ts
  src/hearings/converters/panel-exclusion.answer.converter.spec.ts
  src/hearings/converters/panel-inclusion.answer.converter.spec.ts
  src/hearings/converters/participant-attendence.answer.converter.spec.ts
  src/hearings/converters/participant-attendence.answer.converter.ts
  src/hearings/converters/participant-channel-attendance.converter.spec.ts
  src/hearings/converters/participant-channel-attendance.converter.ts
  src/hearings/converters/party-channels-answer.converter.spec.ts
  src/hearings/converters/party-channels-answer.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/hearings.routes.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/resolvers/hearing-actual-party-subchannel-resolver.service.spec.ts
  src/hearings/resolvers/hearing-actual-party-subchannel-resolver.service.ts
  src/hearings/resolvers/party-subchannels-resolver.service.spec.ts
  src/hearings/resolvers/party-subchannels-resolver.service.ts
  src/hearings/resolvers/ref-data-resolver.resolve.ts
  src/hearings/store/reducers/hearing-actuals.reducer.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2729

#2472 EUI-7004-testing
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2472

#2508 Feature/eu 6403 add user confirm
  src/app/components/index.ts
  src/app/components/info-message/info-message.component.html
  src/app/components/info-message/info-message.component.spec.ts
  src/app/components/info-message/info-message.component.ts
  src/app/containers/info-message-container/info-message-container.component.html
  src/app/containers/info-message-container/info-message-container.component.spec.ts
  src/app/containers/info-message-container/info-message-container.component.ts
  src/app/shared/enums/info-message-type.ts
  src/app/shared/enums/info-message.ts
  src/app/shared/models/index.ts
  src/app/shared/models/infomation-message.model.ts
  src/app/shared/services/info-message-comms.service.spec.ts
  src/app/shared/services/info-message-comms.service.ts
  src/app/shared/shared.module.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/case-details-home/case-details-home.component.spec.ts
  src/role-access/store/effects/exclusion.effects.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  src/staff-administrator/components/staff-users/staff-search/staff-search.component.ts
  src/staff-administrator/containers/staff-users/staff-users.component.html
  src/staff-administrator/containers/staff-users/staff-users.component.ts
  src/staff-administrator/services/staff-data-signal.service.ts
  src/work-allocation/components/constants/task-action.constants.ts
  src/work-allocation/components/index.ts
  src/work-allocation/containers/all-work-home/all-work-home.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/index.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.ts
  src/work-allocation/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation/containers/task-assignment-confirm/task-assignment-confirm.component.ts
  src/work-allocation/containers/task-home/task-home.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation/enums/index.ts
  src/work-allocation/models/common/route-data.ts
  src/work-allocation/models/comms/infomation-message.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2508
