Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-04, with the labels that each got.

#2889 Feature/e UI 7298
  src/app/containers/app/app.component.scss
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html
  src/staff-administrator/containers/staff-add-user/staff-add-user.component.html
  src/staff-administrator/containers/staff-edit-user-container/staff-edit-user-container.component.html
  src/staff-administrator/containers/staff-main-container/staff-main-container.component.html
  src/staff-administrator/containers/staff-users/staff-users.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2889

#2899 Remove empty and incorrect Yarn lock file
  yarn-audit-known-issues
  yarn-audit-known-issuesyarn
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2899

#2906 EUI-7894 Hearings date range validation
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.html
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2906

#2907 EUI-7936 Hearings AM and PM to be passed through to HMC
  api/hearings/models/hearings.enum.ts
  src/hearings/models/hearings.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2907

#2896 story/EUI-7992
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2896

#2905 Feature/e UI 8032
  src/staff-administrator/components/staff-user-details/staff-status/staff-status.component.html
  src/staff-administrator/components/staff-user-details/staff-status/staff-status.component.scss
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.scss
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2905

#2764 Update media viewer
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2764

#2777 updated ccd-toolkit package
  package.json
  src/role-access/containers/specific-access/specific-access-duration/specific-access-duration.component.spec.ts
  src/role-access/services/duration-helper.service.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2777

#2911 EUI-8025 Linked cases continue button not showing error message
  .yarn/install-state.gz
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2911

#2919 EUI-8097
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form-validation-messages.enum.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/services/staff-add-edit-form/staff-add-edit-form.service.ts
  src/staff-administrator/utils/form/staff-form.utils.ts
  src/staff-administrator/utils/form/validators/no-primary-location.validator.spec.ts
  src/staff-administrator/utils/form/validators/no-primary-location.validator.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2919

#2913 EUI 8034 new
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2913

#2914 Feature/e UI 7977
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.html
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.spec.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2914

#2366 EUI-3967 loading spinner
  src/cases/containers/case-hearings/case-hearings.component.html
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/cases/containers/case-share-complete/case-share-complete.component.html
  src/cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/cases/containers/case-share-complete/case-share-complete.component.ts
  src/cases/containers/case-share-confirm/case-share-confirm.component.html
  src/cases/containers/case-share-confirm/case-share-confirm.component.spec.ts
  src/cases/containers/case-share-confirm/case-share-confirm.component.ts
  src/cases/containers/tasks-container/tasks-container.component.html
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/hearings/components/hearing-summary/hearing-summary.component.html
  src/hearings/components/hearing-summary/hearing-summary.component.spec.ts
  src/hearings/components/hearing-summary/hearing-summary.component.ts
  src/hearings/components/listing-information-summary/listing-information-summary.component.html
  src/hearings/components/listing-information-summary/listing-information-summary.component.spec.ts
  src/hearings/components/listing-information-summary/listing-information-summary.component.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.html
  src/hearings/containers/cancel-hearing/cancel-hearing.component.spec.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-final-confirmation/hearing-actuals-final-confirmation.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-final-confirmation/hearing-actuals-final-confirmation.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-final-confirmation/hearing-actuals-final-confirmation.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/containers/request-hearing/hearing-final-confirmation/hearing-final-confirmation.component.html
  src/hearings/containers/request-hearing/hearing-final-confirmation/hearing-final-confirmation.component.spec.ts
  src/hearings/containers/request-hearing/hearing-final-confirmation/hearing-final-confirmation.component.ts
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-adjourned-summary/hearing-adjourned-summary.component.html
  src/hearings/containers/view-hearing/hearing-adjourned-summary/hearing-adjourned-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-adjourned-summary/hearing-adjourned-summary.component.ts
  src/hearings/containers/view-hearing/hearing-completed-summary/hearing-completed-summary.component.html
  src/hearings/containers/view-hearing/hearing-completed-summary/hearing-completed-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-completed-summary/hearing-completed-summary.component.ts
  src/hearings/containers/view-hearing/hearing-view-actual-summary/hearing-view-actual-summary.component.html
  src/hearings/containers/view-hearing/hearing-view-actual-summary/hearing-view-actual-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-view-actual-summary/hearing-view-actual-summary.component.ts
  src/hearings/hearings.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2366

#2924 EUI-7819 Case file view display document upload date
  api/.yarn/install-state.gz
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2924

#2920 bug/EUI-8026 package update
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2920

#2931 EXUI-207 Remove security.sh
  security.sh
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2931

#2927 Show banner
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2927

#2900 next hearing date
  api/workAllocation/index.ts
  api/workAllocation/interfaces/case.ts
  api/workAllocation/interfaces/roleCaseData.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2900

#2923 Priority Label Changes
  src/app/app-utils.spec.ts
  src/app/app-utils.ts
  src/cases/components/case-task/case-task.component.html
  src/work-allocation/components/priority-field/priority-field.component.spec.ts
  src/work-allocation/components/priority-field/priority-field.component.ts
  src/work-allocation/components/task-field/task-field.component.html
  src/work-allocation/containers/task-assignment-confirm/task-assignment-confirm.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2923

#2929 EUI-8100
  package.json
  src/work-allocation/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2929

#2930 removed status form check answers page on add/update staff user
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  src/staff-administrator/services/staff-add-edit-form/staff-add-edit-form.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2930

#2936 Remove update button for pending status
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.scss
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2936

#2925 Bug/EUI 7172
  src/role-access/services/duration-helper.service.spec.ts
  src/work-allocation/components/constants/config.constants.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2925

#2932 EUI-7812 Case file view sorting by date
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2932

#2902 EUI-7489-refund-v2
  api/configuration/references.ts
  api/proxy.config.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/refunds/refunds/refunds.component.html
  src/refunds/refunds/refunds.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2902

#2940 EXUI-208 Migrate .internal url
  src/app/app-utils.spec.ts
  whitelist.sh
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2940

#2937 Feature/e UI 6841
  package.json
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.spec.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
  src/staff-administrator/components/staff-users/staff-search/staff-search.component.spec.ts
  src/staff-administrator/components/staff-users/staff-search/staff-search.component.ts
  src/staff-administrator/containers/staff-users/staff-users.component.spec.ts
  src/staff-administrator/containers/staff-users/staff-users.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2937

#2945 Feature/e UI 8227
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.html
  src/staff-administrator/components/staff-add-user/staff-add-user.component.html
  src/staff-administrator/components/staff-add-user/staff-add-user.component.spec.ts
  src/staff-administrator/components/staff-add-user/staff-add-user.component.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/containers/staff-add-edit-user-container/staff-add-edit-user-container.component.html
  src/staff-administrator/containers/staff-add-edit-user-container/staff-add-edit-user-container.component.scss
  src/staff-administrator/containers/staff-add-edit-user-container/staff-add-edit-user-container.component.spec.ts
  src/staff-administrator/containers/staff-add-edit-user-container/staff-add-edit-user-container.component.ts
  src/staff-administrator/containers/staff-add-user-container/staff-add-user-container.component.scss
  src/staff-administrator/containers/staff-add-user-container/staff-add-user-container.component.spec.ts
  src/staff-administrator/containers/staff-add-user-container/staff-add-user-container.component.ts
  src/staff-administrator/containers/staff-edit-user-container/staff-edit-user-container.component.html
  src/staff-administrator/containers/staff-edit-user-container/staff-edit-user-container.component.scss
  src/staff-administrator/containers/staff-edit-user-container/staff-edit-user-container.component.spec.ts
  src/staff-administrator/containers/staff-edit-user-container/staff-edit-user-container.component.ts
  src/staff-administrator/containers/staff-user-details-container/staff-user-details-container.component.ts
  src/staff-administrator/services/staff-add-edit-form/staff-add-edit-form.service.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/staff-administrator.routes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2945

#2946 INC5502434: Add app insight logging for debugging
  api/lib/appInsights.ts
  api/user/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2946

#2939 Feature/e UI 8120
  src/cases/cases.module.ts
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.ts
  src/work-allocation/components/priority-field/priority-field-current/priority-field-current.component.html
  src/work-allocation/components/priority-field/priority-field-current/priority-field-current.component.spec.ts
  src/work-allocation/components/priority-field/priority-field-current/priority-field-current.component.ts
  src/work-allocation/components/priority-field/priority-field-legacy/priority-field-legacy.component.html
  src/work-allocation/components/priority-field/priority-field-legacy/priority-field-legacy.component.spec.ts
  src/work-allocation/components/priority-field/priority-field-legacy/priority-field-legacy.component.ts
  src/work-allocation/components/priority-field/priority-field.component.html
  src/work-allocation/components/priority-field/priority-field.component.spec.ts
  src/work-allocation/components/priority-field/priority-field.component.ts
  src/work-allocation/components/priority-field/priority-field.module.ts
  src/work-allocation/components/priority-field/priority.module.ts
  src/work-allocation/components/task-field/task-field.component.html
  src/work-allocation/components/work-allocation.components.module.ts
  src/work-allocation/containers/task-action/task-action-container.component.spec.ts
  src/work-allocation/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts
  src/work-allocation/work-allocation.module.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2939

#2950 EXUI-180: Add .gitattributes
  .gitattributes
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2950

#2952 INC5502435: Null check refreshRoleAssignmentForUser and improved logging
  api/lib/appInsights.ts
  api/test/pact/pact-tests/accessManagement/getRoleAssignments.spec.ts
  api/user/index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2952

#2953 EUI-8280
  src/staff-administrator/components/staff-users/services/staff-data-filter/staff-data-filter.service.spec.ts
  src/staff-administrator/components/staff-users/services/staff-data-filter/staff-data-filter.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2953

#2955 check to see if at least one user id is present
  api/workAllocation/caseWorkerService.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2955

#2961 fix copying a suspended user
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/containers/staff-users/staff-users.component.html
  src/staff-administrator/models/staff-user-idam-status.enum.ts
  src/staff-administrator/models/staff-user.model.ts
  src/staff-administrator/services/staff-add-edit-form/staff-add-edit-form.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2961

#2966 Update task-list-wrapper.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2966
