Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-07, with the labels that each got.

#3060 EUI 8472 buffer/codecept migration new
  package.json
  test/e2e/features/step_definitions/workAccessBookingUI/workAccessPage.steps.js
  test_codecept/backendMock/client/index.js
  test_codecept/backendMock/services/roleAssignments/index.js
  test_codecept/backendMock/services/session/index.js
  test_codecept/backendMock/services/session/routes.js
  test_codecept/backendMock/services/task-management-api/index.js
  test_codecept/backendMock/services/users.js
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/codeceptCommon/hooks.js
  test_codecept/dataModels/bookings.js
  test_codecept/dataModels/workAllocation.js
  test_codecept/e2e/features/app/TCCreateCase.feature
  test_codecept/e2e/features/app/TCSearchCaseandCaseList.feature
  test_codecept/e2e/features/app/globalSearch/searchPage.feature
  test_codecept/e2e/features/app/loginLogout.feature
  test_codecept/e2e/features/app/staffUI/manageUser.feature
  test_codecept/e2e/features/app/staffUI/search.feature
  test_codecept/e2e/features/app/workAllocation/workallocation2.feature
  test_codecept/e2e/features/step_definitions/globalSearchPage.steps.js
  test_codecept/e2e/features/step_definitions/workallocation/workallocation.steps.js
  test_codecept/ngIntegration/mockData/workAllocation/mockData.js
  test_codecept/ngIntegration/tests/features/globalSearch.feature
  test_codecept/ngIntegration/tests/features/navigationHeader.feature
  test_codecept/ngIntegration/tests/features/workAccessBookingUI/featureToggle-guard.feature
  test_codecept/ngIntegration/tests/features/workAccessBookingUI/workAccess.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allWork_filters.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allwork.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allwork_manageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allwork_paginationSorting.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork_cases/allWorkCases.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/availableTasks_manageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks_paginationSorting.feature
  test_codecept/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/taskManageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/tasksTab.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myTask_taskActionWorkflow.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks_manageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks_paginationSorting.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_taskAssignmentWorkFlows.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myWorkFilters/workFilters.feature
  test_codecept/ngIntegration/tests/features/workallocation2/taskActions.feature
  test_codecept/ngIntegration/tests/stepDefinitions/mockCase.steps.js
  test_codecept/ngIntegration/tests/stepDefinitions/workallocation/waCommon.steps.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3060

#3128 EUI-8603 QM raise a query cya
  api/.yarn/install-state.gz
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3128

#3124 COT-354 Amending a Hearing cause error
  .gitignore
  Jenkinsfile_CNP
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  infrastructure/main.tf
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/services/hearings.service.spec.ts
  src/hearings/services/hearings.service.ts
  src/hearings/utils/validators.utils.spec.ts
  src/hearings/utils/validators.utils.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3124

#3084 Hearings 6.16 fixes
  api/.yarn/install-state.gz
  package.json
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actual-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
  src/hearings/utils/actual-hearings.utils.spec.ts
  src/hearings/utils/actual-hearings.utils.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3084

#3133 Hotfix 6.17.1
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3133

#3080 EXUI-360: Upgrade ccpay version to 5.2.8
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3080

#3052 EXUI-249 Prevent multiple TimeoutNotificationService instantiations
  config/default.json
  package.json
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/services/logger/logger.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3052

#3138 EXUI-310 & EXUI364
  api/test/pact/publish/publish.ts
  sonar-project.properties
  src/app/app-initilizer.ts
  src/app/components/case-reference-search-box/case-reference-search-box.component.spec.ts
  src/app/components/case-reference-search-box/case-reference-search-box.component.ts
  src/app/store/effects/router.effect.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.spec.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/store/effects/hearing-request.effects.spec.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/noc/containers/noc-home/noc-home.component.spec.ts
  src/noc/containers/noc-home/noc-home.component.ts
  src/role-access/containers/remove-role/remove-role.component.spec.ts
  src/role-access/containers/remove-role/remove-role.component.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3138

#2988 Sonar fixes
  sonar-project.properties
  src/app/app-initilizer.ts
  src/app/components/case-reference-search-box/case-reference-search-box.component.spec.ts
  src/app/components/case-reference-search-box/case-reference-search-box.component.ts
  src/app/store/effects/router.effect.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.spec.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/store/effects/hearing-request.effects.spec.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/noc/containers/noc-home/noc-home.component.spec.ts
  src/noc/containers/noc-home/noc-home.component.ts
  src/role-access/containers/remove-role/remove-role.component.spec.ts
  src/role-access/containers/remove-role/remove-role.component.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts
  src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2988

#3043 EUI-8429: Fix pactbroker publish SSL issue
  api/test/pact/publish/publish.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3043

#3137 EUI-8602 QM raise a query changes
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3137

#3123 EUI-8604 QM query details ui changes
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3123

#3127 EUI-8607 QM follow up query cya
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3127

#3143 EXUI-430 - Scale Redis to P2
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3143

#3140 EUI-8623 QM remove grey bar
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3140

#3139 Respond query ui changes
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3139

#3145 Fix pagination issue
  api/.yarn/install-state.gz
  api/application.ts
  api/idamCheck.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3145

#3150 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3150

#3130 EUI_8481
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3130

#3136 EXUI-393-added SSCS contact details
  sonar-project.properties
  src/app/app.constants.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3136

#3148 Feature/e UI 8561
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3148

#3157 use idam api for idam check
  api/idamCheck.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3157

#3159 Fix nightly build
  test/e2e/features/app/workAllocation/workallocation2.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3159

#3167 exclude irrelevant content from Fortify scans
  test/java/config/fortify-client.properties
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3167

#3172 EUI-8636 QM amend mock data
  package.json
  src/cases/containers/query-management-container/query-management-container.component.ts
  src/cases/mock/query-management.mock.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3172

#3175 EXUI-626 - Update ET help contact details
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3175

#3176 Feature/EUI 8568
  api/test/pact/pact-tests/rolesAccess/getAccessRolesByCaseId.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3176

#3092 COT-287: add ST to staff ui services
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3092

#3169 COT-427 IAC Hearings Onboarding: Configure ExUI to point to IAC hearings endpoints
  api/.yarn/install-state.gz
  config/custom-environment-variables.json
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3169

#3171 Re-add next param into error handler
  api/lib/error.handler.spec.ts
  api/lib/error.handler.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3171

#3182 Temp disable flaky test scenarios and assertions
  test/e2e/config/conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/TCCreateCase.feature
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/workAllocation/workallocation2.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3182

#3177 EXUI-631-remove-feature-flag-updated-task-permission
  api/configuration/appConfig.ts
  api/configuration/references.ts
  config/custom-environment-variables.json
  config/default.json
  src/app/app.constants.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-action/task-action-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/services/work-allocation-feature.service.spec.ts
  src/work-allocation/services/work-allocation-feature.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3177
