Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-02, with the labels that each got.

#2740 Feature/release3.5 civil 7065
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.html
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.ts
  src/work-allocation/services/index.ts
  test/e2e/features/pageObjects/workAllocation/allWorkPage.js
  test/e2e/features/step_definitions/workallocation/workallocation2.steps.js
  test/ngIntegration/tests/features/workallocation2/allWork/allWork_filters.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/Cases_caseActionWorkflow.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/Cases_manageLinks.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/Cases_pagination.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/allWorkCases.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2740

#2736 EUI-7688: Case Flags v2 - Support multiple Case Flags tabs
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2736

#2748 find person by service
  package.json
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2748

#2747 Add the necessary feature changes
  src/app/app.constants.ts
  src/app/components/routing/application-routing.component.spec.ts
  src/app/components/routing/application-routing.component.ts
  src/work-allocation/models/common/service-config.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2747

#2756 EUI 7674 release-06-feb-2023
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2756

#2719 Fix sorting issue
  src/work-allocation/components/constants/config.constants.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  test/ngIntegration/tests/features/workallocation2/allWork/allwork_paginationSorting.feature
  test/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks_paginationSorting.feature
  test/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks_paginationSorting.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2719

#2761 Feature/fix r4 issues
  package.json
  src/app/components/info-message/info-message.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
  src/staff-administrator/containers/staff-users/staff-users.component.ts
  src/staff-administrator/models/banner-data-model.ts
  src/staff-administrator/services/staff-data-signal.service.ts
  src/work-allocation/containers/task-action/task-action-container.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2761

#2766 EUI-7676 Configure new case link
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2766

#2771 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2771

#2772 EUI-7659 Linked hearings handle cross jurisdiction cases
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.html
  src/hearings/containers/linked-hearings/linked-hearings-with-case/linked-hearings-with-case.component.ts
  src/hearings/containers/linked-hearings/linked-hearings.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2772

#2600 EUI-7114: Added feature toggle - next hearing date
  src/work-allocation/components/constants/config.constants.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-cases/my-cases.component.spec.ts
  src/work-allocation/containers/my-cases/my-cases.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.spec.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation/services/check-release-version.service.ts
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2600

#2770 Feature/EUI 7747
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  config/custom-environment-variables.json
  config/default.json
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/models/environmentConfig.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2770

#2774 Feature/EUI 7747
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2774

#2703 EUI-7021 No is selected for hearing pause
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
  src/hearings/converters/participant-channel-attendance.converter.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/utils/actual-hearings.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2703

#2778 XUI bump base chart
  charts/xui-webapp/Chart.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2778

#2775 EUI-7732 Request hearing organisation party details are not submitted
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2775

#2738 Feature/release3.5 civil
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/locations/index.spec.ts
  api/locations/index.ts
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/app.constants.ts
  src/app/components/routing/application-routing.component.spec.ts
  src/app/components/routing/application-routing.component.ts
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/models/environmentConfig.model.ts
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation/components/constants/config.constants.ts
  src/work-allocation/components/task-list-filter/task-list-filter.component.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.html
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.html
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/models/common/service-config.model.ts
  src/work-allocation/resolvers/location-resolver.service.ts
  src/work-allocation/resolvers/location.resolver.spec.ts
  src/work-allocation/services/index.ts
  test/e2e/features/pageObjects/workAllocation/allWorkPage.js
  test/e2e/features/step_definitions/workallocation/workallocation2.steps.js
  test/ngIntegration/tests/features/workallocation2/allWork/allWork_filters.feature
  test/ngIntegration/tests/features/workallocation2/allWork/allwork_paginationSorting.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/Cases_caseActionWorkflow.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/Cases_manageLinks.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/Cases_pagination.feature
  test/ngIntegration/tests/features/workallocation2/allWork_cases/allWorkCases.feature
  test/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks_paginationSorting.feature
  test/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks_paginationSorting.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2738

#2773 new ccd-case-ui-toolkit version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2773

#2633 Feature/e UI 7489 notification fee n pay
  api/configuration/references.ts
  api/proxy.config.ts
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/refunds/refunds/refunds.component.html
  src/refunds/refunds/refunds.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2633, no-changes

#2783 Fix the issue with find person
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  test/integration/tests/config/config.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2783

#2789 Fix issue with find person control
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  test/integration/tests/config/config.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2789

#2792 EUI-7840 Organisation details should not be displayed in Listing Information
  src/hearings/converters/participant-attendence.answer.converter.spec.ts
  src/hearings/converters/participant-attendence.answer.converter.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2792

#2794 EUI-7246 Linked cases capture other reason
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2794

#2793 Add ctsc to all work cases
  api/workAllocation/interfaces/person.ts
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2793

#2781 Feature/EUI 7747
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/configuration/waSupportedServicesCaseTypesHelper.spec.ts
  api/configuration/waSupportedServicesCaseTypesHelper.ts
  config/custom-environment-variables.json
  config/default.json
  src/models/environmentConfig.model.ts
  src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  test/integration/tests/config/config.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2781

#2806 Replace master code with release 4
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2806

#2767 from EUI-6740 & PR2420
  api/.env.defaults
  api/staff-ref-data/index.ts
  api/staff-ref-data/mock-data/staff-ref-users-list.mock.data.ts
  api/staff-ref-data/models/staff-data-user.model.ts
  api/staff-ref-data/models/staff-filter-option.model.ts
  api/staff-ref-data/real-api.ts
  api/staff-ref-data/routes.ts
  api/test/pact/pactUtil.ts
  api/user/index.ts
  api/user/utils.spec.ts
  api/workAllocation/locationService.ts
  package.json
  src/app/containers/app/app.component.scss
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/components/staff-suspended-banner/staff-suspended-banner.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.spec.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.html
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.scss
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2767

#2603 Set min selection property for service and location fields
  package.json
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
  yarn.lock
Labels: add-or-update

#2640 Fetch the service code from the configuration
  api/staff-ref-data/models/staff-filter-option.model.ts
  api/staff-ref-data/real-api.ts
  api/user/index.ts
  api/user/utils.spec.ts
  package.json
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-2640

#2713 Feature/eu 7298 user search page desing issue
  src/app/containers/app/app.component.scss
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2713

#2577 Eui 6408 select to copy user details
  api/staff-ref-data/index.ts
  api/staff-ref-data/mock-data/staff-ref-users-list.mock.data.ts
  api/staff-ref-data/models/staff-data-user.model.ts
  api/staff-ref-data/routes.ts
  api/workAllocation/locationService.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.ts
  src/staff-administrator/components/staff-suspended-banner/staff-suspended-banner.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
  src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.html
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2577

#2795 Feature/e UI 7804 prs consolidated part 2
  api/.env.defaults
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2795

#2805 increased coverage in application-routing.component.ts
  src/app/components/routing/application-routing.component.spec.ts
  src/app/components/routing/application-routing.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2805

#2722 Feature/eui 7419 display job title
  api/staff-ref-data/index.ts
  api/staff-ref-data/mock-data/staff-ref-users-list.mock.data.ts
  api/staff-ref-data/models/staff-data-user.model.ts
  api/staff-ref-data/models/staff-filter-option.model.ts
  api/staff-ref-data/real-api.ts
  api/staff-ref-data/routes.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
  src/staff-administrator/components/staff-user-details/staff-user-details.component.ts
  src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.spec.ts
  src/staff-administrator/models/staff-user.model.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.spec.ts
  src/staff-administrator/services/staff-data-access/staff-data-access.service.ts
  src/staff-administrator/test-data/staff-user-details.test.data.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2722

#2810 EUI-7350: Case Flags v2 - Confirm flag status step
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2810

#2811 EUI-7362: Case Flags v2 - "Request support" and "Manage support" legal rep journeys
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2811

#2819 Mc release 6.13.0 rc1
  package.json
  sonar-project.properties
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/style/app.scss
  test/integration/tests/config/config.ts
  yarn-audit-known-issues
  yarn-audit-known-issuesyarn
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2819
