Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-06, with the labels that each got.

#3036 EXUI-316-temporary hide suspend button
  src/staff-administrator/components/staff-user-details/staff-user-details.component.html
  src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3036

#3051 Bug/EUI 8467
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3051

#3062 INC5516582 Hotfix: Fix duplicate tab navigation
  package.json
  test/integration/tests/nodeApp_endpoints.spec.ts
  test_codecept/integration/tests/nodeApp_endpoints.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3062

#3032 EXUI-282 removing booking url to avoid unncessary redirect
  config/default.json
  package.json
  src/app/services/auth/auth.guard.ts
  src/noc/containers/noc-submit-success/noc-submit-success.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3032

#3061 'Refer' no longer a valid value from WA_searchTasks
  api/test/pact/pact-tests/idam/oidc.spec.ts
  api/test/pact/pact-tests/wa2/searchTasks.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3061

#2947 EXUI-199: Add grey bar to date field
  package.json
  sonar-project.properties
  src/cases/containers/case-list/case-list.component.ts
  src/cases/containers/case-search/case-search.component.ts
  src/cases/store/reducers/case-list.reducer.spec.ts
  src/cases/store/reducers/case-list.reducer.ts
  src/cases/store/reducers/search-filter.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-2947

#3018 send hearing date along with time
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3018

#3013 exui-272-restricting append of task Id to url
  src/cases/components/case-task/case-task.util.spec.ts
  src/cases/components/case-task/case-task.util.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3013

#3059 Feature/e UI 8379
  package.json
  src/cases/cases.module.ts
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.scss
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  src/cases/query-management.routes.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/work-case-list/work-case-list.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3059

#3065 EUI-8497 Remove CYA link from the Hearings tab
  api/.yarn/install-state.gz
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3065

#3074 Feature/e UI 8397
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3074

#3066 Feature/e UI 8428
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3066

#3069 Feature/e UI 8483
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3069

#3081 EUI-8488 fix tests tab
  test_codecept/backendMock/services/task-management-api/index.js
  test_codecept/backendMock/services/users.js
  test_codecept/ngIntegration/mockData/workAllocation/mockData.js
  test_codecept/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/taskManageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/tasksTab.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3081

#3086 EUI-8527 Hearings update participants page showing spinner indefinitely
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3086

#3091 Suppress recursive CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3091

#3083 EUI-8453 QM Raise a query error scenarios
  api/.yarn/install-state.gz
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.scss
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  src/cases/models/raise-query-error-message.enum.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3083

#3076 Feature/EUI 8372
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3076

#3104 Pass buffer branch tests
  package.json
  test_codecept/e2e/features/app/TCCreateCase.feature
  test_codecept/e2e/features/app/TCSearchCaseandCaseList.feature
  test_codecept/e2e/features/app/globalSearch/searchPage.feature
  test_codecept/e2e/features/app/loginLogout.feature
  test_codecept/e2e/features/app/staffUI/manageUser.feature
  test_codecept/e2e/features/app/staffUI/search.feature
  test_codecept/e2e/features/app/workAllocation/workallocation2.feature
  test_codecept/ngIntegration/tests/features/navigationHeader.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allwork.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allwork_manageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allwork_paginationSorting.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork_cases/allWorkCases.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/availableTasks_manageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks_paginationSorting.feature
  test_codecept/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/taskManageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myTask_taskActionWorkflow.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks_manageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks_paginationSorting.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myWorkFilters/workFilters.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3104

#3107 All work filters tests fix
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allWork_filters.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3107

#3108 cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3108

#3089 Feature/e UI 8425
  api/.yarn/install-state.gz
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  src/cases/models/raise-query-error-message.enum.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3089

#3087 Feature/e UI 8451
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3087

#3112 Feature/e UI 8526
  package.json
  src/app/models/user-details.model.ts
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3112

#3118 EXUI-268 Step 1: Add Redis V6 instance
  .gitignore
  infrastructure/main.tf
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3118

#3119 EXUI-268 Step 2: Point to Redis V6 instance
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3119

#3125 EXUI-268 Step 3: Remove Redis V4 instance
  infrastructure/main.tf
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3125
