Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-12, with the labels that each got.

#3369 Reinstate CHANGE_ID for Preview deployment ID
  charts/xui-webapp/values.preview.template.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3369

#3368 Feature/EUI 8903 auto update hearing values
  .yarn/install-state.gz
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.ts
  src/hearings/store/effects/hearing-request.effects.ts
  test_codecept/backendMock/services/hearings/serviceHearingValuesMock.js
  test_codecept/backendMock/services/roleAssignments/routes.js
  test_codecept/e2e/documents/ccd-config-aat-xui-testCaseType_v2.1.dev.xlsx
  test_codecept/e2e/documents/ccd-config-aat-xui-testCaseType_v2.dev.xlsx
  test_codecept/e2e/features/step_definitions/common.steps.js
  test_codecept/ngIntegration/tests/features/hearings/hearingsAutomaticUpdates.feature
  test_codecept/ngIntegration/tests/features/hearings/hearingsSemiAutomaticUpdates.feature
  test_codecept/ngIntegration/tests/stepDefinitions/hearingsMock.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3368

#3391 Update case hearings list page link
  src/app/app.constants.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  test_codecept/backendMock/services/ccd/caseDetails_data.js
  test_codecept/backendMock/services/ccd/caseFlagsTabConfig.js
  test_codecept/backendMock/services/hearings/index.js
  test_codecept/backendMock/services/hearings/mockData/serviceHearingValues.js
  test_codecept/backendMock/services/prd/hearingType_Categories.js
  test_codecept/backendMock/services/prd/index.js
  test_codecept/backendMock/services/prd/routes.js
  test_codecept/backendMock/services/rdJudicial/index.js
  test_codecept/backendMock/services/rdJudicial/routes.js
  test_codecept/backendMock/services/rdLocation/index.js
  test_codecept/backendMock/services/session/routes.js
  test_codecept/e2e/config/appTestConfig.js
  test_codecept/e2e/features/pageObjects/hearings/createhearingWorkflow.js
  test_codecept/e2e/features/pageObjects/hearings/hearingsTabPage.js
  test_codecept/e2e/features/step_definitions/hearings.steps.js
  test_codecept/e2e/features/step_definitions/hearings/createHearings.steps.js
  test_codecept/e2e/features/step_definitions/hearings/hearingsTab.steps.js
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
  test_codecept/ngIntegration/tests/features/hearings/createHearingNavigationControls.feature
  test_codecept/ngIntegration/tests/features/hearings/hearingTabHearingActions.feature
  test_codecept/ngIntegration/tests/features/hearings/hearingsAutomaticUpdates.feature
  test_codecept/ngIntegration/tests/features/hearings/hearingsSemiAutomaticUpdates.feature
  test_codecept/ngIntegration/tests/features/hearings/hearingsTab.feature
  test_codecept/ngIntegration/tests/features/restrictedCaseAccess.feature
  test_codecept/ngIntegration/tests/stepDefinitions/mockCase.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3391

#3395 EUI-8920 CR-84 Hearings edit summary
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.html
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3395

#3405 exui-1175-Complex fields not being unhidden by Show Conditions
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3405

#3415 Tests/pact test update to match provider test
  api/test/pact/pact-tests/accessManagement/refreshRoleAssignments.spec.ts
  api/test/pact/pact-tests/wa2/taskRoles.spec.ts
  api/test/pact/pact-tests/wa2/typeOfWork.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3415

#3361 duplicate texts removed
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3361

#3410 Display internal case name
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.spec.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.ts
  src/hearings/hearing.test.data.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3410

#3416 EUI-9080 Hearing CR-84 Remove Welsh changes
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-instructions-section/additional-instructions-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-instructions-section/additional-instructions-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/case-details-section/case-details-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/case-details-section/case-details-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-stage-section/hearing-stage-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-stage-section/hearing-stage-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-venue-section/hearing-venue-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-venue-section/hearing-venue-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/language-requirements-section/language-requirements-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/language-requirements-section/language-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/linked-hearing-section/linked-hearing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/linked-hearing-section/linked-hearing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/panel-details-section/panel-details-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/panel-details-section/panel-details-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/warning-and-error-section/warning-and-error-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/warning-and-error-section/warning-and-error-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/warning-and-error-section/warning-and-error-section.component.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.html
  src/hearings/hearings.module.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/services/hearings.service.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3416

#3424 SourceMap fix for MC after node upgrade
  angular.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3424

#3409 Feature/EUI 8966
  .yarn/install-state.gz
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  test_codecept/backendMock/services/hearings/serviceHearingValuesMock.js
  test_codecept/e2e/features/pageObjects/hearings/editHearingPage.js
  test_codecept/e2e/features/step_definitions/hearings/viewOrEditHearing.steps.js
  test_codecept/e2e/utils/jsonUtil.js
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingSubPages.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingPagelessUpdates.feature
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3409

#3420 EUI-8905 Hearing CR-84 Summary page labels
  .yarn/install-state.gz
  src/hearings/components/index.ts
  src/hearings/containers/request-hearing/amendment-label/amendment-label.component.html
  src/hearings/containers/request-hearing/amendment-label/amendment-label.component.spec.ts
  src/hearings/containers/request-hearing/amendment-label/amendment-label.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/case-details-section/case-details-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/case-details-section/case-details-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/case-details-section/case-details-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/utils/case-flags.utils.ts
  test_codecept/backendMock/services/hearings/index.js
  test_codecept/backendMock/services/hearings/routes.js
  test_codecept/backendMock/services/mockApiData.js
  test_codecept/codeceptCommon/hooks.js
  test_codecept/e2e/features/pageObjects/common/summaryTable.js
  test_codecept/e2e/features/pageObjects/hearings/viewOrEditHearingPage.js
  test_codecept/e2e/features/step_definitions/framework/hooks.steps.js
  test_codecept/e2e/features/step_definitions/hearings/viewOrEditHearing.steps.js
  test_codecept/e2e/support/hooks.js
  test_codecept/e2e/utils/jsonUtil.js
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingPagelessUpdates.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingsAutomaticUpdates.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingsSemiAutomaticUpdates.feature
  test_codecept/ngIntegration/tests/stepDefinitions/hearingsMock.steps.js
  test_codecept/ngIntegration/util/cucumberHooks.js
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3420
