Repository hmcts/rpx-xui-webapp, pull requests merged in 2023-08, with the labels that each got.

#3186 EXUI-661 - Fix CSP config
  api/application.ts
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3186

#3194 Add translatioin
  src/cases/components/restricted-case-access/restricted-case-access.component.html
  src/cases/components/restricted-case-access/restricted-case-access.component.spec.ts
  src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.html
  src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3194

#3197 update known issue suppressions
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3197

#3196 COT-444 aSupportedServiceandCaseTypes.SSCS.caseTypes" not defined
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3196

#3199 add console logs
  package.json
  src/app/services/errorHandler/defaultErrorHandler.ts
  src/app/services/logger/logger.service.spec.ts
  src/app/services/logger/logger.service.ts
  src/app/shared/services/environment.service.spec.ts
  src/app/shared/services/environment.service.ts
  src/cases/containers/case-details-home/case-details-home.component.ts
  src/cases/containers/case-home/case-home.component.spec.ts
  src/cases/containers/case-home/case-home.component.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3199

#3202 Ex UI 681 enable console logs in prod
  src/app/services/logger/logger.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3202

#3210 Update suppressions causing nightly build failures
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3210

#3224 provide the timeout in the second element
  src/assets/config/config.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3224

#3154 Set initial service codes for location and add unit tests
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-select-location/staff-select-location.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-select-location/staff-select-location.component.ts
  src/staff-administrator/models/location-by-service-code-model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3154

#3231 COT-461 Incorrect roles when adding a participant in the actuals journey.
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3231

#3230 EXUI-266: Configure github action to update preview deployment id
  .github/workflows/populate-preview-deployment-id.yaml
  api/lib/http/index.ts
  charts/xui-webapp/values.preview.template.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3230

#3243 Remove App Insights agent from client bundle
  .gitignore
  charts/xui-webapp/values.preview.template.yaml
  package.json
  src/app/app.module.ts
  src/app/services/logger/appInsightsWrapper.ts
  src/app/services/logger/logger.service.spec.ts
  src/app/services/logger/logger.service.ts
  src/app/services/logger/monitoring.service.spec.ts
  src/app/services/logger/monitoring.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3243

#3241 EUI-8779 Reasonable adjustments - update base branch with un-merged code
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3241
