Repository hmcts/rpx-xui-webapp, pull requests merged in 2024-03, with the labels that each got.

#3522 Task/e UI 1067 postcode validation
  README.md
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3522

#3446 rate limit for document uploads added
  README.md
  api/documents/index.spec.ts
  api/documents/index.ts
  api/proxy.config.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3446

#3560 CSFD-54
  src/hearings/containers/request-hearing/request-hearing.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3560

#3556 fix COT-790
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3556

#3562 Upgrade crypto-js
  charts/xui-webapp/values.preview.template.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3562

#3532 connectSrc configurations changes
  api/application.ts
  config/default.json
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3532

#3542 EXUI-909 Use standard redis SKU on non-prod environments
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:xui, prd:xui, destroy, pr-values:srt, rel:xui-webapp-pr-3542

#3575 CSFD-76
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3575

#3540 test PR for EXUI-1322
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3540

#3574 Create aat.tfvars bump redis to C3
  infrastructure/aat.tfvars
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3574

#3577 CSFD-82
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.ts
  test_codecept/e2e/features/pageObjects/hearings/viewOrEditHearingPage.js
  test_codecept/e2e/features/step_definitions/hearings/createHearings.steps.js
  test_codecept/e2e/features/step_definitions/hearings/viewOrEditHearing.steps.js
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_CAT1_only.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_CAT2_only.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingManulaUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/summaryPageValidations.feature
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3577

#3581 DTSPO-17006: AAT - back to premium Redis cache tier
  infrastructure/aat.tfvars
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3581

#3582 CSFD-75
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3582

#3583 AAT: Redis - move to Standard before Premium
  infrastructure/aat.tfvars
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3583

#3588 AAT - Redis Cache - Premium
  infrastructure/aat.tfvars
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3588

#3591 new vars for perftest to make redis setup the same on perftest and prod
  infrastructure/perftest.tfvars
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3591

#3587 CSFD-77
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3587

#3589 CSFD-87
  src/hearings/pipes/show-hide.pipe.spec.ts
  src/hearings/pipes/show-hide.pipe.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3589

#3593 CSFD-90
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3593

#3594 exui-1511-ccpay upgrade
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3594

#3572 CSFD-18 Event flow cancel navigation
  package.json
  test_codecept/e2e/features/app/caseFlags/createCaseFlagV1_languageInterpreter.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV1_reasonableAdjustments.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_languageInterpreter.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_reasonableAdjustments.feature
  test_codecept/e2e/features/app/caseFlags/createSupport_reasonableAdjustments.feature
  test_codecept/e2e/features/pageObjects/caseFlags/caseFlagsWorkflow.js
  test_codecept/e2e/features/step_definitions/caseFlags.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3572

#3596 CSFD-93
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3596

#3537 Bug/e UI 1307 comments not languages
  .yarn/install-state.gz
  api/hearings/models/partyFlags.model.ts
  api/test/pact/pact-tests/wa2/taskRoles.spec.ts
  api/test/pact/pact-tests/wa2/typeOfWork.spec.ts
  src/hearings/components/case-flags/case-flags.component.html
  src/hearings/components/case-flags/case-flags.component.ts
Labels: DO NOT MERGE, ns:xui, prd:xui, destroy, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3537

#3606 CSFD-88
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.html
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.scss
  src/hearings/components/parties-unavailable-dates/parties-unavailable-dates.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.html
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.scss
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/utils/hearings.utils.ts
Labels: ns:xui, prd:xui, add-or-update, rel:xui-webapp-pr-3606

#3608 enable fortify scan
  Jenkinsfile_nightly
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3608

#3568 Increase default resources for Preview
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.srt.preview.template.yaml
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3568

#3553 toolkit version updated
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3553

#3580 Remove wa-service-config for WA support
  api/configuration/references.ts
  api/configuration/uiConfigRouter.ts
  api/configuration/waSupportedServicesCaseTypesHelper.spec.ts
  api/configuration/waSupportedServicesCaseTypesHelper.ts
  config/default.json
  src/cases/cases.module.ts
  src/cases/components/case-task/case-task.component.html
  src/cases/components/case-task/case-task.component.spec.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/components/roles-and-access/roles-and-access.component.html
  src/cases/components/roles-and-access/roles-and-access.component.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.html
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/work-allocation/components/index.ts
  src/work-allocation/components/priority-field/priority-field-current/priority-field-current.component.html
  src/work-allocation/components/priority-field/priority-field-current/priority-field-current.component.spec.ts
  src/work-allocation/components/priority-field/priority-field-current/priority-field-current.component.ts
  src/work-allocation/components/priority-field/priority-field-legacy/priority-field-legacy.component.html
  src/work-allocation/components/priority-field/priority-field-legacy/priority-field-legacy.component.spec.ts
  src/work-allocation/components/priority-field/priority-field-legacy/priority-field-legacy.component.ts
  src/work-allocation/components/priority-field/priority-field.component.html
  src/work-allocation/components/priority-field/priority-field.component.spec.ts
  src/work-allocation/components/priority-field/priority-field.component.ts
  src/work-allocation/components/priority-field/priority-field.module.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
  src/work-allocation/components/work-allocation.components.module.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.spec.ts
  src/work-allocation/containers/all-work-task/all-work-task.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.ts
  src/work-allocation/containers/my-access/my-access.component.spec.ts
  src/work-allocation/containers/my-cases/my-cases.component.spec.ts
  src/work-allocation/containers/my-cases/my-cases.component.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
  src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.spec.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation/services/check-release-version.service.ts
  src/work-allocation/services/index.ts
  src/work-allocation/services/work-allocation-feature.service.spec.ts
  src/work-allocation/services/work-allocation-feature.service.ts
  src/work-allocation/work-allocation.module.ts
  test/integration/tests/config/config.ts
  test_codecept/integration/tests/config/config.ts
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3580

#3604 Add accessibility fixes
  src/app/components/case-reference-search-box/case-reference-search-box.component.html
  src/app/components/case-reference-search-box/case-reference-search-box.component.scss
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3604

#3529 common-lib library version changed-DO_NOT_MERGE
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, rel:xui-webapp-pr-3529

#3569 Task/1194 security issue
  README.md
  api/documents/index.spec.ts
  api/documents/index.ts
  api/lib/middleware/proxy.ts
  api/proxy.config.ts
  package.json
  test_codecept/e2e/features/pageObjects/common/CaseManager.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, destroy, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3569

#3611 exui-1529-validation for same judge selection
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/models/hearings.enum.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3611

#3617 CSFD-124
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3617

#3607 use csfd-95 ccd ui toolkit fix
  .yarn/install-state.gz
  package.json
  test_codecept/e2e/features/app/caseFlags/createCaseFlagV1_languageInterpreter.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV1_reasonableAdjustments.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_languageInterpreter.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_reasonableAdjustments.feature
  test_codecept/e2e/features/app/caseFlags/createSupport_reasonableAdjustments.feature
  test_codecept/e2e/features/step_definitions/caseFlags.steps.js
  test_codecept/e2e/features/step_definitions/caseManager.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3607

#3585 CSFD-42 Bug fix for incorrect organisation party details on hearing update
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3585

#3620 CSFD-125
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.html
  src/hearings/utils/case-flags.utils.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3620

#3621 exui-1691-revert exui-1316
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/converters/hearing-panel.amended.converter.spec.ts
  src/hearings/converters/hearing-panel.amended.converter.ts
  src/hearings/converters/hearing-panel.answer.converter.spec.ts
  src/hearings/converters/hearing-panel.answer.converter.ts
  src/hearings/converters/judge-types.amended.converter.spec.ts
  src/hearings/converters/judge-types.amended.converter.ts
  src/hearings/converters/judge-types.answer.converter.spec.ts
  src/hearings/converters/judge-types.answer.converter.ts
  src/hearings/converters/judge-types.hidden.converter.spec.ts
  src/hearings/converters/judge-types.hidden.converter.ts
  src/hearings/converters/need-judge.amended.converter.spec.ts
  src/hearings/converters/need-judge.amended.converter.ts
  src/hearings/converters/need-judge.answer.converter.ts
  src/hearings/converters/panel-member-roles.amended.converter.spec.ts
  src/hearings/converters/panel-member-roles.amended.converter.ts
  src/hearings/converters/panel-member-roles.answer.converter.spec.ts
  src/hearings/converters/panel-member-roles.answer.converter.ts
  src/hearings/converters/panel-member-roles.hidden.converter.spec.ts
  src/hearings/converters/panel-member-roles.hidden.converter.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/pipes/show-hide.pipe.spec.ts
  src/hearings/pipes/show-hide.pipe.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingActions_preCR84.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3621
