Repository hmcts/rpx-xui-webapp, pull requests merged in 2024-08, with the labels that each got.

#3826 exui-2219-revert-exui-1540
  package.json
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3826

#3818 Release exui-1117
  src/cases/components/case-alert/alert.component.html
  src/cases/components/case-alert/alert.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3818

#3816 exui-2085-added trace logs to identify task completion action
  api/workAllocation/index.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3816

#3820 adds a fix for amend showing when re-ordering locations
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-venue-section/hearing-venue-section.component.ts
Labels: ns:xui, prd:xui, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-3820

#3665 exui-1845-flagcomment added
  src/hearings/components/case-flags/case-flags.component.html
  src/hearings/components/case-flags/case-flags.component.spec.ts
  src/hearings/components/case-flags/case-flags.component.ts
  src/hearings/models/partyFlags.model.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3665

#3723 EXUI-227: Reduce api calls to user/details
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/refunds/refunds/refunds.component.spec.ts
  src/refunds/refunds/refunds.component.ts
  src/role-access/store/effects/allocate-role.effects.spec.ts
  src/role-access/store/effects/allocate-role.effects.ts
  src/work-allocation/resolvers/location-resolver.service.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3723

#3827 Add pageSize from config
  api/configuration/references.ts
  api/workAllocation/util.ts
  config/custom-environment-variables.json
  config/default.json
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3827

#3830 1785, fixes a sonar issue
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-venue-section/hearing-venue-section.component.ts
Labels: ns:xui, prd:xui, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-3830

#3822 EXUI-2202 - Location Filter not working reliably
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3822

#3812 EXUI-1775 - Change the default value for the available-external-flag
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3812

#3808 exui-2106-missing jurisdiction
  package.json
  src/work-allocation/utils/work-allocation-utils.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3808

#3819 Bug/e UI 2030 duplicate assignees
  api/workAllocation/caseWorkerUserDataCacheService.spec.ts
  api/workAllocation/caseWorkerUserDataCacheService.ts
  api/workAllocation/fullUserDetailCache.ts
  api/workAllocation/index.ts
  api/workAllocation/interfaces/common.ts
  api/workAllocation/interfaces/staffUserDetails.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3819

#3829 Make technical change to caching
  api/workAllocation/caseWorkerUserDataCacheService.ts
  api/workAllocation/fullUserDetailCache.ts
  api/workAllocation/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3829

#3825 EM-2209: media viewer upgraded to 4.07
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3825

#3442 hearing button loading fix
  src/cases/containers/case-hearings/case-hearings.component.html
  src/cases/containers/case-hearings/case-hearings.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3442

#3811 EXUI-2100 - Nightly pipeline
  Jenkinsfile_nightly
  package.json
  test/e2e/config/appTestConfig.js
  test/e2e/config/conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/pageObjects/caseEditPage.js
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/step_definitions/browser.steps.js
  test/e2e/features/step_definitions/caseAccessManagement/specificAccess.steps.js
  test/e2e/features/step_definitions/caseDetails.steps.js
  test/e2e/features/step_definitions/caseDetailsPage.steps.js
  test/e2e/features/step_definitions/caseList.steps.js
  test/e2e/features/step_definitions/caseManager.steps.js
  test/e2e/features/step_definitions/checkFunctionalities.steps.js
  test/e2e/features/step_definitions/cookieBanner.steps.js
  test/e2e/features/step_definitions/createCase.steps.js
  test/e2e/features/step_definitions/errorPage.steps.js
  test/e2e/features/step_definitions/errorValidation.steps.js
  test/e2e/features/step_definitions/globalSearchPage.steps.js
  test/e2e/features/step_definitions/hearingRecordingsCase.steps.js
  test/e2e/features/step_definitions/ldService.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/navigationHeader.steps.js
  test/e2e/features/step_definitions/referenceValues.steps.js
  test/e2e/features/step_definitions/refunds.steps.js
  test/e2e/features/step_definitions/searchCase.steps.js
  test/e2e/features/step_definitions/shareCase.steps.js
  test/e2e/features/step_definitions/shareCaseCheckAndConfirm.steps.js
  test/e2e/features/step_definitions/support.steps.js
  test/e2e/features/step_definitions/testCaseType.steps.js
  test/e2e/features/step_definitions/timestamp.steps.js
  test/e2e/features/step_definitions/workAccessBookingUI/workAccessPage.steps.js
  test/e2e/features/step_definitions/workallocation/allocateRoles.steps.js
  test/e2e/features/step_definitions/workallocation/allworkPage.steps.js
  test/e2e/features/step_definitions/workallocation/caseDetailsTasksTab.steps.js
  test/e2e/features/step_definitions/workallocation/caseRolesAccess.steps.js
  test/e2e/features/step_definitions/workallocation/checkYourAnswers.steps.js
  test/e2e/features/step_definitions/workallocation/common.steps.js
  test/e2e/features/step_definitions/workallocation/exclusion.steps.js
  test/e2e/features/step_definitions/workallocation/findPerson.steps.js
  test/e2e/features/step_definitions/workallocation/myCases.steps.js
  test/e2e/features/step_definitions/workallocation/selectRoleType.steps.js
  test/e2e/features/step_definitions/workallocation/taskEventCompletion.steps.js
  test/e2e/features/step_definitions/workallocation/tasksCasesTable.steps.js
  test/e2e/features/step_definitions/workallocation/workFilter.steps.js
  test/e2e/features/step_definitions/workallocation/workallocation.steps.js
  test/e2e/features/step_definitions/workallocation/workallocation2.steps.js
  test/e2e/features/step_definitions/workflow.steps.js
  test/e2e/support/timeout.js
  test/e2e/support/world.js
  test/e2e/utils/ccdApi.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3811

#3832 EXUI-1730 - remove confirm for new participant
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3832

#3839 EXUI-2229
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3839

#3402 Fix typo in environment variable SERVICES_HEARINGS_CASETYPES_IAC
  config/custom-environment-variables.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3402

#3840 Exui 2228
  api/application.ts
  config/default.json
  src/web.config
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3840

#3584 Ex UI 1270 accessibility bug
  package.json
  src/app/components/case-reference-search-box/case-reference-search-box.component.html
  src/app/components/header/header.component.html
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/work-case-list/work-case-list.component.html
  test_codecept/e2e/features/step_definitions/workallocation/common.steps.js
  test_codecept/e2e/features/step_definitions/workallocation/myCases.steps.js
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks.feature
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3584, aat/add-or-update, prod/add-or-update

#3842 EXUI-2273 removing logs prior to merge with master.
  src/hearings/utils/case-flags.utils.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3842

#3845 Revert "Ex UI 1270 accessibility bug"
  package.json
  src/app/components/case-reference-search-box/case-reference-search-box.component.html
  src/app/components/header/header.component.html
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.html
  src/work-allocation/containers/work-case-list/work-case-list.component.html
  test_codecept/e2e/features/step_definitions/workallocation/common.steps.js
  test_codecept/e2e/features/step_definitions/workallocation/myCases.steps.js
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3845

#3848 #EXUI-2280: Media viewer upgrade to 4.0.8
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3848

#3851 removes strict ssl which was commited in error
  .yarnrc.yml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3851

#3815 EXUI-2135 - Fortify issue roleAssignmentService.ts
  api/roleAccess/roleAssignmentService.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3815

#3813 EXUI-2134 - Fortify issue
  api/user/index.spec.ts
  api/user/index.ts
  test/ngIntegration/tests/features/workallocation2/myWorkFilters/workFilters.feature
  test_codecept/ngIntegration/tests/features/caseFileView/caseFileView.feature
  test_codecept/ngIntegration/tests/features/caseFileView/caseFileViewSort.feature
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
  test_codecept/ngIntegration/tests/features/hearings/createHearingNavigationControls.feature
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allwork.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myWorkFilters/workFilters.feature
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3813

#3847 Ex UI 152 noc sonar security latest renamed
  src/noc/containers/noc-field/utils/noc-validators.spec.ts
  src/noc/containers/noc-field/utils/noc-validators.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3847
