Repository hmcts/rpx-xui-webapp, pull requests merged in 2024-11, with the labels that each got.

#3865 axios upgraded to 1.7.5
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3865

#3968 exui-2415-Redirect to an new event by a hyperlink
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3968

#4095 EXUI-2517 - Authenticated routes test
  test_codecept/integration/tests/authenticated_routes.spec.ts
  test_codecept/integration/tests/config/authenticatedRoutes.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4095

#3950 exui-2144-noc-date-issue
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3950

#4099 Revert "exui-2144-noc-date-issue"
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4099

#4090 exui-2518-date field validation for month which should accept 1 to 12 value
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4090

#3910 Fix potential race condition in AppConfig init
  api/.yarn/install-state.gz
  api/lib/error.handler.ts
  api/specificAccessOrchastrator/index.spec.ts
  browserslist
  config/custom-environment-variables.json
  package.json
  playwright.config.ts
  src/app/app.constants.ts
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/app/services/ccd-config/launch-darkly-defaults.constants.ts
  src/cases/guards/restricted-case-access-guard.ts
  test/e2e/features/pageObjects/common/CaseManager.js
  test_codecept/backendMock/local-mock.json
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/e2e/features/pageObjects/common/CaseManager.js
  test_codecept/ngIntegration/tests/features/launchDarklyService.feature
  test_codecept/ngIntegration/tests/features/navigationHeader.feature
  test_codecept/ngIntegration/tests/features/workallocation2/taskEventCompletion/taskEventCompletion.feature
  test_codecept/ngIntegration/tests/stepDefinitions/mockCase.steps.js
  test_codecept/ngIntegration/util/idamLogin.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3910

#3985 SSCSSI-419: Update XUI urls to point sscs-tribunals-case-api after he…
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  config/default.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3985

#2993 Query management feature
  angular.json
  package.json
  src/app/app.routes.ts
  src/app/models/user-details.model.ts
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  src/cases/cases.module.ts
  src/cases/components/case-alert/alert.component.spec.ts
  src/cases/containers/index.ts
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.scss
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  src/cases/mock/query-management.mock.ts
  src/cases/models/qualifying-questions/casetype-qualifying-questions.model.ts
  src/cases/models/qualifying-questions/qualifying-question.model.ts
  src/cases/models/raise-query-error-message.enum.ts
  src/cases/query-management.routes.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.html
  src/work-allocation/containers/my-access/my-access.component.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
  src/work-allocation/containers/task-list/task-list.component.spec.ts
  test/accessibility/config/config.js
  test_codecept/backendMock/services/userApiData.js
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/codeceptCommon/statsReporter.js
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-2993

#3974 exui-2261-globalsearch-service-name-list
  .yarnrc.yml
  api/globalSearch/index.spec.ts
  api/globalSearch/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3974

#4093 #EXUI-2465: Change page title wording and guidance text wording
  src/noc/containers/noc-q-and-a/noc-q-and-a.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4093

#4101 #EXUI-2531: Update yarn and node version for rpx-xui-node-lib
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4101

#4115 update yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4115

#4100 EXUI-2503 - Remove secrets from local-mock
  Jenkinsfile_CNP
  package.json
  test_codecept/backendMock/configCopy.js
  test_codecept/backendMock/local-mock.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4100

#4123 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4123

#4124 uncommented test
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4124

#4121 update faker lib
  api/noc/noCService.mock.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4121

#3958 exui-2315-Language in client context
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-3958
