Repository hmcts/rpx-xui-webapp, pull requests merged in 2024-10, with the labels that each got.

#3945 Update yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3945

#3836 exui-2146-display utc time to local time
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3836

#3953 playwright tests should look at TEST_URL to determine what they are testing
  README.md
  playwright_tests/E2E/global-search.test.ts
  playwright_tests/config.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3953

#3689 fix date-time issue
  src/hearings/components/error-page/error-page.component.ts
  src/hearings/components/hearing-actual-summary-single-day/hearing-actual-summary-single-day.component.html
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.spec.ts
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-summary-base/hearing-actuals-summary-base.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-summary-base/hearing-actuals-summary-base.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts
  src/hearings/converters/case-number.answer.converter.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3689, aat/add-or-update, prod/add-or-update

#3960 exui-2454-incorrect-contact-number
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3960

#3962 fix issue with radio button not persisting
  package.json
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3962

#3966 Exui 2420 name refernce missing
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3966

#3954 toolkit version updated
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3954

#3956 EXUI-2417 - playwright wait for spinner
  playwright_tests/E2E/global-search.test.ts
  playwright_tests/E2E/staff-search.test.ts
  playwright_tests/E2E/steps/spinner-steps.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3956

#3955 SRT - fixes for EXUI-2193 / 2346
  api/configuration/menuConfigs/aat-diffs.ts
  api/configuration/menuConfigs/base-config.ts
  api/configuration/menuConfigs/configs.ts
  api/configuration/menuConfigs/preview-diffs.ts
  api/configuration/uiConfigRouter.ts
  config/custom-environment-variables.json
  package.json
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/containers/app-header/app-header.component.spec.ts
  src/app/containers/app-header/app-header.component.ts
  src/app/services/header-config/header-config.service.spec.ts
  src/app/services/header-config/header-config.service.ts
  src/models/environmentConfig.model.ts
  test/integration/tests/config/config.ts
  test_codecept/e2e/config/userRolesConfig.js
  test_codecept/integration/tests/config/config.ts
  test_codecept/ngIntegration/config/baseConfig.js
  test_codecept/ngIntegration/mockData/nodeApp/mockData.js
  test_codecept/ngIntegration/tests/features/workallocation2/allWork/allwork.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/availableTasks_manageLinks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/availableTasks/myWork_AvailableTasks_paginationSorting.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myCases/myCases.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks.feature
  test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_MyTasks_paginationSorting.feature
  test_codecept/ngIntegration/tests/features/workallocation2/rolesAccess/rolesAndAccessTabPage.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3955

#3961 EXUI-2281 - Fix console errors when running integration tests
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3961

#3964 EXUI-2453 - Case flag test resilience
  playwright_tests/E2E/case-flags.test.ts
  playwright_tests/E2E/steps/flag-steps.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3964

#3852 EXUI-2244 latest date error
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3852

#3858 EXUI-2255 Unable to submit hearing
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3858

#3881 exio-2227-error-handling
  api/specificAccessOrchastrator/index.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3881

#3969 Ex UI 2284
  api/accessManagement/index.ts
  api/challengedAccess/index.ts
  api/configuration/appConfig.ts
  api/configuration/references.ts
  api/services/lau.spec.ts
  api/services/lau.ts
  api/specificAccessOrchastrator/index.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3969

#3951 EXUI-1284: Upgrade yarn to v 4.5.0
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.6.3.cjs
  .yarn/releases/yarn-4.5.0.cjs
  .yarnrc.yml
  api/yarn.lock
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3951

#3981 Initialise config with correct keys
  src/app/app.constants.ts
  src/app/services/ccd-config/ccd-case.config.spec.ts
  src/app/services/ccd-config/ccd-case.config.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3981

#3983 Hide Continue button when when qualifying question has no url
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3983

#4044 Force additional check on user presence in session
  api/workAllocation/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4044
