Repository hmcts/rpx-xui-webapp, pull requests merged in 2024-01, with the labels that each got.

#3430 Feature/EUI 9081
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/hearings/templates/hearing-request-view-summary.template.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3430

#3427 EUI-9038 Hearing CR-84 Hearing requirements page labels
  src/hearings/components/case-flags/case-flags.component.html
  src/hearings/components/case-flags/case-flags.component.spec.ts
  src/hearings/components/case-flags/case-flags.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/models/caseFlagGroup.model.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/models/partyFlags.model.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
  test_codecept/e2e/features/step_definitions/hearings/viewOrEditHearing.steps.js
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingRequirementsPageLabels.feature
  test_codecept/ngIntegration/tests/stepDefinitions/hearingsMock.steps.js
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3427

#3428 Feature/EUI 9034
  src/hearings/components/hearing-case-name/hearing-case-name.component.spec.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/warning-and-error-section/warning-and-error-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/warning-and-error-section/warning-and-error-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/warning-and-error-section/warning-and-error-section.component.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.ts
  src/hearings/converters/case-name.answer.converter.spec.ts
  src/hearings/converters/need-welsh.amended.converter.spec.ts
  src/hearings/converters/public-case-name.answer.converter.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/services/hearings.service.ts
  test_codecept/e2e/features/step_definitions/hearings/viewOrEditHearing.steps.js
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/stepDefinitions/hearingsMock.steps.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3428

#3433 unit test fix
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3433

#3436 Feature/EUI 9098 hearing cr 84 case flag timestamps
  api/hearings/models/partyFlags.model.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.spec.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/models/partyFlags.model.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3436

#3434 EUI-9040 Hearing CR-84 Hearing requirement page confirm changes
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3434

#3432 Fix for bug COT-692: add named admin roles
  src/cases/components/roles-and-access/roles-and-access.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3432

#3422 exui-1109 fix - set reasonable adjustments from service hearing values if not found in hearing request
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3422

#3413 Bug/cot 675
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3413

#3372 party-channels-answer.converted refactored
  src/hearings/converters/party-channels-answer.converter.spec.ts
  src/hearings/converters/party-channels-answer.converter.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3372

#3407 fix: EXUI-1135 resolve issue with amend appearing
  src/hearings/converters/hearing-specific-date.amended.converter.spec.ts
  src/hearings/converters/hearing-specific-date.amended.converter.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3407

#3406 Remove whitespace around text in table cells and align to top
  src/work-allocation/components/task-field/task-field.component.scss
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3406

#3380 exui-1097-task-description-missing
  README.md
  src/cases/components/case-task/case-task.util.spec.ts
  src/cases/components/case-task/case-task.util.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3380

#3354 remove duplicate jurisdiction response from API
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.spec.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3354

#3417 exui-1173-common-lib-version-change DO-NOT-MERGE
  package.json
  test_codecept/integration/tests/utils/authUtil.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3417

#3345 common-lib version updates
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3345

#3464 Bug/exui 1109 rc1
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3464

#3469 Fix/ex UI 1135 date amend rc1
  src/hearings/converters/hearing-specific-date.amended.converter.spec.ts
  src/hearings/converters/hearing-specific-date.amended.converter.ts
Labels: enable_keep_helm, pr-values:srt

#3471 Bug/cot 675 rc1
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3471

#3470 Bug/cot 692 rc1
  src/cases/components/roles-and-access/roles-and-access.component.ts
Labels: enable_keep_helm, pr-values:srt

#3437 EUI-9054 Hearing CR-84 Additional facilities display
  package.json
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/partyFlags.model.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
  test_codecept/backendMock/services/prd/index.js
  test_codecept/backendMock/services/userApiData.js
  test_codecept/codeceptCommon/browser.js
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/codeceptCommon/customHelper.js
  test_codecept/codeceptCommon/hooks.js
  test_codecept/codeceptCommon/reportLogger.js
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/HearingFacilitiesPage.js
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/HearingRequirementsPage.js
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/ParticipantAttendancePage.js
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/partyCaseFlagsTable.js
  test_codecept/e2e/features/pageObjects/hearings/viewOrEditHearingPage.js
  test_codecept/e2e/features/step_definitions/hearings/hearingsCommon.steps.js
  test_codecept/e2e/features/step_definitions/hearings/viewOrEditHearing.steps.js
  test_codecept/e2e/utils/jsonUtil.js
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/caseHearings.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_HMC_setup.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_1.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_2.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_3.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_4.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_setup.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingPagelessUpdates.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingRequirementsPageLabels.feature
  test_codecept/ngIntegration/tests/stepDefinitions/hearingsMock.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3437

#3431 DTSPO-15909 - migrated Application Insights
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/provider.tf
Labels: ns:xui, prd:xui, add-or-update, pr-values:srt, rel:xui-webapp-pr-3431

#3440 EUI-9057 Hearing CR-84 Participant attendance display
  src/hearings/components/case-flags/case-flags.component.html
  src/hearings/components/case-flags/case-flags.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/models/partyDetails.model.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
  test_codecept/backendMock/services/prd/hearingChannel_Categories.js
  test_codecept/backendMock/services/prd/hearingSubChannel_Categories.js
  test_codecept/backendMock/services/prd/index.js
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/ParticipantAttendancePage.js
  test_codecept/e2e/features/step_definitions/hearings/hearingsCommon.steps.js
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_1.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_4.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3440

#3454 Add ammendment label
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-instructions-section/additional-instructions-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-instructions-section/additional-instructions-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-instructions-section/additional-instructions-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-stage-section/hearing-stage-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-stage-section/hearing-stage-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-stage-section/hearing-stage-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-venue-section/hearing-venue-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-venue-section/hearing-venue-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-venue-section/hearing-venue-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/language-requirements-section/language-requirements-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/language-requirements-section/language-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/language-requirements-section/language-requirements-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/linked-hearing-section/linked-hearing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/linked-hearing-section/linked-hearing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/linked-hearing-section/linked-hearing-section.component.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingManulaUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingRequirementsPageLabels.feature
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3454

#3473 EUI-9138 Hearing CR-84 Case flags not displayed
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: enable_keep_helm

#3438 EUI-9056 Hearing CR-84 Additional facilities implementation
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3438

#3479 DTSPO-15909 - migrated Application Insights -revert
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
Labels: ns:xui, prd:xui, add-or-update, pr-values:srt, rel:xui-webapp-pr-3479

#3439 Adding hearing-amendments-guard
  src/app/app.constants.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.spec.ts
  src/hearings/components/hearing-parties-title/hearing-parties-title.component.ts
  src/hearings/containers/request-hearing/hearing-change-reasons/hearing-change-reasons.component.spec.ts
  src/hearings/containers/request-hearing/hearing-change-reasons/hearing-change-reasons.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.spec.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.ts
  src/hearings/guards/hearing-amendments-guard.ts
  src/hearings/guards/hearings-guard.ts
  src/hearings/hearings.module.ts
  src/hearings/hearings.routes.ts
  src/hearings/services/hearings-feature.service.ts
  test_codecept/backendMock/services/ccd/routes.js
  test_codecept/backendMock/services/mockApiData.js
  test_codecept/ngIntegration/tests/features/hearings/featureToggleSettings.feature
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, rel:xui-webapp-pr-3439

#3456 EUI-9063 Hearing CR-84 First hearing date display
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3456

#3481 DTSPO-15909 - migrated Application Insights -revert2
  infrastructure/main.tf
  infrastructure/output.tf
Labels: ns:xui, prd:xui, add-or-update, pr-values:srt, rel:xui-webapp-pr-3481

#3458 EUI-9065 Hearing CR-84 First hearing date functionality
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.html
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.scss
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  src/hearings/utils/validators.utils.spec.ts
  src/hearings/utils/validators.utils.ts
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/HearingTimingPage.js
  test_codecept/e2e/features/step_definitions/hearings/hearingsCommon.steps.js
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_HMC_setup.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_4.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingManulaUpdateLabels.feature
Labels: ns:xui, prd:xui, destroy, enable_keep_helm, rel:xui-webapp-pr-3458

#3482 EUI-9143 Hearing CR-84 Participant attendance fixes
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, rel:xui-webapp-pr-3482

#3465 Add validation error
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  test_codecept/e2e/features/pageObjects/hearings/editHearingPage.js
  test_codecept/e2e/features/step_definitions/hearings/viewOrEditHearing.steps.js
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_CAT1_only.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_CAT2_only.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/summaryPageValidations.feature
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3465

#3484 EUI-9141/EUI-9142: Case Flags v2 - Case-level flag types not being retrieved
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, destroy, enable_keep_helm, rel:xui-webapp-pr-3484

#3487 unit test added
  src/cases/components/case-task/case-task.util.spec.ts
  src/hearings/converters/party-channels-answer.converter.spec.ts
Labels: ns:xui, prd:xui, pr-values:srt, rel:xui-webapp-pr-3487

#3489 Bug/EUI 9097
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/utils/case-flags.utils.spec.ts
  test_codecept/e2e/features/pageObjects/hearings/editHearingPage.js
  test_codecept/e2e/features/pageObjects/hearings/viewOrEditHearingPage.js
  test_codecept/e2e/features/step_definitions/hearings/hearingsCommon.steps.js
  test_codecept/e2e/features/step_definitions/hearings/viewOrEditHearing.steps.js
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_CAT2_only.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingManulaUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingRequirementsPageLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/summaryPageValidations.feature
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3489

#3491 cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, pr-values:srt, rel:xui-webapp-pr-3491

#3476 TL version updated
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3476

#3503 EUI-9162 Hearing CR-84 Feature turned off - Additional facilities error
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3503

#3486 EUI-9144 Hearing CR-84 Participant attendance fixes
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_HMC_setup.json
Labels: ns:xui, prd:xui, destroy, rel:xui-webapp-pr-3486

#3435 adding default config for WA service
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3435

#3441 exui-1225-remove hardcoded name
  src/hearings/containers/cancel-hearing/cancel-hearing.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3441

#3457 Fix for COT-689: Add check for null values, fix spelling of panel
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3457

#3494 Mv upgrade 3.0.1
  package.json
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.html
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3494
