Repository hmcts/rpx-xui-webapp, pull requests merged in 2024-05, with the labels that each got.

#3626 toolkit version update
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3626

#3667 exui-1873-failed FT fixed
  test_codecept/e2e/features/app/TCCreateCase_1.feature
  test_codecept/e2e/features/app/TCCreateCase_3.feature
  test_codecept/e2e/features/app/caseFlags/caseFlagsTab.feature
  test_codecept/e2e/features/app/globalSearch/searchPage.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3667

#3641 Add current user to search - DO_NOT_MERGE
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3641

#3180 fix CVEs
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3180, enable_keep_helm, pr-values:srt

#3666 exui-1870-ccpay upgrade
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3666

#3658 ExUI-1770
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  test_codecept/e2e/features/app/TCCreateCase_1.feature
  test_codecept/e2e/features/app/TCCreateCase_3.feature
  test_codecept/e2e/features/app/caseFlags/caseFlagsTab.feature
  test_codecept/e2e/features/app/globalSearch/searchPage.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3658

#3659 exui-1749: CR-84: Fixed toggling between paper hearing
  api/.yarn/install-state.gz
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-change-reasons/hearing-change-reasons.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.ts
  src/hearings/converters/is-paper-hearing.answer.converter.ts
  src/hearings/converters/paper-hearing.hidden.converter.ts
  src/hearings/models/hearingDetails.model.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/services/hearings.service.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3659

#3679 Ex UI 1770 testing and quality updates
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/services/hearings-feature.service.spec.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3679

#3671 pipeline reliability
  package.json
  test_codecept/e2e/support/customWaits.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3671

#3664 Make caseworker session storage change
  api/auth/index.ts
  api/workAllocation/caseWorkerService.ts
  api/workAllocation/caseWorkerUserDataCacheService.ts
  api/workAllocation/fullUserDetailCache.ts
  api/workAllocation/index.ts
  api/workAllocation/interfaces/common.ts
  api/workAllocation/interfaces/staffUserDetails.ts
  api/workAllocation/routes.ts
  api/workAllocation/util.ts
  package.json
  src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.spec.ts
  src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.spec.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.ts
  src/role-access/containers/remove-role/remove-role.component.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation/resolvers/location.resolver.spec.ts
  src/work-allocation/resolvers/task.resolver.spec.ts
  src/work-allocation/resolvers/task.resolver.ts
  src/work-allocation/services/caseworker-data.service.spec.ts
  src/work-allocation/services/caseworker-data.service.ts
  test/integration/tests/workallocation/person.spec.ts
  test/ngIntegration/tests/stepDefinitions/mockUsers.steps.js
  test/nodeMock/RUNTIME_ROUTES.txt
  test/nodeMock/backEndMock/rdCaseworkerRefApi.js
  test/nodeMock/config.js
  test/nodeMock/workAllocation/mockData.js
  test/nodeMock/workAllocation/reqResMapping.js
  test_codecept/backendMock/app.js
  test_codecept/backendMock/services/rdCaseworker/index.js
  test_codecept/backendMock/services/rdCaseworker/routes.js
  test_codecept/backendMock/services/users.js
  test_codecept/integration/tests/workallocation/person.spec.ts
  test_codecept/ngIntegration/mockData/workAllocation/mockData.js
  test_codecept/ngIntegration/mockData/workAllocation/reqResMapping.js
  test_codecept/ngIntegration/tests/stepDefinitions/mockUsers.steps.js
  test_codecept/nodeMock/RUNTIME_ROUTES.txt
  test_codecept/nodeMock/backEndMock/rdCaseworkerRefApi.js
  test_codecept/nodeMock/config.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3664

#3684 ExUI-1770 - further change to add sorting and remove null values
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3684

#3444 Fix/exui 330 security issue
  test/e2e/features/step_definitions/workallocation/workFilter.steps.js
  test_codecept/codeceptCommon/elements.js
  test_codecept/e2e/features/step_definitions/caseFlags.steps.js
  test_codecept/e2e/features/step_definitions/loginLogout.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3444

#3676 exui-1791 initial check in
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingManulaUpdateLabels.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3676

#3674 cve
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3674

#3254 fix: EXUI-388 - Timestamp in Hearing Requests in error page
  src/hearings/converters/date-request-failed.answer.converter.spec.ts
  src/hearings/converters/date-request-failed.answer.converter.ts
  src/hearings/models/hearings.enum.ts
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, rel:xui-webapp-pr-3254, pr-values:srt

#3693 DTSS-5011 - update playwright version to 1.42
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3693

#3701 DTSSE 5019 - navigate to login page test
  README.md
  playwright_tests/E2E/login-direct-link-navigate-to-login-page.test.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3701

#3699 Exui 1957
  src/hearings/containers/request-hearing/hearing-change-reasons/hearing-change-reasons.component.spec.ts
  src/hearings/containers/request-hearing/hearing-change-reasons/hearing-change-reasons.component.ts
  src/hearings/containers/request-hearing/request-hearing.component.html
  src/hearings/containers/request-hearing/request-hearing.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/services/hearings.service.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3699

#3480 Fix/ex UI 1263 security vulnerability
  package.json
  test/e2e/support/reports.js
  test_codecept/e2e/support/reports.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3480

#3687 MC SRT release
  README.md
  api/auth/index.ts
  api/workAllocation/caseWorkerService.ts
  api/workAllocation/caseWorkerUserDataCacheService.ts
  api/workAllocation/fullUserDetailCache.ts
  api/workAllocation/index.ts
  api/workAllocation/interfaces/common.ts
  api/workAllocation/interfaces/staffUserDetails.ts
  api/workAllocation/routes.ts
  api/workAllocation/util.ts
  package.json
  src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.spec.ts
  src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts
  src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
  src/cases/containers/tasks-container/tasks-container.component.spec.ts
  src/cases/containers/tasks-container/tasks-container.component.ts
  src/role-access/containers/delete-exclusion/delete-exclusion.component.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.spec.ts
  src/role-access/containers/rejected-request-view/rejected-request-view.component.ts
  src/role-access/containers/remove-role/remove-role.component.ts
  src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
  src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts
  src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation/resolvers/location.resolver.spec.ts
  src/work-allocation/resolvers/task.resolver.spec.ts
  src/work-allocation/resolvers/task.resolver.ts
  src/work-allocation/services/caseworker-data.service.spec.ts
  src/work-allocation/services/caseworker-data.service.ts
  test/e2e/features/step_definitions/workallocation/workFilter.steps.js
  test/integration/tests/workallocation/person.spec.ts
  test/ngIntegration/tests/stepDefinitions/mockUsers.steps.js
  test/nodeMock/RUNTIME_ROUTES.txt
  test/nodeMock/backEndMock/rdCaseworkerRefApi.js
  test/nodeMock/config.js
  test/nodeMock/workAllocation/mockData.js
  test/nodeMock/workAllocation/reqResMapping.js
  test_codecept/backendMock/app.js
  test_codecept/backendMock/services/rdCaseworker/index.js
  test_codecept/backendMock/services/rdCaseworker/routes.js
  test_codecept/backendMock/services/users.js
  test_codecept/codeceptCommon/elements.js
  test_codecept/e2e/features/step_definitions/caseFlags.steps.js
  test_codecept/e2e/features/step_definitions/loginLogout.steps.js
  test_codecept/integration/tests/workallocation/person.spec.ts
  test_codecept/ngIntegration/mockData/workAllocation/mockData.js
  test_codecept/ngIntegration/mockData/workAllocation/reqResMapping.js
  test_codecept/ngIntegration/tests/stepDefinitions/mockUsers.steps.js
  test_codecept/nodeMock/RUNTIME_ROUTES.txt
  test_codecept/nodeMock/backEndMock/rdCaseworkerRefApi.js
  test_codecept/nodeMock/config.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3687

#3702 exui-1958-current date to be accepted for hearing
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3702
