Repository hmcts/rpx-xui-webapp, pull requests merged in 2024-07, with the labels that each got.

#3738 DTSSE 5120 - Case flags tab
  playwright_tests/E2E/case-flags.test.ts
  playwright_tests/E2E/steps/case-steps.ts
  playwright_tests/E2E/steps/table-steps.ts
  playwright_tests/E2E/workallocation2.test.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3738

#3771 Terraform only changes for EXUI-1272
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-3771

#3725 Ex UI 1999
  infrastructure/variables.tf
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.spec.ts
  src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-instructions-section/additional-instructions-section.component.html
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3725, prod/add-or-update, aat/destroy

#3774 exui-1858-Sort Order Should be by upload_date
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3774

#3740 exui-2007-show-warning
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3740

#3793 Initialise LD with useReport
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3793

#3722 Add tag
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3722

#3765 EXUI-375: Use v2.29.0 node-lib
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3765

#3683 exui-1915-flag for message preserve
  src/cases/store/effects/case-create.effects.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3683, prod/add-or-update, aat/destroy

#3698 EXUI-929 - Feature/exui 929
  charts/xui-webapp/values.preview.template.yaml
  package.json
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3698

#3798 Revert "EXUI-2018"
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
Labels: ns:xui, prd:xui, aat/destroy, prod/destroy, rel:xui-webapp-pr-3798

#3761 DTSSE-5147 Add Global Search Tests
  playwright_tests/E2E/global-search.test.ts
  playwright_tests/E2E/steps/steps-functions.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3761

#3802 EXUI-2018 re-instatement
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, aat/destroy, prod/destroy, rel:xui-webapp-pr-3802

#3767 EXUI-2052: Additional Facilities not loading in hearing request
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3767

#3719 add optional chaining to prevent runtime error
  src/app/components/get-help/get-help.component.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/components/routing/application-routing.component.ts
  src/app/containers/app/app.component.ts
  src/app/guards/case-allocator.guard.ts
  src/app/guards/task-supervisor.guard.ts
  src/app/store/effects/app.effects.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/hearings/containers/view-hearing/hearing-view-summary/hearing-view-summary.component.ts
  src/hearings/converters/listed-hearing-viewer.hidden.converter.ts
  src/refunds/refunds/refunds.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
  src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3719

#3795 toolkit version update-DO_NOT_MERGE
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3795

#3757 Ex UI 2031 list of validation rules needed on adding new users on the staff tab
  src/app/models/error-message.model.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts
  src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3757, prod/add-or-update, aat/destroy

#3756 test CFV timestamp fix
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3756

#3797 EXUI-2047
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, aat/destroy, prod/destroy, rel:xui-webapp-pr-3797

#3801 MC version for common-lib changes
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3801

#3605 Adding CTSC exclusion capability
  api/workAllocation/index.ts
  package.json
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3605

#3788 EXUI-1538/39 - use pr toolkit for accessibility
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3788

#3720 EXUI-1786 remove unused feature flag mc-user-role-mapping
  src/app/services/role-category-mapping/role-category-mapping.service.spec.ts
  src/app/services/role-category-mapping/role-category-mapping.service.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3720

#3598 fix accessibility issue
  package.json
  src/app/containers/app/app.component.scss
  src/style/app.scss
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3598

#3792 DTSEE-5303 - Retries in Playwright Tests
  package.json
  playwright.config.ts
  playwright_tests/E2E/global-search.test.ts
  playwright_tests/E2E/staff-search.test.ts
  playwright_tests/E2E/steps/retry-steps.ts
  playwright_tests/E2E/steps/staff-steps.ts
  playwright_tests/E2E/workallocation2.test.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3792

#3317 EUI-8460 QM Raise a query submission
  src/app/models/user-details.model.ts
  src/cases/cases.module.ts
  src/cases/containers/index.ts
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3317

#3714 EXUI-1688: Accessibility with details/summary element
  src/cases/containers/case-list/case-list.component.html
  test_codecept/e2e/features/pageObjects/caseFileViewPage.js
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3714

#3760 exui-667-node lib upgrade
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3760

#3718 Ex UI 1782 rework case role allocation screens to allow allocate to me
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/models/allocate-role.enum.ts
  api/test/pact/pact-tests/rolesAccess/confirmAllocateRole.spec.ts
  api/test/pact/pact-tests/rolesAccess/createSpecificAccessApprovalRole.spec.ts
  api/test/pact/pact-tests/rolesAccess/createSpecificAccessDenyRole.spec.ts
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.spec.ts
  src/role-access/containers/allocate-role/choose-allocate-to/choose-allocate-to.component.spec.ts
  src/role-access/containers/allocate-role/choose-allocate-to/choose-allocate-to.component.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
  src/role-access/models/allocate-role.enum.ts
  src/role-access/services/allocate-role.service.spec.ts
  src/role-access/store/effects/allocate-role.effects.spec.ts
  src/role-access/store/reducers/allocate-role.reducer.spec.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3718

#3751 Add fix for caseworker names not appearing in task lists
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3751, prod/add-or-update, aat/destroy

#3794 Bug/e UI 2028 tasks not being unassigned
  api/application.ts
  api/workAllocation/caseWorkerService.ts
  api/workAllocation/caseWorkerUserDataCacheService.spec.ts
  api/workAllocation/caseWorkerUserDataCacheService.ts
  api/workAllocation/index.ts
  package.json
  test_codecept/backendMock/services/rdCaseworker/index.js
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3794

#3775 upgrade most dependencies with high sev vuln
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3775

#3778 EXUI-2058: Add error message on staffUI
  src/staff-administrator/containers/staff-users/staff-users.component.html
  src/staff-administrator/containers/staff-users/staff-users.component.spec.ts
  src/staff-administrator/containers/staff-users/staff-users.component.ts
  src/staff-administrator/models/staff-state.model.ts
  src/staff-administrator/models/staff-user-response-error.model.ts
  src/staff-administrator/resolvers/staff-user-details-resolver.service.ts
  src/staff-administrator/staff-administrator.module.ts
  src/staff-administrator/store/actions/staff-select.action.spec.ts
  src/staff-administrator/store/actions/staff-select.action.ts
  src/staff-administrator/store/reducers/staff-select.reducer.spec.ts
  src/staff-administrator/store/reducers/staff-select.reducer.ts
  src/staff-administrator/store/selectors/staff-select.selector.spec.ts
  src/staff-administrator/store/selectors/staff-select.selector.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3778

#3804 adjusted the person table column to reflect full name rather than the…
  src/work-allocation/containers/task-action/task-action-container.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3804

#3810 mc release 22-07-24
  api/application.ts
  api/roleAccess/dtos/to-role-assignment-dto.ts
  api/roleAccess/models/allocate-role.enum.ts
  api/test/pact/pact-tests/rolesAccess/confirmAllocateRole.spec.ts
  api/test/pact/pact-tests/rolesAccess/createSpecificAccessApprovalRole.spec.ts
  api/test/pact/pact-tests/rolesAccess/createSpecificAccessDenyRole.spec.ts
  api/workAllocation/caseWorkerService.ts
  api/workAllocation/caseWorkerUserDataCacheService.spec.ts
  api/workAllocation/caseWorkerUserDataCacheService.ts
  api/workAllocation/index.ts
  package.json
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.spec.ts
  src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
  src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.spec.ts
  src/role-access/containers/allocate-role/choose-allocate-to/choose-allocate-to.component.spec.ts
  src/role-access/containers/allocate-role/choose-allocate-to/choose-allocate-to.component.ts
  src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.spec.ts
  src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
  src/role-access/models/allocate-role.enum.ts
  src/role-access/services/allocate-role.service.spec.ts
  src/role-access/store/effects/allocate-role.effects.spec.ts
  src/role-access/store/reducers/allocate-role.reducer.spec.ts
  src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
  test_codecept/backendMock/services/rdCaseworker/index.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3810

#3814 DTSSE 5222 - Replace 17 Codeceptjs E2E test by 17 Playwright Tests
  README.md
  package.json
  playwright.config.ts
  test_codecept/e2e/features/app/caseFlags/caseFlagsTab.feature
  test_codecept/e2e/features/app/caseFlags/createSupport_reasonableAdjustments.feature
  test_codecept/e2e/features/app/globalSearch/searchPage.feature
  test_codecept/e2e/features/app/staffUI/search.feature
  test_codecept/e2e/features/app/workAllocation/workallocation2.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3814

#3563 multiple api call fix
  package.json
  src/cases/containers/case-search/case-search.component.ts
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, rel:xui-webapp-pr-3563

#3559 Add the case management category in its actual required field
  api/test/pact/pact-tests/rdLocation/getLocationsByServiceCode.spec.ts
  api/workAllocation/interfaces/case.ts
  api/workAllocation/locationController.ts
  api/workAllocation/locationService.ts
  api/workAllocation/util.ts
  package.json
  src/work-allocation/components/available-tasks-filter/available-tasks-filter.component.html
  src/work-allocation/components/available-tasks-filter/available-tasks-filter.component.scss
  src/work-allocation/components/available-tasks-filter/available-tasks-filter.component.spec.ts
  src/work-allocation/components/available-tasks-filter/available-tasks-filter.component.ts
  src/work-allocation/components/index.ts
  src/work-allocation/components/my-cases-filter/my-cases-filter.component.html
  src/work-allocation/components/my-cases-filter/my-cases-filter.component.scss
  src/work-allocation/components/my-cases-filter/my-cases-filter.component.spec.ts
  src/work-allocation/components/my-cases-filter/my-cases-filter.component.ts
  src/work-allocation/containers/all-work-case/all-work-case.component.html
  src/work-allocation/containers/all-work-case/all-work-case.component.spec.ts
  src/work-allocation/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
  src/work-allocation/containers/work-case-list/work-case-list.component.html
  src/work-allocation/services/location-data.service.spec.ts
  src/work-allocation/services/location-data.service.ts
Labels: ns:xui, prd:xui, add-or-update, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3559

#3745 Move AppInsights output to xui-webapp-appinsights-<env>
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  api/.env.defaults
  api/configuration/references.ts
  api/interfaces/environment.config.ts
  api/lib/appInsights.ts
  api/routes.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/custom-environment-variables.json
  infrastructure/output.tf
  src/app/services/logger/monitoring.service.spec.ts
  src/app/services/logger/monitoring.service.ts
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-3745

#3806 Updates functional test suite
  test_codecept/backendMock/services/rdLocation/index.js
  test_codecept/backendMock/services/rdLocation/routes.js
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/createhearingWorkflow.js
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
  test_codecept/ngIntegration/tests/features/hearings/createHearingNavigationControls.feature
  test_codecept/ngIntegration/tests/features/hearings/hearingActuals.feature
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_HMC_setup.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_setup.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingManulaUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingSubPages.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingActions_preCR84.feature
Labels: ns:xui, prd:xui, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-3806

#3770 EXUI-2067 - Support `PROFESSIONAL` role categories from RAS
  api/roleAccess/exclusionService.ts
  api/roleAccess/models/allocate-role.enum.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3770

#3805 changes for role_name and role_category
  api/test/pact/pact-tests/wa2/taskRoles.spec.ts
  api/test/pact/pact-tests/wa2/typeOfWork.spec.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3805

#3638 Add the etag change
  api/roleAccess/index.ts
  api/user/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3638
