Repository hmcts/rpx-xui-webapp, pull requests merged in 2024-02, with the labels that each got.

#3510 EUI-9165: Yes/no field fix
  package.json
  test_codecept/codeceptCommon/customHelper.js
  test_codecept/codeceptCommon/hooks.js
  test_codecept/e2e/features/pageObjects/common/CaseManager.js
  test_codecept/e2e/support/customWaits.js
  test_codecept/integration/tests/config/config.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3510

#3504 Enable Dynatrace RUM functionality via parameter to cookie banner
  package.json
  src/app/containers/app/app.component.html
  src/app/shared/services/mc-launch-darkly-service.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  test_codecept/e2e/features/app/TCCreateCase_1.feature
  test_codecept/e2e/features/app/TCCreateCase_3.feature
  test_codecept/e2e/features/app/TCSearchCaseandCaseList.feature
  yarn.lock
Labels: DO NOT MERGE, ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3504

#3497 EUI-9153 Hearing CR-84 Length date priority page
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/converters/party-channels-answer.converter.spec.ts
  src/hearings/hearings.routes.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  src/hearings/utils/validators.utils.spec.ts
  test_codecept/ngIntegration/tests/features/caseAccessManagement/requestCaseAccess.feature
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_HMC_setup.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_4.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_setup.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  tsconfig.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3497

#3519 EUI-9130: Welsh translation of static content
  src/app/components/case-reference-search-box/case-reference-search-box.component.html
  src/app/components/header/header.component.html
  src/app/components/header/header.component.spec.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
  src/app/components/info-message/info-message.component.html
  src/app/components/info-message/info-message.component.spec.ts
  src/app/components/not-authorised/not-authorised.component.html
  src/app/components/not-authorised/not-authorised.component.spec.ts
  src/app/components/phase-banner/phase-banner.component.html
  src/app/components/phase-banner/phase-banner.component.spec.ts
  src/app/components/service-down/service-down.component.html
  src/app/components/service-down/service-down.component.spec.ts
  src/app/components/signed-out/signed-out.component.html
  src/app/components/signed-out/signed-out.component.spec.ts
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3519

#3526 COT-675 Choose a date range is not pre selecting
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3526

#3516 cot-689
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3516

#3521 PR to test EXUI-1275
  package.json
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_languageInterpreter.feature
  test_codecept/e2e/features/pageObjects/caseFlags/searchLanguageInterpreterPage.js
  yarn.lock
Labels: DO NOT MERGE, ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3521

#3514 EUI-9182 Hearing CR-84 Hearing requirements page warning message
  src/hearings/components/case-flags/case-flags.component.html
  src/hearings/containers/request-hearing/amendment-label/amendment-label.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3514

#3517 EUI-9106 Hearing CR-84 Incorrect field used when comparing party
  src/hearings/containers/request-hearing/amendment-label/amendment-label.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/warning-and-error-section/warning-and-error-section.component.html
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_3.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_4.json
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3517

#3483 remove unneeded item from CYA page if already removed from workflow.
  src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.ts
  src/hearings/models/section.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3483

#3535 EUI-9144 Hearing CR-84 Participant attendance updated values not displayed in UI on revisit
  api/hearings/models/partyFlags.model.ts
  api/hearings/services.index.spec.ts
  api/hearings/services.index.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3535

#3539 EUI-9107 Hearing CR-84 Language interpreter label
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3539

#3524 EUI-9188 Unable to create hearing request if no case flags
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/utils/case-flags.utils.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/HearingTimingPage.js
  test_codecept/e2e/features/step_definitions/caseFileView.steps.js
  test_codecept/ngIntegration/tests/features/caseAccessManagement/requestCaseAccess.feature
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
  test_codecept/ngIntegration/tests/features/hearings/createHearingNavigationControls.feature
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_setup_no_case_flags.json
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3524

#3546 chart version changed to 3.0.2
  charts/xui-webapp/Chart.yaml
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3546

#3548 Case flags test input data update
  test_codecept/e2e/features/app/caseFlags/createCaseFlagV1_languageInterpreter.feature
  test_codecept/e2e/features/app/caseFlags/createSupport_reasonableAdjustments.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3548

#3533 nightly buid failure fix
  Jenkinsfile_nightly
  charts/xui-webapp/Chart.yaml
  package.json
  test_codecept/e2e/features/app/caseFlags/caseFlagsTab.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV1_reasonableAdjustments.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_languageInterpreter.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_reasonableAdjustments.feature
  test_codecept/e2e/features/app/caseFlags/createSupport_reasonableAdjustments.feature
  test_codecept/e2e/features/pageObjects/caseFlags/caseSetUp.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3533

#3543 CSFD-21
  Jenkinsfile_nightly
  charts/xui-webapp/Chart.yaml
  package.json
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  test_codecept/e2e/features/app/caseFlags/caseFlagsTab.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagV1_languageInterpreter.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV1_reasonableAdjustments.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_languageInterpreter.feature
  test_codecept/e2e/features/app/caseFlags/createCaseFlagsV2.1_reasonableAdjustments.feature
  test_codecept/e2e/features/app/caseFlags/createSupport_reasonableAdjustments.feature
  test_codecept/e2e/features/pageObjects/caseFlags/caseSetUp.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3543

#3558 CSFD-21 Additional fixes
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-3558

#3557 ccd-ui toolkit version 7.0.16-welsh-event-trigger
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3557

#3531 exui-1316
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts
  src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts
  src/hearings/containers/request-hearing/hearing-panel/hearing-panel.component.ts
  src/hearings/converters/hearing-panel.amended.converter.spec.ts
  src/hearings/converters/hearing-panel.amended.converter.ts
  src/hearings/converters/hearing-panel.answer.converter.spec.ts
  src/hearings/converters/hearing-panel.answer.converter.ts
  src/hearings/converters/judge-types.amended.converter.spec.ts
  src/hearings/converters/judge-types.amended.converter.ts
  src/hearings/converters/judge-types.answer.converter.spec.ts
  src/hearings/converters/judge-types.answer.converter.ts
  src/hearings/converters/judge-types.hidden.converter.spec.ts
  src/hearings/converters/judge-types.hidden.converter.ts
  src/hearings/converters/need-judge.amended.converter.spec.ts
  src/hearings/converters/need-judge.amended.converter.ts
  src/hearings/converters/need-judge.answer.converter.ts
  src/hearings/converters/panel-member-roles.amended.converter.spec.ts
  src/hearings/converters/panel-member-roles.amended.converter.ts
  src/hearings/converters/panel-member-roles.answer.converter.spec.ts
  src/hearings/converters/panel-member-roles.answer.converter.ts
  src/hearings/converters/panel-member-roles.hidden.converter.spec.ts
  src/hearings/converters/panel-member-roles.hidden.converter.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/pipes/is-amended.pipe.ts
  src/hearings/pipes/show-hide.pipe.spec.ts
  src/hearings/pipes/show-hide.pipe.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/hearingActions_preCR84.feature
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-3531
