Repository hmcts/rpx-xui-webapp, pull requests merged in 2025-02, with the labels that each got.

#4221 Cot 887
  api/hearings/models/serviceHearingValues.model.ts
  src/hearings/containers/request-hearing/hearing-panel-required/hearing-panel-required.component.spec.ts
  src/hearings/containers/request-hearing/hearing-panel-required/hearing-panel-required.component.ts
  src/hearings/models/serviceHearingValues.model.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4221

#4164 WIP:adds hearing store reset to edit journeys with/without CR84 enabled
  src/hearings/containers/request-hearing/request-hearing.page.flow.spec.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.ts
  src/hearings/utils/hearings.utils.ts
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/summaryPageValidations.feature
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-4164

#3894 text overlap fix for task list page
  src/work-allocation/containers/task-list/task-list.component.scss
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3894

#4140 Add extra option to qualifying questions and fix radio button state p…
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-4140

#4214 Exui-2639-playwright-test-fix
  playwright_tests/E2E/steps/create-xui-case-poc-steps.ts
  playwright_tests/E2E/steps/create-xui-case-test-case-type-dev-steps.ts
  playwright_tests/E2E/steps/submit-update-case-event-steps.ts
  playwright_tests/E2E/test-case.test.ts
  test_codecept/e2e/features/app/TCCreateCase_1.feature
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4214

#4167 noc back button fix and qm qualifying question style fix
  package.json
  src/noc/containers/noc-home/noc-home.component.spec.ts
  src/noc/containers/noc-home/noc-home.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4167

#4193 toolkit version update
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-4193

#4240 WIP:updates sign out link to be keyboard navigable
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4240

#4238 WIP:role removal from pagination
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4238

#3972 COT-900 - Date validation enhancement on hearing timing
  package.json
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearings.enum.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3972

#3880 financial remedy error text wordings changed
  src/noc/constants/nocErrorMap.enum.ts
  src/noc/containers/noc-case-ref/noc-case-ref.component.html
  src/noc/containers/noc-case-ref/noc-case-ref.component.spec.ts
  src/noc/containers/noc-case-ref/noc-case-ref.component.ts
  src/noc/containers/noc-fill-form-offline/noc-fill-form-offline.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-3880

#4249 EXUI-2766 - upper case file extension
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4249

#4266 fix issue with response to query
  src/cases/containers/query-management-container/query-management-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4266

#4267 update redis chart
  charts/xui-webapp/Chart.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4267

#4271 use new default screenflow if a paneldefault has been set
  api/hearings/data/defaultScreenFlow.data.ts
  api/hearings/services.index.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4271

#4252 Exui 2770 mc srt pr
  api/workAllocation/caseWorkerUserDataCacheService.spec.ts
  api/workAllocation/caseWorkerUserDataCacheService.ts
  api/workAllocation/util.ts
  api/workAllocation/utils.spec.ts
  package.json
  src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-4252

#4237 Tests/exui 2715
  package.json
  playwright_tests/E2E/staff.test.ts
  playwright_tests/E2E/test-case.test.ts
  test_codecept/e2e/features/app/TCCreateCase_2.feature
  test_codecept/e2e/features/app/TCCreateCase_3.feature
  test_codecept/e2e/features/app/TCSearchCaseandCaseList.feature
  test_codecept/e2e/features/app/loginLogout.feature
  test_codecept/e2e/features/app/staffUI/manageUser.feature
  test_codecept/e2e/features/app/staffUI/search.feature
Labels: ns:xui, prd:xui, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-4237

#4277 Add upgraded common library
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4277

#4239 WIP:Feature/exui 1629
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html
  src/staff-administrator/containers/staff-users/staff-users.component.html
  src/work-allocation/containers/all-work-home/all-work-home.component.html
  src/work-allocation/containers/task-action/task-action-container.component.html
  src/work-allocation/containers/task-assignment-choose-role/task-assignment-choose-role.component.html
  src/work-allocation/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation/containers/task-home/task-home.component.html
  src/work-allocation/containers/task-manager/task-manager.component.html
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4239

#4275 EXUI-1606 - removes aria tags
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-search/case-search.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4275

#4261 EXUI-1634 - clickable hide message testing
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4261

#4254 EXUI-1615 updates version for testing
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4254

#4257 WIP:updates version for testing
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4257

#4284 Accessibility/20 02 2025
  package.json
  playwright_tests/E2E/staff-search.test.ts
  playwright_tests/E2E/staff.test.ts
  playwright_tests/E2E/steps/staff-steps.ts
  src/cases/containers/case-list/case-list.component.html
  src/cases/containers/case-search/case-search.component.html
  src/cases/containers/query-management-container/query-management-container.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html
  src/hearings/containers/hearing-actuals/hearing-stage-result/hearing-stage-result.component.html
  src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html
  src/staff-administrator/containers/staff-users/staff-users.component.html
  src/work-allocation/containers/all-work-home/all-work-home.component.html
  src/work-allocation/containers/task-action/task-action-container.component.html
  src/work-allocation/containers/task-assignment-choose-role/task-assignment-choose-role.component.html
  src/work-allocation/containers/task-assignment-confirm/task-assignment-confirm.component.html
  src/work-allocation/containers/task-assignment/task-assignment-container.component.html
  src/work-allocation/containers/task-home/task-home.component.html
  src/work-allocation/containers/task-manager/task-manager.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4284

#4283 EXUI-2820 - Fix crossbrowser failure
  package.json
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4283

#4276 additional text add for upload document
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4276

#3967 #EXUI-2388: PED to working locally with exui
  README.md
  api/proxy.config.ts
  charts/xui-webapp/Chart.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3967

#4294 mc-toolkit release
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4294

#4279 EXUI-2767
  src/work-allocation/resolvers/location-resolver.service.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4279

#4272 Exui 2792 response to query
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4272
