Repository hmcts/rpx-xui-webapp, pull requests merged in 2025-03, with the labels that each got.

#4219 EXUI-2747 - update contact info in get help
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4219

#3905 EXUI-2104 - Event History Summary
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3905

#4288 WIP:adds updated grouping and labels
  .nvmrc
  api/.env.defaults
  api/common/crudService.ts
  package.json
  src/app/app.constants.ts
  src/app/components/phase-banner/phase-banner.component.spec.ts
  src/app/components/phase-banner/phase-banner.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-check-your-answers/linked-hearings-check-your-answers.component.ts
  src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts
  src/hearings/containers/linked-hearings/linked-hearings.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4288

#4142 WIP:Feature/exui 1571 1579
  package.json
  src/app/components/error-message/error-message.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-4142

#4302 exui-2868-pipeline failure
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4302

#3979 Add ability to set CCD/RAS url when talking to HMC
  api/configuration/references.ts
  api/hearings/hmc.index.ts
  api/hearings/routes.ts
  api/lib/proxy.ts
  config/custom-environment-variables.json
  config/default.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3979

#4301 WIP: Feature/exui 1594
  src/hearings/components/hearing-summary/hearing-summary.component.html
  src/hearings/components/hearing-summary/hearing-summary.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4301

#4163 Add DIVORCE and FR to staff UI
  api/staffSupportedJurisdictions/index.spec.ts
  config/default.json
  test_codecept/ngIntegration/tests/features/hearings/mockData/viewEditHearings/mock_SHV_SCR_1.json
Labels: DO NOT MERGE, ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4163

#4305 EXUI-2555
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4305

#3807 EXUI-2039 - Ungrey back button
  package.json
  playwright_tests/E2E/createFlag-scenario.test.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-3807

#3975 #EXUI-2000: remove the cookie from request header
  api/documents/index.spec.ts
  api/documents/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-3975

#4356 WIP:updates the headings within the description list
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.html
  test_codecept/e2e/features/pageObjects/hearings/hearingActualsPage.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4356

#4297 EXUI-2748 - update pkg version
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4297

#4318 Exui 2883 task completing
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4318

#4360 exui-2902-Ignore warning and go button not working
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4360

#4290 EXUI-2483 - add new Coat of Arms SVG to the footer
  package.json
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/assets/images/govuk-crest.svg
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4290

#4348 code tidy
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4348

#4354 EXUI-2897 - Update contact email for SSCS Infected blood
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4354

#4373 Feature/cot 886
  src/hearings/components/radio-list-builder/radio-list-builder.component.ts
  src/hearings/containers/request-hearing/hearing-panel-required/hearing-panel-required.component.ts
  src/hearings/containers/request-hearing/hearing-panel-selector/hearing-panel-selector.component.ts
  src/hearings/store/effects/hearing-request.effects.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4373

#4287 exui-2516 - fix a vulnerability in Content Security Policy
  src/web.config
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4287

#4374 CME-383: MC: Update Helm chart
  charts/xui-webapp/Chart.yaml
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4374

#4372 fix task not displaying
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4372

#4379 EXUI-2924: upgrade media version
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4379

#4197 Branch for all IAC CR84 tickets
  .nvmrc
  api/globalSearch/index.spec.ts
  api/globalSearch/index.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/hearings/containers/cancel-hearing/cancel-hearing.component.html
  src/hearings/containers/cancel-hearing/cancel-hearing.component.spec.ts
  src/hearings/containers/cancel-hearing/cancel-hearing.component.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.html
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  test_codecept/ngIntegration/tests/features/hearings/featureToggleSettings.feature
  test_codecept/ngIntegration/tests/features/hearings/hearingDetails.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/edithearingManulaUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/summaryPageValidations.feature
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-4197

#4215 test PR for welsh translation improvements
  package.json
  src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.ts
  src/cases/components/case-task/case-task.component.ts
  src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.ts
  src/cases/services/search-filter.service.ts
  src/cases/store/effects/share-case.effects.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: DO NOT MERGE, ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-webapp-pr-4215

#4260 EXUI-2640 - Exclusion list for CDAM
  package.json
  src/app/services/ccd-config/ccd-case.config.ts
  src/assets/config/config.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4260

#4375 EXUi-2898 - Service message banner persistent across tabs
  package.json
  src/app/services/auth/auth.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4375

#4366 WIP:Feature/exui 1587
  src/hearings/containers/request-hearing/hearing-welsh/hearing-welsh.component.html
  test_codecept/e2e/features/pageObjects/hearings/createHearingWorkflow/hearingWelshPage.js
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4366

#4388 WIP:Feature/exui 1585
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4388

#4390 exui-2963 - fix for cross browser build errors
  package.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4390
