Repository hmcts/rpx-xui-webapp, pull requests merged in 2025-04, with the labels that each got.

#4393 EXUI-2974 - update fortify version
  package.json
  playwright-nightly.config.ts
  test_codecept/java/build.gradle
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4393

#4382 toolkit update
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4382

#4389 exui-2921
  src/hearings/utils/case-flags.utils.spec.ts
  src/hearings/utils/case-flags.utils.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4389

#4391 EXUI-2914-session expired issue
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4391

#4362 media viewer upgrade
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4362

#4403 update node-lib
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4403

#4404 EXUI-2987 - use pre-release toolkit
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4404

#4319 toolkit version update
  package.json
  src/style/app.scss
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4319

#4396 Exui 2957 service message
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  src/cases/models/service-message/service-message.model.ts
  src/style/app.scss
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4396

#4172 Update query-management-container.component.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4172

#4402 EXUI-2972
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4402

#4411 Cme-376 node 20 rebase
  .github/workflows/dependency-check.yml
  .nvmrc
  Dockerfile
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4411

#4408 help text for document added
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  src/cases/models/service-message/service-message.model.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4408

#4394 exui-2835 - update TK version
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4394

#4186 adds for label to get around accessible name error
  src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4186

#4420 exui-3022-cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4420

#4407 EXUI-2997 - use pre-release toolkit
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4407

#4415 CME-379 - use pre-release node lib
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4415

#4409 exui-2976 - Bump common lib pkg version
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4409

#4419 toolkit update
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4419

#4429 exui-3041-cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4429

#4413 Fix/exui 2960 v2
  api/common/crudService.ts
  api/hearings/services.index.ts
  api/roleAccess/exclusionService.ts
  package.json
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/cases/containers/case-details-home/case-details-home.component.spec.ts
  src/cases/containers/case-details-home/case-details-home.component.ts
  src/cases/containers/case-hearings/case-hearings.component.html
  src/cases/containers/case-hearings/case-hearings.component.spec.ts
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/cases/containers/case-viewer-container/case-viewer-container.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.ts
  src/hearings/containers/linked-hearings/linked-hearings.component.ts
  src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/request-hearing.component.ts
  src/hearings/containers/request-hearing/request-hearing.page.flow.ts
  src/hearings/converters/additional-security.amended.converter.spec.ts
  src/hearings/converters/participant-attendence.answer.converter.spec.ts
  src/hearings/guards/hearing-amendments-guard.spec.ts
  src/hearings/guards/hearing-amendments-guard.ts
  src/hearings/guards/hearings-edit-guard.spec.ts
  src/hearings/guards/hearings-edit-guard.ts
  src/hearings/guards/hearings-guard.spec.ts
  src/hearings/guards/hearings-guard.ts
  src/hearings/guards/hearings-view-guard.spec.ts
  src/hearings/guards/hearings-view-guard.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearingListMain.model.ts
  src/hearings/models/hearingValuesStateData.ts
  src/hearings/services/hearings-feature.service.ts
  src/hearings/store/actions/hearing-case-info.action.ts
  src/hearings/store/actions/hearing-links.action.spec.ts
  src/hearings/store/actions/hearing-links.action.ts
  src/hearings/store/actions/hearing-values.action.spec.ts
  src/hearings/store/actions/hearing-values.action.ts
  src/hearings/store/effects/hearing-links.effects.spec.ts
  src/hearings/store/effects/hearing-links.effects.ts
  src/hearings/store/effects/hearing-values.effects.spec.ts
  src/hearings/store/effects/hearing-values.effects.ts
  src/hearings/store/reducers/hearing-values.reducer.spec.ts
  src/hearings/store/reducers/hearing-values.reducer.ts
  src/work-allocation/containers/my-access/my-access.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4413

#4433 Exui 3054 consolidate qm prs
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  src/style/app.scss
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4433

#4431 toolkit update
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4431
