Repository hmcts/rpx-xui-webapp, pull requests merged in 2025-05, with the labels that each got.

#4430 exui-3017-cve fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4430

#4441 Revert exui-3017-cve fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4441

#4370 exui-2334-log-error
  api/hearings/hearing.mock.ts
  api/hearings/hmc.index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4370

#4445 Exui 3075 follow up issue
  src/cases/containers/query-management-container/query-management-container.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4445

#4452 EXUI-3099 - resolve broken tests from CCD cleanup
  playwright_tests/E2E/case-flags.test.ts
  playwright_tests/E2E/global-search.test.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4452

#4451 exui-3012-Pact test failure
  README.md
  api/specificAccessOrchastrator/index.ts
  api/tsconfig.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4451

#4442 Add upgraded playwright
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4442

#4458 exui-3109-cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4458

#4464 cr97-screen-refactor
  api/hearings/data/defaultScreenFlow.data.ts
  api/hearings/data/serviceHearingValues.mock.data.ts
  api/hearings/services.index.spec.ts
  api/hearings/services.index.ts
  package.json
  src/cases/containers/case-hearings/case-hearings.component.ts
  src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-view-summary/hearing-view-summary.component.spec.ts
  src/hearings/containers/request-hearing/request-hearing.component.spec.ts
  src/hearings/hearing.test.data.ts
  src/hearings/pipes/show-hide.pipe.spec.ts
  src/hearings/utils/page-flow.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4464

#4463 EXUI-3124 - Use pre-release toolkit for 3124
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4463

#4446 Test PR for EXUI-3037
  package.json
  playwright.config.ts
  test_codecept/ngIntegration/util/idamLogin.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4446

#4398 Ex UI 2079 new version
  api/application.ts
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.preview.template.yaml
  charts/xui-webapp/values.yaml
  config/default.json
  package.json
  test_codecept/backendMock/local-mock.json
  test_codecept/integration/tests/nodeApp_endpoints.spec.ts
  test_codecept/ngIntegration/util/idamLogin.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, pr-values:srt, rel:xui-webapp-pr-4398
