Repository hmcts/rpx-xui-webapp, pull requests merged in 2025-10, with the labels that each got.

#4655 Add potential test fix
  charts/xui-webapp/Chart.yaml
  charts/xui-webapp/values.yaml
  playwright_tests/E2E/steps/table-steps.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4655

#4661 EXUI-3541 - Provider -> State name changed to match with the value in the WA Provider Test
  api/test/pact/pact-tests/wa2/typeOfWork.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4661

#4609 Exui 2916 welsh translation issues
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4609

#4666 EXUI-3469 - use mv and tk release vers for 3469
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4666
