Repository hmcts/rpx-xui-webapp, pull requests merged in 2025-07, with the labels that each got.

#4524 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: enable_keep_helm

#4520 COT-938 panel specialisms
  src/hearings/containers/request-hearing/hearing-panel-selector/hearing-panel-selector.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4520

#4471 EXUI-2811 - Add hearing id and update text on multiple hearings pages
  src/cases/components/case-hearings-list/case-hearings-list.component.html
  src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts
  src/cases/components/case-hearings-list/case-hearings-list.component.ts
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
  src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.spec.ts
  src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.html
  src/hearings/containers/hearing-actuals/hearing-actuals-summary-base/hearing-actuals-summary-base.component.ts
  src/hearings/containers/hearing-actuals/hearing-actuals.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/converters/hearing-id.converter.spec.ts
  src/hearings/converters/hearing-id.converter.ts
  src/hearings/hearing.test.data.ts
  src/hearings/models/hearings.enum.ts
  src/hearings/pipes/hearing-answers.pipe.spec.ts
  src/hearings/pipes/hearing-answers.pipe.ts
  src/hearings/store/actions/hearing-request.action.ts
  src/hearings/store/effects/hearing-request.effects.ts
  src/hearings/templates/hearing-cancelled-summary.template.ts
  src/hearings/templates/hearing-create-edit-summary.template.ts
  src/hearings/templates/hearing-request-failed-summary.template.ts
  src/hearings/templates/hearing-request-view-summary.template.ts
  src/hearings/templates/hearing-view-edit-summary.template.ts
  test_codecept/e2e/features/pageObjects/hearings/hearingsTabPage.js
  test_codecept/ngIntegration/tests/features/hearings/createHearing.feature
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4471

#4465 EXUI-3127 - Fix hearing track trace to add logs to AI
  api/accessManagement/index.ts
  api/common/crudService.spec.ts
  api/common/crudService.ts
  api/globalSearch/index.ts
  api/hearings/hmc.index.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4465

#4535 Mc release 08 07 2025
  api/accessManagement/index.ts
  api/common/crudService.spec.ts
  api/common/crudService.ts
  api/globalSearch/index.ts
  api/hearings/hmc.index.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearings.enum.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4535

#4509 fires google analytics event on clicking continue button
  package.json
  src/cases/containers/query-management-container/query-management-container.component.html
  src/cases/containers/query-management-container/query-management-container.component.spec.ts
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4509

#4508 Exui 3167 close query
  package.json
  src/cases/containers/query-management-container/query-management-container.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4508

#4521 EXUI-3247 spike to increase unit test coverage
  .eslintrc.cjs
  api/.nycrc.json
  api/accessManagement/data/booking.mock.data.ts
  api/accessManagement/index.spec.ts
  api/accessManagement/routes.spec.ts
  api/activityTracker/index.spec.ts
  api/amendedJurisdictions/index.spec.ts
  api/caseshare/index.spec.ts
  api/caseshare/real-api.spec.ts
  api/caseshare/routes.spec.ts
  api/caseshare/stub-api.spec.ts
  api/hearings/hmc.index.spec.ts
  api/hearings/routes.spec.ts
  api/hearings/services.index.spec.ts
  api/hearings/services.index.ts
  api/roleAccess/index.spec.ts
  src/karma.conf.js
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4521

#4537 added in sonar run exclusion list for master pipeline failure
  sonar-project.properties
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4537

#4538 Revert "EXUI-3247 spike to increase unit test coverage"
  .eslintrc.cjs
  api/.nycrc.json
  api/accessManagement/data/booking.mock.data.ts
  api/accessManagement/index.spec.ts
  api/accessManagement/routes.spec.ts
  api/activityTracker/index.spec.ts
  api/amendedJurisdictions/index.spec.ts
  api/caseshare/index.spec.ts
  api/caseshare/real-api.spec.ts
  api/caseshare/routes.spec.ts
  api/caseshare/stub-api.spec.ts
  api/hearings/hmc.index.spec.ts
  api/hearings/routes.spec.ts
  api/hearings/services.index.spec.ts
  api/hearings/services.index.ts
  api/roleAccess/index.spec.ts
  sonar-project.properties
  src/karma.conf.js
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4538

#4527 EXUI-2895 - use pre-release tk
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4527

#4444 #EXUI-1853: Translate static content on Expert UI MC - "Get help" & "Terms and conditions"
  src/app/components/get-help/get-help.component.html
  src/app/components/get-help/get-help.component.spec.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.spec.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4444

#4483 EXUI-3079
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4483

#4543 Exui 3206
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
  src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-timing-section/hearing-timing-section.component.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/participant-attendance-section/participant-attendance-section.component.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.spec.ts
  src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
  src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
  src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
  src/hearings/models/hearingsUpdateMode.enum.ts
  src/hearings/models/individualDetails.model.ts
  src/hearings/utils/hearings.utils.spec.ts
  src/hearings/utils/hearings.utils.ts
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/editHearingUpdateLabels.feature
  test_codecept/ngIntegration/tests/features/hearings/viewEditHearings/summaryPageValidations.feature
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4543

#4528 cot-998 adding amend labels to panel section
  src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/panel-details-section/panel-details-section.component.html
  src/hearings/containers/request-hearing/hearing-edit-summary/panel-details-section/panel-details-section.component.spec.ts
  src/hearings/containers/request-hearing/hearing-edit-summary/panel-details-section/panel-details-section.component.ts
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4528

#4547 exui-3313-accept decimal value
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4547

#4541 test pr for media viewer redaction issues
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4541

#4549 toolkit update
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4549

#4554 DTSPB-4490 Update Probate Privacy policy
  src/app/components/privacy-policy/privacy-policy.component.html
Labels: ns:xui, prd:xui, rel:xui-webapp-pr-4554

#4552 exui-3329-remove console log
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-webapp-pr-4552
